/* eslint-disable */
/**
 * 用于本地 mock 试卷数据
 */
export const paperData = {
  "code": "0",
  "message": "",
  "data": {
    "id": 190,
    "name": "测试复制考点到知识点",
    "typeId": null,
    "businessCardId": 1,
    "examTypeId": null,
    "subjectId": 1,
    "gradeId": 2,
    "termId": 1,
    "year": 2018,
    "averageScore": null,
    "quoteCount": 0,
    "storageTime": null,
    "questionAmount": 10,
    "createdUser": 1294984332,
    "createUserName": null,
    "createdTime": 1526017721000,
    "updatedTime": 1545137711000,
    "updatedUser": 1326216013,
    "updatedUserName": null,
    "state": 14,
    "provinceId": 0,
    "cityId": null,
    "countyId": null,
    "provinceName": null,
    "cityName": null,
    "countyName": null,
    "picUrlList": [
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-0.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-1.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-2.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-3.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-4.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-5.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-6.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-7.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-8.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-9.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-10.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-11.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-12.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-13.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-14.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/50131544-1f23-472f-9739-f56f1ac54002/slide-15.png"
    ],
    "examPaperContentOutputDTOList": [
      {
        "id": 7456,
        "serialNumber": 1,
        "name": "选择题",
        "examPaperContentQuestionOutputDTOList": [
          {
            "id": 12652,
            "serialNumber": 1,
            "questionId": 358709,
            "questionOutputDTO": {
              "id": 358709,
              "title": "<p>下列数据与事实相接近的是（　　）</p>",
              "content": null,
              "optionList": [
                "<p>两个鸡蛋的重力大约是1N</p>",
                "<p>一瓶普通矿泉水的质量约为5kg</p>",
                "<p>人正常步行的速度约为5m/s</p>",
                "<p>物理教材的长度约为30dm</p>"
              ],
              "answerList": [
                "A"
              ],
              "analysis": "<p>【考点】77：重力大小的估测；23：质量的估测；63：长度的估测；68：速度与物体运动．</p><p>【分析】首先对题目中涉及的物理量有个初步的了解，对于选项中的单位，可根据需要进行相应的换算或转换，排除与生活实际相差较远的选项，找出符合生活实际的答案．</p><p>【解答】解：</p><p>A、两个鸡蛋的质量在100g=0.1kg左右，受到的重力为G=mg=0.1kg×10N/kg=1N．故A符合实际；</p><p>B、一瓶普通矿泉水的体积在500cm3左右，质量在m=ρV=1.0g/cm3×500cm3=500g=0.5kg左右．故B不符合实际；</p><p>C、人正常步行的速度在4km/h=4×m/s≈1.1m/s左右．故C不符合实际；</p><p>D、一根筷子的长度在25cm左右，物理教材的长度略大于此数值，在26cm=2.6dm左右．故D不符合实际．</p><p>故选A</p>",
              "subjectId": 1,
              "gradeId": 2,
              "phaseId": 1,
              "termId": 1,
              "typeId": 1,
              "questionType": "单选题",
              "provinceId": 0,
              "cityId": null,
              "countyId": null,
              "schoolId": null,
              "year": 2018,
              "score": 6,
              "sourceId": null,
              "difficulty": null,
              "distinction": null,
              "recommendationIndex": null,
              "rating": null,
              "comprehensiveDegreeId": null,
              "abilityIdList": [],
              "subjectCharacteristicIdList": null,
              "editionIdList": null,
              "chapterIdList": null,
              "knowledgeIdList": [],
              "examPointIdList": [],
              "coreLiteracyIdList": null,
              "costTime": null,
              "browseCount": 0,
              "quoteCount": 0,
              "examCount": 0,
              "correctRate": null,
              "storageTime": null,
              "sub": false,
              "state": 18,
              "createdTime": 1526018011000,
              "createdUser": 1294984332,
              "updatedTime": 1526018212000,
              "updatedUser": 1294984332,
              "versions": null,
              "remarks": null,
              "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180511135055_8628.jpeg",
              "cutUserId": 1294984332,
              "auditCutUserId": 1294984332,
              "entryUserId": 1294984332,
              "auditEntryUserId": 1294984332,
              "tagUserId1": 1294984332,
              "tagUserId2": 1294971535,
              "auditTagUserId": null,
              "cutTime": 1526018011000,
              "auditCutTime": 1526018041000,
              "entryTime": 1526018212000,
              "auditEntryTime": 1526018611000,
              "tag1Time": 1526018738000,
              "tag2Time": 1526026200000,
              "auditTagTime": null,
              "errType": 0,
              "errReason": "",
              "templateType": 1,
              "adoptUser1Tag": null,
              "adoptUser2Tag": null,
              "children": [
                {
                  "id": 646298,
                  "questionId": 361198,
                  "title": "<p>zz</p>",
                  "optionList": [
                    "<p>选项1</p>",
                    "<p>选项2<br/></p>",
                    "<p>选项3<br/></p>",
                    "",
                    "<p>选项5<br/></p>"
                  ],
                  "answerList": [
                    "D"
                  ],
                  "analysis": "<p>选择4 缺失，答案 却是 选项4</p>",
                  "typeId": 2,
                  "score": 3,
                  "difficulty": null,
                  "knowledgeIdList": null,
                  "examPointIdList": null,
                  "subQuestionMemberList": null
                },
                {
                  "id": 646299,
                  "questionId": 361198,
                  "title": "<p>testa<br/></p>",
                  "optionList": [
                    "<p>434<br/></p>",
                    "",
                    "<p>34<br/></p>",
                    ""
                  ],
                  "answerList": [
                    "B",
                    "D"
                  ],
                  "analysis": "<p>5<br/></p>",
                  "typeId": 2,
                  "score": 3,
                  "difficulty": null,
                  "knowledgeIdList": null,
                  "examPointIdList": null,
                  "subQuestionMemberList": null
                }
              ],
              "questionTag1": {
                "id": 117934,
                "epId": 190,
                "questionId": 358709,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "112963",
                "examPointIds": null,
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526018738000,
                "createdUser": 1294984332,
                "updatedTime": 1526018738000,
                "updatedUser": 1294984332,
                "children": []
              },
              "questionTag2": {
                "id": 117948,
                "epId": 190,
                "questionId": 358709,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "112963",
                "examPointIds": null,
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526026200000,
                "createdUser": 1294971535,
                "updatedTime": 1526026200000,
                "updatedUser": 1294971535,
                "children": []
              },
              "tagAdopt": null,
              "tagReason": null,
              "tagFeedback1": "",
              "tagFeedback2": "",
              "auditTagFeedback": null,
              "sceneIdList": null,
              "suggestTime": null,
              "examTypeId": null,
              "tagUser1FeedbackAdoptFlag": null,
              "tagUser2FeedbackAdoptFlag": null,
              "auditTagUserFeedbackAdoptFlag": null,
              "tagUser1AdoptFlag": null,
              "tagUser2AdoptFlag": null,
              "knowledgeNameList": null,
              "examPointNameList": null,
              "layoutStyle": 3,
              "x1": null,
              "y1": null,
              "x2": null,
              "y2": null,
              "picIndex": null,
              "label": null,
              "deleted": false,
              "parentTypeId": null,
              "parentTypeName": null,
              "originPaperName": null,
              "examPaperTypeId": null
            },
            "epcId": 7456,
            "score": null
          },
          {
            "id": 12653,
            "serialNumber": 2,
            "questionId": 358710,
            "questionOutputDTO": {
              "id": 358710,
              "title": "<p>下面列举了四位科学家和他们有关的研究，其中描述正确的是（　　）</p>",
              "content": null,
              "optionList": [
                "<p>托里拆利﹣用马德堡半球实验证明大气压的存在</p>",
                "<p>哥白尼﹣地心说</p>",
                "<p>伽利略﹣研究力与运动的关系</p>",
                "<p>亚里士多德﹣研究浮力原理</p>"
              ],
              "answerList": [
                "C"
              ],
              "analysis": "<p>A、托里拆利最早测出了大气压的数值，马德堡半球实验是马德堡市的市长奥托•格里克主持进行的，第一次证明了大气压的存在．故A错误；</p><p>B、哥白尼创立了日心说，对传承千年的地心说理论提出挑战．故B错误；</p><p>C、伽利略等科学家一直致力于研究运动和力的关系，伽利略提出了物体运动不需要力维持的科学观点．故C正确；</p><p>D、浮力原理，也就是阿基米德原理，是阿基米德最早发现的．故D错误．</p><p>故选C</p>",
              "subjectId": 1,
              "gradeId": 2,
              "phaseId": 1,
              "termId": 1,
              "typeId": 1,
              "questionType": "单选题",
              "provinceId": 0,
              "cityId": null,
              "countyId": null,
              "schoolId": null,
              "year": 2018,
              "score": 3,
              "sourceId": null,
              "difficulty": null,
              "distinction": null,
              "recommendationIndex": null,
              "rating": null,
              "comprehensiveDegreeId": null,
              "abilityIdList": [],
              "subjectCharacteristicIdList": null,
              "editionIdList": null,
              "chapterIdList": null,
              "knowledgeIdList": [],
              "examPointIdList": [],
              "coreLiteracyIdList": null,
              "costTime": null,
              "browseCount": 0,
              "quoteCount": 0,
              "examCount": 0,
              "correctRate": null,
              "storageTime": null,
              "sub": false,
              "state": 18,
              "createdTime": 1526018011000,
              "createdUser": 1294984332,
              "updatedTime": 1526018344000,
              "updatedUser": 1294984332,
              "versions": null,
              "remarks": null,
              "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180511135106_4220.jpeg",
              "cutUserId": 1294984332,
              "auditCutUserId": 1294984332,
              "entryUserId": 1294984332,
              "auditEntryUserId": 1294984332,
              "tagUserId1": 1294984332,
              "tagUserId2": 1294971535,
              "auditTagUserId": null,
              "cutTime": 1526018011000,
              "auditCutTime": 1526018041000,
              "entryTime": 1526018344000,
              "auditEntryTime": 1526018611000,
              "tag1Time": 1526019923000,
              "tag2Time": 1526026208000,
              "auditTagTime": null,
              "errType": 0,
              "errReason": "",
              "templateType": 2,
              "adoptUser1Tag": null,
              "adoptUser2Tag": null,
              "children": null,
              "questionTag1": {
                "id": 117940,
                "epId": 190,
                "questionId": 358710,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "113034,113035",
                "examPointIds": "12963",
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526019923000,
                "createdUser": 1294984332,
                "updatedTime": 1526019923000,
                "updatedUser": 1294984332,
                "children": []
              },
              "questionTag2": {
                "id": 117949,
                "epId": 190,
                "questionId": 358710,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "115005",
                "examPointIds": null,
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526026208000,
                "createdUser": 1294971535,
                "updatedTime": 1526026208000,
                "updatedUser": 1294971535,
                "children": []
              },
              "tagAdopt": null,
              "tagReason": null,
              "tagFeedback1": "",
              "tagFeedback2": "",
              "auditTagFeedback": null,
              "sceneIdList": null,
              "suggestTime": null,
              "examTypeId": null,
              "tagUser1FeedbackAdoptFlag": null,
              "tagUser2FeedbackAdoptFlag": null,
              "auditTagUserFeedbackAdoptFlag": null,
              "tagUser1AdoptFlag": null,
              "tagUser2AdoptFlag": null,
              "knowledgeNameList": null,
              "examPointNameList": null,
              "layoutStyle": 3,
              "x1": null,
              "y1": null,
              "x2": null,
              "y2": null,
              "picIndex": null,
              "label": null,
              "deleted": false,
              "parentTypeId": null,
              "parentTypeName": null,
              "originPaperName": null,
              "examPaperTypeId": null
            },
            "epcId": 7456,
            "score": null
          }
        ]
      },
      {
        "id": 7457,
        "serialNumber": 2,
        "name": "填空题",
        "examPaperContentQuestionOutputDTOList": [
          {
            "id": 12654,
            "serialNumber": 3,
            "questionId": 358711,
            "questionOutputDTO": {
              "id": 358711,
              "title": "<p>如图所示，某同学用50N的力将重30N的长方体物块紧压在标有刻度的竖直墙壁上静止，则该长方体的长为　2.00　cm，此时物体受到的摩擦力为<zmsubline></zmsubline>N</p>",
              "content": null,
              "optionList": [],
              "answerList": [
                "<p>2.00；30</p>"
              ],
              "analysis": "<p>解：</p><p>由图知：刻度尺上1cm之间有10个小格，所以一个小格代表的长度是0.1cm=1mm，即此刻度尺的分度值为1mm；</p><p>长方体下端与83.00cm对齐，上端与85.00cm对齐，所以长方体的长度为L=85.00cm﹣83.00cm=2.00cm；</p><p>由于长方体处于静止状态，所以受力平衡，在竖直方向上，长方体受到一个竖直向下的重力，还有一个竖直向上的摩擦力，这两个力是一对平衡力，大小相等，故摩擦力为30N．</p><p>故答案为：2.00；30．</p>",
              "subjectId": 1,
              "gradeId": 2,
              "phaseId": 1,
              "termId": 1,
              "typeId": 1,
              "questionType": "单选题",
              "provinceId": 0,
              "cityId": null,
              "countyId": null,
              "schoolId": null,
              "year": 2018,
              "score": 3,
              "sourceId": null,
              "difficulty": null,
              "distinction": null,
              "recommendationIndex": null,
              "rating": null,
              "comprehensiveDegreeId": null,
              "abilityIdList": [],
              "subjectCharacteristicIdList": null,
              "editionIdList": null,
              "chapterIdList": null,
              "knowledgeIdList": [],
              "examPointIdList": [],
              "coreLiteracyIdList": null,
              "costTime": null,
              "browseCount": 0,
              "quoteCount": 0,
              "examCount": 0,
              "correctRate": null,
              "storageTime": null,
              "sub": false,
              "state": 18,
              "createdTime": 1526018011000,
              "createdUser": 1294984332,
              "updatedTime": 1526018449000,
              "updatedUser": 1294984332,
              "versions": null,
              "remarks": null,
              "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180511135138_2508.jpeg",
              "cutUserId": 1294984332,
              "auditCutUserId": 1294984332,
              "entryUserId": 1294984332,
              "auditEntryUserId": 1294984332,
              "tagUserId1": 1294984332,
              "tagUserId2": 1294971535,
              "auditTagUserId": null,
              "cutTime": 1526018011000,
              "auditCutTime": 1526018041000,
              "entryTime": 1526018449000,
              "auditEntryTime": 1526018611000,
              "tag1Time": 1526019943000,
              "tag2Time": 1526026215000,
              "auditTagTime": null,
              "errType": 0,
              "errReason": "",
              "templateType": 3,
              "adoptUser1Tag": null,
              "adoptUser2Tag": null,
              "children": null,
              "questionTag1": {
                "id": 117941,
                "epId": 190,
                "questionId": 358711,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "113037,113038",
                "examPointIds": "12963",
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526019943000,
                "createdUser": 1294984332,
                "updatedTime": 1526019943000,
                "updatedUser": 1294984332,
                "children": []
              },
              "questionTag2": {
                "id": 117950,
                "epId": 190,
                "questionId": 358711,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "113047",
                "examPointIds": null,
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526026215000,
                "createdUser": 1294971535,
                "updatedTime": 1526026215000,
                "updatedUser": 1294971535,
                "children": []
              },
              "tagAdopt": null,
              "tagReason": null,
              "tagFeedback1": "",
              "tagFeedback2": "",
              "auditTagFeedback": null,
              "sceneIdList": null,
              "suggestTime": null,
              "examTypeId": null,
              "tagUser1FeedbackAdoptFlag": null,
              "tagUser2FeedbackAdoptFlag": null,
              "auditTagUserFeedbackAdoptFlag": null,
              "tagUser1AdoptFlag": null,
              "tagUser2AdoptFlag": null,
              "knowledgeNameList": null,
              "examPointNameList": null,
              "layoutStyle": 3,
              "x1": null,
              "y1": null,
              "x2": null,
              "y2": null,
              "picIndex": null,
              "label": null,
              "deleted": false,
              "parentTypeId": null,
              "parentTypeName": null,
              "originPaperName": null,
              "examPaperTypeId": null
            },
            "epcId": 7457,
            "score": null
          },
          {
            "id": 12655,
            "serialNumber": 4,
            "questionId": 358712,
            "questionOutputDTO": {
              "id": 358712,
              "title": "<p>弓开如满月，箭去似流星”形容射箭运动员拉弓放箭的情形，那么在这个过程中弓的<zmsubline></zmsubline>能转化为箭的<zmsubline></zmsubline>能</p>",
              "content": null,
              "optionList": [],
              "answerList": [
                "<p>弹性势；动能</p>"
              ],
              "analysis": "<p>拉弯的弓具有弹性势能，箭射出去后具有动能，这一过程中是弓的弹性势能转化为箭的动能．</p><p>故答案为：弹性势；动能</p>",
              "subjectId": 1,
              "gradeId": 2,
              "phaseId": 1,
              "termId": 1,
              "typeId": 1,
              "questionType": "单选题",
              "provinceId": 0,
              "cityId": null,
              "countyId": null,
              "schoolId": null,
              "year": 2018,
              "score": 3,
              "sourceId": null,
              "difficulty": null,
              "distinction": null,
              "recommendationIndex": null,
              "rating": null,
              "comprehensiveDegreeId": null,
              "abilityIdList": [],
              "subjectCharacteristicIdList": null,
              "editionIdList": null,
              "chapterIdList": null,
              "knowledgeIdList": [],
              "examPointIdList": [],
              "coreLiteracyIdList": null,
              "costTime": null,
              "browseCount": 0,
              "quoteCount": 0,
              "examCount": 0,
              "correctRate": null,
              "storageTime": null,
              "sub": false,
              "state": 18,
              "createdTime": 1526018011000,
              "createdUser": 1294984332,
              "updatedTime": 1526018529000,
              "updatedUser": 1294984332,
              "versions": null,
              "remarks": null,
              "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180511135243_3830.jpeg",
              "cutUserId": 1294984332,
              "auditCutUserId": 1294984332,
              "entryUserId": 1294984332,
              "auditEntryUserId": 1294984332,
              "tagUserId1": 1294984332,
              "tagUserId2": 1294971535,
              "auditTagUserId": null,
              "cutTime": 1526018011000,
              "auditCutTime": 1526018041000,
              "entryTime": 1526018529000,
              "auditEntryTime": 1526018611000,
              "tag1Time": 1526019950000,
              "tag2Time": 1526026220000,
              "auditTagTime": null,
              "errType": 0,
              "errReason": "",
              "templateType": 3,
              "adoptUser1Tag": null,
              "adoptUser2Tag": null,
              "children": null,
              "questionTag1": {
                "id": 117942,
                "epId": 190,
                "questionId": 358712,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "112963",
                "examPointIds": "12963",
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526019950000,
                "createdUser": 1294984332,
                "updatedTime": 1526019950000,
                "updatedUser": 1294984332,
                "children": []
              },
              "questionTag2": {
                "id": 117951,
                "epId": 190,
                "questionId": 358712,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "112963",
                "examPointIds": null,
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526026220000,
                "createdUser": 1294971535,
                "updatedTime": 1526026220000,
                "updatedUser": 1294971535,
                "children": []
              },
              "tagAdopt": null,
              "tagReason": null,
              "tagFeedback1": "",
              "tagFeedback2": "",
              "auditTagFeedback": null,
              "sceneIdList": null,
              "suggestTime": null,
              "examTypeId": null,
              "tagUser1FeedbackAdoptFlag": null,
              "tagUser2FeedbackAdoptFlag": null,
              "auditTagUserFeedbackAdoptFlag": null,
              "tagUser1AdoptFlag": null,
              "tagUser2AdoptFlag": null,
              "knowledgeNameList": null,
              "examPointNameList": null,
              "layoutStyle": 3,
              "x1": null,
              "y1": null,
              "x2": null,
              "y2": null,
              "picIndex": null,
              "label": null,
              "deleted": false,
              "parentTypeId": null,
              "parentTypeName": null,
              "originPaperName": null,
              "examPaperTypeId": null
            },
            "epcId": 7457,
            "score": null
          },
          {
            "id": 12656,
            "serialNumber": 5,
            "questionId": 358713,
            "questionOutputDTO": {
              "id": 358713,
              "title": "<p>如图所示，物体A在水平拉力F的作用下，沿水平面以0.4m/s的速度运动了2s，弹簧测力计的是示数为5N．则拉力F做功为<zmsubline></zmsubline>J</p>",
              "content": null,
              "optionList": [],
              "answerList": [
                "<p>8</p>"
              ],
              "analysis": "<p>图中使用的是动滑轮，拉力等于弹簧测力计的示数，F=5N，</p><p>拉力端移动的距离：s=2s物=2v物t=2×0.4m/s×2s=1.6m，</p><p>拉力做功：</p><p>W=Fs=5N×1.6m=8J．</p><p>故答案为：8</p>",
              "subjectId": 1,
              "gradeId": 2,
              "phaseId": 1,
              "termId": 1,
              "typeId": 1,
              "questionType": "单选题",
              "provinceId": 0,
              "cityId": null,
              "countyId": null,
              "schoolId": null,
              "year": 2018,
              "score": 3,
              "sourceId": null,
              "difficulty": null,
              "distinction": null,
              "recommendationIndex": null,
              "rating": null,
              "comprehensiveDegreeId": null,
              "abilityIdList": [],
              "subjectCharacteristicIdList": null,
              "editionIdList": null,
              "chapterIdList": null,
              "knowledgeIdList": [],
              "examPointIdList": [],
              "coreLiteracyIdList": null,
              "costTime": null,
              "browseCount": 0,
              "quoteCount": 0,
              "examCount": 0,
              "correctRate": null,
              "storageTime": null,
              "sub": false,
              "state": 18,
              "createdTime": 1526018011000,
              "createdUser": 1294984332,
              "updatedTime": 1526018571000,
              "updatedUser": 1294984332,
              "versions": null,
              "remarks": null,
              "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180511135319_8597.jpeg",
              "cutUserId": 1294984332,
              "auditCutUserId": 1294984332,
              "entryUserId": 1294984332,
              "auditEntryUserId": 1294984332,
              "tagUserId1": 1294984332,
              "tagUserId2": 1294971535,
              "auditTagUserId": null,
              "cutTime": 1526018011000,
              "auditCutTime": 1526018041000,
              "entryTime": 1526018571000,
              "auditEntryTime": 1526018611000,
              "tag1Time": 1526020020000,
              "tag2Time": 1526026226000,
              "auditTagTime": null,
              "errType": 0,
              "errReason": "",
              "templateType": 3,
              "adoptUser1Tag": null,
              "adoptUser2Tag": null,
              "children": null,
              "questionTag1": {
                "id": 117943,
                "epId": 190,
                "questionId": 358713,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "113031,113032",
                "examPointIds": "12963",
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526020020000,
                "createdUser": 1294984332,
                "updatedTime": 1526020020000,
                "updatedUser": 1294984332,
                "children": []
              },
              "questionTag2": {
                "id": 117953,
                "epId": 190,
                "questionId": 358713,
                "sourceId": null,
                "difficulty": 1,
                "distinction": 1,
                "recommendationIndex": 3,
                "rating": 1,
                "comprehensiveDegreeId": 1,
                "knowledgeIds": "12702",
                "examPointIds": null,
                "subjectCharacteristicIds": null,
                "abilityIds": null,
                "keywords": null,
                "coreLiteracyIds": null,
                "editionIds": null,
                "chapterIds": null,
                "courseSystemIds": null,
                "createdTime": 1526026226000,
                "createdUser": 1294971535,
                "updatedTime": 1526026226000,
                "updatedUser": 1294971535,
                "children": []
              },
              "tagAdopt": null,
              "tagReason": null,
              "tagFeedback1": "",
              "tagFeedback2": "",
              "auditTagFeedback": null,
              "sceneIdList": null,
              "suggestTime": null,
              "examTypeId": null,
              "tagUser1FeedbackAdoptFlag": null,
              "tagUser2FeedbackAdoptFlag": null,
              "auditTagUserFeedbackAdoptFlag": null,
              "tagUser1AdoptFlag": null,
              "tagUser2AdoptFlag": null,
              "knowledgeNameList": null,
              "examPointNameList": null,
              "layoutStyle": 3,
              "x1": null,
              "y1": null,
              "x2": null,
              "y2": null,
              "picIndex": null,
              "label": null,
              "deleted": false,
              "parentTypeId": null,
              "parentTypeName": null,
              "originPaperName": null,
              "examPaperTypeId": null
            },
            "epcId": 7457,
            "score": null
          }
        ]
      }
    ],
    "tagUserId1": 1294984332,
    "tagUserName1": null,
    "tagUserId2": 1294971535,
    "tagUserName2": null,
    "fileUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180511134640_1578.doc",
    "editionId": 37,
    "tag1SubmitFlag": true,
    "tag2SubmitFlag": true,
    "cutUserId": 1294984332,
    "cutUserName": null,
    "auditCutUserId": 1294984332,
    "auditCutUserName": null,
    "entryUserId": 1294984332,
    "entryUserName": null,
    "auditEntryUserId": 1294984332,
    "auditEntryUserName": null,
    "auditTagUserId": 1294971535,
    "auditTagUserName": null,
    "cutTime": 1526018011000,
    "auditCutTime": 1526018041000,
    "entryTime": 1526018574000,
    "auditEntryTime": 1526018611000,
    "tag1Time": 1526020089000,
    "tag2Time": 1526026228000,
    "auditTagTime": null,
    "cutReceiveTime": 1526017795000,
    "entryReceiveTime": 1526018050000,
    "tagReceiveTime1": 1526018655000,
    "tagReceiveTime2": 1526020540000,
    "finalAuditUserId": null,
    "finalAuditUserName": null,
    "wrongFlag": false,
    "difficulty": null,
    "cutPassFlag": true,
    "entryPassFlag": true,
    "phaseId": 1,
    "purpose": 1,
    "courseContentName": null,
    "examPaperTextbook": null,
    "examPaperCourseContent": null,
    "examPaperLongPicUrlOutputDTOList": null
  }
}