import { fromJS } from "immutable";

export const dataListOne = fromJS({
    "data": [
        {
            "id": 346567,
            "title": "<p>公司最近那种虫灾严重<zmblank></zmblank></p>",
            "content": null,
            "optionList": [
                "<p>蝮蛇</p>",
                "<p>蚂蚁</p>",
                "<p>老鼠</p>",
                "<p>蟑螂</p>"
            ],
            "answerList": [
                "C",
                "D"
            ],
            "analysis": "<p>咦~好恶心啊<zmlatex>{{100}^\\circ C}</zmlatex>水烫死~</p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": 1,
            "typeId": 2,
            "questionType": "多选题",
            "provinceId": 0,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 2,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12688,
                12689,
                12690
            ],
            "examPointIdList": [
                12924,
                12925,
                12926,
                14986,
                14992,
                14993
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 131,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1523519818000,
            "createdUser": 180,
            "updatedTime": 1526712622000,
            "updatedUser": 1294971565,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": 5,
            "examTypeId": 1,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "阿斯顿士大夫士大夫",
                "是的发色发",
                "是的发色发"
            ],
            "examPointNameList": [
                "借助字典",
                "结合上下文",
                "分析词语引申义",
                "测试",
                "啊实打实",
                "sfsaf撒打发撒"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null,
            "parentTypeId": 38,
            "parentTypeName": "选择题"
        },
        {
            "id": 346566,
            "title": "<p>公司最近哪种虫害十分严重？</p>",
            "content": null,
            "optionList": [
                "<p>蛇24242424</p>",
                "<p>鼠</p>",
                "<p>蚁</p>",
                "<p>蜈蚣</p>"
            ],
            "answerList": [
                "D"
            ],
            "analysis": "<p>嘿嘿嘿，可爱的鼠鼠2424242424242</p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": 1,
            "typeId": 1,
            "questionType": "单选题",
            "provinceId": 0,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 6,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 2,
            "abilityIdList": [
                5,
                7,
                8,
                0,
                9,
                6,
                2
            ],
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12688,
                12689,
                12690
            ],
            "examPointIdList": [
                14986,
                14992,
                14993
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 69,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": null,
            "createdUser": null,
            "updatedTime": null,
            "updatedUser": null,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": [
                1
            ],
            "suggestTime": 10,
            "examTypeId": 7,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "阿斯顿士大夫士大夫",
                "是的发色发",
                "是的发色发"
            ],
            "examPointNameList": [
                "测试",
                "啊实打实",
                "sfsaf撒打发撒"
            ],
            "layoutStyle": null,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null,
            "parentTypeId": 38,
            "parentTypeName": "选择题"
        },
        {
            "id": 359162,
            "title": "<p>1z2131asdasdasd<br/></p>",
            "content": null,
            "optionList": [
                "<p>asdasda<br/></p>",
                "<p>asdasd<br/></p>",
                "<p>asdasd<br/></p>",
                "<p>dasdasd<br/></p>"
            ],
            "answerList": [
                "D"
            ],
            "analysis": "<p>asdasdas<br/></p>",
            "subjectId": 1,
            "gradeId": 5,
            "phaseId": 1,
            "termId": null,
            "typeId": 1,
            "questionType": "单选题",
            "provinceId": null,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": null,
            "score": 3,
            "sourceId": 5,
            "difficulty": 1,
            "distinction": 2,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": [
                1
            ],
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                119015
            ],
            "examPointIdList": [],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 11,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1527243165000,
            "createdUser": 180,
            "updatedTime": 1530539996000,
            "updatedUser": 1294984332,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": null,
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": [
                1
            ],
            "suggestTime": 3,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "z213"
            ],
            "examPointNameList": [],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": "",
            "parentTypeId": 38,
            "parentTypeName": "选择题"
        },
        {
            "id": 360177,
            "title": "<p>dsfsafewg<br/></p>",
            "content": null,
            "optionList": null,
            "answerList": null,
            "analysis": null,
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": null,
            "typeId": 2,
            "questionType": "多选题",
            "provinceId": null,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 6,
            "sourceId": 6,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12688
            ],
            "examPointIdList": [],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 0,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": true,
            "state": null,
            "createdTime": null,
            "createdUser": null,
            "updatedTime": null,
            "updatedUser": null,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": null,
            "errReason": null,
            "templateType": 1,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": [
                {
                    "id": 644113,
                    "questionId": 360177,
                    "title": "<p>幅度萨芬萨<br/></p>",
                    "optionList": null,
                    "answerList": [
                        "<p>safas<br/></p>"
                    ],
                    "analysis": "<p>dsfsaf<br/></p>",
                    "typeId": 3,
                    "score": 3,
                    "difficulty": null,
                    "knowledgeIdList": null,
                    "examPointIdList": null,
                    "subQuestionMemberList": null
                },
                {
                    "id": 644114,
                    "questionId": 360177,
                    "title": "<p>dsfsaf<br/></p>",
                    "optionList": [
                        "<p>sdfsfas<br/></p>",
                        "<p>sdfsa<br/></p>",
                        "<p>fsa<br/></p>",
                        "<p>fasf<br/></p>"
                    ],
                    "answerList": [
                        "B"
                    ],
                    "analysis": "<p>dsfsafas<br/></p>",
                    "typeId": 2,
                    "score": 3,
                    "difficulty": null,
                    "knowledgeIdList": null,
                    "examPointIdList": null,
                    "subQuestionMemberList": null
                }
            ],
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": 3,
            "examTypeId": 1,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "阿斯顿士大夫士大夫"
            ],
            "examPointNameList": [],
            "layoutStyle": null,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null,
            "parentTypeId": 38,
            "parentTypeName": "选择题"
        },
        {
            "id": 360016,
            "title": "<p>掌门的吉祥物是什么动物</p>",
            "content": null,
            "optionList": [
                "<p>狐狸<br/></p>",
                "<p>狸猫<br/></p>",
                "<p>兔子<br/></p>",
                "<p>斑马<img src=\"https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180531150637_8840.jpg\" zmtype=\"small\"/></p>"
            ],
            "answerList": [
                "A"
            ],
            "analysis": "<p>好吧。<br/></p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": null,
            "typeId": 2,
            "questionType": "多选题",
            "provinceId": null,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 5,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": [
                0,
                1
            ],
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12688
            ],
            "examPointIdList": [
                12963
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 2,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1527750458000,
            "createdUser": 1294979443,
            "updatedTime": 1528337511000,
            "updatedUser": 1294984332,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": null,
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": [
                1
            ],
            "suggestTime": 3,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "阿斯顿士大夫士大夫"
            ],
            "examPointNameList": [
                "作文"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": "2018年",
            "parentTypeId": 38,
            "parentTypeName": "选择题"
        },
        {
            "id": 359163,
            "title": "<p>asdasdasda<br/></p>",
            "content": null,
            "optionList": [
                "<p>asdasd<br/></p>",
                "<p>sdasda<br/></p>",
                "<p>dasd<br/></p>",
                "<p>sdasd<br/></p>"
            ],
            "answerList": [
                "D"
            ],
            "analysis": "<p>sdasdasd<br/></p>",
            "subjectId": 1,
            "gradeId": 5,
            "phaseId": 1,
            "termId": null,
            "typeId": 1,
            "questionType": "单选题",
            "provinceId": null,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": null,
            "score": 3,
            "sourceId": 5,
            "difficulty": 1,
            "distinction": 2,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 2,
            "abilityIdList": [
                1
            ],
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                119015
            ],
            "examPointIdList": [
                18789
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 0,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": null,
            "createdUser": null,
            "updatedTime": null,
            "updatedUser": null,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": null,
            "errReason": null,
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": [
                1
            ],
            "suggestTime": 3,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "z213"
            ],
            "examPointNameList": [
                "k2k2k2"
            ],
            "layoutStyle": null,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null,
            "parentTypeId": 38,
            "parentTypeName": "选择题"
        },
        {
            "id": 5698,
            "title": "<p>1．（<zmblank contenteditable=\"false\">空类1</zmblank>）是夏天还是冬天，樟树（<zmblank contenteditable=\"false\">空类1</zmblank>）那么蓬蓬勃勃。（填合适的关联词）</p><p>2.按要求写成语。</p><p>王文好像有难言之隐，想说又不愿说,他此刻的样子可以用这些成语来形容：&nbsp;<zmsubline contenteditable=\"false\">空类2</zmsubline>、<zmsubline contenteditable=\"false\">空类2</zmsubline>、<zmsubline contenteditable=\"false\">空类2</zmsubline>。</p><p>3．小芳在看书。（扩句，至少扩两处）</p><p><zmsubline contenteditable=\"false\">空类2</zmsubline>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p><p>4.弯弯的月亮挂在夜空。（改成比喻句）</p><p><zmsubline contenteditable=\"false\">空类2</zmsubline>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p><p>5. 星星布满了天空。（改成拟人句）</p><p><zmsubline contenteditable=\"false\">空类2</zmsubline>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p><p>6．地球是人类惟一的家园，怎么能破坏她呢？（改为陈述句）</p><p><zmsubline contenteditable=\"false\">空类2</zmsubline>&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p><p>7．奶奶经常回忆她小时侯的往事。（用修改符号改在原处）&nbsp;</p><p><zmsubline contenteditable=\"false\">空类2</zmsubline></p><p>8.泪水湿润了他的眼睛。</p><p>改成“把”字句：<zmsubline contenteditable=\"false\">空类2</zmsubline></p><p>改成“被”字句：&nbsp;<zmsubline contenteditable=\"false\">空类2</zmsubline></p>",
            "content": null,
            "optionList": null,
            "answerList": [
                "<p>无论</p>",
                "<p>总是</p>",
                "<p>欲言又止</p>",
                "<p>吞吞吐吐&nbsp;</p>",
                "<p>闪烁其词</p>",
                "<p>小芳在教室里仔细地看书。</p>",
                "<p>弯弯的月亮像小船一样挂在夜空。</p>",
                "<p>星星在天上眨着眼睛，布满了天空。</p>",
                "<p>地球是人类惟一的家园，我们不能破坏她。</p>",
                "<p>删去“小时候的”或“往事”</p>",
                "<p>泪水把他的眼睛湿润了。</p>",
                "<p>他的眼睛被泪水湿润了。</p>"
            ],
            "analysis": "<p>略</p>",
            "subjectId": 1,
            "gradeId": 4,
            "phaseId": 1,
            "termId": 2,
            "typeId": 3,
            "questionType": "填空题",
            "provinceId": 24,
            "cityId": 165,
            "countyId": 1312,
            "schoolId": null,
            "year": null,
            "score": 3,
            "sourceId": null,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                10570,
                12689,
                12690
            ],
            "examPointIdList": [
                13037,
                13038,
                13039
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 106,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": null,
            "createdUser": null,
            "updatedTime": null,
            "updatedUser": null,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 3,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": null,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "大师傅大师傅",
                "是的发色发",
                "是的发色发"
            ],
            "examPointNameList": [
                "作者、国家",
                "主要人物",
                "典型事件"
            ],
            "layoutStyle": null,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null,
            "parentTypeId": 39,
            "parentTypeName": "填空题"
        },
        {
            "id": 346565,
            "title": "<p>公司的名字叫啥？</p>",
            "content": null,
            "optionList": null,
            "answerList": [
                "<p>掌门1对1</p>"
            ],
            "analysis": "<p>如此简单的问题</p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": 1,
            "typeId": 3,
            "questionType": "填空题",
            "provinceId": 0,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 19,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12701,
                12703,
                12717
            ],
            "examPointIdList": [
                15007,
                18789,
                18799
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 93,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1523519818000,
            "createdUser": 180,
            "updatedTime": 1527857998000,
            "updatedUser": 1294984332,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 3,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": 15,
            "examTypeId": 1,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "撒旦飞洒发",
                "sdfsaf",
                "所发生的发生地方"
            ],
            "examPointNameList": [
                "但是根深蒂固",
                "k2k2k2",
                "weiweitang考点测试"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null,
            "parentTypeId": 39,
            "parentTypeName": "填空题"
        },
        {
            "id": 5701,
            "title": "<p><zmindent></zmindent>人一生中最幸福的时光是童年。童年发生的事情往往充满稚趣，又很有意思。你的童年一定有许多值得回忆的事。请你从中选择一件把它写下来。</p><p>题目：难忘的童年</p><p>要求：写出自己的真实感受，内容要具体，语句要通顺。</p><p><br/></p>",
            "content": null,
            "optionList": null,
            "answerList": [
                "<p>略</p>"
            ],
            "analysis": "<p>略</p>",
            "subjectId": 1,
            "gradeId": 4,
            "phaseId": 1,
            "termId": 2,
            "typeId": 18,
            "questionType": "书面表达",
            "provinceId": 24,
            "cityId": 165,
            "countyId": 1312,
            "schoolId": null,
            "year": null,
            "score": 3,
            "sourceId": 2,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12688,
                12689,
                12690
            ],
            "examPointIdList": [
                14986,
                14992,
                14993
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 345,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1512014674000,
            "createdUser": 44212,
            "updatedTime": 1527751885000,
            "updatedUser": 1294984332,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 4,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": null,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "阿斯顿士大夫士大夫",
                "是的发色发",
                "是的发色发"
            ],
            "examPointNameList": [
                "测试",
                "啊实打实",
                "sfsaf撒打发撒"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": "江苏省南京市玄武区",
            "parentTypeId": 46,
            "parentTypeName": "写作题"
        },
        {
            "id": 5700,
            "title": "<p style=\"text-align: center;\">11111美的启发</p><p><zmindent contenteditable=\"false\">空类0</zmindent>我家在古城一角，窗外有块空地，附近的居民竟把它当成了堆垃圾的地方。怎么办？我制了个“禁止倒垃圾”的木牌插在那里，可人们连看都不看它一眼，那里照样垃圾成堆，臭气熏天。为此，我们伤透了脑筋。</p><p><zmindent contenteditable=\"false\">空类0</zmindent>一个星期天的早上，爸爸妈妈小声商量了一会儿，爸爸告诉我一个好主意。我听了，乐得直拍手。于是，我们全家动员，先将垃圾铲成一堆；再从河边挑来石块，砌成一个椭圆形的花坛；再糊上水泥，并在石缝外勾出美丽的图案；又在花坛的垃圾上面堆上一尺多厚的细土，栽上各种花苗；还就近挖来了两丛翠竹，栽在花坛的东西两旁。一天工夫，这儿便呈现出另一番景象。附近的居民不但没再来这儿倒垃圾，反而纷纷把家里的珍贵花木奉献出来，为这小小的花圃增美添色。</p><p><zmindent contenteditable=\"false\">空类0</zmindent>春去秋来，这里花团锦簇，树木葱茏，竟然成了古城的一角风景。工作之余，人们常来这儿休息聊天，看书下棋。你瞧，一位小姐姐正坐在花坛边抚琴弄弦呢！</p><p><zmindent contenteditable=\"false\">空类0</zmindent>窗外，飘扬着动人的琴声；窗外，洋溢着沁人心脾的清香；窗外，小鸟在枝头欢乐地歌唱······</p><p><zmindent contenteditable=\"false\">空类0</zmindent>看者窗外的美丽风景，我蓦(mò)然懂得了：只有用美，才能启发更多的人爱美。</p>",
            "content": null,
            "optionList": null,
            "answerList": null,
            "analysis": null,
            "subjectId": 1,
            "gradeId": 4,
            "phaseId": 1,
            "termId": 2,
            "typeId": 16,
            "questionType": "阅读理解",
            "provinceId": 24,
            "cityId": 165,
            "countyId": 1312,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 5,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 2,
            "comprehensiveDegreeId": 1,
            "abilityIdList": [
                0,
                3,
                5,
                7,
                8
            ],
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                10570,
                12688,
                12689,
                12690
            ],
            "examPointIdList": [
                13031,
                14986,
                15005,
                15006
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 274,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": true,
            "state": null,
            "createdTime": 1512014674000,
            "createdUser": 44212,
            "updatedTime": 1527856444000,
            "updatedUser": 1294984332,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 1,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": [],
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": [
                1
            ],
            "suggestTime": 3,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "大师傅大师傅",
                "阿斯顿士大夫士大夫",
                "是的发色发",
                "是的发色发"
            ],
            "examPointNameList": [
                "作者、朝代",
                "测试",
                "士大夫",
                "撒的方法"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null,
            "parentTypeId": 44,
            "parentTypeName": "阅读题"
        }
    ]
})