/*
 *
 * LeftNavC constants
 *
 */

export const DEFAULT_ACTION = 'app/LeftNavC/DEFAULT_ACTION';
export const GET_SUBJECT_ACTION = 'app/LeftNavC/GET_SUBJECT_ACTION';
export const GET_GRADE_ACTION = 'app/LeftNavC/GET_GRADE_ACTION';
export const GET_LESSONTYPE_ACTION = 'app/LeftNavC/GET_LESSONTYPE_ACTION';
export const SET_GRADELIST_ACTION = 'app/LeftNavC/SET_GRADELIST_ACTION';
export const SET_SUBJECTLIST_ACTION = 'app/LeftNavC/SET_SUBJECTLIST_ACTION';
export const SET_LESSONTYPELIST_ACTION = 'app/LeftNavC/SET_LESSONTYPELIST_ACTION';
export const CHANGE_ALERT_SHOW_OR_HIDE_ACTION = 'app/LeftNavC/CHANGE_ALERT_SHOW_OR_HIDE_ACTION';
export const SET_ALERT_STATES_ACTION = 'app/LeftNavC/SET_ALERT_STATES_ACTION';
export const CHANGE_DATA_GETTING_STATE_ACTION = 'app/GetAndCutPaper/CHANGE_DATA_GETTING_STATE_ACTION';
export const CHANGE_BACK_PROMPT_ALERT_SHOW_ACTION = 'app/GetAndCutPaper/CHANGE_BACK_PROMPT_ALERT_SHOW_ACTION';
export const SET_BACK_ALERT_STATES_ACTION = 'app/GetAndCutPaper/SET_BACK_ALERT_STATES_ACTION';
export const CHANGE_BTN_CAN_CLICK_ACTION = 'app/GetAndCutPaper/CHANGE_BTN_CAN_CLICK_ACTION';
export const CHANGE_ISLOADING_STATE_ACTION = 'app/GetAndCutPaper/CHANGE_ISLOADING_STATE_ACTION';
