export const simulateData = {
    "code": "0",
    "message": "",
    "data": {
        "id": 200,
        "name": "模拟数学",
        "typeId": 1,
        "businessCardId": 2,
        "examTypeId": 1,
        "subjectId": 2,
        "gradeId": 2,
        "termId": 2,
        "year": 2017,
        "averageScore": null,
        "quoteCount": null,
        "storageTime": null,
        "questionAmount": 4,
        "createdUser": 180,
        "createUserName": "唐测试（不要删除）",
        "updatedTime": 1515728672000,
        "state": 11,
        "provinceId": 0,
        "cityId": null,
        "countyId": null,
        "picUrlList": [
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-0.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-1.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-2.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-3.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-4.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-5.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-6.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-7.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-8.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-9.png",
            "https://oss-cn-beijing.aliyuncs.com/zm-tiku/3b1e7cf2-4baa-4f09-934a-c9c00a7c748c/slide-10.png"
        ],
        "examPaperContentOutputDTOList": [
            {
                "id": 230,
                "serialNumber": 1,
                "name": "这是一份数学试卷",
                "examPaperContentQuestionOutputDTOList": [
                    {
                        "id": 601,
                        "serialNumber": 1,
                        "questionId": 601,
                        "questionOutputDTO": {
                            "id": 601,
                            "title": "<p>化学与社会、科学、技术、环境等有密切联系。下列有关说法正确的是</p>",
                            "optionList": [
                                "<p><span style=\"font-size:10.5pt;font-family:宋体;\nmso-ascii-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;\nmso-font-kerning:1.0pt;mso-ansi-language:EN-US;mso-fareast-language:ZH-CN;\nmso-bidi-language:AR-SA\">用浸泡过酸性高锰酸钾溶液的硅藻土吸收水果产生的乙烯以达到保鲜目的</span>&nbsp;<br></p>",
                                "<p><span lang=\"EN-US\" style=\"font-size:10.5pt;font-family:\n&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:宋体;mso-font-kerning:1.0pt;\nmso-ansi-language:EN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA\">PM\n2.5</span><span style=\"font-size:10.5pt;font-family:宋体;mso-ascii-font-family:\n&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-font-kerning:1.0pt;\nmso-ansi-language:EN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA\">是指氮、硫的氧化物溶于水形成的酸性液体造成的空气污染</span>&nbsp;<br></p>",
                                "<p><span style=\"font-size:10.5pt;font-family:宋体;\nmso-ascii-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;\nmso-font-kerning:1.0pt;mso-ansi-language:EN-US;mso-fareast-language:ZH-CN;\nmso-bidi-language:AR-SA\">新型材料聚酯纤维、光导纤维都属于有机高分子</span>&nbsp;<br></p>",
                                "<p><span style=\"font-size:10.5pt;font-family:宋体;\nmso-ascii-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;\nmso-font-kerning:1.0pt;mso-ansi-language:EN-US;mso-fareast-language:ZH-CN;\nmso-bidi-language:AR-SA\">在食品袋中放入盛有硅胶的透气袋，可防止食物氧化变质</span>&nbsp;<br></p>"
                            ],
                            "answerList": [
                                "A"
                            ],
                            "analysis": "<p>A．乙烯具有催熟作用，高锰酸钾能氧化乙烯，则用浸泡过的高锰酸钾溶液的硅藻土吸收水果释放的乙烯，可达到水果保鲜的目的，A正确；B．PM2.5为固体颗粒物导致的空气污染，而氮、硫的氧化物溶于水形成的酸性液体为酸雨，B错误；C．光导纤维是二氧化硅制成的，不是有机高分子，C错误；D、硅胶是干燥剂。不能防止食品氧化，D错误，答案选A。</p>",
                            "subjectId": 2,
                            "gradeId": 2,
                            "termId": 2,
                            "typeId": 1,
                            "provinceId": 0,
                            "cityId": null,
                            "countyId": null,
                            "schoolId": null,
                            "year": null,
                            "score": 3,
                            "sourceId": null,
                            "difficulty": 1,
                            "distinction": 2,
                            "recommendationIndex": null,
                            "rating": 2,
                            "comprehensiveDegreeId": null,
                            "abilityIdList": [],
                            "subjectCharacteristicIdList": [],
                            "editionIdList": [],
                            "chapterIdList": [],
                            "knowledgeIdList": [
                                9,
                                10
                            ],
                            "examPointIdList": [
                                13077
                            ],
                            "keywordList": null,
                            "coreLiteracyIdList": [],
                            "courseSystemIdList": [],
                            "costTime": null,
                            "browseCount": null,
                            "quoteCount": null,
                            "examCount": null,
                            "correctRate": null,
                            "storageTime": null,
                            "sub": false,
                            "state": 11,
                            "createdTime": 1514372013000,
                            "createdUser": 1294978438,
                            "updatedTime": 1515728672000,
                            "updatedUser": 1294978438,
                            "versions": null,
                            "remarks": null,
                            "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20171227122454_4997.jpeg",
                            "cutUserId": 1294978438,
                            "auditCutUserId": 180,
                            "entryUserId": 1294978438,
                            "auditEntryUserId": 180,
                            "tagUserId1": 1294978438,
                            "tagUserId2": 180,
                            "auditTagUserId": 1294978438,
                            "cutTime": 1514372013000,
                            "auditCutTime": 1514372040000,
                            "entryTime": 1514372231000,
                            "auditEntryTime": 1514372596000,
                            "tag1Time": 1514372687000,
                            "tag2Time": 1514619938000,
                            "auditTagTime": 1515728672000,
                            "errType": 0,
                            "errReason": "",
                            "templateType": 2,
                            "adoptUser1Tag": false,
                            "adoptUser2Tag": true,
                            "children": null,
                            "questionTag1": {
                                "id": 348,
                                "epId": 200,
                                "questionId": 601,
                                "sourceId": null,
                                "difficulty": 2,
                                "distinction": 2,
                                "recommendationIndex": 3,
                                "rating": 2,
                                "comprehensiveDegreeId": 2,
                                "knowledgeIds": "9,10",
                                "examPointIds": "13077",
                                "subjectCharacteristicIds": null,
                                "abilityIds": null,
                                "keywords": null,
                                "coreLiteracyIds": null,
                                "editionIds": null,
                                "chapterIds": null,
                                "courseSystemIds": null,
                                "createdTime": 1514619593000,
                                "createdUser": 1294978438,
                                "updatedTime": 1514619593000,
                                "updatedUser": 1294978438,
                                "children": []
                            },
                            "questionTag2": {
                                "id": 352,
                                "epId": 200,
                                "questionId": 601,
                                "sourceId": null,
                                "difficulty": 1,
                                "distinction": 1,
                                "recommendationIndex": 3,
                                "rating": 1,
                                "comprehensiveDegreeId": 1,
                                "knowledgeIds": null,
                                "examPointIds": null,
                                "subjectCharacteristicIds": null,
                                "abilityIds": null,
                                "keywords": null,
                                "coreLiteracyIds": null,
                                "editionIds": null,
                                "chapterIds": null,
                                "courseSystemIds": null,
                                "createdTime": 1514619938000,
                                "createdUser": 180,
                                "updatedTime": 1514619938000,
                                "updatedUser": 180,
                                "children": []
                            },
                            "tagAdopt": 2,
                            "tagReason": "哈哈哈哈哈哈，就是不对"
                        }
                    },
                    {
                        "id": 602,
                        "serialNumber": 2,
                        "questionId": 602,
                        "questionOutputDTO": {
                            "id": 602,
                            "title": "<p>设NA表示阿伏加德罗常数的数值，下列说法正确的是</p>",
                            "optionList": [
                                "<p><span lang=\"EN-US\" style=\"font-size:10.5pt;font-family:\n&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;\nmso-font-kerning:1.0pt;mso-ansi-language:EN-US;mso-fareast-language:ZH-CN;\nmso-bidi-language:AR-SA\">80 mL10 mol/L</span><span style=\"font-size:10.5pt;\nfont-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;\nmso-font-kerning:1.0pt;mso-ansi-language:EN-US;mso-fareast-language:ZH-CN;\nmso-bidi-language:AR-SA\">的浓盐酸与足量<span lang=\"EN-US\">MnO<sub>2</sub></span>反应，转移电子数为<span lang=\"EN-US\">0.4 N<sub>A</sub></span></span>&nbsp;<br></p>",
                                "<p><span style=\"font-size:10.5pt;font-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;\nmso-bidi-font-family:&quot;Times New Roman&quot;;mso-font-kerning:1.0pt;mso-ansi-language:\nEN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA\">通入了<span lang=\"EN-US\">1\nmol Cl<sub>2</sub></span>的新制氯水中，<span lang=\"EN-US\">HC1O</span>、<span lang=\"EN-US\">Cl</span><sup>－</sup>、<span lang=\"EN-US\">C1O</span><sup>－</sup>粒子数之和为<span lang=\"EN-US\">2N<sub>A</sub></span></span>&nbsp;<br></p>",
                                "<p><span lang=\"EN-US\" style=\"font-size:10.5pt;font-family:\n&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;\nmso-font-kerning:1.0pt;mso-ansi-language:EN-US;mso-fareast-language:ZH-CN;\nmso-bidi-language:AR-SA\">1 mol Na<sub>2</sub>O<sub>2</sub></span><span style=\"font-size:10.5pt;font-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;mso-bidi-font-family:\n&quot;Times New Roman&quot;;mso-font-kerning:1.0pt;mso-ansi-language:EN-US;mso-fareast-language:\nZH-CN;mso-bidi-language:AR-SA\">中含有的阴离子数为<span lang=\"EN-US\">2 N<sub>A</sub></span></span>&nbsp;<br></p>",
                                "<p><span style=\"font-size:10.5pt;font-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;\nmso-bidi-font-family:&quot;Times New Roman&quot;;mso-font-kerning:1.0pt;mso-ansi-language:\nEN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA\">标准状况下，<st1:chmetcnv unitname=\"l\" sourcevalue=\"4.48\" hasspace=\"False\" negative=\"False\" numbertype=\"1\" tcsc=\"0\" w:st=\"on\"><span lang=\"EN-US\">4.48L</span></st1:chmetcnv><span lang=\"EN-US\"> NH<sub>3</sub></span>中共用电子对数为<span lang=\"EN-US\">0.6 N<sub>A</sub>&nbsp;</span></span><br></p>"
                            ],
                            "answerList": [
                                "D"
                            ],
                            "analysis": "<p>A．稀盐酸与二氧化锰不反应，因此80 mL10 mol/L的浓盐酸与足量MnO2反应，转移电子数小于0.4 NA，A错误；B．通入了1 mol Cl2的新制氯水中，HC1O、Cl－、C1O－粒子数之和小于2NA，意外还有未反应的氯气，B错误；C．1 mol Na2O2中含有的阴离子数为 NA，C错误；D．标准状况下，4.48L NH3是0.2mol，其中共用电子对数为0.6 NA，D正确，答案选D。</p>",
                            "subjectId": 2,
                            "gradeId": 2,
                            "termId": 2,
                            "typeId": 3,
                            "provinceId": 0,
                            "cityId": null,
                            "countyId": null,
                            "schoolId": null,
                            "year": null,
                            "score": 3,
                            "sourceId": null,
                            "difficulty": 2,
                            "distinction": 2,
                            "recommendationIndex": null,
                            "rating": 2,
                            "comprehensiveDegreeId": null,
                            "abilityIdList": [],
                            "subjectCharacteristicIdList": [],
                            "editionIdList": [],
                            "chapterIdList": [],
                            "knowledgeIdList": [
                                342,
                                343,
                                346
                            ],
                            "examPointIdList": [
                                13077
                            ],
                            "keywordList": null,
                            "coreLiteracyIdList": [],
                            "courseSystemIdList": [],
                            "costTime": null,
                            "browseCount": null,
                            "quoteCount": null,
                            "examCount": null,
                            "correctRate": null,
                            "storageTime": null,
                            "sub": false,
                            "state": 11,
                            "createdTime": 1514372013000,
                            "createdUser": 1294978438,
                            "updatedTime": 1515728672000,
                            "updatedUser": 1294978438,
                            "versions": null,
                            "remarks": null,
                            "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20171227122502_3146.jpeg",
                            "cutUserId": 1294978438,
                            "auditCutUserId": 180,
                            "entryUserId": 1294978438,
                            "auditEntryUserId": 180,
                            "tagUserId1": 1294978438,
                            "tagUserId2": 180,
                            "auditTagUserId": 1294978438,
                            "cutTime": 1514372013000,
                            "auditCutTime": 1514372040000,
                            "entryTime": 1514372316000,
                            "auditEntryTime": 1514372596000,
                            "tag1Time": 1514372718000,
                            "tag2Time": 1514619949000,
                            "auditTagTime": 1515728672000,
                            "errType": 0,
                            "errReason": "",
                            "templateType": 2,
                            "adoptUser1Tag": true,
                            "adoptUser2Tag": true,
                            "children": null,
                            "questionTag1": {
                                "id": 349,
                                "epId": 200,
                                "questionId": 602,
                                "sourceId": null,
                                "difficulty": 2,
                                "distinction": 2,
                                "recommendationIndex": 3,
                                "rating": 2,
                                "comprehensiveDegreeId": 2,
                                "knowledgeIds": "342,343",
                                "examPointIds": "13077",
                                "subjectCharacteristicIds": null,
                                "abilityIds": null,
                                "keywords": null,
                                "coreLiteracyIds": null,
                                "editionIds": null,
                                "chapterIds": null,
                                "courseSystemIds": null,
                                "createdTime": 1514619606000,
                                "createdUser": 1294978438,
                                "updatedTime": 1514619606000,
                                "updatedUser": 1294978438,
                                "children": []
                            },
                            "questionTag2": {
                                "id": 353,
                                "epId": 200,
                                "questionId": 602,
                                "sourceId": null,
                                "difficulty": 2,
                                "distinction": 2,
                                "recommendationIndex": 3,
                                "rating": 2,
                                "comprehensiveDegreeId": 2,
                                "knowledgeIds": null,
                                "examPointIds": "13077",
                                "subjectCharacteristicIds": null,
                                "abilityIds": null,
                                "keywords": null,
                                "coreLiteracyIds": null,
                                "editionIds": null,
                                "chapterIds": null,
                                "courseSystemIds": null,
                                "createdTime": 1514619949000,
                                "createdUser": 180,
                                "updatedTime": 1514619949000,
                                "updatedUser": 180,
                                "children": []
                            },
                            "tagAdopt": 3,
                            "tagReason": ""
                        }
                    }
                ]
            },
            {
                "id": 231,
                "serialNumber": 2,
                "name": "相信我，真的时数学",
                "examPaperContentQuestionOutputDTOList": [
                    {
                        "id": 603,
                        "serialNumber": 3,
                        "questionId": 603,
                        "questionOutputDTO": {
                            "id": 603,
                            "title": "<p>这是一道选择题</p>",
                            "optionList": [],
                            "answerList": [],
                            "analysis": null,
                            "subjectId": 2,
                            "gradeId": 2,
                            "termId": 2,
                            "typeId": 8,
                            "provinceId": 0,
                            "cityId": null,
                            "countyId": null,
                            "schoolId": null,
                            "year": null,
                            "score": 3,
                            "sourceId": null,
                            "difficulty": 3,
                            "distinction": 3,
                            "recommendationIndex": null,
                            "rating": 3,
                            "comprehensiveDegreeId": null,
                            "abilityIdList": [],
                            "subjectCharacteristicIdList": [],
                            "editionIdList": [],
                            "chapterIdList": [],
                            "knowledgeIdList": [
                                18,
                                19
                            ],
                            "examPointIdList": [
                                13078
                            ],
                            "keywordList": null,
                            "coreLiteracyIdList": [],
                            "courseSystemIdList": [],
                            "costTime": null,
                            "browseCount": null,
                            "quoteCount": null,
                            "examCount": null,
                            "correctRate": null,
                            "storageTime": null,
                            "sub": true,
                            "state": 11,
                            "createdTime": 1514372013000,
                            "createdUser": 1294978438,
                            "updatedTime": 1515728672000,
                            "updatedUser": 1294978438,
                            "versions": null,
                            "remarks": null,
                            "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20171227122523_6293.jpeg",
                            "cutUserId": 1294978438,
                            "auditCutUserId": 180,
                            "entryUserId": 1294978438,
                            "auditEntryUserId": 180,
                            "tagUserId1": 1294978438,
                            "tagUserId2": 180,
                            "auditTagUserId": 1294978438,
                            "cutTime": 1514372013000,
                            "auditCutTime": 1514372040000,
                            "entryTime": 1514372432000,
                            "auditEntryTime": 1514372596000,
                            "tag1Time": 1514372770000,
                            "tag2Time": 1514619990000,
                            "auditTagTime": 1515728672000,
                            "errType": 0,
                            "errReason": "",
                            "templateType": 1,
                            "adoptUser1Tag": true,
                            "adoptUser2Tag": false,
                            "children": [
                                {
                                    "id": 217,
                                    "questionId": 603,
                                    "title": "<p><span style=\"font-size:10.5pt;font-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;\nmso-bidi-font-family:&quot;Times New Roman&quot;;mso-font-kerning:1.0pt;mso-ansi-language:\nEN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA\">某有机物分子式为<span lang=\"EN-US\">C<sub>4</sub>H<sub>8</sub></span>，据此推测其结构和性质均正确的是</span>&nbsp;<br></p>",
                                    "optionList": [
                                        "<p><span style=\"font-size:10.5pt;font-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;\nmso-bidi-font-family:&quot;Times New Roman&quot;;mso-font-kerning:1.0pt;mso-ansi-language:\nEN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA\">它与乙烯一定是同系物</span>&nbsp;<br></p>",
                                        "<p><span style=\"font-size:10.5pt;font-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;\nmso-bidi-font-family:&quot;Times New Roman&quot;;mso-font-kerning:1.0pt;mso-ansi-language:\nEN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA\">它一定能使溴水褪色</span>&nbsp;<br></p>",
                                        "<p><span style=\"font-size:10.5pt;font-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;\nmso-bidi-font-family:&quot;Times New Roman&quot;;mso-font-kerning:1.0pt;mso-ansi-language:\nEN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA\">它的一氯代物可能只有一种</span>&nbsp;<br></p>",
                                        "<p><span style=\"font-size:10.5pt;font-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;\nmso-bidi-font-family:&quot;Times New Roman&quot;;mso-font-kerning:1.0pt;mso-ansi-language:\nEN-US;mso-fareast-language:ZH-CN;mso-bidi-language:AR-SA\">等质量<span lang=\"EN-US\">CH<sub>4</sub></span>和<span lang=\"EN-US\">C<sub>4</sub>H<sub>8</sub></span>分别在氧气中完全燃烧，<span lang=\"EN-US\">CH<sub>4</sub></span>的耗氧量小于<span lang=\"EN-US\">C<sub>4</sub>H<sub>8</sub></span></span>&nbsp;<br></p>"
                                    ],
                                    "answerList": [
                                        "C"
                                    ],
                                    "analysis": "<p><span style=\"font-size:10.5pt;font-family:&quot;思源黑体 CN Normal&quot;,&quot;sans-serif&quot;;\nmso-bidi-font-family:&quot;Times New Roman&quot;;color:black;mso-themecolor:text1;\nmso-font-kerning:1.0pt;mso-ansi-language:EN-US;mso-fareast-language:ZH-CN;\nmso-bidi-language:AR-SA;mso-bidi-font-weight:bold\">考查有机物结构和性质</span>&nbsp;<br></p>",
                                    "typeId": 2,
                                    "score": 3,
                                    "difficulty": null,
                                    "knowledgeIdList": null,
                                    "examPointIdList": null
                                }
                            ],
                            "questionTag1": {
                                "id": 350,
                                "epId": 200,
                                "questionId": 603,
                                "sourceId": null,
                                "difficulty": 3,
                                "distinction": 3,
                                "recommendationIndex": 3,
                                "rating": 3,
                                "comprehensiveDegreeId": 3,
                                "knowledgeIds": "18,19",
                                "examPointIds": "13078",
                                "subjectCharacteristicIds": null,
                                "abilityIds": null,
                                "keywords": null,
                                "coreLiteracyIds": null,
                                "editionIds": null,
                                "chapterIds": null,
                                "courseSystemIds": null,
                                "createdTime": 1514619660000,
                                "createdUser": 1294978438,
                                "updatedTime": 1514619660000,
                                "updatedUser": 1294978438,
                                "children": [
                                    {
                                        "id": 254,
                                        "subQuestionId": 217,
                                        "knowledgeIds": "89,90",
                                        "examPointIds": "13078",
                                        "createdUser": 1294978438,
                                        "createdTime": 1514619660000,
                                        "updatedUser": 1294978438,
                                        "updatedTime": 1514619660000,
                                        "qtId": 350,
                                        "questionId": 603
                                    }
                                ]
                            },
                            "questionTag2": {
                                "id": 354,
                                "epId": 200,
                                "questionId": 603,
                                "sourceId": null,
                                "difficulty": 3,
                                "distinction": 3,
                                "recommendationIndex": 3,
                                "rating": 3,
                                "comprehensiveDegreeId": 3,
                                "knowledgeIds": null,
                                "examPointIds": null,
                                "subjectCharacteristicIds": null,
                                "abilityIds": null,
                                "keywords": null,
                                "coreLiteracyIds": null,
                                "editionIds": null,
                                "chapterIds": null,
                                "courseSystemIds": null,
                                "createdTime": 1514619990000,
                                "createdUser": 180,
                                "updatedTime": 1514619990000,
                                "updatedUser": 180,
                                "children": []
                            },
                            "tagAdopt": 1,
                            "tagReason": "的方式的，所以呢"
                        }
                    },
                    {
                        "id": 604,
                        "serialNumber": 4,
                        "questionId": 604,
                        "questionOutputDTO": {
                            "id": 604,
                            "title": "<p>下列实验中，对应的现象以及结论都正确且两者具有因果关系的是</p>     <p align=\"center\" >选项</p>      <p align=\"center\" >实验</p>      <p align=\"center\" >现象</p>      <p align=\"center\" >结论</p>        <p align=\"center\" >A</p>      <p >炭粉中加入浓硝酸并加热，导出的气体通入少量澄清石灰水中</p>      <p >有红棕色气体产生，石灰水变浑浊</p>      <p >有NO2和CO2产生</p>        <p align=\"center\" >B</p>      <p  >加热盛有NH4Cl固体的试管</p>      <p  >试管底部固体消失，试管口有晶体凝结</p>      <p  >NH4Cl固体可以升华</p>        <p  align=\"center\" >C</p>      <p  >向含I－的无色溶液中滴加少量新制氯水，再滴加淀粉溶液</p>      <p  >加入淀粉后溶液变成蓝色</p>      <p  >氧化性：Cl2 &gt; I2</p>        <p align=\"center\" >D</p>      <p >蔗糖中滴加浓硫酸并不断搅拌</p>      <p >产生黑色蓬松多孔固体</p>      <p >浓硫酸具有吸水性和强氧化性</p>   ",
                            "optionList": [],
                            "answerList": [
                                "<p>C</p>"
                            ],
                            "analysis": "<p>A、NO2溶于水生成硝酸，硝酸与石灰水反应，CO2不能与氢氧化钙反应产生白色沉淀，A错误；B、氯化铵分解生成的氨气和氯化氢在试管口又重新结合生成氯化铵，不是升华，B错误；C、溶液变蓝，说明有碘生成，因此氯气的氧化性强于碘，C正确；D、体现浓硫酸的脱水性和氧化性，D错误，答案选C。</p>",
                            "subjectId": 2,
                            "gradeId": 2,
                            "termId": 2,
                            "typeId": 27,
                            "provinceId": 0,
                            "cityId": null,
                            "countyId": null,
                            "schoolId": null,
                            "year": null,
                            "score": 3,
                            "sourceId": null,
                            "difficulty": 2,
                            "distinction": 1,
                            "recommendationIndex": null,
                            "rating": 1,
                            "comprehensiveDegreeId": null,
                            "abilityIdList": [],
                            "subjectCharacteristicIdList": [],
                            "editionIdList": [],
                            "chapterIdList": [],
                            "knowledgeIdList": [
                                172,
                                173
                            ],
                            "examPointIdList": [
                                13077
                            ],
                            "keywordList": null,
                            "coreLiteracyIdList": [],
                            "courseSystemIdList": [],
                            "costTime": null,
                            "browseCount": null,
                            "quoteCount": null,
                            "examCount": null,
                            "correctRate": null,
                            "storageTime": null,
                            "sub": false,
                            "state": 11,
                            "createdTime": 1514372013000,
                            "createdUser": 1294978438,
                            "updatedTime": 1515728672000,
                            "updatedUser": 1294978438,
                            "versions": null,
                            "remarks": null,
                            "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20171227122539_9780.jpeg",
                            "cutUserId": 1294978438,
                            "auditCutUserId": 180,
                            "entryUserId": 1294978438,
                            "auditEntryUserId": 180,
                            "tagUserId1": 1294978438,
                            "tagUserId2": 180,
                            "auditTagUserId": 1294978438,
                            "cutTime": 1514372013000,
                            "auditCutTime": 1514372040000,
                            "entryTime": 1514372540000,
                            "auditEntryTime": 1514372596000,
                            "tag1Time": 1514372840000,
                            "tag2Time": 1514620000000,
                            "auditTagTime": 1515728672000,
                            "errType": 0,
                            "errReason": "",
                            "templateType": 4,
                            "adoptUser1Tag": false,
                            "adoptUser2Tag": false,
                            "children": null,
                            "questionTag1": {
                                "id": 351,
                                "epId": 200,
                                "questionId": 604,
                                "sourceId": null,
                                "difficulty": 1,
                                "distinction": 1,
                                "recommendationIndex": 3,
                                "rating": 1,
                                "comprehensiveDegreeId": 1,
                                "knowledgeIds": "172,173",
                                "examPointIds": "13077",
                                "subjectCharacteristicIds": null,
                                "abilityIds": null,
                                "keywords": null,
                                "coreLiteracyIds": null,
                                "editionIds": null,
                                "chapterIds": null,
                                "courseSystemIds": null,
                                "createdTime": 1514619674000,
                                "createdUser": 1294978438,
                                "updatedTime": 1514619674000,
                                "updatedUser": 1294978438,
                                "children": []
                            },
                            "questionTag2": {
                                "id": 355,
                                "epId": 200,
                                "questionId": 604,
                                "sourceId": null,
                                "difficulty": 4,
                                "distinction": 1,
                                "recommendationIndex": 3,
                                "rating": 1,
                                "comprehensiveDegreeId": 1,
                                "knowledgeIds": null,
                                "examPointIds": null,
                                "subjectCharacteristicIds": null,
                                "abilityIds": null,
                                "keywords": null,
                                "coreLiteracyIds": null,
                                "editionIds": null,
                                "chapterIds": null,
                                "courseSystemIds": null,
                                "createdTime": 1514620000000,
                                "createdUser": 180,
                                "updatedTime": 1514620000000,
                                "updatedUser": 180,
                                "children": []
                            },
                            "tagAdopt": 4,
                            "tagReason": "都不对哦"
                        }
                    }
                ]
            }
        ],
        "tagUserId1": 180,
        "tagUserId2": 1294978438,
        "fileUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20171227121803_8031.doc",
        "editionId": 2,
        "tag1SubmitFlag": true,
        "tag2SubmitFlag": true,
        "cutUserId": 1294978438,
        "auditCutUserId": 180,
        "entryUserId": 1294978438,
        "auditEntryUserId": 180,
        "auditTagUserId": 1294978438,
        "cutTime": 1514372013000,
        "auditCutTime": 1514372040000,
        "entryTime": 1514372545000,
        "auditEntryTime": 1514372596000,
        "tag1Time": 1514620003000,
        "tag2Time": 1514619689000,
        "auditTagTime": 1515728672000,
        "cutReceiveTime": 1483200000000,
        "entryReceiveTime": null,
        "tagReceiveTime1": null,
        "tagReceiveTime2": null,
        "entryUserName": "张银杰(测试账号)"
    }
};
