/*
 *
 * PaperCutVerify constants
 *
 */

export const DEFAULT_ACTION = 'app/PaperCutVerify/DEFAULT_ACTION';
export const CHANGE_PAGE_STATE_ACTION = 'app/PaperCutVerify/CHANGE_PAGE_STATE_ACTION';
export const CHANGE_IMG_SRC_ACTION = 'app/PaperCutVerify/CHANGE_IMG_SRC_ACTION';
export const GET_PAPER_MSG_ACTION = 'app/PaperCutVerify/GET_PAPER_MSG_ACTION';
export const CHANGE_PAPER_STATE_ACTION = 'app/PaperCutVerify/CHANGE_PAPER_STATE_ACTION';
export const CHANGE_ALERT_SHOW_OR_HIDE_ACTION = 'app/PaperCutVerify/CHANGE_ALERT_SHOW_OR_HIDE_ACTION';
export const SET_PAPER_LIST_ACTION = 'app/PaperCutVerify/SET_PAPER_LIST_ACTION';
export const CHANGE_NOT_GET_PAPER_COUNT_ACTION = 'app/PaperCutVerify/CHANGE_NOT_GET_PAPER_COUNT_ACTION';
export const CHANGE_HAS_GET_PAPER_COUNT_ACTION = 'app/PaperCutVerify/CHANGE_HAS_GET_PAPER_COUNT_ACTION';
export const CHANGE_CURRENT_PAPER_ITEM_ACTION = 'app/PaperCutVerify/CHANGE_CURRENT_PAPER_ITEM_ACTION';
export const CHANGE_NEED_VERIFY_PAPER_ID_ACTION = 'app/PaperCutVerify/CHANGE_NEED_VERIFY_PAPER_ID_ACTION';
export const CHANGE_NEED_VERIFY_PAPER_ITEM_ACTION = 'app/PaperCutVerify/CHANGE_NEED_VERIFY_PAPER_ITEM_ACTION';
export const CHANGE_SELECTED_QUESTION_INDEX_ACTION = 'app/PaperCutVerify/CHANGE_SELECTED_QUESTION_INDEX_ACTION';
export const CHANGE_QUESTION_LIST_ACTION = 'app/PaperCutVerify/CHANGE_QUESTION_LIST_ACTION';
export const CHANGE_QUESTION_MSG_LIST_ACTION = 'app/PaperCutVerify/CHANGE_QUESTION_MSG_LIST_ACTION';
export const CHANGE_PREVIEW_IMG_SRC_ACTION = 'app/PaperCutVerify/CHANGE_PREVIEW_IMG_SRC_ACTION';
export const GET_ALL_QUESTION_TYPE_LIST_ACTION = 'app/PaperCutVerify/GET_ALL_QUESTION_TYPE_LIST_ACTION';
export const SET_ALL_QUESTION_TYPE_LIST_ACTION = 'app/PaperCutVerify/SET_ALL_QUESTION_TYPE_LIST_ACTION';
export const CHANGE_ERR_TEXTAREA_SHOW_ACTION = 'app/PaperCutVerify/CHANGE_ERR_TEXTAREA_SHOW_ACTION';
export const CHANGE_QUESTION_RESULT_ACTION = 'app/PaperCutVerify/CHANGE_QUESTION_RESULT_ACTION';
export const CHANGE_REAL_QUESTION_COUNT_ACTION = 'app/PaperCutVerify/CHANGE_REAL_QUESTION_COUNT_ACTION';
export const CHANGE_QUESTION_RESULT_STATE_ACTION = 'app/PaperCutVerify/CHANGE_QUESTION_RESULT_STATE_ACTION';
export const SUBMIT_QUESTION_CUT_VERIFY_ACTION = 'app/PaperCutVerify/SUBMIT_QUESTION_CUT_VERIFY_ACTION';
export const CHANGE_PAGE_INDEX_ACTION = 'app/PaperCutVerify/CHANGE_PAGE_INDEX_ACTION';
export const CHANGE_SORT_ACTION = 'app/PaperCutVerify/CHANGE_SORT_ACTION';
export const INIT_VERIFY_DATA_ACTION = 'app/PaperCutVerify/INIT_VERIFY_DATA_ACTION';
export const SET_PAPER_DOWNLOAD_MSG_ACTION = 'app/PaperCutVerify/SET_PAPER_DOWNLOAD_MSG_ACTION';
export const CHANGE_SHOW_SUBMIT_BTN_ACTION = 'app/PaperCutVerify/CHANGE_SHOW_SUBMIT_BTN_ACTION';
