/*
 *
 * StandHomeWork constants
 *
 */

export const DEFAULT_ACTION = 'app/StandHomeWork/DEFAULT_ACTION';
export const GET_GRADE_LIST_ACTION = 'app/StandHomeWork/GET_GRADE_LIST_ACTION';
export const SET_PREVIEW_SELECT_OBJ_ACTION = 'app/StandHomeWork/SET_PREVIEW_SELECT_OBJ_ACTION';
export const GET_SUBJECT_LIST_ACTION = 'app/StandHomeWork/GET_SUBJECT_LIST_ACTION';
export const GET_COURSE_LIST_ACTION = 'app/StandHomeWork/GET_COURSE_LIST_ACTION';
export const GET_EDITION_LIST_ACTION = 'app/StandHomeWork/GET_EDITION_LIST_ACTION';
export const SET_SEARCH_PARAMS_ACTION = 'app/StandHomeWork/SET_SEARCH_PARAMS_ACTION';
export const GET_PHASE_SUBJECT_ACTION = 'app/StandHomeWork/GET_PHASE_SUBJECT_ACTION';
export const SET_SEARCH_QUESTION_PARAMS_ACTION = 'app/StandHomeWork/SET_SEARCH_QUESTION_PARAMS_ACTION';
export const SET_SEARCH_QUESTION_PARAMS_ITEM_ACTION = 'app/StandHomeWork/SET_SEARCH_QUESTION_PARAMS_ITEM_ACTION';
export const GET_KNOWLEDEGE_LIST_ACTION = 'app/StandHomeWork/GET_KNOWLEDEGE_LIST_ACTION';
export const GET_QUESTION_TYPE_LIST_ACTION = 'app/StandHomeWork/GET_QUESTION_TYPE_LIST_ACTION';
export const SET_CREATE_HOMEWORK_STEP_PARAMS_ACTION = 'app/StandHomeWork/SET_CREATE_HOMEWORK_STEP_PARAMS_ACTION';
export const GET_QUESTION_LIST_ACTION = 'app/StandHomeWork/GET_QUESTION_LIST_ACTION';
export const SAVE_STAND_HOMEWORK_ACTION = 'app/StandHomeWork/SAVE_STAND_HOMEWORK_ACTION';
export const INIT_DATA_WHEN_CLOSE_ACTION = 'app/StandHomeWork/INIT_DATA_WHEN_CLOSE_ACTION';
export const GET_STAND_HOMEWORK_LIST_ACTION = 'app/StandHomeWork/GET_STAND_HOMEWORK_LIST_ACTION';
export const GET_PREVIEW_HOMEWORK_DATA_LIST_ACTION = 'app/StandHomeWork/GET_PREVIEW_HOMEWORK_DATA_LIST_ACTION';
export const SET_PREVIEW_HOMEWORK_DATA_LIST_ACTION = 'app/StandHomeWork/SET_PREVIEW_HOMEWORK_DATA_LIST_ACTION';
//  export const INIT_PREVIEW_DATA_ACTION = 'app/StandHomeWork/INIT_PREVIEW_DATA_ACTION';
export const EDIT_HOMEWORK_ACTION = 'app/StandHomeWork/EDIT_HOMEWORK_ACTION';
export const GET_ALL_GRADE_LIST_ACTION = 'app/StandHomeWork/GET_ALL_GRADE_LIST_ACTION';
export const SET_ALL_GRADE_LIST_ACTION = 'app/StandHomeWork/SET_ALL_GRADE_LIST_ACTION';
export const DELETE_HOMEWORK_ACTION = 'app/StandHomeWork/DELETE_HOMEWORK_ACTION';
export const CHANGE_IS_REEDIT_HOMEWORK_ACTION = 'app/StandHomeWork/CHANGE_IS_REEDIT_HOMEWORK_ACTION';
export const CHANGE_HOMEWORK_TYPE_ACTION = 'app/StandHomeWork/CHANGE_HOMEWORK_TYPE_ACTION';
export const GET_KNOWLEDGELIST_BY_CSID_ACTION = 'app/StandHomeWork/GET_KNOWLEDGELIST_BY_CSID_ACTION';
export const SET_AI_HOMEWORK_PARAMS_ITEM_ACTION = 'app/StandHomeWork/SET_AI_HOMEWORK_PARAMS_ITEM_ACTION';
export const GET_QUESTION_TYPE_FOR_AIHW_ACTION = 'app/StandHomeWork/GET_QUESTION_TYPE_FOR_AIHW_ACTION';
export const SET_AI_HOMEWORK_PARAMS_ACTION = 'app/StandHomeWork/SET_AI_HOMEWORK_PARAMS_ACTION';
export const GET_QUESTION_FOR_AIHW_ACTION = 'app/StandHomeWork/GET_QUESTION_FOR_AIHW_ACTION';
export const SAVE_AI_HOMEWORK_ACTION = 'app/StandHomeWork/SAVE_AI_HOMEWORK_ACTION';
export const SET_CREATE_HOMEWORK_STEP_PARAMS_ITEM_ACTION = 'app/StandHomeWork/SET_CREATE_HOMEWORK_STEP_PARAMS_ITEM_ACTION';
export const GET_CHANGE_ITEMDATALIST_ACTION = 'app/StandHomeWork/GET_CHANGE_ITEMDATALIST_ACTION';
export const CAHNGE_PAGE_STATE = 'app/StandHomeWork/CAHNGE_PAGE_STATE';
export const CLASS_TYPE_CODE = 'app/StandHomeWork/CLASS_TYPE_CODE';
export const SET_SLIDER_STATE = 'app/StandHomeWork/SET_SLIDER_STATE';
export const RESET_STATE = 'app/StandHomeWork/RESET_STATE';

// export default {
//   DEFAULT_ACTION,
//   DELETE_HOMEWORK_ACTION,
//   EDIT_HOMEWORK_ACTION,
//   GET_GRADE_LIST_ACTION,
//   GET_COURSE_LIST_ACTION,
//   GET_ALL_GRADE_LIST_ACTION,
//   GET_SUBJECT_LIST_ACTION,
//   GET_EDITION_LIST_ACTION,
//   GET_PHASE_SUBJECT_ACTION,
//   GET_KNOWLEDEGE_LIST_ACTION,
//   GET_QUESTION_LIST_ACTION,
//   GET_QUESTION_TYPE_LIST_ACTION,
//   GET_STAND_HOMEWORK_LIST_ACTION,
//   GET_PREVIEW_HOMEWORK_DATA_LIST_ACTION,
//   INIT_DATA_WHEN_CLOSE_ACTION,
//   SET_PREVIEW_HOMEWORK_DATA_LIST_ACTION,
//   SET_PREVIEW_SELECT_OBJ_ACTION,
//   SET_SEARCH_PARAMS_ACTION,
//   SET_SEARCH_QUESTION_PARAMS_ACTION,
//   SET_SEARCH_QUESTION_PARAMS_ITEM_ACTION,
//   SET_CREATE_HOMEWORK_STEP_PARAMS_ACTION,
//   SET_ALL_GRADE_LIST_ACTION,
//   SAVE_STAND_HOMEWORK_ACTION,
//   CHANGE_IS_REEDIT_HOMEWORK_ACTION,
//   CHANGE_HOMEWORK_TYPE_ACTION,
//   GET_KNOWLEDGELIST_BY_CSID_ACTION,
//   SET_AI_HOMEWORK_PARAMS_ITEM_ACTION,
//   GET_QUESTION_TYPE_FOR_AIHW_ACTION,
//   SET_AI_HOMEWORK_PARAMS_ACTION,
//   GET_QUESTION_FOR_AIHW_ACTION,
// };
export const SHELF_OR_OBTAINED_ACTION = 'app/StandHomeWork/SHELF_OR_OBTAINED_ACTION';
export const SAVE_RE_EDIT_HOMEOWK_ACTION = 'app/StandHomeWork/SAVE_RE_EDIT_HOMEOWK_ACTION';
