export const questionData = {
    "code": "0",
    "message": "",
    "data": [
        {
            "id": 358777,
            "title": "<p>asdasdasdfsd阿斯顿大少阿斯顿阿斯顿阿斯顿</p>",
            "content": null,
            "optionList": [
                "<p>大师傅士大夫士大夫稍等发</p>",
                "<p>为去问驱蚊器为</p>",
                "<p>的阿斯顿阿斯顿阿斯顿阿斯顿</p>",
                "<p>去问去问驱蚊器为</p>"
            ],
            "answerList": [
                "B"
            ],
            "analysis": "<p>似的发射点发射点发射点</p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": 1,
            "typeId": 1,
            "questionType": "单选题",
            "provinceId": 3,
            "cityId": 3,
            "countyId": 3,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 14,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                10569,
                112963
            ],
            "examPointIdList": [
                12963,
                15005
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 1,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": null,
            "createdUser": null,
            "updatedTime": null,
            "updatedUser": null,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": null,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "啊实打实",
                "作文"
            ],
            "examPointNameList": [
                "作文",
                "士大夫"
            ],
            "layoutStyle": null,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null
        },
        {
            "id": 360177,
            "title": "<p>dsfsafewg<br/></p>",
            "content": null,
            "optionList": null,
            "answerList": null,
            "analysis": null,
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": null,
            "typeId": 2,
            "questionType": "多选题",
            "provinceId": null,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 6,
            "sourceId": 6,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12688
            ],
            "examPointIdList": [],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 0,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": true,
            "state": null,
            "createdTime": null,
            "createdUser": null,
            "updatedTime": null,
            "updatedUser": null,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": null,
            "errReason": null,
            "templateType": 1,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": [
                {
                    "id": 644113,
                    "questionId": 360177,
                    "title": "<p>幅度萨芬萨<br/></p>",
                    "optionList": null,
                    "answerList": [
                        "<p>safas<br/></p>"
                    ],
                    "analysis": "<p>dsfsaf<br/></p>",
                    "typeId": 3,
                    "score": 3,
                    "difficulty": null,
                    "knowledgeIdList": null,
                    "examPointIdList": null,
                    "subQuestionMemberList": null
                },
                {
                    "id": 644114,
                    "questionId": 360177,
                    "title": "<p>dsfsaf<br/></p>",
                    "optionList": [
                        "<p>sdfsfas<br/></p>",
                        "<p>sdfsa<br/></p>",
                        "<p>fsa<br/></p>",
                        "<p>fasf<br/></p>"
                    ],
                    "answerList": [
                        "B"
                    ],
                    "analysis": "<p>dsfsafas<br/></p>",
                    "typeId": 2,
                    "score": 3,
                    "difficulty": null,
                    "knowledgeIdList": null,
                    "examPointIdList": null,
                    "subQuestionMemberList": null
                }
            ],
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": 3,
            "examTypeId": 1,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "阿斯顿士大夫士大夫"
            ],
            "examPointNameList": [],
            "layoutStyle": null,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null
        },
        {
            "id": 360016,
            "title": "<p>掌门的吉祥物是什么动物</p>",
            "content": null,
            "optionList": [
                "<p>狐狸<br/></p>",
                "<p>狸猫<br/></p>",
                "<p>兔子<br/></p>",
                "<p>斑马<img src=\"https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180531150637_8840.jpg\" zmtype=\"small\"/></p>"
            ],
            "answerList": [
                "A"
            ],
            "analysis": "<p>好吧。<br/></p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": null,
            "typeId": 2,
            "questionType": "多选题",
            "provinceId": null,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 5,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": [
                0,
                1
            ],
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12688
            ],
            "examPointIdList": [
                12963
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 2,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1527750458000,
            "createdUser": 1294979443,
            "updatedTime": 1528337511000,
            "updatedUser": 1294984332,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": null,
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": [
                1
            ],
            "suggestTime": 3,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "阿斯顿士大夫士大夫"
            ],
            "examPointNameList": [
                "作文"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": "2018年"
        },
        {
            "id": 360220,
            "title": "<p>阿萨法拉萨开发商开发举手的反馈申达股份阿萨法拉萨开发商开发举手的反馈申达股份阿萨法拉萨开发商开发举手的反馈申达股份阿萨法拉萨开发商开发举手的反馈申达股份阿萨法拉萨开发商开发举手的反馈申达股份阿萨法拉萨开发商开发举手的反馈申达股份阿萨法拉萨开发商开发举手的反馈申达股份阿萨法拉萨开发商开发举手的反馈申达股份阿萨法拉萨开发商开发举手的反馈申达股份阿萨法拉萨开发商开发举手的反馈申达股份</p>",
            "content": null,
            "optionList": [
                "<p><img src=\"https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180615111340_4930.png\" zmtype=\"small\"/></p>",
                "",
                "",
                ""
            ],
            "answerList": [
                "A",
                "B"
            ],
            "analysis": "<p>但是古代诗歌 稍等；根深蒂固&nbsp;<br/></p>",
            "subjectId": 2,
            "gradeId": 2,
            "phaseId": 1,
            "termId": null,
            "typeId": 2,
            "questionType": "多选题",
            "provinceId": null,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2017,
            "score": 0,
            "sourceId": 5,
            "difficulty": 2,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 2,
            "comprehensiveDegreeId": 2,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                10569
            ],
            "examPointIdList": [
                12963
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 0,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": null,
            "createdUser": null,
            "updatedTime": null,
            "updatedUser": null,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": null,
            "errReason": null,
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": 3,
            "examTypeId": 2,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "啊实打实"
            ],
            "examPointNameList": [
                "作文"
            ],
            "layoutStyle": null,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null
        },
        {
            "id": 360492,
            "title": "<p>&nbsp;fsd gd sdf sdf sd&nbsp;</p>",
            "content": null,
            "optionList": [
                "<p>asdasdasdasd</p>",
                "<p>fsdfsdfdsfsdf</p>",
                "<p>cvxcvxcvxcv</p>",
                "<p>qweqweqweqwe</p>"
            ],
            "answerList": [
                "B"
            ],
            "analysis": "<p>ad asd asd asd&nbsp;</p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": -1,
            "typeId": 1,
            "questionType": "单选题",
            "provinceId": 0,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 2,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                10568,
                10569
            ],
            "examPointIdList": [
                12963
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 1,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1530940818000,
            "createdUser": 180,
            "updatedTime": 1530941153000,
            "updatedUser": 180,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": null,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "士大夫士大夫撒地方撒地方1",
                "啊实打实"
            ],
            "examPointNameList": [
                "作文"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null
        },
        {
            "id": 358679,
            "title": "<p>阿斯顿阿斯顿阿斯顿阿斯顿<br/></p>",
            "content": null,
            "optionList": [
                "<p>阿斯顿阿斯顿阿斯顿<br/></p>",
                "<p>s的发射点发射点f<br/></p>",
                "<p>阿斯顿阿斯顿阿斯顿s<br/></p>",
                "<p>去问驱蚊器为<br/></p>"
            ],
            "answerList": [
                "C"
            ],
            "analysis": "<p>阿斯顿阿斯顿啊实打实<br/></p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": -1,
            "typeId": 1,
            "questionType": "单选题",
            "provinceId": 0,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 2,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                10568,
                10569
            ],
            "examPointIdList": [
                12963
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 50,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1525349783000,
            "createdUser": 1294978847,
            "updatedTime": 1528351845000,
            "updatedUser": 1294984332,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": null,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "士大夫士大夫撒地方撒地方1",
                "啊实打实"
            ],
            "examPointNameList": [
                "作文"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": "2018年全国"
        },
        {
            "id": 346566,
            "title": "<p>公司最近哪种虫害十分严重？</p>",
            "content": null,
            "optionList": [
                "<p>蛇24242424</p>",
                "<p>鼠</p>",
                "<p>蚁</p>",
                "<p>蜈蚣</p>"
            ],
            "answerList": [
                "D"
            ],
            "analysis": "<p>嘿嘿嘿，可爱的鼠鼠2424242424242</p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": 1,
            "typeId": 1,
            "questionType": "单选题",
            "provinceId": 0,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 6,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 2,
            "abilityIdList": [
                5,
                7,
                8,
                0,
                9,
                6,
                2
            ],
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12688,
                12689,
                12690
            ],
            "examPointIdList": [
                14986,
                14992,
                14993
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 69,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": null,
            "createdUser": null,
            "updatedTime": null,
            "updatedUser": null,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": [
                1
            ],
            "suggestTime": 10,
            "examTypeId": 7,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "阿斯顿士大夫士大夫",
                "是的发色发",
                "是的发色发"
            ],
            "examPointNameList": [
                "测试",
                "啊实打实",
                "sfsaf撒打发撒"
            ],
            "layoutStyle": null,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null
        },
        {
            "id": 346567,
            "title": "<p>公司最近那种虫灾严重<zmblank></zmblank></p>",
            "content": null,
            "optionList": [
                "<p>蝮蛇</p>",
                "<p>蚂蚁</p>",
                "<p>老鼠</p>",
                "<p>蟑螂</p>"
            ],
            "answerList": [
                "C",
                "D"
            ],
            "analysis": "<p>咦~好恶心啊<zmlatex>{{100}^\\circ C}</zmlatex>水烫死~</p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": 1,
            "typeId": 2,
            "questionType": "多选题",
            "provinceId": 0,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 2,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                12688,
                12689,
                12690
            ],
            "examPointIdList": [
                12924,
                12925,
                12926,
                14986,
                14992,
                14993
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 131,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1523519818000,
            "createdUser": 180,
            "updatedTime": 1526712622000,
            "updatedUser": 1294971565,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": 5,
            "examTypeId": 1,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "阿斯顿士大夫士大夫",
                "是的发色发",
                "是的发色发"
            ],
            "examPointNameList": [
                "借助字典",
                "结合上下文",
                "分析词语引申义",
                "测试",
                "啊实打实",
                "sfsaf撒打发撒"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null
        },
        {
            "id": 358786,
            "title": "<p>234234<br/></p>",
            "content": null,
            "optionList": [
                "<p>234<br/></p>",
                "<p>223<br/></p>",
                "<p>234<br/></p>",
                "<p>234<br/></p>"
            ],
            "answerList": [
                "A"
            ],
            "analysis": "<p>3244234<br/></p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": null,
            "typeId": 2,
            "questionType": "多选题",
            "provinceId": null,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": null,
            "score": 3,
            "sourceId": 5,
            "difficulty": 1,
            "distinction": 2,
            "recommendationIndex": null,
            "rating": 2,
            "comprehensiveDegreeId": 1,
            "abilityIdList": [
                2,
                1
            ],
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                10568,
                10569,
                10570
            ],
            "examPointIdList": [
                15005,
                15006
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 1,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": null,
            "createdUser": null,
            "updatedTime": null,
            "updatedUser": null,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": null,
            "errReason": null,
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": [
                1,
                2,
                3
            ],
            "suggestTime": 3,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "士大夫士大夫撒地方撒地方1",
                "啊实打实",
                "大师傅大师傅"
            ],
            "examPointNameList": [
                "士大夫",
                "撒的方法"
            ],
            "layoutStyle": null,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null
        },
        {
            "id": 360481,
            "title": "<p>阿斯达四方稍等发稍等发稍等发s&#39;d</p>",
            "content": null,
            "optionList": [
                "<p>是请问阿斯顿阿斯顿阿斯顿</p>",
                "<p>zX zxc zxc xzc zx&nbsp;</p>",
                "<p>asdas asd asdasd&nbsp;</p>",
                "<p>fghghjghjghj豆腐干地方</p>"
            ],
            "answerList": [
                "C"
            ],
            "analysis": "<p>阿斯顿多少分稍等发稍等发多少分稍等发</p>",
            "subjectId": 1,
            "gradeId": 1,
            "phaseId": 1,
            "termId": 1,
            "typeId": 1,
            "questionType": "单选题",
            "provinceId": 0,
            "cityId": null,
            "countyId": null,
            "schoolId": null,
            "year": 2018,
            "score": 3,
            "sourceId": 2,
            "difficulty": 1,
            "distinction": 1,
            "recommendationIndex": null,
            "rating": 1,
            "comprehensiveDegreeId": 1,
            "abilityIdList": null,
            "subjectCharacteristicIdList": null,
            "editionIdList": null,
            "chapterIdList": null,
            "knowledgeIdList": [
                10569,
                112963,
                119000
            ],
            "examPointIdList": [
                12963
            ],
            "coreLiteracyIdList": null,
            "costTime": null,
            "browseCount": 0,
            "quoteCount": 0,
            "examCount": 0,
            "correctRate": null,
            "storageTime": null,
            "sub": false,
            "state": null,
            "createdTime": 1530863369000,
            "createdUser": 1294978847,
            "updatedTime": 1530871301000,
            "updatedUser": 1294978847,
            "versions": null,
            "remarks": null,
            "picUrl": null,
            "cutUserId": null,
            "auditCutUserId": null,
            "entryUserId": null,
            "auditEntryUserId": null,
            "tagUserId1": null,
            "tagUserId2": null,
            "auditTagUserId": null,
            "cutTime": null,
            "auditCutTime": null,
            "entryTime": null,
            "auditEntryTime": null,
            "tag1Time": null,
            "tag2Time": null,
            "auditTagTime": null,
            "errType": 0,
            "errReason": "",
            "templateType": 2,
            "adoptUser1Tag": null,
            "adoptUser2Tag": null,
            "children": null,
            "questionTag1": null,
            "questionTag2": null,
            "tagAdopt": null,
            "tagReason": null,
            "tagFeedback1": null,
            "tagFeedback2": null,
            "auditTagFeedback": null,
            "sceneIdList": null,
            "suggestTime": null,
            "examTypeId": null,
            "tagUser1FeedbackAdoptFlag": null,
            "tagUser2FeedbackAdoptFlag": null,
            "auditTagUserFeedbackAdoptFlag": null,
            "tagUser1AdoptFlag": null,
            "tagUser2AdoptFlag": null,
            "knowledgeNameList": [
                "啊实打实",
                "作文",
                "语法解析"
            ],
            "examPointNameList": [
                "作文"
            ],
            "layoutStyle": 3,
            "x1": null,
            "y1": null,
            "x2": null,
            "y2": null,
            "picIndex": null,
            "label": null
        }
    ]
};