/*
 *
 * SetTags constants
 *
 */

export const DEFAULT_ACTION = 'app/SetTags/DEFAULT_ACTION';
export const SET_INPUTDTO_ACTION = 'app/SetTags/SET_INPUTDTO_ACTION';
export const GET_EDITION_LIST = 'app/SetTags/GET_EDITION_LIST';
export const SET_EDITION_LIST_ACTION = 'app/SetTags/SET_EDITION_LIST_ACTION';
export const GET_COURSE_SYSTEM = 'app/SetTags/GET_COURSE_SYSTEM';
export const SET_COURSE_SYSTEM = 'app/SetTags/SET_COURSE_SYSTEM';
export const SET_COURSE_CHECKED = 'app/SetTags/SET_COURSE_CHECKED';
export const SET_MODAL_TOGGLE = 'app/SetTags/SET_MODAL_TOGGLE';
export const CHANGE_PAPER_STATE_ACTION = 'app/SetTags/CHANGE_PAPER_STATE_ACTION';
export const GET_PAPER_MSG_ACTION = 'app/GET_PAPER_MSG_ACTION';
export const CHANGE_NOT_GET_PAPER_COUNT_ACTION = 'app/SetTags/CHANGE_NOT_GET_PAPER_COUNT_ACTION';
export const CHANGE_HAS_GET_PAPER_COUNT_ACTION = 'app/SetTags/CHANGE_HAS_GET_PAPER_COUNT_ACTION';
export const SET_PAPER_LIST_ACTION = 'app/SetTags/SET_PAPER_LIST_ACTION';
export const SET_EP_ID = 'app/SetTags/SET_EP_ID';
export const GET_CUR_PAPER = 'app/SetTags/GET_CUR_PAPER';
export const SUBMIT_ACTION = 'app/SetTags/SUBMIT_ACTION';
export const SET_QUESTION_LIST = 'app/SetTags/SET_QUESTION_LIST';
export const SET_QUESTION_INDEX = 'app/SetTags/SET_QUESTION_INDEX';
export const INIT_CUR_INPUT = 'app/SetTags/INIT_CUR_INPUT';
export const CHANGE_PAGE_STATE = 'app/SetTags/CHANGE_PAGE_STATE';
export const NEXT_QUES_ACTION = 'app/SetTags//NEXT_QUES_ACTION';
export const SET_COMMON_INFO = 'app/SetTags/SET_COMMON_INFO';
export const SET_QUESTION_LIST_ORIGIN = 'app/SetTags/SET_QUESTION_LIST_ORIGIN';
export const SET_FINISHED_LIST = 'app/SetTags/SET_FINISHED_LIST';
export const SET_PAPER_TITLE = 'app/SetTags/SET_PAPER_TITLE';
export const SET_TO_GET = 'app/SetTags/SET_TO_GET';
export const TO_GET_PAPER = 'app/SetTags/TO_GET_PAPER';
export const TOGGLE_DIALOG_MODAL = 'app/SetTags/TOGGLE_DIALOG_MODAL';
export const SET_PAGE_INDEX = 'app/SetTags/SET_PAGE_INDEX';
export const SET_PAGE_SIZE = 'app/SetTags/SET_PAGE_INDEX';
export const SUBMIT_VERIFY = 'app/SetTags/SUBMIT_VERIFY';
export const SET_SORT = 'app/SetTags/SET_SORT';
export const SET_PAPER_DOWNLOAD_MSG_ACTION = 'app/SET_PAPER_DOWNLOAD_MSG_ACTION';
export const SET_EXAMPOINT_LIST = 'app/SetTags/SET_EXAMPOINT_LIST';
export const SET_KNOWLEDGE_LIST = 'app/SetTags/SET_KNOWLEDGE_LIST';
export const TO_GET_KNOWLEDGE = 'app/SetTags/TO_GET_KNOWLEDGE';
export const TO_GET_EXAMPOINT = 'app/SetTags/TO_GET_EXAMPOINT';
export const CHANGE_IS_OPEN_CHILDREN_TAGS_ACTION = 'app/SetTags/CHANGE_IS_OPEN_CHILDREN_TAGS_ACTION';
export const CHANGE_CHILDREN_SELECTED_INDEX_ACTION = 'app/SetTags/CHANGE_CHILDREN_SELECTED_INDEX_ACTION';
export const SET_CHILDREN_QUESTION_MSG_ACTION = 'app/SetTags/SET_CHILDREN_QUESTION_MSG_ACTION';
export const SET_QUESTION_TYPE_LIST_ACTION = 'app/SetTags/SET_QUESTION_TYPE_LIST_ACTION';
export const GET_QUESTION_TYPE_LIST_ACTION = 'app/SetTags/GET_QUESTION_TYPE_LIST_ACTION';
export const SET_BIG_MSG_ACTION = 'app/SetTags/SET_BIG_MSG_ACTION';
export const SET_CHILDREN_TAGS_ACTION = 'app/SetTags/SET_CHILDREN_TAGS_ACTION';
export const SET_SHOW_QUESTION_TREE_ACTION = 'app/SetTags/SET_SHOW_QUESTION_TREE_ACTION';
export const GET_PAPER_MSG_TO_SEE_ACTION = 'app/SetTags/GET_PAPER_MSG_TO_SEE_ACTION';
export const SEE_PAPER_VERIFY_RESULT_ACTION = 'app/SetTags/SEE_PAPER_VERIFY_RESULT_ACTION';
export const SET_PAPER_MSG_ACTION = 'app/SetTags/SET_PAPER_MSG_ACTION';
export const SET_TAGS_MEMORY_ACTION = 'app/SetTags/SET_TAGS_MEMORY_ACTION';
export const SET_HIGHLIGHT_ITEM_ACTION = 'app/SetTags/SET_HIGHLIGHT_ITEM_ACTION';
export const INIT_HIGHLIGHT_ITEM_ACTION = 'app/SetTags/INIT_HIGHLIGHT_ITEM_ACTION';
export const SET_POINT_ID_LIST_ACTION = 'app/SetTags/SET_POINT_ID_LIST_ACTION';
export const SELECT_PAPEER_STATE_ACTION = 'app/SetTags/SELECT_PAPEER_STATE_ACTION';
