/* eslint-disable quote-props */
/* eslint-disable quotes */
export const paperImitation = {
  "code": "0",
  "message": "",
  "data": {
    "id": 224,
    "name": "录入打回",
    "typeId": 4,
    "businessCardId": 1,
    "examTypeId": 1,
    "subjectId": 2,
    "gradeId": 9,
    "termId": -1,
    "year": 2018,
    "averageScore": null,
    "quoteCount": 0,
    "storageTime": null,
    "questionAmount": 10,
    "createdUser": 1294984332,
    "createUserName": "刘胜果",
    "createdTime": 1526972631000,
    "updatedTime": 1530932361000,
    "updatedUser": 180,
    "updatedUserName": null,
    "state": 8,
    "provinceId": 0,
    "cityId": null,
    "countyId": null,
    "provinceName": null,
    "cityName": null,
    "countyName": null,
    "picUrlList": [
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-0.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-1.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-2.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-3.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-4.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-5.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-6.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-7.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-8.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-9.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-10.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-11.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-12.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-13.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-14.png",
      "https://oss-cn-beijing.aliyuncs.com/zm-tiku/535c2c47-830c-49f4-9b5b-40446e127df9/slide-15.png"
    ],
    "examPaperContentOutputDTOList": [
      {
        "id": 7696,
        "serialNumber": 1,
        "name": "1111111",
        "examPaperContentQuestionOutputDTOList": [
          {
            "id": 13173,
            "serialNumber": 1,
            "questionId": 358985,
            "questionOutputDTO": {
              "id": 358985,
              "title": "<p>3333333333333<zmblank contenteditable=\"false\">空类1</zmblank></p><p>再来个空类2<zmsubline contenteditable=\"false\">空类2</zmsubline></p>",
              "content": null,
              "optionList": [
                "<p>3232342</p>",
                "<p>233223</p>",
                "<p>23323</p>",
                "<p>323232</p>"
              ],
              "answerList": [
                "A"
              ],
              "analysis": "<p>2让哇356</p>",
              "subjectId": 2,
              "gradeId": 9,
              "phaseId": 2,
              "termId": -1,
              "typeId": 1,
              "questionType": "单选题",
              "provinceId": 0,
              "cityId": null,
              "countyId": null,
              "schoolId": null,
              "year": 2018,
              "score": 3,
              "sourceId": null,
              "difficulty": null,
              "distinction": null,
              "recommendationIndex": null,
              "rating": null,
              "comprehensiveDegreeId": null,
              "abilityIdList": [],
              "subjectCharacteristicIdList": null,
              "editionIdList": null,
              "chapterIdList": null,
              "knowledgeIdList": [],
              "examPointIdList": [],
              "coreLiteracyIdList": null,
              "costTime": null,
              "browseCount": 0,
              "quoteCount": 0,
              "examCount": 0,
              "correctRate": null,
              "storageTime": null,
              "sub": false,
              "state": 8,
              "createdTime": 1526987382000,
              "createdUser": 1294984332,
              "updatedTime": 1530932330000,
              "updatedUser": 180,
              "versions": null,
              "remarks": null,
              "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180522190910_1676.jpeg",
              "cutUserId": 1294984332,
              "auditCutUserId": null,
              "entryUserId": 1294984332,
              "auditEntryUserId": null,
              "tagUserId1": null,
              "tagUserId2": null,
              "auditTagUserId": null,
              "cutTime": 1526987382000,
              "auditCutTime": null,
              "entryTime": 1527044651000,
              "auditEntryTime": null,
              "tag1Time": null,
              "tag2Time": null,
              "auditTagTime": null,
              "errType": 0,
              "errReason": "",
              "templateType": 1,
              "adoptUser1Tag": null,
              "adoptUser2Tag": null,
              "children": [
                {
                  "id": 646298,
                  "questionId": 361198,
                  "title": "<p>zz</p>",
                  "optionList": [
                    "<p>选项1</p>",
                    "<p>选项2<br/></p>",
                    "<p>选项3<br/></p>",
                    "",
                    "<p>选项5<br/></p>"
                  ],
                  "answerList": [
                    "D"
                  ],
                  "analysis": "<p>选择4 缺失，答案 却是 选项4</p>",
                  "typeId": 2,
                  "score": 3,
                  "difficulty": null,
                  "knowledgeIdList": null,
                  "examPointIdList": null,
                  "subQuestionMemberList": null
                },
                {
                  "id": 646299,
                  "questionId": 361198,
                  "title": "<p>testa<br/></p>",
                  "optionList": [
                    "<p>434<br/></p>",
                    "",
                    "<p>34<br/></p>",
                    ""
                  ],
                  "answerList": [
                    "B",
                    "D"
                  ],
                  "analysis": "<p>5<br/></p>",
                  "typeId": 2,
                  "score": 3,
                  "difficulty": null,
                  "knowledgeIdList": null,
                  "examPointIdList": null,
                  "subQuestionMemberList": null
                }
              ],
              "questionTag1": null,
              "questionTag2": null,
              "tagAdopt": null,
              "tagReason": null,
              "tagFeedback1": null,
              "tagFeedback2": null,
              "auditTagFeedback": null,
              "sceneIdList": null,
              "suggestTime": null,
              "examTypeId": null,
              "tagUser1FeedbackAdoptFlag": null,
              "tagUser2FeedbackAdoptFlag": null,
              "auditTagUserFeedbackAdoptFlag": null,
              "tagUser1AdoptFlag": null,
              "tagUser2AdoptFlag": null,
              "knowledgeNameList": null,
              "examPointNameList": null,
              "layoutStyle": 3,
              "x1": null,
              "y1": null,
              "x2": null,
              "y2": null,
              "picIndex": null,
              "label": null
            },
            "epcId": 7696,
            "score": null
          },
          {
            "id": 13174,
            "serialNumber": 2,
            "questionId": 358986,
            "questionOutputDTO": {
              "id": 358986,
              "title": "<p>+8665465</p>",
              "content": null,
              "optionList": [
                "<p>35534636</p>",
                "<p>3535353</p>",
                "<p>sdfdsgdsg</p>",
                "<p>353535</p>"
              ],
              "answerList": [
                "B"
              ],
              "analysis": "<p>364646</p>",
              "subjectId": 2,
              "gradeId": 9,
              "phaseId": 2,
              "termId": -1,
              "typeId": 1,
              "questionType": "单选题",
              "provinceId": 0,
              "cityId": null,
              "countyId": null,
              "schoolId": null,
              "year": 2018,
              "score": 3,
              "sourceId": null,
              "difficulty": null,
              "distinction": null,
              "recommendationIndex": null,
              "rating": null,
              "comprehensiveDegreeId": null,
              "abilityIdList": [],
              "subjectCharacteristicIdList": null,
              "editionIdList": null,
              "chapterIdList": null,
              "knowledgeIdList": [],
              "examPointIdList": [],
              "coreLiteracyIdList": null,
              "costTime": null,
              "browseCount": 0,
              "quoteCount": 0,
              "examCount": 0,
              "correctRate": null,
              "storageTime": null,
              "sub": false,
              "state": 8,
              "createdTime": 1526987382000,
              "createdUser": 1294984332,
              "updatedTime": 1527044708000,
              "updatedUser": 1294984332,
              "versions": null,
              "remarks": null,
              "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180522190915_8297.jpeg",
              "cutUserId": 1294984332,
              "auditCutUserId": null,
              "entryUserId": 1294984332,
              "auditEntryUserId": null,
              "tagUserId1": null,
              "tagUserId2": null,
              "auditTagUserId": null,
              "cutTime": 1526987382000,
              "auditCutTime": null,
              "entryTime": 1527044708000,
              "auditEntryTime": null,
              "tag1Time": null,
              "tag2Time": null,
              "auditTagTime": null,
              "errType": 0,
              "errReason": "",
              "templateType": 2,
              "adoptUser1Tag": null,
              "adoptUser2Tag": null,
              "children": null,
              "questionTag1": null,
              "questionTag2": null,
              "tagAdopt": null,
              "tagReason": null,
              "tagFeedback1": null,
              "tagFeedback2": null,
              "auditTagFeedback": null,
              "sceneIdList": null,
              "suggestTime": null,
              "examTypeId": null,
              "tagUser1FeedbackAdoptFlag": null,
              "tagUser2FeedbackAdoptFlag": null,
              "auditTagUserFeedbackAdoptFlag": null,
              "tagUser1AdoptFlag": null,
              "tagUser2AdoptFlag": null,
              "knowledgeNameList": null,
              "examPointNameList": null,
              "layoutStyle": 3,
              "x1": null,
              "y1": null,
              "x2": null,
              "y2": null,
              "picIndex": null,
              "label": null
            },
            "epcId": 7696,
            "score": null
          }
        ]
      },
      {
        "id": 7697,
        "serialNumber": 2,
        "name": "2222222",
        "examPaperContentQuestionOutputDTOList": [
          {
            "id": 13175,
            "serialNumber": 3,
            "questionId": 358987,
            "questionOutputDTO": {
              "id": 358987,
              "title": "<p>afsgsgsgsg---xiugai</p>",
              "content": null,
              "optionList": [],
              "answerList": [
                "<p>qrwrwrwrw</p><p>空类<zmblank contenteditable=\"false\">空类1</zmblank>空类<zmsubline contenteditable=\"false\">空类2</zmsubline>我爱你</p>"
              ],
              "analysis": "<p>wrwrwrwrw</p>",
              "subjectId": 2,
              "gradeId": 9,
              "phaseId": 2,
              "termId": -1,
              "typeId": 3,
              "questionType": "填空题",
              "provinceId": 0,
              "cityId": null,
              "countyId": null,
              "schoolId": null,
              "year": 2018,
              "score": 3,
              "sourceId": null,
              "difficulty": null,
              "distinction": null,
              "recommendationIndex": null,
              "rating": null,
              "comprehensiveDegreeId": null,
              "abilityIdList": [],
              "subjectCharacteristicIdList": null,
              "editionIdList": null,
              "chapterIdList": null,
              "knowledgeIdList": [],
              "examPointIdList": [],
              "coreLiteracyIdList": null,
              "costTime": null,
              "browseCount": 0,
              "quoteCount": 0,
              "examCount": 0,
              "correctRate": null,
              "storageTime": null,
              "sub": false,
              "state": 8,
              "createdTime": 1526987382000,
              "createdUser": 1294984332,
              "updatedTime": 1530932354000,
              "updatedUser": 180,
              "versions": null,
              "remarks": null,
              "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180522190922_3630.jpeg",
              "cutUserId": 1294984332,
              "auditCutUserId": null,
              "entryUserId": 1294984332,
              "auditEntryUserId": null,
              "tagUserId1": null,
              "tagUserId2": null,
              "auditTagUserId": null,
              "cutTime": 1526987382000,
              "auditCutTime": null,
              "entryTime": 1527046449000,
              "auditEntryTime": null,
              "tag1Time": null,
              "tag2Time": null,
              "auditTagTime": null,
              "errType": 0,
              "errReason": "",
              "templateType": 3,
              "adoptUser1Tag": null,
              "adoptUser2Tag": null,
              "children": null,
              "questionTag1": null,
              "questionTag2": null,
              "tagAdopt": null,
              "tagReason": null,
              "tagFeedback1": null,
              "tagFeedback2": null,
              "auditTagFeedback": null,
              "sceneIdList": null,
              "suggestTime": null,
              "examTypeId": null,
              "tagUser1FeedbackAdoptFlag": null,
              "tagUser2FeedbackAdoptFlag": null,
              "auditTagUserFeedbackAdoptFlag": null,
              "tagUser1AdoptFlag": null,
              "tagUser2AdoptFlag": null,
              "knowledgeNameList": null,
              "examPointNameList": null,
              "layoutStyle": 3,
              "x1": null,
              "y1": null,
              "x2": null,
              "y2": null,
              "picIndex": null,
              "label": null
            },
            "epcId": 7697,
            "score": null
          }
        ]
      },
      {
        "id": 7698,
        "serialNumber": 3,
        "name": "33333",
        "examPaperContentQuestionOutputDTOList": [
          {
            "id": 13176,
            "serialNumber": 4,
            "questionId": 358988,
            "questionOutputDTO": {
              "id": 358988,
              "title": "<p>35353535------修改</p>",
              "content": null,
              "optionList": [],
              "answerList": [
                "<p>645646464</p>"
              ],
              "analysis": "<p>9826349bkdjjfhidfhdhf</p>",
              "subjectId": 2,
              "gradeId": 9,
              "phaseId": 2,
              "termId": -1,
              "typeId": 5,
              "questionType": "翻译题",
              "provinceId": 0,
              "cityId": null,
              "countyId": null,
              "schoolId": null,
              "year": 2018,
              "score": 3,
              "sourceId": null,
              "difficulty": null,
              "distinction": null,
              "recommendationIndex": null,
              "rating": null,
              "comprehensiveDegreeId": null,
              "abilityIdList": [],
              "subjectCharacteristicIdList": null,
              "editionIdList": null,
              "chapterIdList": null,
              "knowledgeIdList": [],
              "examPointIdList": [],
              "coreLiteracyIdList": null,
              "costTime": null,
              "browseCount": 0,
              "quoteCount": 0,
              "examCount": 0,
              "correctRate": null,
              "storageTime": null,
              "sub": false,
              "state": 8,
              "createdTime": 1526987382000,
              "createdUser": 1294984332,
              "updatedTime": 1527046454000,
              "updatedUser": 1294984332,
              "versions": null,
              "remarks": null,
              "picUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180522190939_9822.jpeg",
              "cutUserId": 1294984332,
              "auditCutUserId": null,
              "entryUserId": 1294984332,
              "auditEntryUserId": null,
              "tagUserId1": null,
              "tagUserId2": null,
              "auditTagUserId": null,
              "cutTime": 1526987382000,
              "auditCutTime": null,
              "entryTime": 1527046454000,
              "auditEntryTime": null,
              "tag1Time": null,
              "tag2Time": null,
              "auditTagTime": null,
              "errType": 0,
              "errReason": "",
              "templateType": 3,
              "adoptUser1Tag": null,
              "adoptUser2Tag": null,
              "children": null,
              "questionTag1": null,
              "questionTag2": null,
              "tagAdopt": null,
              "tagReason": null,
              "tagFeedback1": null,
              "tagFeedback2": null,
              "auditTagFeedback": null,
              "sceneIdList": null,
              "suggestTime": null,
              "examTypeId": null,
              "tagUser1FeedbackAdoptFlag": null,
              "tagUser2FeedbackAdoptFlag": null,
              "auditTagUserFeedbackAdoptFlag": null,
              "tagUser1AdoptFlag": null,
              "tagUser2AdoptFlag": null,
              "knowledgeNameList": null,
              "examPointNameList": null,
              "layoutStyle": 3,
              "x1": null,
              "y1": null,
              "x2": null,
              "y2": null,
              "picIndex": null,
              "label": null
            },
            "epcId": 7698,
            "score": null
          }
        ]
      }
    ],
    "tagUserId1": -1,
    "tagUserName1": null,
    "tagUserId2": -1,
    "tagUserName2": null,
    "fileUrl": "https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_test/20180522150335_5936.doc",
    "editionId": null,
    "tag1SubmitFlag": false,
    "tag2SubmitFlag": false,
    "cutUserId": 1294984332,
    "cutUserName": null,
    "auditCutUserId": 1294984332,
    "auditCutUserName": null,
    "entryUserId": 1294984332,
    "entryUserName": "刘胜果",
    "auditEntryUserId": 180,
    "auditEntryUserName": null,
    "auditTagUserId": null,
    "auditTagUserName": null,
    "cutTime": 1526987382000,
    "auditCutTime": 1527043712000,
    "entryTime": 1527046457000,
    "auditEntryTime": 1530932361000,
    "tag1Time": null,
    "tag2Time": null,
    "auditTagTime": null,
    "cutReceiveTime": 1526986979000,
    "entryReceiveTime": 1527044107000,
    "tagReceiveTime1": null,
    "tagReceiveTime2": null,
    "finalAuditUserId": null,
    "finalAuditUserName": null,
    "wrongFlag": false,
    "difficulty": null,
    "cutPassFlag": true,
    "entryPassFlag": true,
    "phaseId": 2,
    "examPaperLongPicUrlOutputDTOList": null
  }
};
