/*
 *
 * VideoManageWrapper constants
 *
 */

export const DEFAULT_ACTION = 'app/VideoManageWrapper/DEFAULT_ACTION';
export const SET_SEARCHPANELOPEN_ACTION = 'app/VideoManageWrapper/SET_SEARCHPANELOPEN_ACTION';
export const CHANGE_SEARCHPANELCONTENT_ACTION = 'app/VideoManageWrapper/CHANGE_SEARCHPANELCONTENT_ACTION';
export const SET_VIDEOOPERATEMODAL_OPEN = 'app/VideoManageWrapper/SET_VIDEOOPERATEMODAL_OPEN';
export const GET_VIODERECORDLIST_ACTION = 'app/VideoManageWrapper/GET_VIODERECORDLIST_ACTION';
export const SET_SEARCHFIEIDSITEM_ACTION = 'app/VideoManageWrapper/SET_SEARCHFIEIDSITEM_ACTION';
export const SET_VIDEOBRLONGTYPE_ACTION = 'app/VideoManageWrapper/SET_VIDEOBRLONGTYPE_ACTION';
export const SET_TREEDRIECTIONOPEN_ACTION = 'app/VideoManageWrapper/SET_TREEDRIECTIONOPEN_ACTION';
export const GET_TREEDIRECTION_ACTION = 'app/VideoManageWrapper/GET_TREEDIRECTION_ACTION';
export const SET_TREEDIRECTIONDATA_ACTION = 'app/VideoManageWrapper/SET_TREEDIRECTIONDATA_ACTION';
export const SET_TREERIGHTCLICKITEM_ACTION = 'app/VideoManageWrapper/SET_TREERIGHTCLICKITEM_ACTION';
export const SET_VIDEOLISTS_ACTION = 'app/VideoManageWrapper/SET_VIDEOLISTS_ACTION';
export const SET_VIDEOTOTALCOUNT_ACTION = 'app/VideoManageWrapper/SET_VIDEOTOTALCOUNT_ACTION';
export const SET_CURRENTPAGENUMBER_ACTION = 'app/VideoManageWrapper/SET_CURRENTPAGENUMBER_ACTION';
export const SET_LOADINGSTATE_ACTION = 'app/VideoManageWrapper/SET_LOADINGSTATE_ACTION';
export const SET_SEARCHITEMSINIT_ACTION = 'app/VideoManageWrapper/SET_SEARCHITEMSINIT_ACTION';
export const SET_BATCHUPVIDEO_ACTION = 'app/VideoManageWrapper/SET_BATCHUPVIDEO_ACTION';
export const SET_SELECTUPVIDEOITEMS_ACTION = 'app/VideoManageWrapper/SET_SELECTUPVIDEOITEMS_ACTION';
export const SET_BATCHDOWNVIDEO_ACTION = 'app/VideoManageWrapper/SET_BATCHDOWNVIDEO_ACTION';
export const SET_BATCHDELETEVIDEO_ACTION = 'app/VideoManageWrapper/SET_BATCHDELETEVIDEO_ACTION';
export const SET_CREATEDIRECTION_ACTION = 'app/VideoManageWrapper/SET_CREATEDIRECTION_ACTION';
export const SET_DELETEDIRECTION_ACTION = 'app/VideoManageWrapper/SET_DELETEDIRECTION_ACTION';
export const SET_SELECTDIRECTIONINFO_ACTION = 'app/VideoManageWrapper/SET_SELECTDIRECTIONINFO_ACTION';
export const SET_SETWRAPPEROPEN_ACTION = 'app/VideoManageWrapper/SET_SETWRAPPEROPEN_ACTION';

export const SET_FRISTDIRECTIONITEM_ACTION = 'app/VideoManageWrapper/SET_FRISTDIRECTIONITEM_ACTION';
export const GET_FIRSTDIRECTIONITEM_ACTION = 'app/VideoManageWrapper/GET_FIRSTDIRECTIONITEM_ACTION';
export const SET_VIDEOCOVERCONTENT_ACTION = 'app/VideoManageWrapper/SET_VIDEOCOVERCONTENT_ACTION';
export const SET_VIDEOCOVERURL_ACTION = 'app/VideoManageWrapper/SET_VIDEOCOVERURL_ACTION';
export const SET_VIDEOCOVER_ACTION = 'app/VideoManageWrapper/SET_VIDEOCOVER_ACTION';
export const SET_VIDEOCOVERINFO_ACTION = 'app/VideoManageWrapper/SET_VIDEOCOVERINFO_ACTION';
export const SET_SELECTOPERATEVIDEOITEM_ACTION = 'app/VideoManageWrapper/SET_SELECTOPERATEVIDEOITEM_ACTION';
export const SET_CHANGEOPERATEVIDEOVALUE_ACTION = 'app/VideoManageWrapper/SET_CHANGEOPERATEVIDEOVALUE_ACTION';
export const SET_CHANGESELECTDIRECTIONID_ACTION = 'app/VideoManageWrapper/SET_CHANGESELECTDIRECTIONID_ACTION';
export const SET_SECONDDIRECTIONITEM_ACTION = 'app/VideoManageWrapper/SET_SECONDDIRECTIONITEM_ACTION';
export const SET_THIRDDIRECTIONITEM_ACTION = 'app/VideoManageWrapper/SET_THIRDDIRECTIONITEM_ACTION';
export const SUBMIT_OPERATEVIDEO_ACTION = 'app/VideoManageWrapper/SUBMIT_OPERATEVIDEO_ACTION';
export const SET_SEARCHBYSETEDITEMS_ACTION = 'app/VideoManageWrapper/SET_SEARCHBYSETEDITEMS_ACTION';
export const SET_SEARCHBYSETITEMSINIT_ACTION = 'app/VideoManageWrapper/SET_SEARCHBYSETITEMSINIT_ACTION';
export const SET_TREERIGHTMENUOPEN_ACTION = 'app/VideoManageWrapper/SET_TREERIGHTMENUOPEN_ACTION';
export const SET_TREERIGHTMENUTYPE_ACTION = 'app/VideoManageWrapper/SET_TREERIGHTMENUTYPE_ACTION';
export const SET_RENAMESELECTTREEITEM_ACTION = 'app/VideoManageWrapper/SET_RENAMESELECTTREEITEM_ACTION';
export const SET_RENAMEDIRECTION_ACTION = 'app/VideoManageWrapper/SET_RENAMEDIRECTION_ACTION';
export const SET_ADDDIRECTIONINFO_ACTION = 'app/VideoManageWrapper/SET_ADDDIRECTIONINFO_ACTION';
export const SET_REMOVEDIRECTION_ACTION = 'app/VideoManageWrapper/SET_REMOVEDIRECTION_ACTION';
export const SET_DRAGDIRECTIONITEM_ACTION = 'app/VideoManageWrapper/SET_DRAGDIRECTIONITEM_ACTION';
export const SET_DROPDIRECTIONITEM_ACTION = 'app/VideoManageWrapper/SET_DROPDIRECTIONITEM_ACTION';
export const SET_SECONDDIRECTIONINIT_ACTION = 'app/VideoManageWrapper/SET_SECONDDIRECTIONINIT_ACTION';
export const SET_THIRDDIRECTIONINIT_ACTION = 'app/VideoManageWrapper/SET_THIRDDIRECTIONINIT_ACTION';
export const SET_SELECTROTETREEITEM_ACTION = 'app/VideoManageWrapper/SET_SELECTROTETREEITEM_ACTION';
export const SET_RESETADDDIRECTIONINFO_ACTION = 'app/VideoManageWrapper/SET_RESETADDDIRECTIONINFO_ACTION';



