/*eslint-disable*/
// import { paperCardList } from '../../../utils/zmConfig';
// const purposes = purposeList.toJS();
// purposes.unshift({ id: '-1', name: '全部' });
const allFormData = [
  {
    type: 'epName',
    name: '试卷名称',
    value: undefined,
    require: true,
    data: '',
    formType: 1,
    width: 70,
    placeholder: '请输入试卷名称',
  },
  {
    type: 'gradeId',
    name: '年级',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择年级',
  },
  {
    type: 'subjectId',
    name: '学科',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择学科',
  },
  {
    type: 'year',
    name: '年份',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择年份',
  },
  {
    type: 'difficulty',
    name: '试卷难度',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择试卷难度',
  },
  {
    type: 'paperTypeId',
    name: '试卷类型',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 70,
    placeholder: '请选择试卷类型',
  },
  {
    type: 'termId',
    name: '学期',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择学期',
  },
  {
    type: 'purpose',
    name: '用途',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择用途',
  },
  {
    type: 'onlineFlag',
    name: '上架状态',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择上架状态',
  },
  {
    type: 'provinceId',
    name: '省份',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择省份',
  },
  {
    type: 'cityId',
    name: '市',
    value: undefined,
    require: false,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择市',
  },
  {
    type: 'countyId',
    name: '区/县',
    value: undefined,
    require: false,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择区/县',
  },
  {
    type: 'source',
    name: '试卷来源',
    value: '1',
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择试卷来源',
  },
  {
    type: 'examTypeId',
    name: '卷型',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择卷型',
  },
  {
    type: 'businessCardId',
    name: '试卷名片',
    value: undefined,
    require: false,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择试卷名片',
  },
  {
    type: 'evaluationTarget',
    name: '测评对象',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择测评对象',
  },
  {
    type: 'evaluationPurpose',
    name: '测评用途',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择测评用途',
  },
  {
    type: 'epBu',
    name: '适用BU',
    value: undefined,
    require: true,
    data: [],
    formType: 2,
    width: 33,
    placeholder: '请选择适用BU',
  },
];

export default allFormData;
