export default {
  code: '0',
  message: '',
  data: [
    {
      id: 1529752,
      title: '<p>阅读下面的文字，完成下列小题&nbsp;&nbsp;</p><p style="text-align: left;"><zmindent></zmindent>诸子之学，兴起于先秦，当时一大批富有创见的思想家喷涌而出，蔚为思想史之奇观。在狭义上，诸子之学与先秦时代相联系；在广义上，诸子之学则不限于先秦而绵延于此后中国思想发展的整个过程。这一过程至今仍没有终结。</p><p style="text-align: left;"><zmindent></zmindent>诸子之学的内在品格是历史的承继性以及思想的创造性和突破性。“新子学”，即新时代的诸子之学，也应有同样的品格。这可以从“照着讲”和“接着讲”两个方面来理解。一般而言，“照着讲”主要是从历史角度对以往经典作具体的实证性研究，诸如训诂、校勘、文献编纂，等等。这方面的研究涉及对以往思想的回顾、反思，既应把握历史上的思想家实际说了些什么，也应总结其中具有创造性和生命力的内容，从而为今天的思考提供重要的思想资源。</p><p style="text-align: left;"><zmindent></zmindent>与“照着讲”相关的是“接着讲”。从思想的发展与诸子之学的关联看，“接着讲”接近诸子之学所具有的思想突破性的内在品格，它意味着延续诸子注重思想创造的传统。以近代以来中西思想的互动为背景，“接着讲”无法回避中西思想之间的关系。在中西之学已相遇的背景下，“接着讲”同时展开为中西之学的交融，从更深的层次看，这种交融具体展开为世界文化的建构与发展过程。中国思想传统与西方的思想传统都构成了世界文化的重要资源，而世界文化的发展，则以二者的互动为其重要前提。这一意义上的“新子学”，同时表现为世界文化发展过程中创造性的思想系统。相对于传统的诸子之学，“新子学”无疑获得了新的内涵与新的形态。</p><p style="text-align: left;"><zmindent></zmindent>“照着讲”与“接着讲”二者无法分离。从逻辑上说，任何新思想的形成，都不能从“无”开始，它总是基于现有的思想演进过程。并需要对既有思想范围进行反思批判。“照着讲”的意义，在于梳理以往的思想发展过程，打开前人思想的丰富内容，由此为后继的思想提供理论之源。在此意义上，“照着讲”是“接着讲”的出发点。然而，仅仅停留在“照着讲”，思想便容易止过去，难以继续前行，可能无助于思想的创新。就此而言，在“照着讲”之后，需要继之以“接着讲”。“接着讲”的基本精神，是突破以往思想或推进以往思想，而新的思想系统的形成，则是其逻辑结果。进而言之，从现实的过程看，“照着讲”与“接着讲”总是相互渗入“照着讲”包含对以往思想的逻辑重构与理论阐释，这种重构与阐释已内含“接着讲”；“接着讲”基于已有的思想发展，也相应地内含“照着讲”。“新子学”应追求“照着讲”与”接着讲”的统一。</p><p style="text-align: right;">（摘编自杨国荣《历史视域中的诸子学》）</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 9,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 4,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2497178,
          questionId: 1529752,
          title: '<p>下列关于原文内容的理解和分析，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>广义上的诸子之学始于先秦，贯穿于此后中国思想史，也是当代思想的组成部分。</p>',
            '<p>“照着讲”主要指对经典的整理和实证性研究，并发掘历史上思想家的思想内涵。</p>',
            '<p>“接着讲”主要指接续诸子注重思想创造的传统，在新条件下形成创造性的思想。</p>',
            '<p>不同于以往诸子之学，“新子学”受西方思想影响，脱离了既有思想演进的过程。</p>'
          ],
          answerList: [
            'D'
          ],
          analysis: '<p>本题考查理解文意、筛选并整合文中的信息的能力。D项，原文“诸子之学的内在品格是历史的承继性以及思想的创造性和突破性”。“‘新子学’，即新时代的诸子之学，也应有这样的品格。”“从思想的发展与诸子之学的关联看，‘接着讲’接近诸子之学所具有的思想突破性的内在品格，它意味着延续诸子注重思想创造的传统。”可知“新子学”具有历史的承继性和思想的创造性和突破性，没有脱离思想演进的过程。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2497179,
          questionId: 1529752,
          title: '<p>下列对原文论证的相关分析，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>文章产用了对比的论证手法，以突出“新子学”与历史上诸子之学的差异。</p>',
            '<p>文章指出理解“新子学”的品格可从两方面入手，并就二者的关系进行论证。</p>',
            '<p>文章以中西思想交融互动为前提，论证“新子学”“接着讲”的必要和可能。</p>',
            '<p>文章论证“照着讲”“接着讲”无法分离，是按从逻辑到现实的顺序推进的。</p>'
          ],
          answerList: [
            'A'
          ],
          analysis: '<p>本题考查分析文章结构、归纳内容要点、概括中心意思的能力。A项，无中生有，文章通过对比论证，突出思想的传承和创造发展特性，而不是“新子学”与“诸子之学”的差异。。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2497180,
          questionId: 1529752,
          title: '<p>根景原文内容，下列说法正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>对经典进行文本校勘和文献编纂与进一步阐发之间，在历史上是互相隔膜的。</p>',
            '<p>面对中西思想的交融与互动，“新子学”应该同时致力于中国和世界文化的建构。</p>',
            '<p>“照着讲”内含“接着讲”、虽然能发扬以往的思想，但无助于促进新思想生成。</p>',
            '<p>“新子学”要参与世界文化的发展，就有必要从“照着讲”逐渐过渡到“接着讲”。</p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>本题考查分析概括作者在文中的观点态度的能力。A项，“在历史上是互相隔膜的”错，无中生有，原文“从而为今天思考提供重要的思想资源”。C项，说法过于绝对，“虽然能发扬以往的思想，但无助于促进新思想生成”错误，原文“然而，仅仅停留在‘照着讲’，思想便容易止于过去，难以继续前行，可能无助于思想的创新”。D项，“就有必要从‘照着讲’逐渐过渡到‘接着讲’”，原文最后一句话“‘新子学’应追求‘照着讲’与‘接着讲’的统一”。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529754,
      title: '<p>阅读下面的文字，完成下列各题。<br/></p><p style="text-align: center;">赵一曼女士</p><p style="text-align: center;">阿成</p><p><zmindent></zmindent>伪满时期的哈尔滨市立医院，如今仍是医院。后来得知赵一曼女士曾在这里住过院，我便翻阅了一些她的资料。</p><p><zmindent></zmindent>赵一曼女士，是一个略显瘦秀且成熟的女性，在她身上弥漫着拔俗的文人气质和职业军人的冷峻。在任何地方，你都能看出她有别于他人的风度。</p><p><zmindent></zmindent>赵一曼女士率领的抗联活动在小兴安岭的崇山峻岭中，那儿能够听到来自城镇的钟声。冬夜里，钟声会传得很远很远。钟声里，抗联的兵士在森林里烤火，烤野味儿，或者唱着“火烤胸前暖，风吹背后寒……战士们哟”……这些都给躺在病床上的赵一曼女士留下清晰回忆。<br/></p><p><zmindent></zmindent>赵一曼女士单独一间病房，由警察昼夜看守。</p><p><zmindent></zmindent>白色的小柜上有一个玻璃花瓶，里面插着丁香花，赵一曼女士喜欢丁香花，这束丁香花，是女护士韩勇义摆放在那里的，听说，丁香花现在已经成为这座城市的“市花”了。</p><p><zmindent></zmindent>她是在山区中了日军子弹后被捕的。滨江城警务厅的大野泰治对赵一曼女士进行了严刑拷问。始终没有得到有价值的回答，他觉得很没面子。</p><p><zmindent></zmindent>大野泰治在向上司呈送的审讯报告上写道：</p><p><zmindent></zmindent>赵一曼是中国共产党珠河县委委员，在该党工作上有与赵尚志同等的权力，她是北满共产党的重要干部，通过对此人的严厉审讯，有可能澄清中共与苏联的关系。</p><p><zmindent></zmindent>1936年初，赵一曼女士以假名“王氏”被送到医院监禁治疗。</p><p><zmindent></zmindent>《滨仁省警务厅关于赵一曼的情况》扼要地介绍了赵一曼女士从医院逃走和被害的情况。</p><p><zmindent></zmindent>赵一曼女士是在6月28日逃走的。夜里，看守董宪勋在他叔叔的协助下，将赵一曼抬出医院的后门，一辆雇好的出租车已等在那里，几个人上了车，车立刻就开走了。出租车开到文庙屠宰场的后面，韩勇义早就等侯在那里，扶着赵一曼女士上了雇好的轿子，大家立刻向宾县方向逃去。</p><p><zmindent></zmindent>起一曼女士住院期间，发现警士董宪勋似乎可以争取。经过一段时间的观察、分析，她觉得有把握去试一试。</p><p><zmindent></zmindent>她躺在病床上，和蔼地问董警士“董先生，您一个月的薪俸是多少？”</p><p><zmindent></zmindent>董警士显得有些扭捏：“十多块钱吧……”</p><p><zmindent></zmindent>赵一曼女士遗憾地笑了，说：“真没有想到，薪俸会这样少。”</p><p><zmindent></zmindent>董警士更加了扭捏了。</p><p><zmindent></zmindent>赵一曼女士神情端庄地说：“七尺男儿，为区区十几块钱、甘为日本人役使，不是太愚蠢了吗？</p><p><zmindent></zmindent>董警士无法再正视这位成熟女性的眼了，只是哆哆嗦嗦给自己点了一颗烟。</p><p><zmindent></zmindent>此后，赵一曼女士经常与董警士聊抗联的战斗和生活，聊小兴安岭的风光，飞鸟走兽。她用通俗的，有吸引力的小说体记述日军侵略东北的罪行，写在包药的纸上，董警士对这些纸片很有兴趣，以为这是赵一曼女士记述的一些资料，并不知道是专门写给他看的，看了这些记述，董警士非常向往“山区生活“，愿意救赵一曼女士出去，和她一道上山。</p><p><zmindent></zmindent>赵一曼女士对董警士的争取，共用了20天时间。</p><p><zmindent></zmindent>对女护士韩勇义，赵一曼女士采取的则是“女人对女人”的攻心术。</p><p><zmindent></zmindent>半年多的相处，使韩勇义对赵一曼女士十分信赖，她讲述了自己幼年丧母，恋爱不幸，工作受欺负，等等。赵一曼女士向她讲述自己和其他女战士在抗日队伍中的生活。有趣的、欢乐的生活，语调是深情的、甜蜜的。</p><p><zmindent></zmindent>韩护士真诚地问：“如果中国实现了共产主义，我应该是什么样的地位呢？”</p><p><zmindent></zmindent>赵一曼女士说：“你到了山区，一切都能明白了。”</p><p><zmindent></zmindent>南岗警察署在赵一曼女士逃走后，马上开车去追。</p><p><zmindent></zmindent>追到阿什阿以东20多公里的地方，发现了赵一曼、韩勇义、董宪勋及他的叔父，将他们逮捕。</p><p><zmindent></zmindent>赵一曼女士淡淡地笑了。<br/></p><p><zmindent></zmindent>赵一曼女士是在珠河县被日本宪兵枪杀的。<br/><zmindent></zmindent>那个地方我去过，有一座纪念碑，环境十分幽静，周围种着一些松树。<br/><zmindent></zmindent>我去的时候，在那里遇到一位年迈的老人。他指着石碑说：赵一曼？我说，对，赵一曼。</p><p><zmindent></zmindent>赵一曼被枪杀前，写了一份遗书。<br/><zmindent></zmindent>宁儿：<br/><zmindent></zmindent>母亲对于你没有能尽到教育的责任，实在算遗憾的事情。</p><p><zmindent></zmindent>母亲因为坚决地做了反满抗日的斗争，今天已经到了牺牲的前夕了。</p><p><zmindent></zmindent>母亲和你在生前是永久没有再见的机会了，希望你，宁儿啊！赶快成人，来安慰你地下的母亲！我最亲爱的孩子啊！母亲不用千言万语来教育你，就用实行来教育你。</p><p><zmindent></zmindent>在你长大成人之后，希望不要忘记你的母亲是为国而牺牲的！<br/></p><p style="text-align: right;"><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent>一九三六年八月二日</p><p style="text-align: right;"><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent>（有删改）</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 15,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 1,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2501686,
          questionId: 1529754,
          title: '<p>下列对小说相关内容和艺术特色的分析鉴赏，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）<br/></p>',
          optionList: [
            '<p>小说以“赵一曼女士为题”为题，不同于以往烈士、英雄等惯常用法，称谓的陌生化既表达了对主人公的尊敬之意，又引起了读者的注意。<br/></p>',
            '<p>“通过对此人的严厉审讯，有可能澄清中共与苏联的关系”，这既是大野泰治向上级提出的建议，也暗示他已从赵一曼那里得到有价值的回答。<br/></p>',
            '<p>“他指着石碑说，赵一曼？我说，对，赵一曼。”两个陌生人之间有意无意的搭讪，看似闲笔，实则很有用心，说明赵一曼仍活在人们的记忆里。<br/></p>',
            '<p>医院是“我”与赵一曼的连接点，小说由此切入主人公监禁期间鲜为人知的特殊生活经历，在跨越时空的精神对话中再现了赵一曼的英雄本色。<br/></p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>B选项中“暗示他已从赵一曼那里得到有价值的回答”错误，文中写道“对赵一曼进行严刑拷打，始终没有得到有价值的回答”。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2501687,
          questionId: 1529754,
          title: '<p>小说中说赵一曼“身上弥漫着拔俗的文人气质和职业军人的冷峻”，请结合作品简要分析。</p><p><zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>①文人的气质：喜欢丁香花，情趣不俗；时常深情、甜蜜地回忆战斗生活，文雅浪漫；用大义与真情感化青年，智慧过人；</p><p>②军人的冷峻：遭严刑拷打而不屈服，意志坚定；笑对即将到来的死亡，从容淡定；充满母爱又不忘大义，理智沉稳。</p>'
          ],
          analysis: '<p>本题考查对小说对人物形象的把握，注意结合文本内容，根据分数划得分点，（各3分，意思对即可。）</p>',
          typeId: 4,
          score: 6,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2501688,
          questionId: 1529754,
          title: '<p>小说中历史与现实交织穿插，这种叙述方式有哪些好处？请结合作品简要分析。</p><p><zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>①既能表现当代人对赵一曼女士的尊敬之情，又能表现赵一曼精神的当下意义，使主题内蕴更深刻；②可以拉开时间距离，更加全面地认识英雄，使人物形象更加立体；③灵活使用文献档案，与小说叙述相互印证，使艺术描写更真实。</p>'
          ],
          analysis: '<p>本题考查小说记叙方式，此类题主要从情节，人物，主旨的角度回答（每点2分，答对三点得满分。意思对即可。）</p>',
          typeId: 4,
          score: 6,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529811,
      title: '<p style="text-align: justify;">阅读下面的文字，完成下题。</p><p style="text-align: justify;">&nbsp;材料一：</p><p style="text-align: justify;"><zmindent></zmindent>日前，中国科学院在京召开新闻发布会对外宣布，“墨子号”量子科学实验卫星提前并圆满实现全部既定科学目标，为我国在未来继续引领世界量子方面的研究奠定了坚实的基础。</p><p style="text-align: justify;"><zmindent></zmindent>通信安全是国家信息安全和人类经济社会生活的基本需求，千百年来。人们对于通信安全的追求从未停止，然而，基于计算复杂性的传统，在原理上存在着被破译的可能性。随着数学和计算能力的不断提升。经典密码被破译的可能性与日保增。中国科学技术大学潘建伟教授说:“通过量子通信可以解决这个问题，把量于场理与信息技术相结合，利用量子调控技术，用一种革命性的方式对信息进行编码，存储、传输和操纵，从而在确保信息安全、提高运算速度、提升测量精度等方面突破经典信息技术的瓶颈。“</p><p style="text-align: justify;"><zmindent></zmindent>量子通信主要研究子密钥分发通过量子态的传输，使遥远两地的用户可以共享无条件安全的密钥，利用过密钥对信息进行一次一密的严格加密。这是目前人类唯一已知的不可窃听、不可破译的无条件安全的通信方式。量子通信的另一重要内容量子隐形传态，利用量子纠缠特性、物质的未知力量子态精确传送到遥远地点，而不用传送物质本身，通过隐形传输实现信息传递。&nbsp;</p><p style="text-align: right;">&nbsp;(摘编自吴月辉《“墨子号”，抢占量子科技创新制高点》，(人民日报》2017年8月10日)</p><p>材料二：</p><p style="text-align: justify;"><zmindent></zmindent>潘建伟的导师安东.蔡林格说，潘建伟的团队在量子互联网发展面冲到了领先地位。量子互联网是由卫星和地面设备构成的能够在全球范围分享量子信息的网络。这将使不可破解的全球加密通信成为可能，同时也使我们可以开展一些新的控制远距离量子联系的实验，目前，潘建伟的团队计划发射第二颗卫星，他们还在中国的天宫二号空间站上进行着一项太空量子实验。潘建伟说，未来五年“还会取得很多精彩的成果，一个新的时代已经到来”。</p><p style="text-align: justify;"><zmindent></zmindent>潘建伟是一个有着无穷热情的乐观主义者。他低调地表述了自己的信心，称中国政府将会支持下一个宏伟计划一 一项投资20亿美元的量子通信、 量于计量和量子计算的五年计划，与此形成对照的是欧洲2016年宣布的旗规项目，投资额为12亿美元。</p><p style="text-align: right;">(摘编自伊丽莎白.吉布尼(一位把量子通信带到太空又带目地球的物理学家).《自然》2017年12月)</p><p>材料三：</p><p style="text-align: justify;"><zmindent contenteditable="false"></zmindent>日本《读卖新闻)》5月2日报道；中国宝验设施局大实验设施描准 一流（记者：莳田一彦、船越翔）在中国南部广东省东莞市郊外的丘陵地带，中国刚刚建成了大型实验设施“中国散裂中子源”该实验设施建设费用达到23亿元人民币。3月正式投入运行。中国是继美国、英国、日本之后第四个拥有同样设施的国家。日本的IPARC设施中心主任齐滕直人说：虽然科技和经验领先。但中国发展的实在大快，亚洲的中心正在从日本向中国转移。</p><p style="text-align: justify;"><zmindent></zmindent>中国推进还有很多，3月，中国人民政治协商会议开幕。政协委员潘建伟被传媒体记团团围住，潘建伟是利用2016年发人造卫星进行量子通信研究的研究团队负表人，其团队2017处以后相继发布了多项世界首创的实验成果，潘建伟今年当选美国《时代》杂志“球百大最具影响力人物”。</p><p style="text-align: justify;"><zmindent></zmindent>使用人造卫星的实验要耗费巨额资金，欧洲和日本还在犹豫不决，日本的研究人员认为，“在基础科学领域，中国正在踏入他国难以涉足的领域，领先世界”。<br/></p><p style="text-align: right;">（摘编自《参考消息》2018年5月7日）</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 9,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 4,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2495865,
          questionId: 1529811,
          title: '<p>下列对材料相关内容的理解，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>量子通信把量子物理信息进行编码码、存储、传输和操纵，可以有效解决经典密码被破译的问题。<br/></p>',
            '<p>潘建伟研究团队在天宫二号空间站上进行太空量子实验，并计划发射“墨子号”后的第二科卫星，他对未来五年会取得更多成果充满信息。<br/></p>',
            '<p>中国继美国、英国日本之后成为第四个扔有散裂中子源设施的国家，有些日本科学家有了危机感，认为亚洲的中心正逐渐向中国转移。<br/></p>',
            '<p>在基础科学研究领域，比如使用人造卫星开展科学实验，需要耙费巨额资金，欧洲和日本还在犹豫不决，因而尚未涉足这些领域。</p>'
          ],
          answerList: [
            'D'
          ],
          analysis: '<p>本题考查考生筛选整合新闻要点的能力，考生应当根据选项内容，定位文本信息，筛选相关信息。由材料一第三段的内容，A选项表述正确；材料二中，“目前，潘建伟的团队计划发射第二颗卫星，他们还在中国的天宫二号空间站进行着一项太空量子实验。潘建伟说，未来五年还会取得很多精彩的成果。”可知B表述正确。材料三中，“中国是继美国、英国、日本之后第四个拥有同样XX的国家，日本XX主任XXXX说，虽然日本在XX和经验上领先，但中国发展的实在太快，亚洲的中心正在从日本向中国转移。”可知C表述正确。材料三中，“使用人造卫星的实验要耗费巨额资金，欧洲和日本还在犹豫不决。日本的研究人员以为，在基础科技领域，中国正在进入他国难以涉足的领域，领先世界。”在D选项中，“因而尚未涉足这些领域”的判断错误。</p><p><br/></p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2495866,
          questionId: 1529811,
          title: '<p>下列对材料相关同内容的概括和分析，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）<br/></p>',
          optionList: [
            '<p style="text-align: justify;">利用“墨子号”科学实验卫星研究量子密钥分发和量子隐形传态的量子通信技术，对国家信息安全和人类经济社会生活具有重要意义。</p>',
            '<p style="text-align: justify;">材料，二和材料三中国外媒体对我国量子通信技术研究的相关情况进行了报道认为中国无论是投资力度，还是研究水平都处于世界领先地位。</p>',
            '<p style="text-align: justify;">考虑到千百年来人们对于通信安全的追求从未停止,市场潜力巨大，中国和欧洲都投入巨额资金，首要目的是占尽可能多的市场资源。</p>',
            '<p style="text-align: justify;">材料二和材料三中，国外媒体对我国量子通信技术研究的相关情况进行了报道，认为中国无论是投资力度还是研究水平都处于世界领先地位。</p>'
          ],
          answerList: [
            'C'
          ],
          analysis: '<p>本题考查考生筛选整合新闻要点的能力，考生应当根据选项内容，定位文本信息，筛选相关信息。材料一中第二段第一句，可知A选项表述正确。材料一中第三段，可知B选项表述正确。C选项的“首要目的是抢占尽可能多的市场份额”，通览全文，查不出该项推论得直接依据。材料二中第二段，可知中国的投资力度领先；材料三中，“相继发布了多项世界首创的实验或成果”，可知，D选项表述正确。</p>',
          typeId: 2,
          score: 5,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2495867,
          questionId: 1529811,
          title: '<p>以上三则材料中,《人民日报》《自然》《读卖新闻》报道的侧重点有什么不同？为什么？请结合材料简要分析。</p><p>1、<zmsubline contenteditable="false">空类2</zmsubline></p><p>2、<zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>材料一中，《人民日报》的报道侧重于介绍“墨子号”量子科学实验的巨大成就，彰显了中国速度与中国制造；材料二中，《自然》杂志的报道侧重于介绍潘建伟团队在量子通信领域的贡献，强调其个人能力和国家经费投入；材料三中，《读卖新闻》的报道侧重于以“墨子号”成就为引例，强调中国在基础科学领域的迅猛发展，突出国家投入之大与技术发展之快给日本带来的压力。</p><p>&nbsp;&nbsp;&nbsp;&nbsp;三家媒体杂志的报道侧重不同，这和三家媒体杂志的定位与出发点不同有关系。</p>',
            '<p>&nbsp; &nbsp;三家媒体杂志的报道侧重不同，这和三家媒体杂志的定位与出发点不同有关系。</p>'
          ],
          analysis: '<p>本题考查考生对新闻结构、构思的认识能力，考生需要抓住不同新闻的对比点，分析相同内容、不同内容的内在联系。深化主题思考，从结构、受众的角度认识新闻的定位。</p>',
          typeId: 3,
          score: 4,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529749,
      title: '<p>阅读下面的文言文，完成下列各题。</p><p><zmindent></zmindent>鲁芝字世英，扶风郿人也。世有名德，为西州豪族。父为郭氾所害，芝襁褓流离，年十七，乃移居雍，耽思<strong>坟籍</strong>。郡举上计吏，州辟别驾。魏车骑将军郭淮为雍州刺史，深敬重之。举孝廉，除郎中。后拜骑都尉、参军事、行安南太守，迁尚书郎。曹真出督关右，又参大司马军事。真薨，宣帝代焉，乃引芝参骠骑军事，转天水太守。郡邻于蜀，数被侵掠，户口减削，寇盗充斥，芝倾心镇卫，更造城市，数年间旧境悉复。迁广平太守。天水夷夏慕德，老幼<strong>赴阙</strong>献书，乞留芝。魏明帝许焉。曹爽辅政，引为司马。芝屡有谠言嘉谋，爽弗能纳。及宣帝起兵诛爽，芝率余众犯门斩关，驰出赴爽，劝爽曰：“公居伊周之位，一旦以罪见黜，虽欲牵黄犬，复可得乎！若挟天子保许昌，杖大威以羽檄征四方兵，孰敢不从！舍此而去，欲就东市，岂不痛哉！”<ins>爽懦惑不能用遂委身受戮芝坐爽下狱当死而口不讼直志不苟免宣帝嘉之赦而不诛俄而起为并州刺史</ins>。<strong><ins>诸葛诞以寿春叛，魏帝出征，芝率荆州文武以为先驱。</ins></strong>诞平，迁大尚书，掌刑理。武帝<strong>践阼</strong>，转镇东将军，进爵为侯。<strong><ins>帝以芝清忠履正，素无居宅，使军兵为作屋五十间。</ins></strong>芝以年及悬车，告老<strong>逊位</strong>，章表十余上，于是征为光禄大夫，位特进，给吏卒，门施行马。羊祜为车骑将军，乃以位让芝，曰：“光禄大夫鲁芝洁身寡欲，和而不同，服事华发，以礼终始，未蒙此选，臣更越之，何以塞天下之望！”上不从。其为人所重如是。泰始九年卒，年八十四。帝为举哀，谥曰贞，赐茔田百亩。</p><p style="text-align: right;">（节选自《晋书·鲁芝传》）</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 12,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 4,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2498704,
          questionId: 1529749,
          title: '<p>下列对文中画线部分的断句，正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>爽懦惑不能用/遂委身受戮/芝坐爽/下狱/当死/而口不讼直/志不苟免/宣帝嘉之赦而不诛/俄而起为并州刺史/</p>',
            '<p>爽懦惑不能用/遂委身受戮/芝坐爽下狱/当死/而口不讼直志/不苟免/宣帝嘉之/赦而不诛/俄而起为并州刺史/</p>',
            '<p>爽懦惑不能用/遂委身受戮/芝坐爽下狱/当死/而口不讼直/志不苟免/宣帝嘉之/赦而不诛/俄而起为并州刺史/</p>',
            '<p>爽懦惑不能用/遂委身受戮/芝坐爽/下狱/当死/而口不讼直志/不苟免/宣帝嘉之/赦而不诛/俄而起为并州刺史/</p>'
          ],
          answerList: [
            'C'
          ],
          analysis: '<p>本题考查文言断句的能力。首先要细读所给文段，明确文意，然后根据文意进行判断。注意结合文言文行文的习惯，也可借助标志词。本句中应根据“芝坐爽下狱”一句意为“鲁芝受到曹爽牵连而下狱”无需断句，排除Ａ、Ｄ两项；另“讼直”意为申辩是非曲直，与后句“志不苟免”应断开，故排除Ｂ项。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2498705,
          questionId: 1529749,
          title: '<p>下列对文中加粗词语的相关内容的解说，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）<br/></p>',
          optionList: [
            '<p>《三坟》《五典》传为我国古代典籍,后又以“坟籍”“坟典”为古代典籍通称。</p>',
            '<p>“阙”原指皇宫前面两侧的楼台，又可用作朝廷的代称，赴阙也指入朝觐见皇帝。</p>',
            '<p>“践阼”原指踏上古代庙堂前台阶，又表示用武力打败敌对势力，登上国君宝座。</p>',
            '<p>逊位，也称为让位、退位，多指看王放弃职务和地位，这里指鲁芝的谦让行为。</p>'
          ],
          answerList: [
            'C'
          ],
          analysis: '<p>本题考查理解古代文化常识的能力。在平时学习中应多多识记积累。Ｃ项中“表示用武力打败敌对势力，登上国君宝座”并无此意，“祚”意为：福，福运，相同用法词：祚土(封赐土邑)、祚命(上天赐福)。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2498706,
          questionId: 1529749,
          title: '<p>下列对原文有关内容的概括和分析，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>鲁芝自小受苦，仕途少有挫折。他家本为豪族，但幼年失去父亲后，即流离失所；入仕后受到郭准器重，后又随从曹真出督关右，官职也不断得到升迁。</p>',
            '<p>鲁芝倾心革新，治政卓有成效。任天水太守时，蜀地饱受侵扰，人口减少，他全力守卫，修建城市，恢复旧境；离任时，天水各族百姓均请求让他留任。</p>',
            '<p>鲁芝审时度势，进宫劝谏曹爽。曹爽辅政时，他在曹手下任司马，曹受到讨伐，他率部下驰援。并提出应对策略，对曹挟天子以号令四方，然而未被采纳。</p>',
            '<p>鲁芝洁身自好，深受羊祜推重。羊祜任车骑将军时辞让说，鲁芝为人清心寡欲，与人和睦又不苟同，任职到老，以礼始终，自己愿意将车骑将军礼让鲁芝。</p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>本题考查归纳内容要点，概括中心意思的能力。Ｂ项“蜀地饱受侵扰”错误，根据原文内容来看，应是天水郡饱受侵扰。故选Ｂ项。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2498707,
          questionId: 1529749,
          title: '<p>把文中画横线加粗的句子翻译成现代汉语。</p><p>①诸葛诞以寿春叛，魏帝出征，芝率荆州文武以为先驱。</p><p><zmsubline contenteditable="false">空类2</zmsubline></p><p>②帝以芝清忠履正，素无居宅，使军兵为作屋五十间。</p><p><zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>诸葛诞凭借寿春反叛，魏帝出征，鲁芝率领荆州文武官兵作为先锋。</p>',
            '<p>皇上因为鲁芝清廉忠诚行为端正，一向没有私宅,让士兵为他建造五十间房屋。</p>'
          ],
          analysis: '<p>本题考查理解并翻译文中的句子的能力。文言翻译要以直译为主，意译为辅，同时注意字字落实。翻译后的句子要通顺，不能出现病句。第一句得分点：“以”、“以为”；第二句得分点：“履正”、“素”、“为(之)作屋”。</p>',
          typeId: 3,
          score: 10,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529747,
      title: '<p style="text-align: left;">阅读下面这首唐诗，完成下列各题。</p><p style="text-align: center;">野歌&nbsp; &nbsp; &nbsp; &nbsp;李贺&nbsp;</p><p style="text-align: center;">鸦翎羽箭山桑弓，仰天射落衔芦鸿。</p><p style="text-align: center;">麻衣黑肥冲北风，带酒日晚歌田中。</p><p style="text-align: center;">男儿屈穷心不穷，枯荣不等嗔天公。</p><p style="text-align: center;">寒风又变为春柳，条条看即烟濛濛。</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 9,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 4,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2497438,
          questionId: 1529747,
          title: '<p>下列对这首诗的赏析，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>弯弓射鸿，麻衣冲风，饮酒高歌都是诗人排解心头苦风闷与抑郁的方式。</p>',
            '<p>诗人虽然不得不接受生活贫穷的命运，但是意志并未消沉、气概仍然豪迈。</p>',
            '<p>诗中形容春柳的方式与韩愈《早春呈水部张十八员外》相同，较为常见。</p>',
            '<p>本诗前半描写场景，后半感事抒怀，描写与抒情紧密关联，脉络清晰。</p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>本题考查本题考查筛选信息以及鉴赏诗人形象的能力。B选项明显错误，诗人是参加科举考试时受到别人诽谤而落第，并非因为生活贫穷。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2497439,
          questionId: 1529747,
          title: '<p>诗的最后两句有何含意？请简要分析。</p><p><zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>（1）意为凛冽的寒风终将过去，和煦的春风拂绿枯柳，缀满嫩绿的柳条好像轻烟笼罩一般摇曳多姿;（2）表达了诗人虽感叹不遇于时，但不甘沉沦的乐观、自勉之情。</p>'
          ],
          analysis: '<p>本题考查鉴赏古代诗歌的思想内容、表达技巧、作者情感的能力。“寒风又变为春柳，条条看即烟濛濛”首先要解释诗句的含义，这两句诗写柳树转眼间就枯木逢春，柳条像轻烟笼罩一般，描绘了一幅生机勃勃的画面。其次要联系整首诗歌以及写作背景来理解这两句诗，上两句诗写诗人不甘沉沦，尽管落第，却仍保持着对未来的希望。这两句诗借景抒情，以写景结束全诗，表达了诗人乐观向上的豁达情怀。</p>',
          typeId: 4,
          score: 6,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1530130,
      title: '<p>阅读下面的文字，完成下列小题。</p><p><zmindent></zmindent>“大洋一号”是中国第一艘现代化的综合性远洋科学考察船，自1995年以来，这艘船经历了大大洋矿产资源研究开发专项的多个远洋调查航次和大陆架勘查多个航次的任务。今年，它又完成了历时45天，航程6208海里的综合海试任务。对不熟悉的人而言，（<zmindent></zmindent>）在这里，重力和ADCP实验室、磁力实验室、地震实验室、综合电子实验室、地质实验室、生物基因实验室、深拖和超短基线实验室等各种实验室<zmsubline></zmsubline>，分布在第三，四层船舱，由于船上配备了很多先进设备，人不用下水就能进行海底勘探。比如，深海可视采样系统可以将海底微地形地貌图像传到科学考察船上，犹如有了千里眼，海底世界可以<zmsubline></zmsubline>，并可根据需要<zmsubline></zmsubline>地抓取矿物样品和采集海底水样；深海浅层岩芯取样钻机可以在深海底比较坚硬的岩石上钻取岩芯。</p><p><zmindent></zmindent>“大洋一号”的迹航活动，与郑和下西洋相呼应。600年前，伟大的航海家郑和七下西洋，在世界航海史上留下了光辉的一页，600年后，“大洋一号”不断进步，<zmsubline></zmsubline>，在《联合国海洋法公约》的法律框架下，探索海洋奥秘，开发海洋资源，以实际行动为人类和平利用海洋做出中国人民的贡献。</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 9,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2497557,
          questionId: 1530130,
          title: '<p>文中画横线的句子有话病，下列修改最恰当的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>这艘船经历了大洋矿产资源研究开发专项的多个远洋调查航次和大陆架勘察多个航次的调查。</p>',
            '<p>这艘船执行了大洋矿产资源研究开发专项的多个远洋调查航次少和多个大陆架勘察航次的住务。</p>',
            '<p>这艘船经历了大洋矿产资源研究开发专项的多个远洋调查航次，完成了多个航次大陆架勘察任务。</p>',
            '<p>这艘船执行了大洋矿产资源研究开发专项的多个远洋调查航次，完成了多个大陆架勘察航次的任务。</p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>解答病句辨析题可以抓住病句中明显的标志词语考虑，只要我们“炼”就一双慧眼，迅速盯住这些标志词语，就能找到辨析病句的捷径。比如介词、动词、代词、并列词、关联词、否定词、两面词、数量词、成语、修饰语等，有的病句虽然没有标志词语，但是我们可凭借病句表现出来的症状，依据高考病句的六大类型进行排查。类型不多，只要训练方法得当，适当做一些练习，见多识广，形成能力，依“法”诊断并不难。</p><p><br/></p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2497558,
          questionId: 1530130,
          title: '<p>下列在文中括号内补写的语句，最恰当的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>“大洋一号”的实验多，就像迷宫一样</p>',
            '<p>“大洋一号”有十几个像迷宫一样的实验室</p>',
            '<p>走进“大洋一号”，犹如进入了一座迷宫</p>',
            '<p>进入迷宫一样的“大洋一号”，会分辨不出方向</p>'
          ],
          answerList: [
            'C'
          ],
          analysis: '<p>此题考查的是语言运用的连贯，解答是要结合具体语境分析。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2497559,
          questionId: 1530130,
          title: '<p>依次填入文中横线上的成语，全都恰当的一项是（<zmindent contenteditable="false">空类0</zmindent>） &nbsp;</p>',
          optionList: [
            '<p>一应俱全 &nbsp;一览无余 &nbsp;易如反掌 &nbsp;东山再起</p>',
            '<p>应有尽有 &nbsp;一览无余 &nbsp;轻而易举 &nbsp;再接再厉</p>',
            '<p>一应俱全 &nbsp;一目了然 &nbsp;轻而易举 &nbsp;东山再起</p>',
            '<p>应有尽有 &nbsp;一目了然 &nbsp;易如反掌 再接再厉</p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>“补写句子”是综合考点和能力的考查，这类题目一般要求“根据材料内容”补写句子，要求所补写的句子内容贴切、语意连贯、逻辑严密。解答本题的正确步骤应是：①阅读——认真阅读语段，确定文段中心意思；②推导——将文段划分层次，做到瞻前顾后；③检查——得出答案后应代入原文，最终求得语句连贯。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529756,
      title: '<p>补写出下列句子中的空缺部分。</p><p>1.《论语.为政》中“<zmsubline></zmsubline>，<zmsubline></zmsubline>”两句指出，成为教师的条件是温习学过的知识进而又能从中获得新的理解与体会。</p><p>2.韩愈的《师说》是写给少年李蟠的，文末所说的“<zmsubline></zmsubline>”，点出李蟠的文章爱好，而“<zmsubline></zmsubline>”，则说明了李蟠的儒学素养。</p><p>3.苏轼《念奴娇(大江东去）》中“&nbsp;<zmsubline></zmsubline>&nbsp;”一句，写的是周瑜的儒将装束，“<zmsubline></zmsubline>”一句，表明了周瑜的赫赫战功。</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>温故而知新</p>',
        '<p>可以为师矣</p>',
        '<p>好古文&nbsp;</p>',
        '<p>六艺经传皆通习之</p>',
        '<p>羽扇纶巾</p>',
        '<p>&nbsp;樯橹灰飞烟灭</p>'
      ],
      analysis: '<p>本题考查默写常见的名句名篇的能力，根据题目所给具体情境作答。注意“纶巾”“樯橹”等字的写法。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 3,
      questionType: '填空题',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 6,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 4,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 39,
      parentTypeName: '填空题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529758,
      title: '<p>下面是某校一则启事初稿的片段，其中有五处不合书面语体的要求，请找出并作修改。 &nbsp;&nbsp;</p><p><zmindent></zmindent>我校学生宿舍下水道时常堵住。后勤处认真调查了原因，发现管子陈旧，需要换掉。学校打算7月15日开始施工。施工期间正遇上暑假，为安全起见，请全体学生暑假期间不要在学校住宿。望大家配合。</p><p><zmsubline></zmsubline></p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>①“堵住”改为“堵塞”；</p><p>②“管子”改为“管道”；</p><p>③“换掉”改为“更换”；</p><p>④“打算”改为“计划”；</p><p>⑤“正遇上”改为“正值”。</p>'
      ],
      analysis: '<p>本题考查逻辑推断和语言综合运用，考生须结合材料具体分析。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 4,
      questionType: '解答题',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 5,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 4,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 40,
      parentTypeName: '解答题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529760,
      title: '<p>下面是某校为教师编写个人专业发展规划而提供的流程图，请把这个图转写成一段文字介绍，要求内容完整，表述准确，语言连贯，不超过90个字。</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180607152614_4437.png" zmtype="small"/></p><p><zmsubline></zmsubline></p>',
      content: null,
      optionList: null,
      answerList: [
        '<p><zmindent contenteditable="false">空类0</zmindent>编写教师个人专业发展规划首先要进行环境分析和自我分析，在此基础上进行个人定位并设置发展目标，然后制订达成目标的操作策略，最后展开评估与信息反馈，再据此作进一步修订。</p>'
      ],
      analysis: '<p>本题考察流程图分析以及语言表达的能力。要为在校的老师编写个人专业发展规划，流程图中，最开始是由“环境分析”“自我分析”然后指向“个人定位”“发展目标”，之后共同指向“操作策略”，最后指向“评估与信息反馈”。按照这个流程，逐一阐述，语言连贯即可。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 4,
      questionType: '解答题',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 6,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 4,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 40,
      parentTypeName: '解答题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529367,
      title: '<p>阅读下面的材料，根据要求写作。</p><p><zmindent></zmindent>2000年&nbsp; 农历庚辰龙年，人类迈进新千年，中国千万“世纪宝宝”出生。</p><p><zmindent></zmindent>2008年 &nbsp;汶川大地震。北京奥运会。</p><p><zmindent></zmindent>2013年 &nbsp;“天宫一号”首次太空授课。</p><p><zmindent></zmindent><zmindent></zmindent>公路“村村通”接近完成；“精准扶贫”开始推动。</p><p><zmindent></zmindent>2017年 &nbsp;网民规模达7.72亿，互联网普及率超全球平均水平。</p><p><zmindent></zmindent>2018年 &nbsp;“世纪宝宝”一代长大成人。</p><p style="text-align: left;"><zmindent></zmindent><zmindent></zmindent><zmindent></zmindent>··········</p><p><zmindent></zmindent>2020年 &nbsp;全面建成小康社会。</p><p><zmindent></zmindent>2035年 &nbsp;基本实现社会主义现代化。</p><p><zmindent></zmindent>一代人有一代人的际遇和机缘、使命和挑战。你们与新世纪的中国一路同行、成长，和中国的新时代一起追梦、圆梦。以上材料触发了你怎样的联想和思考?请据此写一篇文章，想象它装进“时光瓶”留待2035年开启，给那时18岁的一代人阅读。</p><p><zmindent></zmindent>要求：选好角度，确定立意，明确文体，自拟标题，不要套作，不得抄袭，不得泄露个人信息；不少于800字。</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>略<br/></p>'
      ],
      analysis: '<p><zmindent contenteditable="false">空类0</zmindent>这是一道任务驱动型材料作文，任务驱动型作文要求明确，为了让考生的思考更集中、更深入，限定了写作范围和对象，比如本题中的“你怎样的联想和思考”就确定了写作范围是我在现时代中的角色定位。但此任务驱动型作文具有一定的新颖性形式——“想象它装进‘时光瓶’留待2035年开启，给那时18岁的一代人阅读”。命题直观地反映时代主题，正面而巧妙地传递价值观念。立意高远却力避空泛，坚持以学生为本，接地气、有生气，时代感强。引导考生关心现实国情与改革发展，展示他们的理想信念、精神状态与综合素质。</p><p><zmindent contenteditable="false">空类0</zmindent>现如今正处在历史变革时期，社会面临巨大的变化，各种新鲜事物层出不穷，政治、经济、文化、人们的思想观念、伦理道德、生活方式等等都发生了深刻的变化，时代在前进，在进步，这对“世纪宝宝”来说是际遇与机缘；但是，我们应该还要看到，由于社会政治经济层面发生的变化，引起了一些很不合理的时期发生，如，贫富分化、法制观念淡漠、道德缺失、腐败堕落、世风日下，许多人因金钱扭曲了灵魂，人们因此而迷茫······这对“世纪宝宝”来说又是使命和挑战。一个时代，表现出了它的两面性，而且都很突出。具体到每位考生，让考生写出自己对新世纪的中国的认识和思考，鼓励考生从所知所学所感出发，在对宏大话题的把握中，感性叙说，理性思辨，畅所欲言，选择自己有素材积累、感触的观点来写。</p><p><zmindent contenteditable="false">空类0</zmindent>此外，命题要求明确文体，而不限制考生写作的文体，只要能写出自己对新时代的中国的认识和思考，论述类、叙述类乃至说明、抒情类的文体都可以自由选择，只要在写作中能体现所选文体的特征。</p><p><zmindent contenteditable="false">空类0</zmindent>可有以下立意</p><p>①不忘初心，继续前进；</p><p>②新起点，新中国，新征程；</p><p>③一切尽在期待中；</p><p>④勇做新时代的弄潮儿。</p><p><zmindent contenteditable="false">空类0</zmindent>本题既给考生提供巨大写作空间，又有效防止套作宿构，从而极大提高了测试的区分度和效度。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 18,
      questionType: '书面表达',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 60,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 4,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: null
    },

  ]
};