export default {
  code: '0',
  message: '',
  data: [
    {
        id: 22567,
        title: '<p>若<zmlatex>0{\\lt}\\alpha {\\lt}\\frac{\\pi}{2}</zmlatex>,<zmlatex>-\\frac{\\pi}{2}{\\lt}\\beta {\\lt}0</zmlatex>,<zmlatex>\\cos (\\frac{\\pi}{4}+\\alpha )=\\frac{1}{3}</zmlatex>,<zmlatex>\\cos (\\frac{\\pi}{4}-\\frac{\\beta }{2} )=\\frac{\\sqrt{3}}{3}</zmlatex>，则<zmlatex>\\cos (\\alpha+\\frac{\\beta }{2} )=</zmlatex>(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>\\frac{\\sqrt{3}}{3}</zmlatex></p>',
          '<p><zmlatex>-\\frac{\\sqrt{3}}{3}</zmlatex></p>',
          '<p><zmlatex>\\frac{5\\sqrt{3}}{9}</zmlatex></p>',
          '<p><zmlatex>-\\frac{\\sqrt{6}}{9}</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p>本题考查同角三角函数的基本关系,差角公式.<zmlatex>0{\\lt}\\alpha {\\lt}\\frac{\\pi}{2}</zmlatex>,所以<zmlatex>\\frac{\\pi}{4}{\\lt}\\frac{\\pi}{4}+\\alpha {\\lt}\\frac{3\\pi}{4}</zmlatex>,</p><p>因为<zmlatex>\\cos(\\frac{\\pi}{4}+\\alpha )=\\frac{1}{3}{\\gt}0</zmlatex>,所以<zmlatex>\\frac{\\pi}{4}{\\lt}\\frac{\\pi}{4}+\\alpha {\\lt}\\frac{\\pi}{2}</zmlatex>,所以<zmlatex>\\sin(\\frac{\\pi}{4}+\\alpha )=\\frac{2\\sqrt{2}}{3}</zmlatex>;</p><p>因为<zmlatex>-\\frac{\\pi}{2}{\\lt}\\beta {\\lt}0</zmlatex>,所以<zmlatex>\\frac{\\pi}{4}{\\lt}\\frac{\\pi}{4}-\\frac{\\beta }{2}{\\lt}\\frac{\\pi}{2}</zmlatex>,<zmlatex>\\cos(\\frac{\\pi}{4}-\\frac{\\beta }{2})=\\frac{\\sqrt{3}}{3}</zmlatex>,所以<zmlatex>\\sin(\\frac{\\pi}{4}-\\frac{\\beta }{2})=\\frac{\\sqrt{6}}{3}</zmlatex>；</p><p>所以<zmlatex>\\cos(\\alpha +\\frac{\\beta }{2})=\\cos[(\\frac{\\pi}{4}+\\alpha )-(\\frac{\\pi}{4}-\\frac{\\beta }{2})]</zmlatex></p><p><zmlatex>=\\cos(\\frac{\\pi}{4}+\\alpha )\\cos(\\frac{\\pi}{4}-\\frac{\\beta }{2})+\\sin(\\frac{\\pi}{4}+\\alpha)\\sin(\\frac{\\pi}{4}-\\frac{\\beta }{2})</zmlatex></p><p><zmlatex>=\\frac{1}{3}\\times\\frac{\\sqrt{3}}{3}+\\frac{2\\sqrt{3}}{3}\\times\\frac{\\sqrt{6}}{3}=\\frac{5\\sqrt{3}}{9}</zmlatex>.选<zmlatex>C</zmlatex>.</p>',
        subjectId: 2,
        gradeId: 10,
        phaseId: 3,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 38,
        cityId: 351,
        countyId: 0,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: null,
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6518,
          6524,
          6585
        ],
        examPointIdList: [
          9209,
          9275,
          9524
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 252,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: null,
        createdUser: null,
        updatedTime: null,
        updatedUser: null,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: null,
        suggestTime: 3,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '三角函数值在各象限的符号',
          '同角三角函数的基本关系的应用',
          '两角差的余弦公式'
        ],
        examPointNameList: [
          '同角三角函数基本关系的运用',
          '利用两角和与差的公式求值',
          '同角三角函数的基本关系的应用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: null,
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 10
     
    },
    {
        id: 253061,
        title: '<p>函数<zmlatex>f(x)=2sin (\\omega x+\\varphi )(\\omega &nbsp;{\\gt}0)</zmlatex>的部分图像如图，其中<zmlatex>M(m,0)</zmlatex>，<zmlatex>N(n,2)</zmlatex>，<zmlatex>P( \\pi ,0)</zmlatex>，且<zmlatex>mn {\\lt}{}0</zmlatex>，则<zmlatex>f(x)</zmlatex>在下列哪个区间中是单调的（&nbsp; ）．</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180320162522_1960.png" zmtype="big"/></p>',
        content: null,
        optionList: [
          '<p><zmlatex>\\left( 0,\\frac{ \\pi }{4} \\right)</zmlatex></p>',
          '<p><zmlatex>\\left( \\frac{ \\pi }{4},\\frac{2 \\pi }{3} \\right)</zmlatex></p>',
          '<p><zmlatex>\\left( \\frac{ \\pi }{2},\\frac{3 \\pi }{4} \\right)</zmlatex></p>',
          '<p><zmlatex>\\left( \\frac{2 \\pi }{3}, \\pi \\right)</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p><zmlatex>{\\because}mn {\\lt}{}0</zmlatex>，</p><p><zmlatex>{\\therefore}m</zmlatex>，<zmlatex>n</zmlatex>异号，&nbsp;</p><p>由图可知：<zmlatex>m {\\lt}{}0</zmlatex>，<zmlatex>n {\\gt}0</zmlatex>，</p><p>又<zmlatex>P( \\pi ,0)</zmlatex>，</p><p><zmlatex>{\\therefore}T {\\gt}\\pi</zmlatex>且<zmlatex>\\frac{3T}{4} {\\lt}{} \\pi</zmlatex>，&nbsp;</p><p>则<zmlatex>\\pi &nbsp;{\\lt}{}T{\\lt}{}\\frac{4 \\pi }{3}</zmlatex>．</p><p>当周期无限接近<zmlatex>\\pi</zmlatex>时，</p><p>图中的最低点自左向右无限接近<zmlatex>\\frac{3 \\pi }{4}</zmlatex>，</p><p><zmlatex>{\\therefore}f(x)</zmlatex>在<zmlatex>\\left( \\frac{2 \\pi }{3}, \\pi &nbsp;\\right)</zmlatex>上先减后增不单调，排除<zmlatex>D</zmlatex>；</p><p>当周期接近<zmlatex>\\frac{4 \\pi }{3}</zmlatex>又小于<zmlatex>\\frac{4 \\pi }{3}</zmlatex>时，</p><p>图中最高点<zmlatex>N</zmlatex>的横坐标大于<zmlatex>0</zmlatex>小于<zmlatex>\\frac{ \\pi }{4}</zmlatex>，</p><p><zmlatex>f(x)</zmlatex>在<zmlatex>\\left( 0,\\frac{ \\pi }{4} \\right)</zmlatex>上先增后减不单调，排除<zmlatex>A</zmlatex>；</p><p>图中的最低点的横坐标大于<zmlatex>\\frac{ \\pi }{2}</zmlatex>小于<zmlatex>\\frac{3 \\pi }{4}</zmlatex>，</p><p><zmlatex>f(x)</zmlatex>在<zmlatex>\\left( \\frac{ \\pi }{2},\\frac{3 \\pi }{4} \\right)</zmlatex>上先减后增不单调，排除<zmlatex>C</zmlatex>．</p><p>故选<zmlatex>B</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 3,
        cityId: 3,
        countyId: 10,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 4,
        distinction: 3,
        recommendationIndex: null,
        rating: 3,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1,
          2,
          3,
          13
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6544,
          6572,
          6579
        ],
        examPointIdList: [
          9234,
          9259,
          9262
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 3999,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1517469837000,
        createdUser: 1002533843,
        updatedTime: 1537150571000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 3,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '正弦函数的单调性',
          '函数y=Asin(wx+φ)的单调区间',
          '由函数图象或部分图象确定解析式'
        ],
        examPointNameList: [
          '正弦函数的单调性问题',
          '由y=Asin(wx+φ)的部分图象确定其表达式',
          '三角函数图象的综合运用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2016年北京省北京市海淀区',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
    },
    {
        id: 738561,
        title: '<p>将函数<zmlatex>y=\\sqrt{3}sin(\\frac{\\pi}{4}x)</zmlatex>的图象向左平移<zmlatex>3</zmlatex>个单位，得函数<zmlatex>f(x)=\\sqrt{3}sin(\\frac{\\pi}{4}x+\\varphi)(|\\varphi|{\\lt}\\pi)</zmlatex>的图象（如图），点<zmlatex>M,N</zmlatex>分别是函数<zmlatex>f(x)</zmlatex>图象上<zmlatex>y</zmlatex>轴两侧相邻的最高点和最低点，设<zmlatex>{\\angle}MON={\\theta}</zmlatex>，则<zmlatex>tan(\\varphi-{\\theta})</zmlatex>的值为（&nbsp; ）</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180426101538_383.png" zmtype="big"/></p>',
        content: null,
        optionList: [
          '<p><zmlatex>-2+\\sqrt{3}</zmlatex></p>',
          '<p><zmlatex>2-\\sqrt{3}</zmlatex></p>',
          '<p><zmlatex>1+\\sqrt{3}</zmlatex></p>',
          '<p><zmlatex>1-\\sqrt{3}</zmlatex></p>'
        ],
        answerList: [
          'A'
        ],
        analysis: '<p>本题考查三角函数的图像、性质与最值，差角公式.将<zmlatex>y=\\sqrt{3}sin(\\frac{\\pi}{4}x)</zmlatex>的图象向左平移<zmlatex>3</zmlatex>个单位，得<zmlatex>y=\\sqrt{3}sin(\\frac{\\pi}{4}x+\\frac{3\\pi}{4})</zmlatex>，即<zmlatex>\\varphi=\\frac{3\\pi}{4}</zmlatex>，而点<zmlatex>M,N</zmlatex>图象上<zmlatex>y</zmlatex>轴两侧相邻的最高点和最低点，所以<zmlatex>M(-1,\\sqrt{3}),(3,-\\sqrt{3}),OM=2,ON=2\\sqrt{3},MN=2\\sqrt{7}</zmlatex>；在三角形<zmlatex>MNO</zmlatex>中，由余弦定理得<zmlatex>cos{\\angle}MON=cos{\\theta}=\\frac{{{OM}^{2}}+{{ON}^{2}}-{{MN}^{2}}}{2OM{\\times}ON}=-\\frac{\\sqrt{3}}{2}</zmlatex>，所以<zmlatex>{\\theta}=\\frac{5\\pi}{6}</zmlatex>，所以<zmlatex>tan(\\varphi-{\\theta})=tan(\\frac{3\\pi}{4}-\\frac{5\\pi}{6})=tan(-\\frac{\\pi}{12})=tan\\frac{\\pi}{12}=-2+\\sqrt{3}</zmlatex>.选<zmlatex>A</zmlatex></p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 37,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 4,
        distinction: 3,
        recommendationIndex: null,
        rating: 3,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          2,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6588,
          6615,
          12487
        ],
        examPointIdList: [
          9275,
          9367,
          15895
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 1429,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1524444617000,
        createdUser: 1002318580,
        updatedTime: 1537001929000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 3,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '两角和与差的正切公式',
          '三角形中余弦定理的应用',
          '三角函数的图像的平移变换'
        ],
        examPointNameList: [
          '利用两角和与差的公式求值',
          '余弦定理与其他知识综合应用',
          '三角函数图像的平移变换'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年安徽省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
     
    },
    {
        id: 95057,
        title: '<p>函数<zmlatex>f\\left( x \\right) = \\cos \\left( {2x - \\frac{{2\\pi }}{3}} \\right) + 4{\\cos ^2}x - 2 - \\frac{3}{{3x - \\pi }}\\left( {x \\in \\left[ { - \\frac{{11\\pi }}{{12}},\\frac{{19\\pi }}{{12}}} \\right]} \\right)</zmlatex>所有零点之和为（&nbsp; ）</p>',
        content: null,
        optionList: [
          '<p><zmlatex>\\frac{{2\\pi }}{3}</zmlatex></p>',
          '<p><zmlatex>\\frac{{4\\pi }}{3}</zmlatex></p>',
          '<p><zmlatex>2\\pi</zmlatex></p>',
          '<p><zmlatex>\\frac{{8\\pi }}{3}</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p>函数<zmlatex>f\\left( x \\right) = \\cos \\left( {2x - \\frac{{2\\pi }}{3}} \\right) + 4{\\cos ^2}x - 2 - \\frac{3}{{3x - \\pi }}\\left( {x \\in \\left[ { - \\frac{{11\\pi }}{{12}},\\frac{{19\\pi }}{{12}}} \\right]} \\right)</zmlatex>所有零点<zmlatex>{\\Leftrightarrow}</zmlatex>函数<zmlatex>g\\left( x \\right) = \\cos \\left( {2x - \\frac{{2\\pi }}{3}} \\right) + 4{\\cos ^2}x - 2</zmlatex>与<zmlatex>h\\left( x \\right) = \\frac{3}{{3x - \\pi }}</zmlatex>的交点的横坐标．<zmlatex>g\\left( x \\right) = \\cos \\left( {2x - \\frac{{2\\pi }}{3}} \\right) + 4{\\cos ^2}x - 2 = \\frac{{\\sqrt 3 }}{2}\\sin 2x + \\frac{3}{2}\\cos 2x = \\sqrt 3 \\sin \\left( {2x + \\frac{\\pi }{3}} \\right)</zmlatex>，<zmlatex>h\\left( x \\right) = \\frac{3}{{3x - \\pi }} = \\frac{1}{{x - \\frac{\\pi }{3}}}</zmlatex>，</p><p>可得函数<zmlatex>g\\left( x \\right)</zmlatex>，<zmlatex>h\\left( x \\right)</zmlatex>的图象，关于点<zmlatex>\\left( {\\frac{\\pi }{3},0} \\right)</zmlatex>对称．</p><p>函数<zmlatex>g\\left( x \\right)</zmlatex>，<zmlatex>h\\left( x \\right)</zmlatex>的图象如下：（只需画出直线<zmlatex>x={\\frac{\\pi }{3}}</zmlatex>右侧部分）</p><p>结合图象可得在区间<zmlatex>{\\left[ { - \\frac{{11\\pi }}{{12}},\\frac{{19\\pi }}{{12}}} \\right]}</zmlatex>，函数<zmlatex>g\\left( x \\right)</zmlatex>，<zmlatex>h\\left( x \\right)</zmlatex>的图象由<zmlatex>4</zmlatex>个交点，关于点<zmlatex>\\left( {\\frac{\\pi }{3},0} \\right)</zmlatex>对称．所有零点之和为<zmlatex>2 {\\times}\\frac{\\pi }{3} + 2 {\\times}\\frac{\\pi }{3} = \\frac{{4\\pi }}{3}</zmlatex>，故选：B</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180224153238_5821.png" zmtype="big"/></p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 25,
        cityId: 0,
        countyId: 0,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 4,
        distinction: 3,
        recommendationIndex: null,
        rating: 3,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1,
          2,
          3,
          12
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6436,
          6569,
          6597
        ],
        examPointIdList: [
          8533,
          8536,
          9262
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 4184,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1513431039000,
        createdUser: 1002525771,
        updatedTime: 1537509921000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 3,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '函数的零点',
          '函数y=Asin(wx+φ)的图象',
          '二倍角公式的变形应用之降幂公式'
        ],
        examPointNameList: [
          '求函数的零点',
          '转化为两个图象交点来处理函数零点问题',
          '三角函数图象的综合运用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年江西省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 10
     
    },
    {
        id: 87431,
        title: '<p>将函数<zmlatex>f(x)y=\\cos (\\omega x+\\phi )(\\omega {\\gt}0,-\\frac{\\pi }{2}{\\lt}\\phi {\\lt}\\frac{\\pi }{2})</zmlatex>图象上每一点的横坐标伸长为原来的<zmlatex>2</zmlatex>倍（纵坐标不变），</p><p>再向右平移<zmlatex>\\frac{\\pi }{6}</zmlatex>个单位长度得到<zmlatex>y=\\cos x</zmlatex>的图象，则函数<zmlatex>f(x)</zmlatex>的单调递增区间为（　　）</p>',
        content: null,
        optionList: [
          '<p><zmlatex>[k\\pi -\\frac{2\\pi }{3},k\\pi +\\frac{\\pi }{3}](k\\in z)</zmlatex></p>',
          '<p><zmlatex>[k\\pi -\\frac{7\\pi }{12},k\\pi -\\frac{\\pi }{12}](k\\in z)</zmlatex></p>',
          '<p><zmlatex>[4k\\pi -\\frac{7\\pi }{3},k\\pi -\\frac{\\pi }{3}](k\\in z)</zmlatex></p>',
          '<p><zmlatex>[4k\\pi -\\frac{\\pi }{3},k\\pi +\\frac{5\\pi }{3}](k\\in z)</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p>将函数<zmlatex>f(x)y=\\cos (\\omega x+\\phi )(\\omega {\\gt}0,-\\frac{\\pi }{2}{\\lt}\\phi {\\lt}\\frac{\\pi }{2})</zmlatex>图象上每一点的横坐标伸长为原来的<zmlatex>2</zmlatex>倍（纵坐标不变），</p><p>可得<zmlatex>y=\\cos (\\frac{1}{2}\\omega x+\\phi )</zmlatex>图象；再向右平移<zmlatex>\\frac{\\pi }{6}</zmlatex>个单位长度，得到<zmlatex>y=\\cos [\\frac{1}{2}\\omega (x-\\frac{\\pi }{6})+\\phi ]=\\cos (\\frac{1}{2}\\omega x-\\frac{\\pi }{12}\\bullet \\omega +\\phi )</zmlatex>的图象，</p><p>而由已知可得，得到的是函数<zmlatex>y=\\cos x</zmlatex>的图象，<zmlatex>\\therefore \\frac{\\omega }{2}=1,\\therefore \\omega =2</zmlatex>；</p><p>再根据<zmlatex>-\\frac{\\pi }{12}\\bullet 2+\\phi =2k\\pi ,k\\in z,\\therefore \\phi =\\frac{\\pi }{6},f(x)=\\cos (2x+\\frac{\\pi }{6})</zmlatex>．</p><p>令<zmlatex>2k\\pi -\\pi \\le 2x+\\frac{\\pi }{6}\\le 2k\\pi</zmlatex>，求得<zmlatex>k\\pi -\\frac{7\\pi }{12}\\le x\\le k\\pi -\\frac{\\pi }{12},(k\\in z)</zmlatex>，</p><p>则函数<zmlatex>f(x)</zmlatex>的单调递增区间为<zmlatex>[k\\pi -\\frac{7\\pi }{12},k\\pi -\\frac{\\pi }{12}],(k\\in z)</zmlatex>，</p><p>故选：<zmlatex>B</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 15,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          2,
          3,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6572,
          6576
        ],
        examPointIdList: [
          9257,
          9258
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 151,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1513328967000,
        createdUser: 1002318580,
        updatedTime: 1537151276000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 3,
        examTypeId: 3,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '函数y=Asin(wx+φ)的单调区间',
          '由y=sinx图象得到y=Asin(wx+φ)的图象变换过程'
        ],
        examPointNameList: [
          '复合三角函数的单调性',
          '函数y=Asin(wx+φ)的图象变换'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年辽宁省全国Ⅱ卷',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
    },
    {
        id: 751970,
        title: '<p>若函数<zmlatex>f(x) = - \\frac{1}{2}\\sin x\\cos x + 3a\\cos x + (\\frac{1}{2} - 4a)x</zmlatex>在区间<zmlatex>\\lbrack 0,\\frac{\\pi}{2}\\rbrack</zmlatex>上单调递减,则实数<zmlatex>a</zmlatex>的取值范围是（&nbsp; ）</p>',
        content: null,
        optionList: [
          '<p><zmlatex>\\lbrack 0,\\frac{1}{7}\\rbrack</zmlatex></p>',
          '<p><zmlatex>\\lbrack - \\frac{16}{9},0\\rbrack</zmlatex></p>',
          '<p><zmlatex>( - \\infty,\\frac{1}{7}\\rbrack</zmlatex></p>',
          '<p><zmlatex>( - \\infty,0\\rbrack</zmlatex></p>'
        ],
        answerList: [
          'D'
        ],
        analysis: '<p><zmlatex>f(x)=\\frac{1}{2}cos2x + 3a(sinx - cosx) + (4a - 1)x</zmlatex>,</p><p><zmlatex>f^{\\prime}(x)=- sin2x + 3a(cosx + sinx) + 4a - 1</zmlatex>,</p><p>依题意,函数<zmlatex>f(x)</zmlatex>在区间<zmlatex>\\lbrack - \\frac{\\pi}{4},0\\rbrack</zmlatex>上为减函数,</p><p>故<zmlatex>f^{{\\prime}}\\left( x \\right)=- \\left( \\sin x + cosx \\right)^{2} + 3a(sinx + cosx) - 4a{\\le}0</zmlatex>恒成立,</p><p>因此<zmlatex>{(sinx + cosx)}^{2} - 3a(sinx + cosx) - 4a \\geq 0</zmlatex>在区间<zmlatex>\\left\\lbrack \\frac{- \\pi}{4},0 \\right\\rbrack</zmlatex>上恒成立,</p><p>令<zmlatex>t = sinx + cosx=\\sqrt{2}sin(x + \\frac{\\pi}{4}) \\in \\lbrack 0,1\\rbrack</zmlatex>,</p><p>因此<zmlatex>g(t) = t^{2} - 3{at} - 4a,t \\in \\lbrack 0,1\\rbrack</zmlatex>,</p><p>若<zmlatex>g(t) \\geq 0</zmlatex>对<zmlatex>t \\in \\lbrack 0,1\\rbrack</zmlatex>恒成立,</p><p>即<zmlatex>t^{2} \\geq a(3a + 4)</zmlatex>,</p><p>因为<zmlatex>3t + 4 {\\gt} 0</zmlatex>,</p><p>故<zmlatex>a \\leq \\frac{t^{2}}{3t + 4}</zmlatex>恒成立,</p><p>即<zmlatex>a \\leq {(\\frac{t^{2}}{3t + 4})}_{min}</zmlatex>,</p><p>设<zmlatex>\\varphi(t) = \\frac{t^{2}}{3t + 4}</zmlatex>,</p><p>则<zmlatex>\\varphi^{\\prime}(t) = \\frac{3t^{2} + 8t}{{(3t + 4)}^{2}} \\geq 0</zmlatex>,故<zmlatex>\\varphi(t)</zmlatex>在区间<zmlatex>\\lbrack 0,1\\rbrack</zmlatex>上单调递增,</p><p>所以<zmlatex>\\varphi{(t)}_{min}=\\varphi(0) = 0</zmlatex>,所以<zmlatex>a \\leq 0</zmlatex>,故选<zmlatex>D</zmlatex>.</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 22,
        cityId: 0,
        countyId: 0,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 4,
        distinction: 3,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          0,
          1,
          2,
          3,
          9,
          10
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6465,
          6474,
          6526
        ],
        examPointIdList: [
          8573,
          8598,
          9209
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 1,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1524479276000,
        createdUser: 1003231785,
        updatedTime: 1536922799000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 4,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '函数单调性和导数的关系',
          '利用最值解不等式恒成立问题',
          'sina+-cosa与sinacosa之间的关系'
        ],
        examPointNameList: [
          '利用导数研究函数的单调性',
          '利用导数解决恒成立问题',
          '同角三角函数基本关系的运用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年湖南省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
    },
    {
        id: 570060,
        title: '<p>已知<zmlatex>\\overrightarrow{AB}=(cos17{{}^\\circ},cos73{{}^\\circ})</zmlatex>,<zmlatex>\\overrightarrow{BC}=(2cos77{{}^\\circ},2cos13{{}^\\circ})</zmlatex>,则<zmlatex>{\\triangle}ABC</zmlatex>的面积为(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>\\frac{\\sqrt{3}}{2}</zmlatex></p>',
          '<p><zmlatex>1</zmlatex></p>',
          '<p><zmlatex>\\sqrt{3}</zmlatex></p>',
          '<p><zmlatex>2</zmlatex></p>'
        ],
        answerList: [
          'A'
        ],
        analysis: '<p>本题考查平面向量的数量积,三角形的面积公式.由题意得<zmlatex>c=|\\overrightarrow{AB}|=1</zmlatex>,<zmlatex>a=|\\overrightarrow{CB}|=2</zmlatex>,<zmlatex>\\overrightarrow{BC}{\\cdot}\\overrightarrow{BA}=-2cos77{{}^\\circ}cos17{{}^\\circ}-2cos13{{}^\\circ}cos73{{}^\\circ}=-2(cos77{{}^\\circ}cos17{{}^\\circ}+sin77{{}^\\circ}sin17{{}^\\circ})=-2cos(77{{}^\\circ}-17{{}^\\circ})=-1</zmlatex>;而<zmlatex>\\overrightarrow{BC}{\\cdot}\\overrightarrow{BA}=|\\overrightarrow{AB}||\\overrightarrow{CB}|cosB=2cosB=-1</zmlatex>,解得<zmlatex>cosB=-\\frac{1}{2}</zmlatex>,所以<zmlatex>sinB=\\frac{\\sqrt{3}}{2}</zmlatex>;所以<zmlatex>{\\triangle}ABC</zmlatex>的面积<zmlatex>S=\\frac{1}{2}acsinB=\\frac{\\sqrt{3}}{2}</zmlatex>.</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 0,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          2,
          1,
          9
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6621,
          6678,
          6680
        ],
        examPointIdList: [
          9209,
          9334,
          9362
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 180,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1523600559000,
        createdUser: 1002318621,
        updatedTime: 1538988944000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '三角形面积公式',
          '向量长度、模的坐标公式',
          '向量夹角公式及坐标表示'
        ],
        examPointNameList: [
          '同角三角函数基本关系的运用',
          '数量积表示两个向量的夹角',
          '求三角形的面积或高'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年全国',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 6
    },
    {
        id: 430061,
        title: '<p>已知<zmlatex>\\frac{{{\\tan }^{2}}x+{{\\tan }^{2}}y}{1+{{\\tan }^{2}}x+{{\\tan }^{2}}y}={{\\sin }^{2}}x+{{\\sin }^{2}}y</zmlatex>，则<zmlatex>\\sin x\\cdot \\sin y</zmlatex>的最大值为( &nbsp;)．</p>',
        content: null,
        optionList: [
          '<p><zmlatex>0</zmlatex></p>',
          '<p><zmlatex>\\frac{1}{4}</zmlatex></p>',
          '<p><zmlatex>\\frac{\\sqrt{2}}{2}</zmlatex></p>',
          '<p>前三个答案都不对</p>'
        ],
        answerList: [
          'A'
        ],
        analysis: '<p><zmlatex>\\frac{{{\\tan }^{2}}x+{{\\tan }^{2}}y}{1+{{\\tan }^{2}}x+{{\\tan }^{2}}y}={{\\sin }^{2}}x+{{\\sin }^{2}}y</zmlatex>，</p><p><zmlatex>\\Leftrightarrow \\frac{{{\\sin }^{2}}x{{\\cos }^{2}}y+{{\\sin }^{2}}y{{\\cos }^{2}}x}{{{\\cos }^{2}}x{{\\cos }^{2}}y+{{\\sin }^{2}}x{{\\cos }^{2}}y+{{\\sin }^{2}}y{{\\cos }^{2}}x}={{\\sin }^{2}}x+{{\\sin }^{2}}y</zmlatex>，</p><p><zmlatex>\\Leftrightarrow {{\\sin }^{2}}x{{\\sin }^{2}}y\\left( {{\\sin }^{2}}x+{{\\sin }^{2}}y-2 \\right)=0</zmlatex>，</p><p>由<zmlatex>x,y\\ne \\frac{\\pi }{2}+k\\pi ,k\\in \\mathbf{Z}</zmlatex>，</p><p>得到<zmlatex>{{\\sin }^{2}}x{\\lt}{}1</zmlatex>，<zmlatex>{{\\sin }^{2}}y{\\lt}{}1</zmlatex>，</p><p>故只能<zmlatex>{{\\sin }^{2}}x{{\\sin }^{2}}y=0</zmlatex>，此时<zmlatex>\\sin x\\sin y=0</zmlatex></p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 0,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 3,
        recommendationIndex: null,
        rating: 4,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6523,
          6524,
          6590
        ],
        examPointIdList: [
          9209,
          9210,
          9276
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 0,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: null,
        createdUser: null,
        updatedTime: null,
        updatedUser: null,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 3,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '同角三角函数的商数关系',
          '同角三角函数的基本关系的应用',
          '化简三角函数式变化技巧之公式变换'
        ],
        examPointNameList: [
          '同角三角函数基本关系的运用',
          '根据同角三角函数关系求值',
          '利用两角和与差的公式化简'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: null,
        deleted: null,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
    },
    {
        id: 408764,
        title: '<p>已知函数<zmlatex>f\\left( x \\right)=\\cos \\left( 2x+\\frac{\\pi }{3} \\right)-\\cos 2x</zmlatex>，其中<zmlatex>x\\in \\mathbf{R}</zmlatex>，给出下列四个结论</p><p>①．函数<zmlatex>f\\left( x \\right)</zmlatex>是最小正周期为<zmlatex>\\pi</zmlatex>的奇函数；</p><p>②．函数<zmlatex>f\\left( x \\right)</zmlatex>图象的一条对称轴是<zmlatex>x=\\frac{2\\pi }{3}</zmlatex>；</p><p>③．函数<zmlatex>f\\left( x \\right)</zmlatex>图象的一个对称中心为<zmlatex>\\left( \\frac{5\\pi }{12},0 \\right)</zmlatex>；</p><p>④．函数<zmlatex>f\\left( x \\right)</zmlatex>的递增区间为<zmlatex>\\left[ k\\pi +\\frac{\\pi }{6},k\\pi +\\frac{2\\pi }{3} \\right]</zmlatex>，<zmlatex>k\\in \\mathbf{Z}</zmlatex>．</p><p>则正确结论的个数是（&nbsp; ）．</p>',
        content: null,
        optionList: [
          '<p><zmlatex>1</zmlatex>个</p>',
          '<p><zmlatex>2</zmlatex>个</p>',
          '<p><zmlatex>3</zmlatex>个</p>',
          '<p><zmlatex>4</zmlatex>个</p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p><zmlatex>{\\because}f\\left( x \\right)=\\cos \\left( 2x+\\frac{\\pi }{3} \\right)-\\cos 2x</zmlatex></p><p><zmlatex>=\\cos 2x\\cos \\frac{\\pi }{3}-\\sin 2x\\sin \\frac{\\pi }{3}-\\cos 2x</zmlatex></p><p><zmlatex>=-\\frac{\\sqrt{3}}{2}\\cos 2x-\\frac{1}{2}\\cos 2x=-\\sin \\left( 2x+\\frac{\\pi }{6} \\right)</zmlatex>．</p><p><zmlatex>{\\therefore}T=\\frac{2\\pi }{2}=\\pi</zmlatex>，即函数<zmlatex>f\\left( x \\right)</zmlatex>的最小正周期为<zmlatex>\\pi</zmlatex>，</p><p>但<zmlatex>f\\left( 0 \\right)=-\\sin \\frac{\\pi }{6}=-\\frac{1}{2}\\ne 0</zmlatex>，函数<zmlatex>f\\left( x \\right)</zmlatex>不是奇函数．命题①错误；</p><p><zmlatex>{\\because}f\\left( \\frac{2\\pi }{3} \\right)=-\\sin \\frac{3\\pi }{2}=1</zmlatex>，</p><p><zmlatex>{\\therefore}</zmlatex>函数<zmlatex>f\\left( x \\right)</zmlatex>图象的一条对称轴是<zmlatex>x=\\frac{2\\pi }{3}</zmlatex>．命题②正确；</p><p><zmlatex>{\\because}f\\left( \\frac{5\\pi }{12} \\right)=-\\sin \\pi =0</zmlatex>，</p><p><zmlatex>{\\therefore}</zmlatex>函数<zmlatex>f\\left( x \\right)</zmlatex>图象的一个对称中心为<zmlatex>\\left( \\frac{5\\pi }{12},0 \\right)</zmlatex>．命题③正确；</p><p>由<zmlatex>\\frac{\\pi }{2}+2k\\pi \\leqslant 2x+\\frac{\\pi }{6}\\leqslant \\frac{3\\pi }{2}+2k\\pi</zmlatex>，得：</p><p><zmlatex>\\frac{\\pi }{6}+k\\pi \\leqslant x\\leqslant \\frac{2\\pi }{3}+k\\pi</zmlatex>，<zmlatex>k\\in \\mathbf{Z}</zmlatex>．</p><p><zmlatex>{\\therefore}</zmlatex>函数<zmlatex>f\\left( x \\right)</zmlatex>的递增区间为<zmlatex>\\left[ k\\pi +\\frac{\\pi }{6},k\\pi +\\frac{2\\pi }{3} \\right]</zmlatex>，<zmlatex>k\\in \\mathbf{Z}</zmlatex>．命题④正确．</p><p><zmlatex>{\\therefore}</zmlatex>正确结论的个数是<zmlatex>3</zmlatex>个．</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 3,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 3,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6572,
          6573,
          6574
        ],
        examPointIdList: [
          9231,
          9235,
          9262
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 3,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: null,
        createdUser: null,
        updatedTime: null,
        updatedUser: null,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 3,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '函数y=Asin(wx+φ)的单调区间',
          '函数y=Asin(wx+φ)的奇偶性',
          '函数y=Asin(wx+φ)的周期性'
        ],
        examPointNameList: [
          '正弦函数的奇偶性问题',
          '正弦函数的对称性问题',
          '三角函数图象的综合运用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: null,
        deleted: null,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
    },
    {
        id: 693624,
        title: '<p>若<zmlatex>G</zmlatex>是<zmlatex>{\\Delta &nbsp;ABC}</zmlatex>的重心，<zmlatex>a</zmlatex>，<zmlatex>b</zmlatex>，<zmlatex>c</zmlatex>分别是角<zmlatex>A</zmlatex>,<zmlatex>B</zmlatex>,<zmlatex>C</zmlatex>的对边，若</p><p><zmlatex>a\\overset{\\rightarrow}{{G{A}}} + b\\overset{\\rightarrow}{GB} + \\frac{\\sqrt{3}}{3}c\\overset{\\rightarrow}{{GC}} = \\overset{\\rightarrow}{0}</zmlatex>，则角<zmlatex>A =</zmlatex>(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>90^{\\circ}</zmlatex></p>',
          '<p><zmlatex>60^{\\circ}</zmlatex></p>',
          '<p><zmlatex>45^{\\circ}</zmlatex></p>',
          '<p><zmlatex>30^{\\circ}</zmlatex></p>'
        ],
        answerList: [
          'D'
        ],
        analysis: '<p>因为<zmlatex>G</zmlatex>是<zmlatex>{\\Delta &nbsp;ABC}</zmlatex>的重心，所以<zmlatex>\\overset{\\rightarrow}{{GA}} + \\overset{\\rightarrow}{{GB }} + \\overset{\\rightarrow}{{GC}} = \\overset{\\rightarrow}{0}</zmlatex>；而<zmlatex>a\\overset{\\rightarrow}{{G{A}}} + b\\overset{\\rightarrow}{{GB}} + \\frac{\\sqrt{3}}{3}c\\overset{\\rightarrow}{{GC}} = \\overset{\\rightarrow}{0}</zmlatex>，两式联立削去<zmlatex>\\overset{\\rightarrow}{{GC}}</zmlatex>得:<zmlatex>(a - \\frac{\\sqrt{3}}{3}c)\\overset{\\rightarrow}{{G{A}}} = - (b - \\frac{\\sqrt{3}}{3}c)\\overset{\\rightarrow}{{GB }}</zmlatex>；而<zmlatex>\\overset{\\rightarrow}{{G{A}}}</zmlatex>,<zmlatex>\\overset{\\rightarrow}{{GB }}</zmlatex>不共线，所以<zmlatex>a - \\frac{\\sqrt{3}}{3}c = b - \\frac{\\sqrt{3}}{3}c = 0</zmlatex>，可得<zmlatex>a = b = \\frac{\\sqrt{3}}{3}c</zmlatex>；<zmlatex>{\\Delta &nbsp;ABC}</zmlatex>中由余弦定理得<zmlatex>{cosA} = \\frac{b^{2} + c^{2} - a^{2}}{2bc} = \\frac{\\sqrt{3}}{2}</zmlatex>，所以<zmlatex>A = 30^{\\circ}</zmlatex>.选<zmlatex>D</zmlatex>.</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180511125818_8078.png" zmtype="big"/></p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 15,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2015,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1,
          2,
          0
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6615,
          6668
        ],
        examPointIdList: [
          9368
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 180,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1524211409000,
        createdUser: 1002318621,
        updatedTime: 1538992695000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 2,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '三角形中余弦定理的应用',
          '重心坐标公式'
        ],
        examPointNameList: [
          '余弦定理的综合应用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2015年辽宁省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 6
    },
    {
        id: 1006474,
        title: '<p>在平面直角坐标系<zmlatex>{xOy}</zmlatex>中有不共线三点<zmlatex>P(a_{1},b_{1}),A(a_{2},b_{2}),B(a_{3},b_{3})</zmlatex>.实数<zmlatex>\\lambda,\\mu</zmlatex>满足<zmlatex>\\lambda + \\mu = {{\\lambda}{\\mu}} \\neq 0</zmlatex>,则以<zmlatex>P</zmlatex>为起点的向量<zmlatex>\\lambda\\overrightarrow{{PA}},\\mu\\overrightarrow{{PB}}</zmlatex>的终点连线一定过点（&nbsp; ）</p>',
        content: null,
        optionList: [
          '<p><zmlatex>(a_{2} + a_{3} - a_{1},b_{2} + b_{3} - b_{1})</zmlatex></p>',
          '<p><zmlatex>(b_{2} + b_{3} - b_{1},a_{2} + a_{3} - a_{1})</zmlatex></p>',
          '<p><zmlatex>(a_{2} + a_{3} - 2a_{1},b_{2} + b_{3} - 2b_{1})</zmlatex></p>',
          '<p><zmlatex>(b_{2} + b_{3} - 2b_{1},a_{2} + a_{3} - 2a_{1})</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p>如图,设<zmlatex>\\lambda\\overrightarrow{{PA}} = \\overrightarrow{{PC}},\\mu\\overrightarrow{{PB}} = \\overrightarrow{{PD}},M</zmlatex>是线段<zmlatex>{CD}</zmlatex>的一点,设<zmlatex>CM = kCD\\left( 0 \\leq k \\leq 1 \\right)</zmlatex>,则<zmlatex>\\overrightarrow{{PC}} = \\lambda\\overrightarrow{{PA}} = \\left( \\lambda\\left( a_{2} - a_{1},b_{2} - b_{1} \\right) \\right),\\overrightarrow{{PD}} = \\mu\\overrightarrow{{PB}} = \\left( \\mu\\left( a_{3} - a_{1},b_{3} - b_{1} \\right) \\right)</zmlatex>,<zmlatex>\\therefore\\overrightarrow{{PM}}=\\overrightarrow{{PC}} + \\overrightarrow{{CM}}=\\overrightarrow{{PC}} + k\\overrightarrow{{CD}}=\\overrightarrow{{PC}} + k\\left( \\overrightarrow{{PD}} - \\overrightarrow{{PC}} \\right)={k{\\mu}}\\overrightarrow{{PB}} + \\left( 1 - k \\right)\\lambda\\overrightarrow{{PA}}</zmlatex></p><p><zmlatex>=({k{\\mu}}\\left( a_{3} - a_{1} \\right) + \\left( 1 - k \\right)\\lambda\\left( a_{2} - a_{1} \\right),{k{\\mu}}\\left( b_{3} - b_{1} \\right) + \\left( 1 - k \\right)\\lambda(b_{2} - b_{1})</zmlatex>,又因为<zmlatex>\\lambda + \\mu = {{\\lambda}{\\mu}} \\neq 0</zmlatex>,所以<zmlatex>\\frac{1}{\\lambda} + \\frac{1}{\\mu} = 1</zmlatex>,所以当<zmlatex>k\\frac{1}{\\mu}</zmlatex>时,<zmlatex>1 - k = \\frac{1}{\\lambda}</zmlatex>,此时,<zmlatex>\\overrightarrow{{PM}} =\n\n\\left( a_{2} + a_{3} - 2a_{1},b_{2} + b_{3} - 2b_{1} \\right)</zmlatex>,即不论<zmlatex>\\lambda,\\mu</zmlatex>取何值,线段<zmlatex>{CD}</zmlatex>都过点<zmlatex>\\left( a_{2} + a_{3} - 2a_{1},b_{2} + b_{3} - 2b_{1} \\right)</zmlatex>.故选<zmlatex>C</zmlatex>.</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180516011052_4764.png" zmtype="big"/></p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 23,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 3,
        recommendationIndex: null,
        rating: 4,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6651,
          6659,
          6662
        ],
        examPointIdList: [
          9312,
          9316,
          9328
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 1700,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1525674519000,
        createdUser: 1002330390,
        updatedTime: 1538991983000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 2,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '向量的线性运算',
          '平面向量基本定理中实数的取值范围',
          '点的坐标与向量坐标的关系'
        ],
        examPointNameList: [
          '三角形法则下的向量表示',
          '向量共线的性质定理',
          '平面向量坐标表示的应用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2016年海南省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 4
    },
    {
        id: 474412,
        title: '<p>已知向量<zmlatex>\\overrightarrow{a}=(1,2)</zmlatex>，<zmlatex>\\overrightarrow{b}=(1,0)</zmlatex>，<zmlatex>\\overrightarrow{c}=(3,4)</zmlatex>．若<zmlatex>\\lambda{}</zmlatex>为实数，<zmlatex>(\\overrightarrow{a}+\\lambda{}\\overrightarrow{b})//{}\\overrightarrow{c}</zmlatex>，则<zmlatex>\\lambda{}=</zmlatex>(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>\\frac{1}{4}</zmlatex></p>',
          '<p><zmlatex>\\frac{1}{2}</zmlatex></p>',
          '<p><zmlatex>1</zmlatex></p>',
          '<p><zmlatex>2</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p><zmlatex>\\because{}</zmlatex>向量<zmlatex>\\overrightarrow{a}=(1,2)</zmlatex>，<zmlatex>\\overrightarrow{b}=(1,0)</zmlatex>，<zmlatex>\\overrightarrow{c}=(3,4)</zmlatex>．</p><p><zmlatex>\\therefore{}\\overrightarrow{a}+\\lambda{}\\overrightarrow{b}=(1+\\lambda{},2)</zmlatex></p><p><zmlatex>{\\because}(\\overrightarrow{a}+\\lambda{}\\overrightarrow{b})//{}\\overrightarrow{c}</zmlatex>，</p><p><zmlatex>\\therefore{}4(1+\\lambda{})-6=0</zmlatex>，</p><p><zmlatex>\\therefore{}\\lambda{}=\\frac{1}{2}</zmlatex></p><p>故选：<zmlatex>B</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 25,
        cityId: 184,
        countyId: null,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6663,
          6664
        ],
        examPointIdList: [
          9325,
          9326,
          9555
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 1,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: null,
        createdUser: null,
        updatedTime: null,
        updatedUser: null,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '平面向量的坐标运算',
          '平面向量共线的坐标表示'
        ],
        examPointNameList: [
          '平面向量的坐标运算',
          '平面向量共线平行的坐标表示',
          '向量共线或平行的坐标表示及应用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: null,
        deleted: null,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
    },
    {
        id: 691834,
        title: '<p>已知<zmlatex>A\\left( 1,-2 \\right)</zmlatex>，<zmlatex>B\\left( a,-1 \\right)</zmlatex>，<zmlatex>C\\left( -b,0 \\right)</zmlatex>三点共线，其中<zmlatex>a{\\gt}0,b{\\gt}0</zmlatex>，则<zmlatex>\\frac{1}{a}+\\frac{2}{b}</zmlatex>的最小值是(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>2</zmlatex></p>',
          '<p><zmlatex>4</zmlatex></p>',
          '<p><zmlatex>6</zmlatex></p>',
          '<p><zmlatex>8</zmlatex></p>'
        ],
        answerList: [
          'D'
        ],
        analysis: '<p>因为<zmlatex>A\\left( 1,-2 \\right)</zmlatex>，<zmlatex>B\\left( a,-1 \\right)</zmlatex>，<zmlatex>C\\left( -b,0 \\right)</zmlatex>三点共线,所以<zmlatex>\\overrightarrow{AB}</zmlatex>与<zmlatex>\\overrightarrow{BC}</zmlatex>共线；而<zmlatex>\\overrightarrow{AB}=\\left( a-1,1 \\right),\\overrightarrow{BC}=\\left( -b-a,1 \\right)</zmlatex>，所以<zmlatex>\\left( a-1 \\right)\\times 1-1\\times \\left( -b-a \\right)=0</zmlatex>,化简得：<zmlatex>2a+b=1</zmlatex>；因为<zmlatex>a{\\gt}0,b{\\gt}0</zmlatex>，所以<zmlatex>\\frac{1}{a}+\\frac{2}{b}=\\left( \\frac{1}{a}+\\frac{2}{b} \\right)\\left( 2a+b \\right)=4+\\frac{4a}{b}+\\frac{b}{a}\\ge 4+2\\sqrt{4}=8</zmlatex>&nbsp;(当且仅当<zmlatex>2a=b=\\frac{1}{2}</zmlatex>时等号成立).所以<zmlatex>\\frac{1}{a}+\\frac{2}{b}</zmlatex>的最小值是<zmlatex>8</zmlatex>.选<zmlatex>D</zmlatex>.</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 26,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2015,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          3,
          2,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6665,
          6769
        ],
        examPointIdList: [
          9136,
          9409
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 1,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1524207847000,
        createdUser: 1003257912,
        updatedTime: 1538992349000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '三点共线的坐标表示',
          '基本不等式与最大（小）值'
        ],
        examPointNameList: [
          '三点共线问题',
          '利用基本不等式求最值'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2015年广东省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 4
    },
    {
        id: 532657,
        title: '<p>已知半径为<zmlatex>2</zmlatex>的扇形<zmlatex>AOB</zmlatex>中,<zmlatex>\\angle AOB=120{}^\\circ</zmlatex>,<zmlatex>C</zmlatex>是<zmlatex>OB</zmlatex>的中点,<zmlatex>P</zmlatex>为弧<zmlatex>AB</zmlatex>上任意一点,且<zmlatex>\\overrightarrow{OP}=\\lambda \\overrightarrow{OA}+\\mu \\overrightarrow{OC}</zmlatex>,则<zmlatex>\\lambda +\\mu</zmlatex>的最大值为（&nbsp; ）</p>',
        content: null,
        optionList: [
          '<p><zmlatex>2</zmlatex></p>',
          '<p><zmlatex>\\frac{\\sqrt{21}}{3}</zmlatex></p>',
          '<p><zmlatex>\\frac{2\\sqrt{21}}{3}</zmlatex></p>',
          '<p><zmlatex>\\frac{4\\sqrt{21}}{3}</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p>建立如图所示的平面直角坐标系,则<zmlatex>A\\left( 2,0 \\right)</zmlatex>,<zmlatex>C\\left( -\\frac{1}{2},\\frac{\\sqrt{3}}{2} \\right)</zmlatex>,</p><p>则<zmlatex>\\overrightarrow{OA}=\\left( 2,0 \\right)</zmlatex>,<zmlatex>\\overrightarrow{OC}=\\left( -\\frac{1}{2},\\frac{\\sqrt{3}}{2} \\right)</zmlatex>,</p><p>设<zmlatex>P\\left( 2\\cos \\theta ,2\\sin \\theta &nbsp;\\right)</zmlatex>,</p><p>则:<zmlatex>\\lambda \\left( 2,0 \\right)+\\mu \\left( -\\frac{1}{2},\\frac{\\sqrt{3}}{2} \\right)=\\left( 2\\cos \\theta ,2\\sin \\theta &nbsp;\\right)\\left\\{ \\begin{matrix}\n\n &nbsp; 2\\lambda -\\frac{1}{2}\\mu =2\\cos \\theta &nbsp; \\\\\n\n &nbsp; \\frac{\\sqrt{3}}{2}\\mu =2\\sin \\theta &nbsp; \\\\\n\n\\end{matrix} \\right.</zmlatex>,</p><p>即:<zmlatex>\\left\\{ \\begin{matrix}\n\n &nbsp; 2\\lambda -\\frac{1}{2}\\mu =2\\cos \\theta &nbsp; \\\\\n\n &nbsp; \\frac{\\sqrt{3}}{2}\\mu =2\\sin \\theta &nbsp; \\\\\n\n\\end{matrix} \\right.</zmlatex>,</p><p>解得:<zmlatex>\\left\\{ \\begin{matrix}\n\n &nbsp; \\mu =\\frac{4}{\\sqrt{3}}\\sin \\theta &nbsp; \\\\\n\n &nbsp; \\lambda =\\cos \\theta +\\frac{1}{\\sqrt{3}}\\sin \\theta &nbsp; \\\\\n\n\\end{matrix} \\right.</zmlatex>,</p><p>则:<zmlatex>\\lambda +\\mu =\\frac{5}{\\sqrt{3}}\\sin \\theta +\\cos \\theta =\\frac{2\\sqrt{21}}{3}\\sin \\left( \\theta +\\varphi &nbsp;\\right)</zmlatex>,</p><p>其中<zmlatex>\\sin \\varphi =\\frac{\\sqrt{3}}{5}</zmlatex>,</p><p>据此可知,当<zmlatex>\\sin \\left( \\theta +\\varphi &nbsp;\\right)=1</zmlatex>时,<zmlatex>\\lambda +\\mu</zmlatex>取得最大值<zmlatex>\\frac{2\\sqrt{21}}{3}</zmlatex>.</p><p>本题选择<zmlatex>C</zmlatex>选项.</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180427225355_4058.jpg" zmtype="big"/></p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 27,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 4,
        distinction: 3,
        recommendationIndex: null,
        rating: 3,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6571,
          6587,
          6663
        ],
        examPointIdList: [
          9233,
          9282,
          9325
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 28,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1523410113000,
        createdUser: 1002318580,
        updatedTime: 1537150521000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 3,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '函数y=Asin(wx+φ)的值域',
          '两角和与差的正弦公式',
          '平面向量的坐标运算'
        ],
        examPointNameList: [
          '正弦函数值域或最值问题',
          '辅助角公式的应用',
          '平面向量的坐标运算'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2016年广西省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
    },
    {
        id: 1044838,
        title: '<p>设点<zmlatex>P</zmlatex>是<zmlatex>{\\triangle}ABC</zmlatex>所在平面内的一点,<zmlatex>\\overrightarrow{{PA}}+2\\overrightarrow{{PB}}+3\\overrightarrow{{PC}}=4\\overrightarrow{{AB}}</zmlatex>,且<zmlatex>{\\triangle}ABC</zmlatex>的面积为<zmlatex>S</zmlatex>,则下列判断正确的是( &nbsp;)</p>',
        content: null,
        optionList: [
          '<p>点<zmlatex>P</zmlatex>在<zmlatex>{\\triangle}ABC</zmlatex>外,且<zmlatex>{\\triangle}APC</zmlatex>的面积为<zmlatex>\\frac{1}{3}S</zmlatex>&nbsp;</p>',
          '<p>点<zmlatex>P</zmlatex>在<zmlatex>{\\triangle}ABC</zmlatex>外,且<zmlatex>{\\triangle}APC</zmlatex>的面积为<zmlatex>\\frac{1}{2}S</zmlatex></p>',
          '<p>点<zmlatex>P</zmlatex>在<zmlatex>{\\triangle}ABC</zmlatex>内,且<zmlatex>{\\triangle}APC</zmlatex>的面积为<zmlatex>\\frac{1}{3}S</zmlatex></p>',
          '<p>点<zmlatex>P</zmlatex>在<zmlatex>{\\triangle}ABC</zmlatex>内,且<zmlatex>{\\triangle}APC</zmlatex>的面积为<zmlatex>\\frac{1}{2}S</zmlatex></p>'
        ],
        answerList: [
          'A'
        ],
        analysis: '<p>由<zmlatex>\\overrightarrow{{PA}}+2\\overrightarrow{{PB}}+3\\overrightarrow{{PC}}=4\\overrightarrow{{AB}}</zmlatex>,得<zmlatex>\\overrightarrow{{AP}}=-\\frac{1}{3}\\overrightarrow{{AB}}+\\frac{1}{2}\\overrightarrow{{AC}}</zmlatex>,根据平面向量基本定理,作出图形,由此知<zmlatex>{\\triangle}APC</zmlatex>与<zmlatex>{\\triangle}ABC</zmlatex>的底相同,都是<zmlatex>AC</zmlatex>,高的比等于<zmlatex>\\frac{|\\overrightarrow{{AB}}{^\\prime}|}{|\\overrightarrow{{AB}}|} = \\frac{1}{3}</zmlatex>,则它们面积的比也是<zmlatex>\\frac{1}{3}</zmlatex>,即<zmlatex>{\\triangle}APC</zmlatex>的面积为<zmlatex>\\frac{1}{3}S</zmlatex>,故选择<zmlatex>A</zmlatex>.</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180523131546_4840.jpg" zmtype="small"/></p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 38,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 4,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          2,
          3,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6651,
          6656,
          6672
        ],
        examPointIdList: [
          9309,
          9323,
          9340
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 1,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1525840470000,
        createdUser: 1003231785,
        updatedTime: 1538987622000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 3,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '向量的线性运算',
          '平面向量基本定理',
          '平面向量数量积的几何意义'
        ],
        examPointNameList: [
          '利用向量及线性运算解决平面几何问题',
          '平面向量基本定理的应用',
          '平面向量数量积的综合运用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2016年浙江省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 4
    },
    {
        id: 741753,
        title: '<p>如图,在<zmlatex>{\\triangle}ABC</zmlatex>中,<zmlatex>BO</zmlatex>为<zmlatex>AC</zmlatex>边上的中线,<zmlatex>\\overrightarrow{BG}{=}2\\overrightarrow{GO}</zmlatex>,设<zmlatex>\\overrightarrow{CD}{/\\!/}\\overrightarrow{AG}</zmlatex>,若<zmlatex>\\overrightarrow{AD}=\\frac{1}{5}\\overrightarrow{AB}+{\\lambda}AC({\\lambda}{\\in}R)</zmlatex>,则<zmlatex>{\\lambda}</zmlatex>的值为(&nbsp; )</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180425231447_5526.png" zmtype="big"/></p>',
        content: null,
        optionList: [
          '<p><zmlatex>\\frac{1}{5}</zmlatex></p>',
          '<p><zmlatex>\\frac{1}{2}</zmlatex></p>',
          '<p><zmlatex>\\frac{6}{5}</zmlatex></p>',
          '<p><zmlatex>2</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p>本题主要考查平面向量基本定理、向量共线定理、三角形性质的判断及向量的线性运算.</p><p>延长<zmlatex>AG</zmlatex>交<zmlatex>BC</zmlatex>于点<zmlatex>F</zmlatex>，</p><p><zmlatex>{\\because}BO</zmlatex>为边<zmlatex>AC</zmlatex>上的中线,<zmlatex>\\overrightarrow{BG}{=}2\\overrightarrow{GO}</zmlatex>,</p><p><zmlatex>{\\therefore}AF</zmlatex>为边<zmlatex>BC</zmlatex>上的中线,<zmlatex>{\\therefore}\\overrightarrow{AF}=\\frac{1}{2}\\overrightarrow{AB}+\\frac{1}{2}\\overrightarrow{AC}</zmlatex>,又<zmlatex>\\overrightarrow{CD}=\\overrightarrow{AD}-\\overrightarrow{AC}=\\frac{1}{5}\\overrightarrow{AB}+({\\lambda}-1)\\overrightarrow{AC}</zmlatex>,</p><p><zmlatex>\\overrightarrow{CD}{/\\!/}\\overrightarrow{AG}</zmlatex></p><p><zmlatex>{\\therefore}\\frac{1}{5}:\\frac{1}{2}=({\\lambda}-1):\\frac{1}{2}</zmlatex>,解得<zmlatex>{\\lambda}=\\frac{6}{5}</zmlatex>.</p><p>故选<zmlatex>C</zmlatex>.</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 13,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          2,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6642,
          6645,
          6656
        ],
        examPointIdList: [
          9304,
          9306,
          9317
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 942,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1524455247000,
        createdUser: 1002330390,
        updatedTime: 1539076360000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 2,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '向量加法的平行四边形法则',
          '向量的减法的定义',
          '平面向量基本定理'
        ],
        examPointNameList: [
          '向量的加减法运算',
          '向量的线性运算性质及几何意义',
          '向量共线定理的应用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2016年黑龙江省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 6
    },
    {
        id: 955422,
        title: '<p><zmlatex>M</zmlatex>是<zmlatex>{\\triangle}ABC</zmlatex>所在平面内一点,<zmlatex>\\frac{2}{3}\\overrightarrow {MB} &nbsp;+ \\overrightarrow {MA} &nbsp;+ \\overrightarrow {MC} &nbsp;= 0</zmlatex>,<zmlatex>D</zmlatex>为<zmlatex>AC</zmlatex>中点,则<zmlatex>\\frac{{|\\overrightarrow {MD} |}}{{|\\overrightarrow {BM} |}}</zmlatex>的值为（ &nbsp;）</p>',
        content: null,
        optionList: [
          '<p><zmlatex>\\frac{1}{2}</zmlatex></p>',
          '<p><zmlatex>\\frac{1}{3}</zmlatex></p>',
          '<p><zmlatex>1</zmlatex></p>',
          '<p><zmlatex>2</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p>如图所示,由<zmlatex>D</zmlatex>为<zmlatex>AC</zmlatex>之中点,延长<zmlatex>MD</zmlatex>至<zmlatex>E</zmlatex>,使得<zmlatex>DE=MD</zmlatex>,故四边形<zmlatex>MAEC</zmlatex>为平行四边形,则<zmlatex>\\overrightarrow {MD} &nbsp;= \\frac{1}{2}\\overrightarrow {ME} &nbsp;= \\frac{1}{2}(\\overrightarrow {MA} &nbsp;+ \\overrightarrow {MC} )</zmlatex>,又<zmlatex>\\overrightarrow {MB} &nbsp;+ \\frac{3}{2}\\overrightarrow {MA} &nbsp;+ \\frac{3}{2}\\overrightarrow {MC} &nbsp;= 0</zmlatex>,则<zmlatex>\\overrightarrow {MB} &nbsp;= &nbsp;- \\frac{3}{2}(\\overrightarrow {MA} &nbsp;+ \\overrightarrow {MC} ) = &nbsp;- 3\\overrightarrow {MD}</zmlatex>;得<zmlatex>\\frac{{|\\overrightarrow {MD} |}}{{|\\overrightarrow {BM} |}} = \\frac{{|\\overrightarrow {MD} |}}{{| - 3\\overrightarrow {MD} |}} = \\frac{1}{3}</zmlatex>.故选<zmlatex>B</zmlatex>.</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180513113751_2989.png" zmtype="big"/></p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 19,
        cityId: 0,
        countyId: 0,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: null,
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6651,
          6652,
          6689
        ],
        examPointIdList: [
          9309,
          9344
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 46,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: null,
        createdUser: null,
        updatedTime: null,
        updatedUser: null,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: null,
        suggestTime: 2,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '向量的线性运算',
          '三角形的中线公式向量表示',
          '平面向量的几何应用'
        ],
        examPointNameList: [
          '利用向量及线性运算解决平面几何问题',
          '向量在几何中的应用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: null,
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 4
    },
    {
        id: 343977,
        title: '<p>在直角梯形<zmlatex>ABCD</zmlatex>中，<zmlatex>\\angle A={{90}^{\\circ }}</zmlatex>，<zmlatex>\\angle B={{30}^{\\circ}}</zmlatex>，<zmlatex>AB=2\\sqrt{3}</zmlatex>，<zmlatex>BC=2</zmlatex>，点<zmlatex>E</zmlatex>在线段<zmlatex>CD</zmlatex>上，若<zmlatex>\\overrightarrow{AE}=\\overrightarrow{AD}+\\mu \\overrightarrow{AB}</zmlatex>，则<zmlatex>\\mu</zmlatex>的取值范围是(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>[0,1]</zmlatex></p>',
          '<p><zmlatex>[0,\\sqrt{3}]</zmlatex></p>',
          '<p><zmlatex>[0,\\frac{1}{2}]</zmlatex></p>',
          '<p><zmlatex>[\\frac{1}{2},2]</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p>如图所示，过点<zmlatex>C</zmlatex>作<zmlatex>CF\\bot AB</zmlatex>，垂足为<zmlatex>F</zmlatex>，</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180320155303_1766.png" zmtype="big"/></p><p>在<zmlatex>\\text{Rt}\\triangle BCF</zmlatex>中，<zmlatex>\\angle B={{30}^{\\circ}}</zmlatex>，<zmlatex>\\therefore CF=1,BF=\\sqrt{3}</zmlatex>，</p><p><zmlatex>\\because AB=2\\sqrt{3}</zmlatex>，<zmlatex>\\therefore AF=\\sqrt{3}</zmlatex>，</p><p>由四边形<zmlatex>AFCD</zmlatex>是平行四边形，可得<zmlatex>CD=AF=\\sqrt{3}=\\frac{1}{2}AB</zmlatex>，</p><p><zmlatex>\\because \\overrightarrow{AE}=\\overrightarrow{AD}+\\overrightarrow{DE}=\\overrightarrow{AD}+\\mu\\overrightarrow{AB}</zmlatex>，</p><p><zmlatex>\\therefore \\overrightarrow{DE}=\\mu \\overrightarrow{AB}</zmlatex>，<zmlatex>\\because \\overrightarrow{DE}\\text{//}\\overrightarrow{DC},\\overrightarrow{DC}=\\frac{1}{2}\\overrightarrow{AB}</zmlatex>，</p><p><zmlatex>\\therefore 0\\leqslant \\mu \\leqslant \\frac{1}{2}</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 3,
        cityId: 3,
        countyId: 3,
        schoolId: null,
        year: 2015,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          2,
          3
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6641,
          6651,
          6661
        ],
        examPointIdList: [
          8959,
          8970,
          8974
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 45,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: null,
        createdUser: null,
        updatedTime: null,
        updatedUser: null,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 3,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '向量加法的三角形法则',
          '向量的线性运算',
          '平面向量的坐标表示'
        ],
        examPointNameList: [
          '空间向量的加减法',
          '利用坐标法解决立体几何中的探索问题',
          '空间向量运算的坐标表示'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: null,
        deleted: null,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
    },
    {
        id: 573355,
        title: '<p>已知平面向量满足：<zmlatex>\\overrightarrow{PA}{\\bot}\\overrightarrow{PB},\\overrightarrow{PA}{+}\\overrightarrow{PB}{=}\\overrightarrow{PM}</zmlatex>,若<zmlatex>|\\overrightarrow{QM}|{\\lt}1</zmlatex>,则<zmlatex>|\\overrightarrow{PQ}|</zmlatex>的取值范围是(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>(2,2\\sqrt{2}]</zmlatex></p>',
          '<p><zmlatex>(\\sqrt{7},3]</zmlatex></p>',
          '<p><zmlatex>(\\sqrt{7},2\\sqrt{2}]</zmlatex></p>',
          '<p><zmlatex>(2\\sqrt{2},3]</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p>本题考查平面向量基本定理、向量的模，意在考查考生的分析问题与解决问题能力及运算求解能力.</p><p>如图以线段<zmlatex>AB</zmlatex>所在的直线为<zmlatex>x</zmlatex>轴，<zmlatex>AB</zmlatex>的中垂线为<zmlatex>y</zmlatex>轴建立平面直角坐标，由<zmlatex>|\\overrightarrow{QA}|=|\\overrightarrow{QB}|=2</zmlatex>,</p><p>则点<zmlatex>Q</zmlatex>在<zmlatex>y</zmlatex>轴上，设点<zmlatex>P(x,y)</zmlatex>，则<zmlatex>M(-x,-y)</zmlatex>，<zmlatex>A(a,0)</zmlatex>，<zmlatex>Q(0,-\\sqrt{4-{{a}^{2}}})</zmlatex>，</p><p>由<zmlatex>\\overrightarrow{PA}\\bot \\overrightarrow{PB}</zmlatex>得<zmlatex>{\\triangle}PAB</zmlatex>为直角三角形，且中线<zmlatex>|PO|=|a|</zmlatex>，又<zmlatex>|\\overrightarrow{QM}|{\\lt}1</zmlatex>得<zmlatex>{{x}^{2}}+{{y}^{2}}={{a}^{2}}</zmlatex>且<zmlatex>0\\le {{x}^{2}}+y-\\sqrt{4-{{a}^{2}}}{\\lt}1</zmlatex>，</p><p>得<zmlatex>3{\\lt}2y\\sqrt{4-{{a}^{2}}}\\le 4</zmlatex>，得<zmlatex>|PQ{{|}^{2}}={{x}^{2}}+{{(y+\\sqrt{4-{{a}^{2}}})}^{2}}=2y\\sqrt{4-{{a}^{2}}}+4</zmlatex>，故<zmlatex>7{\\lt}|PQ{{|}^{2}}\\le 8</zmlatex>，则<zmlatex>\\sqrt{7}{\\lt}|PQ{{|}}\\le 2\\sqrt{2}</zmlatex>.</p><p>故本题正确答案为<zmlatex>C</zmlatex>.</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180425145556_9570.png" zmtype="small"/></p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 37,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6634,
          6656,
          6663
        ],
        examPointIdList: [
          9323,
          9325,
          9335
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 0,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: null,
        createdUser: null,
        updatedTime: null,
        updatedUser: null,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 2,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '向量的模',
          '平面向量基本定理',
          '平面向量的坐标运算'
        ],
        examPointNameList: [
          '平面向量基本定理的应用',
          '平面向量的坐标运算',
          '求向量的模'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: null,
        deleted: null,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
    },
    {
        id: 432651,
        title: '<p>在<zmlatex>\\mathsf{\\triangle }ABC</zmlatex>中，<zmlatex>D</zmlatex>为<zmlatex>BC</zmlatex>边上一点，且<zmlatex>AD\\bot BC</zmlatex>，向量<zmlatex>\\overrightarrow{AB}+\\overrightarrow{AC}</zmlatex>与向量<zmlatex>\\overrightarrow{AD}</zmlatex>共线．</p><p>若<zmlatex>\\left| \\overrightarrow{AC} \\right|=\\sqrt{10}</zmlatex>，<zmlatex>\\left| \\overrightarrow{BC} \\right|=2</zmlatex>，<zmlatex>\\overrightarrow{GA}+\\overrightarrow{GB}+\\overrightarrow{GC}=0</zmlatex>，则<zmlatex>\\frac{\\left| \\overrightarrow{AB} \\right|}{\\left| \\overrightarrow{CG} \\right|}=</zmlatex>(&nbsp; )．</p>',
        content: null,
        optionList: [
          '<p><zmlatex>3</zmlatex></p>',
          '<p><zmlatex>\\sqrt{5}</zmlatex></p>',
          '<p><zmlatex>2</zmlatex></p>',
          '<p><zmlatex>\\frac{\\sqrt{10}}{2}</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p><zmlatex>{\\because}AD\\bot BC</zmlatex>，<zmlatex>\\overrightarrow{AB}+\\overrightarrow{AC}</zmlatex>与向量<zmlatex>\\overrightarrow{AD}</zmlatex>共线，</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180403105320_2809.png" zmtype="big"/>&nbsp;</p><p>可得<zmlatex>BC</zmlatex>边上的中线与<zmlatex>AD</zmlatex>重合，即<zmlatex>\\mathsf{\\triangle }ABC</zmlatex>为等腰三角形，&nbsp;</p><p>且<zmlatex>AB=AC=\\sqrt{10}</zmlatex>，<zmlatex>BD=DC=1</zmlatex>，<zmlatex>AD=\\sqrt{10-1}=3</zmlatex>，&nbsp;</p><p>又<zmlatex>\\overrightarrow{GA}+\\overrightarrow{GB}+\\overrightarrow{GC}=\\overrightarrow{0}</zmlatex>，可知<zmlatex>G</zmlatex>为<zmlatex>\\mathsf{\\triangle }ABC</zmlatex>重心，&nbsp;</p><p>且<zmlatex>AG=2GD\\Rightarrow GD=1</zmlatex>，<zmlatex>CG=\\sqrt{1+1}=\\sqrt{2}</zmlatex>，&nbsp;</p><p><zmlatex>{\\therefore}\\frac{\\left| \\overrightarrow{AB} \\right|}{\\left| \\overrightarrow{CG} \\right|}=\\frac{\\sqrt{10}}{\\sqrt{2}}=\\sqrt{5}</zmlatex>．&nbsp;</p><p>故选<zmlatex>\\text{B}</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 12,
        phaseId: 3,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 26,
        cityId: 191,
        countyId: 1542,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          6651,
          6689
        ],
        examPointIdList: [
          9306,
          9344
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 120,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1522459659000,
        createdUser: 1002318621,
        updatedTime: 1538984660000,
        updatedUser: 1006266140,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          1,
          10
        ],
        suggestTime: 3,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '向量的线性运算',
          '平面向量的几何应用'
        ],
        examPointNameList: [
          '向量的线性运算性质及几何意义',
          '向量在几何中的应用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2016年广东省深圳市宝安区',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 4
    }
  ]
};