export default {
  code: '0',
  message: '',
  data: [
    {
      id: 1529741,
      title: '<p style="text-align: left;"><zmindent></zmindent>阅读下面的文字，完成1~3题。（本题共9分，每题3分）</p><p><zmindent></zmindent>所谓“被遗忘权”，即数据主体有权要求数据控制者永久删除有关数据主体的个人数据，有权被互联网遗忘，除非数据的保留有合法的理由。在大数据时代，数字化、廉价的存储器、易于提取、全球性覆盖作为数字化记忆发展的四大驱动力，改变了记忆的经济学，使得海量的数字化记忆不仅唾手可得，甚至比选择性删除所耗费的成本更低，记忆和遗忘的平衡反转，往事正像刺青一样刻在我们的数字肌肤上；遗忘变得困难，而记忆却成了常态。“被遗忘权”的出现，意在改变数据主体难以“被遗忘”的格局，赋子数据主体对信息进行自决控制的权利，并且有着更深的调节。修复大数据时代数字化记忆伦理的意义。</p><p><zmindent></zmindent>首先，“被遗忘权”不是消极地防御自己的隐私不受侵犯，而是主体能动地控制个人信息，并界定个人隐私的边界，进一步说，是主体争取主动建构个人数字化记忆与遗忘的权利。与纯粹的“隐私权”不同，“被遗忘权”更是一项主动性的权利，其权利主体可自主决定是否行使该项权利对网络上已经被公开的有关个人信息进行删除，是数据主体对自己的个人信息所享有的排除他人非法利用的权利。</p><p><zmindent></zmindent>其次，在数据快速流转且难以被遗忘的大数据时代，“被遗忘权”对调和人类记忆与遗忘的平衡具有重要的意义。如果在大数据时代不能“被遗忘”，那意味着人们容易被囚禁在数字化记忆的监狱之中。不论是个人的遗忘还是社会的遗忘，在某种程度上都是一种个人及社会修复和更新的机制，让我们能够从过去经验中吸取教训，面对现实，想象未来，而不仅仅被过去的记忆所束缚。</p><p><zmindent></zmindent>最后，大数据技术加进了人的主体身份的“被数据化”，人成为数据的表征，个人生活的方方面面都在以数据的形式被记忆。大数据所建构的主体身份会导致一种危险，即“我是”与“我喜欢”变成了“你是”与“你将会喜欢&quot;；大数据的力量可以利用信息去推动、劝服、影响甚至限制我们的认同。也就是说，不是主体想把自身塑造成什么样的人，而是客观的数据来显示主体是什么样的人，技术过程和结果反而成为支配人。压抑人的力量，进一步说，数字化记忆与认同背后的核心问题在于权力不由数据主体掌控，而是数据控制者选择和建构关于我们的数字化记忆，并塑造我们的认同。这种大数据的分类系统并不是客观中立的，而是指向特定的目的。因此，适度的、合理的遗忘，是对这种数字化记忆霸权的抵抗。</p><p style="text-align: right;">(摘编自袁梦倩《“被遗忘权”之争:大数据时代的数字化记忆与隐私边界》)</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 9,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2508559,
          questionId: 1529741,
          title: '<p>下列关于原文内容的理解和分析，正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>由于数字化记忆的发展，记忆与遗忘的平衡发生了反转，记忆变得更加容易。</p>',
            '<p>人的主体身份所以被数据化，是因为个人信息选择性删除所耗费的成本太高。</p>',
            '<p>“被遗忘权”和“隐私权”的提出都是为了对抗大数据，不过前者更积极一些。</p>',
            '<p>我们要对抗数字化记忆霸权，就要成为数据控制者并建构他人的数字化记忆。</p>'
          ],
          answerList: [
            'A'
          ],
          analysis: '<p>本题考查理解文意、筛选并整合文中的信息的能力。解释错误选项：B项，文章第四大段只要说明了人的主体身份被数据化的原因是大数据技术的发展，即“客观的数据来显示主体是什么样的人，技术过程和结果反而成为支配人。”和个人信息删除没有直接逻辑联系；C项，原文只是说“与纯粹的隐私权不同，被遗忘权更是一项主动的权利……非法使用的权利”并没有具体说明隐私权和大数据之间的关系；D项，原文最后一句说明“因此，适度的，合理的遗忘，是对抗数字化记忆霸权的抵抗”因此不是选项的“成为数据控制着并构建他人的数据记忆”。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2508560,
          questionId: 1529741,
          title: '<p>下列对原文论证的相关分析，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>文章以数字化记忆带来的威胁为立论的事实基础，论证了人被数据控制的危险。</p>',
            '<p>通过讨论大数据对隐私、记忆及主体身份等的影响，文章把论证推向了深入。</p>',
            '<p>与重视个人隐私的写作动机有关，文章着重论证了大数据对个人权利的影响。</p>',
            '<p>文章通过分析数字化记忆可能带来的问题，对我们的认同问题作出了全新论证。</p>'
          ],
          answerList: [
            'D'
          ],
          analysis: '<p>本题考查分析文章结构、归纳内容要点、概括中心意思的能力。找出原观点，解释错误选项：D项，文章并不是通过分析数字化记忆可能带来的问题来对我们的认同问题作出论证。分析文章的线索，全文主要通过讨论“被遗忘权”相关介绍来讨论数字化记忆和隐私边界。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2508561,
          questionId: 1529741,
          title: '<p>根据原文内容，下列说法不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>大数据时代的个人留在网上的信息太多，如果没有主动权。就难以保护隐私。</p>',
            '<p>遗忘是个人和社会的一种修复和更新机制，是我们面对现实和想象未来的基础。</p>',
            '<p>技术有支配和压压抑人的力量，这不仅影响个人隐私安全，而且影响整个社会。</p>',
            '<p>大数据的分类系统不是中立的，这将影响数据的客观呈现，使用时应有所辨析。<br/></p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>本题考查分析概括作者在文中的观点态度的能力。找出原观点出现的原句，解释错误选项：B项，原文：“不论是个人的遗忘还是社会的遗忘……”说明某种程度上遗忘是一种修复和封信体制，而且选项“是我们面对现实和未来的基础”无中生有。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 3,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529755,
      title: '<p style="text-align: left;">阅读下面的文字，完成小题。（本题共3小题，15分，第1小题3分，第2、3小题每题6分）<br/></p><p style="text-align: center;">有声电影&nbsp;&nbsp;</p><p style="text-align: center;">老舍</p><p><zmindent></zmindent>二姐还没看过有声电影。可是她已经有了一种理论。在没看见以前，先来一套说法，不独二姐如此，此之谓“知之为知之，不知为知之”也。她以为有声电影便是电机嗒嗒之声特别响亮而已。不然便是当电人——二姐管银幕上的英雄美人叫电人——互相巨吻的时候，台下鼓掌特别发狂，以成其“有声”。她确信这个，所以根本不想去看。</p><p><zmindent></zmindent>但据说有声电影是有说有笑而且有歌，她才想开开眼。恰巧打牌赢了钱，于是大请客。二姥姥三舅妈，四姨，小秃，小顺，四狗子，都在被请之列。<br/> <zmindent></zmindent>大家决定看午后两点半那一场，所以十二点动身也就行了。<br/> <zmindent></zmindent>到了十二点三刻谁也没动身，二姥姥找眼镜找了一刻来钟；确实不容易找，因为眼镜在她自己腰里带着呢。跟着就是三舅妈找钮子，翻了四只箱子也没找到，结果是换了件衣裳。四狗子洗脸又洗了一刻多钟，总算顺当。<br/> <zmindent></zmindent>出发了，走到巷ロ，一点名，小秃没影了。折回家里，找了半点多钟，没找着。大家决定不看电影了，找小秃更重要。把新衣裳全脱了，分头去找小秃。正在这个当儿，小秃回来了；原来他是跑在前面，而折回来找他们。好吧，再穿好衣裳走吧，反正巷外有的是洋车，耽误不了。<br/> <zmindent></zmindent>二姥姥给车价还按着老规矩，多一个铜子不给。这几年了，她不大出门，所以现在拉车的三毛两毛向她要，不是车价高了，是欺侮她年老走不功。她偏要走一个给他们瞧瞧，她确是有志向前迈步，不过脚是向前向后，连她自己也不准知道。四姨倒是能走,可惜为看电影特意换上高底鞋，似乎非扶着点什么不敢抬脚，她过去扶着二姥姥。要是趺倒的话，这二位一定是一齐倒下。<br/> <zmindent></zmindent>三点一刻到了电影院，电影已经开映，这当然是电影院不对；二姐实在觉得有骂一顿街的必要，可是没骂出来，她有时候也能“文明”一气。</p><p><zmindent></zmindent>既来之则安之，打了票，一进门，小顺便不干了，黑的地方有红眼鬼，无论如何不能进去。二姥姥一看里面黑洞洞，以为天已经黑了,想起来睡觉的舒服；她主张带小顺回家。谁不知道二姥姥已经是土埋了半截的人，不看回有声电影，将来见阎王的吋候要是盘问这一层呢？大家开了家庭会议，不行，二姥姥是不能走的，至于小顺，买几块糖好了&nbsp;，吃糖自然就看不见红眼鬼了。事情便这样解决了，四姨搀着二姥姥，三舅妈拉着小顺，二姐招呼着小秃和四狗子。看座的过来招待，可是大家各自为政地找座儿，忽前忽后，忽左忽右，离而复散，分而复合，主张不一，而又愿坐在一块儿。直落得二姐口干舌燥，二姥姥连喘带嗽，四狗子咆哮如雷，看座得满头是汗。观众们全忘了看电影，一齐恶声地“吃”，但是压不下去二姐的指挥口令。二姐在公共场所说话特别响亮，要不怎样是“外场”人呢。</p><p><zmindent></zmindent>直到看座的电筒中的电已使净，大家才一狠心找到了座。不过，总不能忘了谦恭呀，况且是在公共场所。二姥姥年高有德，当然往里坐。可足四姨是姑奶奶呀；而二姐是姐姐兼主人；而三舅妈到底是媳妇；而小顺子等是孩子；一部伦理从何处说起？大家打架似的推让，把前后左右的观众都感化得直叫老天爷。好容易一齐坐下，可是糖还没买呢！二姐喊卖糖的，真喊得有劲，连卖票的都进来了，以为是卖糖的杀了人。</p><p><zmindent></zmindent>糖买过了，二姥姥想起一件大事——还没咳嗽呢。二姥姥一阵咳嗽。引起二姐的孝心，与四姨三舅妈说起二姥姥的后事来。老人家像二姥姥这样的，是不怕儿女当面讲论自己的后事。而且乐意参加些意见。如“别的都是小事，我就是要个金九连环。也别忘了糊一对童儿！”这一说起来，还有完吗？说也奇怪，越是在戏馆电场里，家事越显着复杂。大家刚说到热闹的地方，忽，电灯亮了，人们全往外走。二姐喊卖瓜子的；说起家务要不吃瓜子便不够派儿。看座的过来了，“这场完了，晚场八点才开呢。”</p><p><zmindent></zmindent>只好走吧，一直到二姥姥睡了觉，二姐才想起来问：“有声电影到底怎么说来着？”三舅妈想了想：“管它呢，反正我没听见。”还是四姨细心，说看见一个洋鬼子吸烟，还从鼻子里冒烟呢，“鼻子冒烟，和真的一样，你就说！”大家都赞叹不已。</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 0,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 1,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2508488,
          questionId: 1529755,
          title: '<p>下列对小说相关内容和艺术特色的分析鉴赏，不正确的一项是（ &nbsp;）</p>',
          optionList: [
            '<p>小说塑造了市井妇女的群像，同时对其中认为也分别作了较为精细的刻画，如“外场”人二姐、“特意换上高底鞋”的四姨、“不太出门”的二姥姥。<br/></p>',
            '<p>在公共场所电影院观看具有私密性的“电人巨吻”并发狂鼓掌，或是在这一场合大谈家事而心安理得，都是作者眼中当时社会生活的怪现象。<br/></p>',
            '<p>小说开头部分写二姐等人对有声电影无知，结尾写大家对有声电影“赞叹不已”，较为完整地描写了普通市民令人啼笑皆非的思想意识转变过程。<br/></p>',
            '<p>小说标题为“有声电影”，既是指有声电影这一新奇事物，也可指二姐等人在电影院一系列“有声”的喧哗表现，可谓一语双关。<br/></p>'
          ],
          answerList: [
            'C'
          ],
          analysis: '<p>C选项说法错误，文章之中并不涉及到思想意识的转变。在最初大家对有声电影便是无知的。但当整场电影结束之后，大家实际上依然是“管它呢，反正我没听见”的一种态度。至于说“赞叹不已”不过是自欺欺人罢了，这也是它打上引号的原因。从头至尾，大家从来就没有透彻明白有声电影的真正含义，更不用提“思想意识的转变”了。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2508489,
          questionId: 1529755,
          title: '<p>请结合二姐等人看有声电影的经过，简要分析小说所揭示的市民面对新奇事物的具体心态。</p><p><zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>①对待新奇事物，还没亲见就先有说法，不知为知之，揭示出二姐等人傲慢无知的自大。</p><p>②听说有声电影真有新奇之处，就想开开眼，是一种从众、趋新的心态。</p><p>③到了电影院后也不真的看电影，不愿对新奇事物进一步了解探究，实质上是一种固步自封的心态。</p><p>④对有声电影胡乱作出共识评价，隐含的是二姐等人面对新奇事物时无所适从的焦虑不安。</p>'
          ],
          analysis: '<p>本题考查小说中的人物形象。此题的解答需要关注原文，依据原文内容得出自己的判断认知。原文中“在没看见以前，先来一套说法”、“她确信这个，所以根本不想去看”展现出了二姐先入为主的否定批判，认为外来事物不过如此；直至“据说有声电影是有说有笑而且有歌”她才希望从众进而有所松动；在电影院中“越是在戏馆电影场里，家事越显着复杂”，并不认真的去看电影，只聊家常，显示出他们实质上并非是去认真观看电影的；当电影结束之后，大家没有听清楚任何内容，却连连夸赞“和真的一样”，暗含着盲目媚外，更多的则是自我欺骗、自我麻醉，只能承认这些自己看不懂的内容是美好的。</p>',
          typeId: 4,
          score: 6,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2508490,
          questionId: 1529755,
          title: '<p>小说运用多种手法以取得语言的幽默效果，请从文中举出三处手法不同的例子，并简要分析。<br/><zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>1.“知之为知之，不知为知之”或“一部伦理从何处说起”，借用并改换了经典语句以造成幽默效果。2.如出门时二老找眼镜，三舅妈找钮子，四狗子洗脸，同一行为模式重复多次产生喜剧效果。3.如“既来之则安之，打了票和忽前忽后，忽左忽右，离而复散，分而复合，主张不一而又愿坐在一块儿”，将书面语，口语混搭，庄谐并出；4.如“直落得二姐口干舌燥，二姥姥连喘带咳，四狗子咆哮如雷，看座的满头是汗”，使用了排比手法描写人物窘态，总带有打油诗的诙谐意味。5.如二姐等人打架似的推让座位，把前后左右的观众都感化得直喊叫老天爷”，把抱怨说成“感化”，反话正说，既讽刺又幽默。6.如二姐喊叫卖糖的，声音之大令人“以为是卖糖的杀了人”，这种夸张令人忍俊不禁。</p>'
          ],
          analysis: '<p>本题考查小说的表现手法。常见的表现手法有衬托、对比、象征、欲扬先抑、托物言志、借景抒情、悬念、伏笔、铺垫、照应、以小见大、虚实结合、直抒胸臆、动静结合、讽刺、开门见山、卒章显志、用典、联想、想象、比喻、拟人、夸张、排比等。结合文章内容，进行具体分析，即可得出答案。文章之中运用的表现手法较多，难度不大。写出三个并联系文章加以分析即可。</p>',
          typeId: 4,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 3,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529707,
      title: '<p>阅读下面的材料，完成下列小题。（本题共3小题，12分，第1、2小题每题3分，第3小题6分）</p><p><zmindent></zmindent>材料一：<br/><zmindent></zmindent>创断是引领发展的第一动力，知识产权是加快动能转换、结构优化的重要支撑。我国经济已由高速增长阶段转向高质量发展阶段，正处在转变发展方式。转换增长动力的攻关期。要顺利跨越这个关口，就必须激发出创新这个第一动力，走创新驱动发展道路；就必须“倡导创新文化，强化知识产权创造、保护、运用”。我们要进一步发挥好知识产权的技术供给和制度供給的双重作用，通过加强知识产权的创造和运用，不断为实体经济发展注入新动力；通过强化知识产权保护，推动构建更加公平公正、开放透明的市场环境。<zmindent></zmindent>（摘编自社论《播撒创新种子，守护创新中国——写在2018年全国知识产权宣传周活动启动之际》，《中国知识产权报》2018年4月20日）<br/></p><p><zmindent></zmindent>材料二：<br/></p><p style="text-align: left;"><zmindent></zmindent><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180607143347_5626.png" zmtype="big"/></p><p style="text-align: center;">2011~2016年遭遇过专利侵权的比例（单位：%）</p><p style="text-align: center;">（摘编自国家知识产权局知识产权发展研究中心《2017年中国专利调查报告》）</p><p><zmindent></zmindent>材料三：</p><p><zmindent></zmindent>继山东理工大学、同济大学等高校科技成果转化相继取得突破后，近日，中南大学冶金与环境学院科研团队的“电化学脱嵌法从盐湖卤水提锂”技术专利，成功转让给一家科技公司，许可使用费超过1亿元。双方将共同组建平台公司，由平台公司具体负责专利的产业化。长期以来，我国高校科研创新工作偏重基础理论研究，拥有深厚研发创新能力的科研人才未能将智力资源转化成市场价值。根据市场发展趋势探寻科技创新方向、不断更新升级科技创新思路，正是提升专利质量、实现专利市场价值的核心之义。2015年修订的《中华人民共和国促进科技成果转化法》打破高校科技成果转化藩篱，鼓励高校对持有的科研成果采取转让、许可等方式进行转移转化，对高校以实践为导向的科技创新产生了巨大的推动作用。<zmindent></zmindent>（摘编自王康等《创新为市场，转化显效益》，《中国知识产权报》2017年9月29日）</p><p><zmindent></zmindent>材料四：</p><p><zmindent></zmindent>在科技成果转化的实际过程中，高校普遍遇到了一些障碍，首先，科技成果与企业需求脱钩的矛盾长期存在。大学科研工作与企业技术创新在目标、路径、组织方式、评价标准及环境要求等方面存在着很大的差别，因此高校的成果很难直接转化成适应市场需求的新产品和新技术。其次，成果转化的机制不畅。高校传统体系是为了适应学术研究和人才培养而设计制订的，对于科技成果转化、产学研合作等社会服务方面的需求，现有体系在机构设置、管理制度、激励机制等方面匹配性不足。<zmindent></zmindent>（摘编自胡罡等《地方研究院：高校科技成果转化模式新探索》）</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 0,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2495768,
          questionId: 1529707,
          title: '<p>下列对材料二相关内容的理解和分析，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>2011到2013年，科研单位遭遇侵权的比例由25.3%下降到13.4%，降幅较为明显，但2014年有微小回升，2015 年则回落至8.4%。</p>',
            '<p>2015年企业和高校遭遇侵权的比例较之以往四年有所提高，总体侵权比例也略有反弹；而2016年各项侵权比例均呈下降态势，总体遭遇侵权比例为10.7%。</p>',
            '<p>2012至2016年间，比例一直下降的仅有个人遭遇侵权这一项，企业、高校、科研单位以及总体这四项数据，均有回升的现象发生。</p>',
            '<p>专利侵权总体比例的下降，一定程度上体现了我国知识产权保护工作所取得的成效，当然，我国专利数量的快速增长也可能在一定程度上拉低专利侵权的比例。</p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>本题考查理解文意，筛选并整合文中信息的能力。找出错误选项在图表中的表现，B项，“2015年企业和高校遭遇侵权比例较之以往四年有所提高”表述错误，可见2015年企业和个人遭遇侵权比例与2014，2013年相比有所提高，但与2011年，2012年相比仍在下降，因此表述错误。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2495769,
          questionId: 1529707,
          title: '<p>下列对材料相关内容的概括和分析，正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）<br/></p>',
          optionList: [
            '<p>只有大力倡导创新文化，提高全社会的创新意识，增加知识产权的技术供给，才能够形成全民尊重知识、诚信守法的社会风尚。</p>',
            '<p>根据市场发展趋势判断科技创新方向，充分考虑、合理安排成果转化中企业方的利益诉求，这样才能体现出大学科研工作的价值。</p>',
            '<p>随着高校的科研团队与企业共同合作的创新路径日益受到重视，一些科技成果正被逐渐转化为可以实现市场价值的高质量专利。</p>',
            '<p>高校在科研工作和人才培养的管理制度。评价标准等方面的不足，导致科研成果无法直接转化成适应市场需求的新技术和新产品。</p>'
          ],
          answerList: [
            'C'
          ],
          analysis: '<p>本题考查评价文本的主要观点和基本倾向的能力。找出错误选项出现在文中的语句段落，A项，“只有大力倡导创新文化，增加知识产权的技术供给，才能形成全民尊重知识，诚信守法的社会风尚”，材料一中“发挥好知识产权的技术供给和制度供给的双重作用”因此以偏概全······；B项，“充分考虑、合理安排成果转化中企业方的利益诉求，才能体现出大学科研工作的价值”对文章理解错误，材料三材料四中表述的是高校研究和企业需求之间的脱节和矛盾，但并未说大学的科研价值需要通过对企业转化的成功与否来决定······；D项，根据材料四······“高校在科研工作和人才培养的管理制度。评价标准等方面的不足”一句中“不足”错误，材料四“现有体系在······等方面匹配性不足”是指高校和企业在匹配中的问题，并非指高校自身的问题，因此理解错误。C项通过材料三开头中南大学的例子可说明科技成功正逐渐转化为实现市场价值的专利。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2495770,
          questionId: 1529707,
          title: '<p>促进高校科技成果转化需要哪些相关方协作？简述各方所起的作用。</p><p><zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>相关方：①高校； ②企业； ③政府。</p><p>作用：①高校拥有丰富的人才和知识储备，较强的研究和开发能力，是相关科技成果的创造者和提供方；②企业是科技成果的需求方，可以提供较为充裕的转化资金；③政府具有较强的组织调控能力，可以创造良好的转化环境，给科技成果转化提供坚实的政策动力。</p>'
          ],
          analysis: '<p>本题考查探究对文章的理解和概括能力。需要根据材料三四中总结高校，政府，企业三者的行为和作用，如高校培养人才，企业提供需求，政府政策保证等，再结合自己的积累作答。</p>',
          typeId: 4,
          score: 6,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 3,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529743,
      title: '<p>阅读下面的文言文，完成下列小题。（本题共4小题，共19分，前3小题每题3分，最后一题10分）</p><p><zmindent></zmindent><strong><ins>王涣字稚子广汉郪人也父顺安定太守涣少好侠尚气力数通剽轻少年晚而改节敦儒学习《尚书》读律今略举大义</ins></strong>为太守陈宪功曹，当取割断，不避<strong>豪右</strong>。宠风声大行，入为大司农。和帝问日:“在郡何以为理”宠<strong>顿首</strong>谢日:“臣任功曹王涣以简贤选能，主薄镡显耠遗补阙，臣奉宣诏书而已。”帝大悦，涣由此显名。州举<strong>茂才</strong>，除溫令，县多奸猾，积为人患。涣以方略讨击，悉诛之，境内清夷，商人露宿于道。其有放牛者，辄云以属稚子，终无侵犯。在温三年，迁兖州刺史，绳正部郡，风威大行。后坐考妖言不实论。岁余，征拜侍御史。永元十五年，从驾南巡，还为洛阳令。以平正居身，得宽猛之宜。其冤嫌久讼，历政所不断，法理所难平者，莫不曲尽情诈，压塞群疑。又能以谲数发适奸伏。<strong>京师</strong>称叹，以为涣有神算。元兴元年，病卒。百姓市道莫不咨嗟。男女老壮皆相与赋敛，致莫釅以千数。涣丧西归，道经弘农，民庶皆设盘案于路。吏问其故，咸言平常持米到洛，为卒司所抄，恒亡其半，自王君在事，不见侵枉，故来报恩。其政化怀物如此。<ins>民思其德，为立祠安阳亭西，每食辄弦歌而荐之，</ins>延熹中，桓常事黄老道，悉毁诸房祀，唯特诏密县存敌太傅卓茂庙，洛阳留王涣祠焉。自涣卒后，连诏三公特选洛阳令，皆不称职。永和中，以剧令勃海任峻补之。峻擢用文武吏，皆尽其能，纠别奸盗，不得旋踵，<ins>一岁断狱，不过数十，成风猛于涣，而文理不及之。</ins>峻字叔高，终于太山太守。&nbsp;</p><p style="text-align: right;">(节选自《后汉书·王涣传》</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 0,
      sourceId: 6,
      difficulty: 4,
      distinction: 3,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2496543,
          questionId: 1529743,
          title: '<p>下列对文中画线加粗句子部分的断句，正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>王涣字稚子/广汉鄭人也/父顺/安定太守/涣少好侠/尚气力/数通剽轻少年/晚而改节敦/儒学习《尚书》/读律令/略举大义/</p>',
            '<p>王涣字稚子/广汉鄭人也/父顺/安定太守/涣少好侠/尚气力/数通剽轻少年/晚而改节/敦儒学/习《尚书》/读律令/略举大义/</p>',
            '<p>王涣字稚子/广汉鄭人也/父顺/安定太守涣少/好侠尚气力数通剽轻少年/晚而改节敦/儒学习《尚书》 /读律令/略举大义/</p>',
            '<p>王涣字稚子/广汉鄭人也/父顺/安定太守/涣少/好侠尚气力/数通剽轻少年/晚而改节/敦儒学习《尚书》/读律令/略举大义/</p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>对于文言断句类题目，不要急于答题，应当先诵读这个语段，通过诵读，力求对其内容有个大体的了解，凭语感将能断开的先断开，逐步缩小范围，然后再集中精力分析难断处，遵循先易后难的原则。本题首先要找出专有名词，即人名、地名、官职名等；然后再看有否特殊句式；最后再确定关键字进行翻译，一般为直译。</p><p>翻译：王涣字稚子，是广汉郪县人。年少时喜好行侠仗义打抱不平，崇尚力气和武艺，与强悍轻捷的少年交往频繁。后来才改变了自己的志向，钻研儒学，学习《尚书》，研读律令，大体明晓了这些书典的主要旨义。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2496544,
          questionId: 1529743,
          title: '<p>下列对文中加粗词语的相关内容的解说，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>豪右，指旧时的富豪家族、世家大户:汉代以右为尊，所以习惯上称为“豪右”。</p>',
            '<p>顿首，即以头叩地而拜，是古代交际礼仪；又常常用于书信、表奏中作为敬辞。</p>',
            '<p>茂才，即秀才，东汉时为避光武帝刘秀名讳，改称茂才，后世有时也沿用此名。</p>',
            '<p>京师是古代京域的通称，现代则称为首都：“京”“师”单用，旧时均可指国都。</p>'
          ],
          answerList: [
            'D'
          ],
          analysis: '<p>D项中京师是可以作为古代京城的同称，但是“京” “师”单用，“师”有军队、教育人的老师等意思，作为古代京城之意通常与“京”字连用，不单独使用。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2496545,
          questionId: 1529743,
          title: '<p>下列对原文有关内容的概括和分析，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>王涣初入仕途，才干受到赏识。他在太守陈宠手下担任功曹，遇事敢于决断：陈入朝为大司农，回答皇上询问时褒奖他善于简贤选能，王由此得以显名。</p>',
            '<p>王涣扫除积弊， 境内风清气正。他担任温县县令，以谋略铲除奸猾之徒，世面清平，商人露宿于道；升任兖州刺史后，又依法整肃下属部门，极有声威。</p>',
            '<p>王涣办案严谨，治事宽猛相济。他对于疑难案件以及法理难平者，探寻本来面目，尽力还以公正；又能够揭发奸隐之事，深受外界称叹，被誉为有神算。</p>',
            '<p>王涣政绩卓著，后任难以比肩。他死于洛阳令任上，皇上下令特选其继任者，均不称职；后来选用任峻，任充分发挥文武属吏才干，仍然忙得无法分身。</p>'
          ],
          answerList: [
            'D'
          ],
          analysis: '<p>D选项：无人比肩不对，最后划线句写威风猛于涣。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2496546,
          questionId: 1529743,
          title: '<p>把文中画横线的句子翻译成现代汉语。</p><p>(1)民思其德，为立祠安阳亭西，每食辄弦歌而荐之。</p><p style="text-align: justify;"><zmsubline contenteditable="false">空类2</zmsubline></p><p>(2)一岁断狱，不过数十，威风猛于涣，而文理不及之。</p><p><zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>百姓思念王涣思德，在安阳事西为他建造祠堂，每到进食时就奏乐歌咏而祭祀他。</p>',
            '<p>一年间的断案，不过几十件，声威超过王涣，而在条理方面比不上他。</p>'
          ],
          analysis: '<p>（1）首先找出专有名词，如人名、地名、管治名等；然后看看是否有特殊句式，最后再确定关键字进行翻译，一般为直译。</p><p>为立祠安阳亭西，“为”为动词，后面省略宾语之，为王涣的意思，安阳亭西前省略于字，整个结构介词结构后置。每食辄弦歌而荐之，荐作为动词有祭祀的意思，根据上下文，上文建造祠堂，下文的动词应该是祭奠、祭祀的意思。</p><p>（2）首先找出专有名词，如人名、地名、管治名等；然后看看是否有特殊句式，最后再确定关键字进行翻译，一般为直译。</p><p>一岁不是通常意义上一岁年龄的意思，岁在古代指年，一岁是一年的意思。</p>',
          typeId: 3,
          score: 10,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 3,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529678,
      title: '<p>阅读下面这首宋诗，完成下面小题。（本题共2小题，共9分，第1小题3分，第2小题6分）</p><p style="text-align: center;">&nbsp; 题醉中所作草书卷后(节选)</p><p style="text-align: center;">陆游</p><p style="text-align: center;">&nbsp;胸中磊落藏五兵，欲试无路空峥嵘。</p><p style="text-align: center;">酒为旗鼓笔刀槊，势从天落银河倾。</p><p style="text-align: center;">端溪石池浓作墨，烛光和射飞纵横。</p><p style="text-align: center;">须更收卷复把酒，如见万里烟尘清。</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 0,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2495884,
          questionId: 1529678,
          title: '<p>下列对这首诗的赏析，不正确的一项是（<zmindent contenteditable="false">空类0</zmindent>）</p>',
          optionList: [
            '<p>这首诗写诗人观看自己已完成的一幅草书作品，并回顾它的创作过程。</p>',
            '<p>诗人驰骋疆场杀敬报国的志向无法实现，借书法创作来抒发心中郁闷。</p>',
            '<p>诗人把书法创作中的自己想象成战场上的战士，气吞山河，势不可挡。</p>',
            '<p>诗人豪情勃发，他在砚台中磨出的浓黑墨汁，也映射着烛光纵横飞溅。</p>'
          ],
          answerList: [
            'D'
          ],
          analysis: '<p>本题考查筛选信息的能力。D项对“烛光相射飞纵横”的理解错误，并非烛光纵横飞溅，而是在烛光的照耀下，下笔纵横如飞。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2495886,
          questionId: 1529678,
          title: '<p>诗中前后两次出现“酒”，各有什么作用？请结合诗句简要分析。</p><p><zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: null,
          answerList: [
            '<p>(1)“酒为旗鼓笔刀槊”一句，意为草书如同行军打仗，书写前喝酒，此处的酒，是在创作草书之前饮酒，作书泄愤，引起后文的创作过程，蕴含着诗人胸怀大志却无处施展的愤懑。</p><p>(2)“须臾收卷复把酒”一句，意为完成草书，又端杯饮酒，就像打了一场胜仗一样，此处的酒，是创作完成的庆功酒，暗示扫敌人平逆虏后的清平景象和诗人的得意神情，抒发作者的爱国情怀。</p>'
          ],
          analysis: '<p>本题考查鉴赏古代诗歌的分析意向的能力。</p><p>本诗意为：胸中自有军事谋略，想要试炼一番却没有门路，空怀豪情。草书如同行军打仗，书写前喝酒，好似军中的旗鼓以壮声威，手中的笔好似战士的刀枪，其气势如同银河从天上倾泻而下。以端溪出产的砚台磨墨，在烛光的照耀下，下笔纵横如飞。瞬间就完成草书，又端杯饮酒，就像打了一场胜仗，消除国难，恢复了太平，感觉酣畅淋漓。有志男儿当建立功业，有所立身，金人侵略者的命运已尽，应当去平定他们。何时才能够像汉朝时在五原塞出兵讨伐匈奴那样北伐金人呢？我已能想象到我军队伍十分整肃的场景，只听到扬鞭催马的声音，而没有人语声。</p><p>此诗作于孝宗淳熙三年(1176)三月，陆游52岁，在成都范成大幕府。诗人精通书法，尤擅长草书，几乎出神入化。于是由醉中作草书，联想到用兵，实为妙哉！</p>',
          typeId: 4,
          score: 6,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 3,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529705,
      title: '<p>补写出下列句子中的空缺部分。</p><p>(1)《孟子·鱼我所欲也》中说，虽然一点食物即可关乎生死，但若“<zmsubline></zmsubline>”，饥饿的路人也不会接受：若“<zmsubline></zmsubline>”，即便是乞丐也会拒绝。</p><p>(2)白居易的《琵琶行》中“<zmsubline></zmsubline>，<zmsubline></zmsubline>”两句写昔日的琵琶女身价很高，引来了众多纨绔子弟的追捧。</p><p>(3)苏轼《赤壁赋》中描写明月初升的句子是“<zmsubline></zmsubline>，<zmsubline></zmsubline>”。</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>呼尔而与之</p>',
        '<p>蹴尔而与之</p>',
        '<p>五陵年少争缠头</p>',
        '<p>一曲红绡不知数</p>',
        '<p>月出于东山之上</p>',
        '<p>徘徊于斗牛之间</p>'
      ],
      analysis: '<p>本题考查默写常见的名句名篇的能力。注意“蹴”“陵”“绡”等字的写法。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 3,
      questionType: '填空题',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 6,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 3,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 39,
      parentTypeName: '填空题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529706,
      title: '<p>下面是某报社一则启事初稿的片段，其中有五处词语使用不当，请找出并作修改。要求修改后语意准确。语体风格一致。</p><p><zmindent></zmindent>如果您是重大事件的参加者，事故现场的目击者，业界内幕的打探者，社会热点的关爱者请与我报“社会深度”栏目联系。本栏目长期公开征询有价值的新闻线索，等着您的支持。</p><p><zmsubline></zmsubline></p><p><zmsubline></zmsubline></p><p><zmsubline></zmsubline></p><p><zmsubline></zmsubline></p><p><zmsubline></zmsubline></p><p><br/></p><p><br/></p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>“参加者”改为“亲历者”或者“参与者”</p>',
        '<p>“打探者”改为“知情者&quot;</p>',
        '<p>“关爱者”改为“关注者”</p>',
        '<p>“征询”改为“征集”</p>',
        '<p>“等着”改为“期待”或者“等待”</p>'
      ],
      analysis: '<p>此题考查用词准确和语言得体。“参加者”不能表示融入感，故改称“参与者”；“打探者”是指故意打探消息的人，有点贬义色彩，故改为“知情者”；“征询”的意思是“征集并询问”，故改为“征集”；“等着”不够尊重，应该改为“等待”或者“期待”。</p>',
      subjectId: null,
      gradeId: null,
      phaseId: null,
      termId: null,
      typeId: null,
      questionType: '',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: null,
      score: 0,
      sourceId: 2,
      difficulty: null,
      distinction: null,
      recommendationIndex: null,
      rating: null,
      comprehensiveDegreeId: null,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: null,
      quoteCount: null,
      examCount: null,
      correctRate: null,
      storageTime: null,
      sub: null,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: null,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: null,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: null,
      parentTypeName: null,
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529680,
      title: '<p>阅读下面的文字，回答问题。（本题共3小题，共9分，每小题3分）</p><p><zmindent></zmindent>戏曲既需传承也需创新，这是业内的基本共识。然而近年来，由于一些创新尝试未收到理想效果，有人就将创新和传承对立起来，认为戏曲不必创新，尤其是昆曲的戏曲艺术进入世界非物质文化遗产名录之后，创新在某些人那里几乎成了贬义词。（&nbsp; ）。随着时代的发展变化，戏曲艺术不断被赋予新的内涵。如果一直固守原有形态，只强调复制和模仿，戏曲恐怕早在数百年前就<zmsubline></zmsubline>了。突破前人、大胆创新，这是各个时代取得伟大成就的艺术家的共性。诚如某戏剧评论家所言，没有一位<zmsubline></zmsubline>的京剧名怜是靠模仿或重复而成就自己的。京剧大师梅兰芳，以整定的信念和博大的胸怀为京剧改革作出巨大贡献。他眼界开阔，&nbsp;<zmsubline></zmsubline>, 除唱脸、表演技巧之外，还从化妆、灯光、服装、舞蹈、剧目创作等多个方面进行了大量的探索，可谓“剧剧有创新，剧剧有新腔”。尚小云、荀慧生、于连泉等人，也是因为具有超越前人的理想和切实的努力。不满足于停留在雷池之内<zmsubline></zmsubline>, 才能够在强大的保守情緒的笼罩下突破藩篱，从而成为新流派的创始人。当然，戏曲的创新必须以传承为基础，是传承中的创新，<ins>而不是眼花缭乱甚至任性妄为的创断。才能探索出一条能够被大多数观众接受的创新之路来。</ins></p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 9,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2495933,
          questionId: 1529680,
          title: '<p>下列在文中括号内补写的语句，最恰当的一项是（&nbsp; ）</p>',
          optionList: [
            '<p>当代戏曲的发展，被创新精神的缺失所制约</p>',
            '<p>当代戏曲的发展，因创新精神的缺失而被制约</p>',
            '<p>创新精神的缺失，制约了当代戏曲的发展</p>',
            '<p>创新精神的缺失，对当代戏曲发展起了制约作用</p>'
          ],
          answerList: [
            'C'
          ],
          analysis: '<p>本题综合考察考生语句衔接和连贯的能力。考生可以从联系上下文明确句子内的逻辑关系，通过叙述对象确定句子主语入手答题。此题空前“创新在某些人那里几乎成了贬义词”一句的主语是“创新”可知，要填的这句话应该承接上文对于“创新”的议论，故主语应该是“创新精神的缺失”；“创新精神的缺失”和“当代戏曲的发展”是强因果关系，即制约了戏曲的发展。故此题选C。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2495934,
          questionId: 1529680,
          title: '<p>依次填入文中横线上的成语，全都恰当的一项是（&nbsp; ）</p>',
          optionList: [
            '<p>寿终正寝&nbsp; 名噪一时&nbsp; 兼容并蓄&nbsp; 照猫画虎</p>',
            '<p>无疾而终&nbsp; 名垂青史&nbsp; 兼容井審&nbsp; 按图索骥</p>',
            '<p>寿终正寝&nbsp; 名垂青史&nbsp; 博采众长&nbsp; 照猫通虎</p>',
            '<p>无疾而终&nbsp; 名噪一时&nbsp; 博采众长&nbsp; 按图索骥</p>'
          ],
          answerList: [
            'C'
          ],
          analysis: '<p>本题综合考察成语理解和运用以及成语辨析。</p><p>寿终正寝：寿终，活到老死；正寝，旧式住房的正屋。原指老死在家里，现比喻事物的灭亡。无疾而终：没有病就死了，比喻事物未受外力干扰就自行消灭了，即事情的发展最终走入末路，没有任何结果。这里说戏曲如果一直固守原有形态的话就会在数百年前灭亡，故应该选“寿终正寝”。</p><p>名噪一时：名声传扬于一个时期。名垂青史：姓名事迹记载在历史书籍上，形容功业巨大，永垂不朽。这里用于形容像梅兰芳一样为京剧改革作出巨大贡献的京剧名伶，故应该选“名垂青史”。</p><p>兼容并蓄：把不同内容、不同性质的东西收下来，保存起来；博采众长：博，广泛；采，采纳；长，长处优势。指广泛地吸收各家或者各方面的优点长处。而兼容并蓄的不一定全是优点。这里用于描述梅兰芳在京剧的各个方面探索吸收优秀的东西，故应该选“博采众长”。</p><p>照猫画虎：照着猫画老虎，比喻照着样子模仿。按图索骥：按图，按着图形；索，寻找；骥，好马。比喻按线索去寻找需要的东西；也比喻按教条办事不知变通，墨守成规。这里是说新流派的创始人们不满足于一味模仿前人，而是具有超越前人的理想和努力。故应该选“照猫画虎”。故此题选C。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2495935,
          questionId: 1529680,
          title: '<p>文中画横线的部分有语病，下列修改最恰当的一项是（&nbsp; ）</p>',
          optionList: [
            '<p>而不是眼花缭乱甚至任性安为的创新，这样才能探索出一条能够被大多数观众接受的创新之路来。</p>',
            '<p>而不是令人眼花缭乱甚至任性安为的创新，这样才能探索出一条能够被大多数观众接受的创新之路来。</p>',
            '<p>而不是令人眼花缭乱甚至任性安为的创新，才能探索出一条能够被大多数观众接受的创新之路来。</p>',
            '<p>而不是眼花缭乱甚至任性妄为的创新，这样我们才能探索出一-条能够被大多数观众接受的创新之路来。</p>'
          ],
          answerList: [
            'B'
          ],
          analysis: '<p>本题考查病句修改。“眼花缭乱”不能直接形容“创新”，前面应该加上“令人”；后半句是前面标述内容的目的，依据上下句句意通顺连贯的原则，“才能”前应该加上“这样”来连接上下两句。考生在做答该题时应该结合语感，分析上下句之间的关系，并通过比较选择最佳答案。</p>',
          typeId: 2,
          score: 3,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 3,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529731,
      title: '<p>按照下面的示例，利用所给材料续写三句话，要求内容贴切，句武与所给示例相同。</p><p><zmindent></zmindent>诸子争鸣、造纸印刷、筑长城开运河，中国人民具有伟大的创造精神。</p><p><zmindent></zmindent>材料</p><p><zmindent></zmindent>奋斗团結梦想</p><p><zmindent></zmindent>建强国谋复兴御外悔卫家国脫贫困奔小康</p><p><zmindent></zmindent>基田拓海开天辟地守望相助抗灾治水逐日奔月同舟共济</p><p><zmsubline></zmsubline></p><p><br/></p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>垦田拓海、抗灾治水、脱贫困奔小康，中国人民具有伟大的奋斗精神。</p><p>同舟共济、守望相助、御外侮卫家国，中国人民具有伟大的团结精神。</p><p>开天辟地，逐日奔月、建强国谋复兴，中国人民具有伟大的梦想精神。</p>'
      ],
      analysis: '<p>本题考查句子仿写。要求考生按照要求，把所给的材料归为“奋斗”，“团结”，“梦想”三类，并且以同样的格式续写出来。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 4,
      questionType: '解答题',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 6,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 3,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 40,
      parentTypeName: '解答题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1529426,
      title: '<p><zmindent></zmindent>“二战”期间，为了加强对战机的防护，英美军方调查了作战后幸存飞机上弹痕的分布，决定哪里弹痕多就加强哪里，然而统计学家沃德力排众议，指出更应该注意弹痕少的部位，因为这些部位受到重创的战机，很难有机会返航，而这部分数据被忽略了。事实证明，沃德是正确的。</p><p><zmindent></zmindent>要求：综合材料内容及含意，选好角度，确定立意，明确文体，自拟标题，不要套作，不得抄袭，不少于800字。</p><p><zmsubline></zmsubline></p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>略<br/></p>'
      ],
      analysis: '<p>2018年的全国二卷高考语文卷继续采用了一脉相承的材料作文题型，此次作文材料与近些年的作文材料相似，材料以事例方式呈现，有一定难度，需要考生通过仔细分析研读材料进行观点提炼。</p><p>该事例是典型的幸存者偏差现象，所谓幸存者偏差即只关注筛选后的结果，而忽略了筛选的过程，也即忽略了筛选去的关键信息，也叫做“沉默样本”。在本次考试材料中我们接受到的直接信息是幸存飞机的弹痕情况，而忽略了“幸存”本身经过了一种筛选。考生需要透过现象发现本质问题，注意不要偏题。</p><p>本材料以幸存者偏差为主体，从这一角度考生可以从打破惯性思维，克服认知偏差，全面把控信息等方面入手写作，可以从小到生活点滴写到大至治国政策，有比较广阔的选择。也可以列举生活中经济、心理、政治方面的成功人士的实例加以佐证，使文章更加丰满有说服力。</p><p>除此之外也可以深入素材本身，从其他角度入手。比如材料中统计学家沃德提出了关键的正确意见，从这条信息入手我们可以写关于相信科学，客观听取他人意见，扩大知识面等方面，从追求知识相信科学的角度去立意。也可以通过“加强战机防护”这一信息写忧患意识。</p><p>本次高考作文虽然以事例形式出现，但是在写作内容上却又很大的自由度，文化类、科学类、政治类等各种素材都可以使用。</p><p>本题既给考生提供巨大写作空间，又有效防止考生的套作，从而极大提高了测试的区分度和效度。能够选拔出有思想深度，有创新意识的考生。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 18,
      questionType: '书面表达',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 60,
      sourceId: 6,
      difficulty: 4,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 3,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: null
    }
  ]
};