export default {
  code: '0',
  message: '',
  data: [
    {
      id: 2866700,
      serialNumber: 1,
      questionId: 63362,
      questionOutputDTO: {
        id: 63362,
        title: '<p>下列语句不正确的是（&nbsp; ） .</p>',
        content: null,
        optionList: [
          '<p><zmlatex>0</zmlatex>是代数式</p>',
          '<p><zmlatex>a</zmlatex>是整式</p>',
          '<p><zmlatex>x</zmlatex>的<zmlatex>3</zmlatex>倍与<zmlatex>y</zmlatex>的<zmlatex>\\frac{1}{4}</zmlatex>的差表示为<zmlatex>3x-\\frac{1}{4}y</zmlatex></p>',
          '<p><zmlatex>S=πr^2</zmlatex>是代数式</p>'
        ],
        answerList: [
          'D'
        ],
        analysis: '<p><zmlatex>A</zmlatex>、<zmlatex>0</zmlatex>是代数式是正确的，不符合题意；</p><p><zmlatex>B</zmlatex>、<zmlatex>a</zmlatex>是整式是正确的，不符合题意；</p><p><zmlatex>C</zmlatex>、<zmlatex>x</zmlatex>的<zmlatex>3</zmlatex>倍与<zmlatex>y</zmlatex>的<zmlatex>\\frac{1}{4}</zmlatex>的差表示为<zmlatex>3x-\\frac{1}{4}y</zmlatex>是正确的，不符合题意；</p><p><zmlatex>D</zmlatex>、<zmlatex>S=πr^2</zmlatex>不是代数式，原来的说法是错误的，符合题意；</p><p>故选<zmlatex>D</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 30,
        cityId: 261,
        countyId: null,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 1,
        distinction: 2,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          2,
          5
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          473,
          474,
          545
        ],
        examPointIdList: [
          497,
          505
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 18,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1512987594000,
        createdUser: 1002318624,
        updatedTime: 1537500106000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '用字母表示数',
          '代数式的概念',
          '代数式'
        ],
        examPointNameList: [
          '代数式的概念',
          '单项式的判断'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年四川省宜宾市',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 6
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866701,
      serialNumber: 2,
      questionId: 2166967,
      questionOutputDTO: {
        id: 2166967,
        title: '<p>笔记本的单价为<zmlatex>a</zmlatex>元/本，错题本的单价为<zmlatex>b</zmlatex>元/本，买<zmlatex>2</zmlatex>本笔记本和<zmlatex>3</zmlatex>本错题本共需(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>(a+b)</zmlatex>元</p>',
          '<p><zmlatex>(3a+2b)</zmlatex>元</p>',
          '<p><zmlatex>(2a+3b)</zmlatex>元</p>',
          '<p><zmlatex>5(a+b)</zmlatex>元</p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p>依题意得：<zmlatex>2a+3b</zmlatex>．</p><p>故选：<zmlatex>C</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 14,
        cityId: 26,
        countyId: null,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 1,
        distinction: 1,
        recommendationIndex: null,
        rating: 1,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          2,
          5
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          473,
          545
        ],
        examPointIdList: [
          495,
          499
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 6,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1533105983000,
        createdUser: 1005568428,
        updatedTime: 1537500190000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '用字母表示数',
          '代数式'
        ],
        examPointNameList: [
          '用字母表示数',
          '代数式表示的实际意义'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年吉林省长春市',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 4
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866702,
      serialNumber: 3,
      questionId: 2411987,
      questionOutputDTO: {
        id: 2411987,
        title: '<p>已知单项式<zmlatex>-2a^{2m+3}b^5</zmlatex>与<zmlatex>3a^5b^{m-2n}</zmlatex>的和是单项式，则<zmlatex>(m+n)^{2005}=</zmlatex>(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>1</zmlatex></p>',
          '<p><zmlatex>-1</zmlatex></p>',
          '<p><zmlatex>0</zmlatex></p>',
          '<p><zmlatex>0</zmlatex>或<zmlatex>1</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p>已知单项式<zmlatex>-2a^{2m+3}b^5</zmlatex>与<zmlatex>3a^5b^{m-2n}</zmlatex>的和是单项式，</p><p><zmlatex>{\\therefore}</zmlatex>二单项式为同类项，</p><p><zmlatex>{\\therefore}2m+3=5</zmlatex>，<zmlatex>m-2n=5</zmlatex>，</p><p><zmlatex>{\\therefore}m=1</zmlatex>，<zmlatex>n=-2</zmlatex>，</p><p><zmlatex>{\\therefore}(m+n)^{2005}=(1-2)^{2005}=-1</zmlatex>．</p><p>故选：<zmlatex>B</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 31,
        cityId: 273,
        countyId: 2176,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          475,
          486,
          559
        ],
        examPointIdList: [
          500,
          526
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 15,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1534405703000,
        createdUser: 1002597361,
        updatedTime: 1537507990000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '代数式的值',
          '同类项的定义',
          '列方程'
        ],
        examPointNameList: [
          '已知字母的值 ，求代数式的值',
          '已知同类项求指数中字母的值或代数式的值'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年内蒙古省赤峰市翁牛特旗',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 4
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866703,
      serialNumber: 4,
      questionId: 2243066,
      questionOutputDTO: {
        id: 2243066,
        title: '<p>若<zmlatex>a=\\frac{1}{\\sqrt{2}-1}</zmlatex>，<zmlatex>b=\\frac{1}{\\sqrt{2}+1}</zmlatex>，则<zmlatex>\\sqrt{ab}(\\sqrt{\\frac{a}{b}}-\\sqrt{\\frac{b}{a}})</zmlatex>的值为(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>2</zmlatex></p>',
          '<p><zmlatex>-2</zmlatex></p>',
          '<p><zmlatex>\\sqrt{2}</zmlatex></p>',
          '<p><zmlatex>2\\sqrt{2}</zmlatex></p>'
        ],
        answerList: [
          'A'
        ],
        analysis: '<p>原式<zmlatex>=\\sqrt{ab}(\\sqrt{\\frac{a}{b}}-\\sqrt{\\frac{b}{a}})=\\sqrt{ab}{\\cdot}\\sqrt{\\frac{a}{b}}-\\sqrt{ab}{\\cdot}\\sqrt{\\frac{b}{a}}=a-b</zmlatex>，</p><p>将<zmlatex>a</zmlatex>、<zmlatex>b</zmlatex>的值代入得：</p><p>原式<zmlatex>=a-b=\\frac{1}{\\sqrt{2}-1}-\\frac{1}{\\sqrt{2}+1}=(\\sqrt{2}+1)-(\\sqrt{2}-1)=2</zmlatex>．</p><p>故选：<zmlatex>A</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 9,
        phaseId: 2,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 27,
        cityId: 216,
        countyId: 1694,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          474,
          548,
          552
        ],
        examPointIdList: [
          500,
          643,
          654
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 14,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1533531095000,
        createdUser: 1004343036,
        updatedTime: 1537500629000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '代数式的概念',
          '二次根式的乘法法则',
          '二次根式的加减法'
        ],
        examPointNameList: [
          '已知字母的值 ，求代数式的值',
          '二次根式的乘法',
          '二次根式的加减运算'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年广西省钦州市钦南区',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 4
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866704,
      serialNumber: 5,
      questionId: 1824366,
      questionOutputDTO: {
        id: 1824366,
        title: '<p>若<zmlatex>X</zmlatex>表示一个两位数，<zmlatex>y</zmlatex>表示一个三位数，把<zmlatex>X</zmlatex>放在<zmlatex>y</zmlatex>的左边，组成的五位数可表示为(&nbsp; &nbsp;)</p>',
        content: null,
        optionList: [
          '<p><zmlatex>X+y</zmlatex></p>',
          '<p><zmlatex>100X+y</zmlatex></p>',
          '<p><zmlatex>100X+1000y</zmlatex></p>',
          '<p><zmlatex>1000X+y</zmlatex></p>'
        ],
        answerList: [
          'D'
        ],
        analysis: '<p>这个五位数就可以表示为<zmlatex>1000X+y</zmlatex>．</p><p>故选：<zmlatex>D</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 37,
        cityId: 350,
        countyId: 2671,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 2,
        distinction: 2,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          0,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          473,
          476,
          545
        ],
        examPointIdList: [
          495,
          499
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 8,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1531194017000,
        createdUser: 1002318580,
        updatedTime: 1537499986000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '用字母表示数',
          '代数式的实际意义',
          '代数式'
        ],
        examPointNameList: [
          '用字母表示数',
          '代数式表示的实际意义'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年安徽省宣城市宁国市',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 6
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866705,
      serialNumber: 6,
      questionId: 88917,
      questionOutputDTO: {
        id: 88917,
        title: '<p>如图是用火柴棍摆成的边长分别是<zmlatex>1</zmlatex>、<zmlatex>2</zmlatex>、<zmlatex>3</zmlatex>根火柴棍时的正方形，当边长为<zmlatex>6</zmlatex>根火柴棍时，摆出的正方形所用的火柴棍的根数为（　　）</p><p><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180207234633_1103.jpg" zmtype="big"/></p>',
        content: null,
        optionList: [
          '<p><zmlatex>60</zmlatex></p>',
          '<p><zmlatex>84</zmlatex></p>',
          '<p><zmlatex>96</zmlatex></p>',
          '<p><zmlatex>112</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p>当边长为1根火柴棍时，设摆出的正方形所用的火柴棍的根数为<zmlatex>4=2{\\times}1{\\times}(1+1)</zmlatex>；</p><p>当边长为2根火柴棍时，设摆出的正方形所用的火柴棍的根数为<zmlatex>12=2{\\times}2{\\times}(2+1)</zmlatex>；</p><p>当边长为3根火柴棍时，设摆出的正方形所用的火柴棍的根数为<zmlatex>24=2{\\times}3{\\times}(3+1)</zmlatex>；</p><p><zmlatex>…</zmlatex>；</p><p>故当边长为<zmlatex>n</zmlatex>根火柴棍时，设摆出的正方形所用的火柴棍的根数为<zmlatex>2n(n+1)</zmlatex>．</p><p>当摆成的边长为<zmlatex>6</zmlatex>的正方形图案，需要火柴<zmlatex>2{\\times}6{\\times}(6+1)=84</zmlatex>．</p><p>故选:B</p>',
        subjectId: 2,
        gradeId: 8,
        phaseId: 2,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 38,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 2,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          0,
          5
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          473,
          475,
          545
        ],
        examPointIdList: [
          496,
          532
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 9,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1513348288000,
        createdUser: 1002318616,
        updatedTime: 1537499716000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '用字母表示数',
          '代数式的值',
          '代数式'
        ],
        examPointNameList: [
          '用代数式表示数、图形的规律',
          '图形类规律探索'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年浙江省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: 1
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866706,
      serialNumber: 7,
      questionId: 1829642,
      questionOutputDTO: {
        id: 1829642,
        title: '<p>已知<zmlatex>a+b=0</zmlatex>,<zmlatex>a{\\ne}b</zmlatex>,则化简<zmlatex>\\frac{b}{a}(a + 1) + \\frac{a}{b}(b + 1)</zmlatex>得( &nbsp;)</p>',
        content: null,
        optionList: [
          '<p><zmlatex>2a</zmlatex></p>',
          '<p><zmlatex>2b</zmlatex></p>',
          '<p><zmlatex>+2</zmlatex></p>',
          '<p><zmlatex>-2</zmlatex></p>'
        ],
        answerList: [
          'D'
        ],
        analysis: '<p><zmlatex>\\frac{b}{a}(a + 1) + \\frac{a}{b}(b + 1)</zmlatex>,</p><p><zmlatex>=b+\\frac{b}{a}+a+\\frac{a}{b}</zmlatex>,</p><p><zmlatex>=(a+b)+(\\frac{b}{a} + \\frac{a}{b})</zmlatex>,</p><p>又<zmlatex>{\\because}a+b=0</zmlatex>,<zmlatex>a{\\ne}b</zmlatex>,</p><p><zmlatex>{\\therefore}a=-b</zmlatex>,</p><p><zmlatex>{\\therefore}\\frac{a}{b}=\\frac{b}{a}=-1</zmlatex>,</p><p><zmlatex>{\\therefore}\\frac{b}{a}(a + 1) + \\frac{a}{b}(b + 1)</zmlatex>,</p><p><zmlatex>=(a+b)+(\\frac{b}{a}+\\frac{a}{b})</zmlatex>,</p><p><zmlatex>=-2</zmlatex>．</p><p>故选：<zmlatex>D</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 37,
        cityId: 334,
        countyId: null,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          475,
          523,
          528
        ],
        examPointIdList: [
          516,
          612
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 10,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1531206098000,
        createdUser: 1002318623,
        updatedTime: 1536907128000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '代数式的值',
          '分式乘以分式',
          '异分母分式相加减'
        ],
        examPointNameList: [
          '整体代入法求多项式的值',
          '分式乘除混合运算'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年安徽省合肥市',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866707,
      serialNumber: 8,
      questionId: 2439372,
      questionOutputDTO: {
        id: 2439372,
        title: '<p>若分式<zmlatex>\\frac{1}{x}-\\frac{1}{y}=2</zmlatex>，则分式<zmlatex>\\frac{4x+5xy-4y}{x-3xy-y}</zmlatex>的值等于(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>-\\frac{3}{5}</zmlatex></p>',
          '<p><zmlatex>\\frac{3}{5}</zmlatex></p>',
          '<p><zmlatex>-\\frac{4}{5}</zmlatex></p>',
          '<p><zmlatex>\\frac{4}{5}</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p>整理已知条件得<zmlatex>y-x=2xy</zmlatex>；</p><p><zmlatex>\\therefore{}x-y=-2xy</zmlatex></p><p>将<zmlatex>x-y=-2xy</zmlatex>整体代入分式得</p><p><zmlatex>\\frac{4x+5xy-4y}{x-3xy-y}</zmlatex></p><p><zmlatex>=\\frac{4(x-y)+5xy}{(x-y)-3xy}</zmlatex></p><p><zmlatex>=\\frac{4\\times{}(-2xy)+5xy}{-2xy-3xy}</zmlatex></p><p><zmlatex>=\\frac{-3xy}{-5xy}</zmlatex></p><p><zmlatex>=\\frac{3}{5}</zmlatex>．</p><p>故选：<zmlatex>B</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 8,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 21,
        cityId: 371,
        countyId: 2862,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 2,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          0,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          475,
          519,
          520
        ],
        examPointIdList: [
          501,
          624
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 3,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1534498647000,
        createdUser: 1003235168,
        updatedTime: 1536905928000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 2,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '代数式的值',
          '分式的约分',
          '分式的通分'
        ],
        examPointNameList: [
          '已知式子的值，求代数式的值',
          '分式化简求值'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年湖北省襄阳市襄州区',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866708,
      serialNumber: 9,
      questionId: 1046980,
      questionOutputDTO: {
        id: 1046980,
        title: '<p>代数式<zmlatex>yz(xz+2)-2y(3x{{z}^{2}}+z+x)+5xy{{z}^{2}}</zmlatex>的值(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p>只与<zmlatex>x</zmlatex>，<zmlatex>y</zmlatex>有关</p>',
          '<p>只与<zmlatex>y</zmlatex>，<zmlatex>z</zmlatex>有关</p>',
          '<p>与<zmlatex>x</zmlatex>，<zmlatex>y</zmlatex>，<zmlatex>z</zmlatex>都无关</p>',
          '<p>与<zmlatex>x</zmlatex>，<zmlatex>y</zmlatex>，<zmlatex>z</zmlatex>都有关</p>'
        ],
        answerList: [
          'A'
        ],
        analysis: '<p><zmlatex>yz(xz+2)-2y(3x{{z}^{2}}+z+x)+5xy{{z}^{2}}</zmlatex></p><p><zmlatex>=xy{{z}^{2}}+2yz-6xy{{z}^{2}}-2yz-2xy+5xy{{z}^{2}}</zmlatex></p><p><zmlatex>=-2xy</zmlatex>，</p><p>所以代数式的值只与<zmlatex>x</zmlatex>，<zmlatex>y</zmlatex>有关．</p><p>故选：<zmlatex>A</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 33,
        cityId: 290,
        countyId: 2282,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1,
          3
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          487,
          497
        ],
        examPointIdList: [
          527,
          556
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 1645,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1525846670000,
        createdUser: 1002318580,
        updatedTime: 1536834568000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '合并同类项',
          '单项式与多项式相乘'
        ],
        examPointNameList: [
          '合并同类项',
          '已知多项式乘积不含某项求字母的值'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年甘肃省白银市靖远县',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866709,
      serialNumber: 10,
      questionId: 2706931,
      questionOutputDTO: {
        id: 2706931,
        title: '<p>下面是小芳做的一道多项式的加减运算题,但她不小心把一滴墨水滴在了上面．<zmlatex>(-x^{2}+3xy-\\frac{1}{2}y^{2})-(-\\frac{1}{2}x^{2}+4xy-\\frac{3}{2}y^{2})=-\\frac{1}{2}x^{2}</zmlatex><img src="https://oss-cn-beijing.aliyuncs.com/zm-tiku/qb_prod/20180904193656_8323.png" zmtype="small"/><zmlatex>+y^{2}</zmlatex>,阴影部分即为被墨迹弄污的部分．那么被墨汁遮住的一项应是( &nbsp;)</p>',
        content: null,
        optionList: [
          '<p><zmlatex>-7xy</zmlatex></p>',
          '<p><zmlatex>+7xy</zmlatex></p>',
          '<p><zmlatex>-xy</zmlatex></p>',
          '<p><zmlatex>+xy</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p>由题意得,被墨汁遮住的一项<zmlatex>=(-x^{2}+3xy-\\frac{1}{2}y^{2})-(-\\frac{1}{2}x^{2}+4xy-\\frac{3}{2}y^{2})-(-\\frac{1}{2}x^{2}+y^{2})</zmlatex></p><p><zmlatex>=-x^{2}+3xy-\\frac{1}{2}y^{2}+\\frac{1}{2}x^{2}-4xy+\\frac{3}{2}y^{2}+\\frac{1}{2}x^{2}-y^{2}</zmlatex></p><p><zmlatex>=-xy</zmlatex>．</p><p>故选：<zmlatex>C</zmlatex>.</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 26,
        cityId: 205,
        countyId: 1625,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 4,
        distinction: 3,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1,
          3
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          489
        ],
        examPointIdList: [
          533,
          536
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 7,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1536030059000,
        createdUser: 1004343036,
        updatedTime: 1536739719000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 3,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '整式的加减运算法则'
        ],
        examPointNameList: [
          '整式的加减运算',
          '整式加减的应用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年广东省东莞市东莞市',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866710,
      serialNumber: 11,
      questionId: 304690,
      questionOutputDTO: {
        id: 304690,
        title: '<p>计算<zmlatex>(x-4)\\times \\frac{16-{{x}^{2}}}{{{x}^{2}}-8x+16}</zmlatex>的结果是（&nbsp; ）．</p>',
        content: null,
        optionList: [
          '<p><zmlatex>x+1</zmlatex></p>',
          '<p><zmlatex>-x-4</zmlatex></p>',
          '<p><zmlatex>x-4</zmlatex></p>',
          '<p><zmlatex>4-x</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p>原式<zmlatex>=(x-4)\\cdot \\frac{-(x+4)(x-4)}{{{(x-4)}^{2}}}\n\n=-(x+4)\n\n=-x-4</zmlatex>．</p><p>故选<zmlatex>\\text{B}</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 8,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 26,
        cityId: 189,
        countyId: 1521,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 2,
        distinction: 2,
        recommendationIndex: null,
        rating: 4,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1,
          0
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          510,
          523
        ],
        examPointIdList: [
          581,
          582,
          606
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 131,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1520744167000,
        createdUser: 1002318623,
        updatedTime: 1536908193000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '因式分解的公式法',
          '分式乘以分式'
        ],
        examPointNameList: [
          '运用平方差公式分解因式',
          '运用完全平方公式分解因式',
          '分式的约分'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年广东省广州市白云区',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866711,
      serialNumber: 12,
      questionId: 613303,
      questionOutputDTO: {
        id: 613303,
        title: '<p>如果多项式<zmlatex>{{x}^{2}}+px+12</zmlatex>可以分解成两个一次因式的积,那么整数<zmlatex>p</zmlatex>的值可取多少个(&nbsp; ).</p>',
        content: null,
        optionList: [
          '<p><zmlatex>4</zmlatex></p>',
          '<p><zmlatex>5</zmlatex></p>',
          '<p><zmlatex>6</zmlatex></p>',
          '<p><zmlatex>8</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p><zmlatex>p=\\pm 13</zmlatex>,<zmlatex>p=\\pm 8</zmlatex>,<zmlatex>p=\\pm 7</zmlatex>,共<zmlatex>6</zmlatex>个.</p><p>故选<zmlatex>\\text{C}</zmlatex>.</p>',
        subjectId: 2,
        gradeId: 8,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 5,
        cityId: 5,
        countyId: 0,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 4,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          510,
          512
        ],
        examPointIdList: [
          577,
          582,
          586
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 1893,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1523851904000,
        createdUser: 1002318579,
        updatedTime: 1536896755000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 2,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '因式分解的公式法',
          '因式分解的十字相乘法'
        ],
        examPointNameList: [
          '已知因式分解的结果求参数',
          '运用完全平方公式分解因式',
          '十字相乘法'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年天津省天津市',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866712,
      serialNumber: 13,
      questionId: 173879,
      questionOutputDTO: {
        id: 173879,
        title: '<p>定义一种新运算：<zmlatex>a</zmlatex>♣<zmlatex>b=a(a-b)</zmlatex>，例如，<zmlatex>4</zmlatex>♣<zmlatex>3=4{\\times}(4-3)=4</zmlatex>，若<zmlatex>x</zmlatex>♣<zmlatex>2=3</zmlatex>，则<zmlatex>x</zmlatex>的值是(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>x=3\t </zmlatex></p>',
          '<p><zmlatex>x=-1</zmlatex></p>',
          '<p><zmlatex>{{x}_{1}}=3</zmlatex>,<zmlatex>{{x}_{2}}=1</zmlatex></p>',
          '<p><zmlatex>{{x}_{1}}=3</zmlatex>,<zmlatex>{{x}_{2}}=-1</zmlatex></p>'
        ],
        answerList: [
          'D'
        ],
        analysis: '<p><zmlatex>{\\because}</zmlatex><zmlatex>x</zmlatex>♣<zmlatex>2=3</zmlatex>，</p><p><zmlatex>{\\therefore}</zmlatex><zmlatex>x(x-2)=3</zmlatex>，</p><p>整理得<zmlatex>{{x}^{2}}-2x-3=0</zmlatex>，</p><p><zmlatex>(x-3)(x+1)=0</zmlatex>，</p><p><zmlatex>x-3=0</zmlatex>或<zmlatex>x+1=0</zmlatex>，</p><p>所以<zmlatex>{{x}_{1}}=3</zmlatex>，<zmlatex>{{x}_{2}}=-1</zmlatex>．</p><p>故选<zmlatex>D</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 9,
        phaseId: 2,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 26,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 2,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1,
          3
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          512,
          607
        ],
        examPointIdList: [
          490,
          586,
          743
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 1255,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1514001923000,
        createdUser: 1002318624,
        updatedTime: 1536896586000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 2,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '因式分解的十字相乘法',
          '解一元二次方程的因式分解法'
        ],
        examPointNameList: [
          '新定义下的实数运算',
          '十字相乘法',
          '解一元二次方程——因式分解法'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年广东省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866713,
      serialNumber: 14,
      questionId: 286787,
      questionOutputDTO: {
        id: 286787,
        title: '<p>已知<zmlatex>{{x}^{2}}+x-1=0</zmlatex>，则<zmlatex>{{x}^{8}}-7{{x}^{4}}+11</zmlatex>的值为（&nbsp; ）．</p>',
        content: null,
        optionList: [
          '<p><zmlatex>9</zmlatex></p>',
          '<p><zmlatex>10</zmlatex></p>',
          '<p><zmlatex>11</zmlatex></p>',
          '<p><zmlatex>12</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p><zmlatex>{\\because}{{x}^{2}}+x-1=0</zmlatex>，</p><p><zmlatex>{\\therefore}{{x}^{2}}+x=1,{{x}^{2}}=1-x</zmlatex>，</p><p><zmlatex>{\\therefore}{{x}^{4}}-1=({{x}^{2}}+1)({{x}^{2}}-1)=(1-x+1)(1-x-1)</zmlatex></p><p><zmlatex>=(2-x)\\times (-x)={{x}^{2}}-2x=1-3x</zmlatex>，</p><p>原式<zmlatex>=({{x}^{4}}-1)({{x}^{4}}-6)+5=(1-3x)(1-3x-5)+5\n\n9{{x}^{2}}+9x-4+5=9+1=10</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 8,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 21,
        cityId: 116,
        countyId: 1091,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 5,
        distinction: 3,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1,
          11
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          475,
          12457
        ],
        examPointIdList: [
          501,
          588
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 118,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1519986684000,
        createdUser: 1002318624,
        updatedTime: 1536896802000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 3,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '代数式的值',
          '因式分解的定义'
        ],
        examPointNameList: [
          '已知式子的值，求代数式的值',
          '因式分解的应用'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年湖北省武汉市武昌区',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866714,
      serialNumber: 15,
      questionId: 313784,
      questionOutputDTO: {
        id: 313784,
        title: '<p>要在二次三项式<zmlatex>{{x}^{2}}+( &nbsp;)x-6</zmlatex>的括号中填上一个整数，使它可以按<zmlatex>{{x}^{2}}+(a+b)x+ab=(x+a)(x+b)</zmlatex>形式分解，则括号中可以填写（&nbsp; ）</p>',
        content: null,
        optionList: [
          '<p><zmlatex>1</zmlatex>，<zmlatex>-1</zmlatex></p>',
          '<p><zmlatex>5</zmlatex>，<zmlatex>-5</zmlatex></p>',
          '<p><zmlatex>1</zmlatex>，<zmlatex>-1</zmlatex>，<zmlatex>5</zmlatex>，<zmlatex>-5</zmlatex></p>',
          '<p>以上答案都不对</p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p><zmlatex>-6</zmlatex>可以分成：<zmlatex>-2\\times 3</zmlatex>，<zmlatex>2\\times (-3)</zmlatex>，<zmlatex>-1\\times 6</zmlatex>，<zmlatex>1\\times (-6)</zmlatex>，</p><p>括号中填上的整数应该是<zmlatex>-6</zmlatex>的两个因数的和，即<zmlatex>1</zmlatex>，<zmlatex>-1</zmlatex>，<zmlatex>5</zmlatex>，<zmlatex>-5</zmlatex>，</p><p>故选<zmlatex>\\text{C}</zmlatex>。</p>',
        subjectId: 2,
        gradeId: 8,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 5,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 4,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          512
        ],
        examPointIdList: [
          577
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 20,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1520946722000,
        createdUser: 1002318623,
        updatedTime: 1536896781000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 3,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '因式分解的十字相乘法'
        ],
        examPointNameList: [
          '已知因式分解的结果求参数'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年天津省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866715,
      serialNumber: 16,
      questionId: 311163,
      questionOutputDTO: {
        id: 311163,
        title: '<p>已知多项式<zmlatex>2{{x}^{3}}-{{x}^{2}}+m</zmlatex>分解因式后有一个因式是<zmlatex>x+1</zmlatex>,则<zmlatex>m</zmlatex>的值为（&nbsp; ）．</p>',
        content: null,
        optionList: [
          '<p><zmlatex>3</zmlatex></p>',
          '<p><zmlatex>-3</zmlatex></p>',
          '<p><zmlatex>1</zmlatex></p>',
          '<p><zmlatex>-1</zmlatex></p>'
        ],
        answerList: [
          'A'
        ],
        analysis: '<p>依题意,多项多<zmlatex>2{{x}^{2}}-{{x}^{2}}+m</zmlatex>分解因式后有一个因式是<zmlatex>x+1</zmlatex>,当<zmlatex>x+1=0,x=-1</zmlatex>时,多项式的值为<zmlatex>0</zmlatex>,即<zmlatex>2\\times {{(-1)}^{2}}-{{(-1)}^{2}}+m=-2-1+m=0</zmlatex>,解得<zmlatex>m=3</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 38,
        cityId: 351,
        countyId: 2676,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 4,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          512,
          12457
        ],
        examPointIdList: [
          577,
          743
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 65,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1520918030000,
        createdUser: 1003558921,
        updatedTime: 1536896774000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 2,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '因式分解的十字相乘法',
          '因式分解的定义'
        ],
        examPointNameList: [
          '已知因式分解的结果求参数',
          '解一元二次方程——因式分解法'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2016年浙江省杭州市西湖区',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866716,
      serialNumber: 17,
      questionId: 2337769,
      questionOutputDTO: {
        id: 2337769,
        title: '<p>把多项式<zmlatex>x^2 +ax+b</zmlatex>分解因式,得<zmlatex>(x+1)(x-3)</zmlatex>,则<zmlatex>a+b</zmlatex>的值分别是(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>5</zmlatex></p>',
          '<p><zmlatex>-5</zmlatex></p>',
          '<p><zmlatex>1</zmlatex></p>',
          '<p><zmlatex>-1</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p><zmlatex>(x+1)(x-3)=x^2 -3x+x-3=x^2 -2x-3</zmlatex>,</p><p>由<zmlatex>x^2 +ax+b=(x+1)(x-3)=x^2 -2x-3</zmlatex></p><p>知<zmlatex>a=-2</zmlatex>、<zmlatex>b=-3</zmlatex>,</p><p>则<zmlatex>a+b=-2-3=-5</zmlatex>,</p><p>故选：<zmlatex>B</zmlatex>.</p>',
        subjectId: 2,
        gradeId: 8,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 16,
        cityId: 56,
        countyId: 457,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 3,
        distinction: 2,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          0,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          512
        ],
        examPointIdList: [
          577
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 32,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1534139050000,
        createdUser: 1005940467,
        updatedTime: 1536896762000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '因式分解的十字相乘法'
        ],
        examPointNameList: [
          '已知因式分解的结果求参数'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年山东省济宁市微山县',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866717,
      serialNumber: 18,
      questionId: 1661227,
      questionOutputDTO: {
        id: 1661227,
        title: '<p>若用十字相乘法分解因式：<zmlatex>x^2+mx-12=(x+2)(x+a)</zmlatex>，则<zmlatex>a</zmlatex>、<zmlatex>m</zmlatex>的值分别是(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>-6</zmlatex>，<zmlatex>4</zmlatex></p>',
          '<p><zmlatex>-4</zmlatex>，<zmlatex>-6</zmlatex></p>',
          '<p><zmlatex>-4</zmlatex>，<zmlatex>-6</zmlatex></p>',
          '<p><zmlatex>-6</zmlatex>，<zmlatex>-4</zmlatex></p>'
        ],
        answerList: [
          'D'
        ],
        analysis: '<p>依题意得：<zmlatex>\\left\\{\\begin{matrix} m=2+a\\\\ -12=2a\\\\\\end{matrix}\\right.</zmlatex>，</p><p>解得<zmlatex>\\left\\{\\begin{matrix} a=-6\\\\ m=-4\\\\\\end{matrix}\\right.</zmlatex>．</p><p>故选：<zmlatex>D</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 24,
        cityId: null,
        countyId: null,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 2,
        distinction: 2,
        recommendationIndex: null,
        rating: 5,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          512
        ],
        examPointIdList: [
          577
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 12,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1530254301000,
        createdUser: 1002582619,
        updatedTime: 1536896733000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 2,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '因式分解的十字相乘法'
        ],
        examPointNameList: [
          '已知因式分解的结果求参数'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年江苏省',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866718,
      serialNumber: 19,
      questionId: 2241521,
      questionOutputDTO: {
        id: 2241521,
        title: '<p>若<zmlatex>x^{2}+mx-15=(x+3)(x+n)</zmlatex>，则<zmlatex>m</zmlatex>的值是(&nbsp; )</p>',
        content: null,
        optionList: [
          '<p><zmlatex>-5</zmlatex></p>',
          '<p><zmlatex>5</zmlatex></p>',
          '<p><zmlatex>-2</zmlatex></p>',
          '<p><zmlatex>2</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p><zmlatex>\\because{}x^{2}+mx-15=(x+3)(x+n)</zmlatex>，</p><p><zmlatex>\\therefore{}x^{2}+mx-15=x^{2}+nx+3x+3n</zmlatex>，</p><p><zmlatex>\\therefore{}3n=-15</zmlatex>，<zmlatex>m=n+3</zmlatex>，</p><p>解得<zmlatex>n=-5</zmlatex>，<zmlatex>m=-5+3=-2</zmlatex>．</p><p>故选：<zmlatex>C</zmlatex>．</p>',
        subjectId: 2,
        gradeId: 7,
        phaseId: 2,
        termId: 2,
        typeId: 1,
        questionType: '单选题',
        provinceId: 27,
        cityId: 212,
        countyId: 1672,
        schoolId: null,
        year: 2017,
        score: 5,
        sourceId: 2,
        difficulty: 2,
        distinction: 2,
        recommendationIndex: null,
        rating: 2,
        comprehensiveDegreeId: 2,
        abilityIdList: [
          0,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          498,
          512
        ],
        examPointIdList: [
          554,
          577
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 17,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1533528597000,
        createdUser: 1002318623,
        updatedTime: 1536896570000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 2,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '多项式与多项式相乘',
          '因式分解的十字相乘法'
        ],
        examPointNameList: [
          '（x+p）（x+q）型多项式乘法',
          '已知因式分解的结果求参数'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2017年广西省桂林市永福县',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866719,
      serialNumber: 20,
      questionId: 311530,
      questionOutputDTO: {
        id: 311530,
        title: '<p>下列各式中,从左到右的变形是因式分解的是(&nbsp; )．</p>',
        content: null,
        optionList: [
          '<p><zmlatex>2{{a}^{2}}-2a+1=2a\\left( a-1 \\right)+1</zmlatex></p>',
          '<p><zmlatex>\\left( x+y \\right)\\left( x-y \\right)={{x}^{2}}-{{y}^{2}}</zmlatex></p>',
          '<p><zmlatex>{{x}^{2}}-6x+5=\\left( x-5 \\right)\\left( x-1 \\right)</zmlatex></p>',
          '<p><zmlatex>{{x}^{2}}+{{y}^{2}}={{\\left( x-y \\right)}^{2}}+2xy</zmlatex></p>'
        ],
        answerList: [
          'C'
        ],
        analysis: '<p>只有选项<zmlatex>\\text{C}</zmlatex>是因式分解,选项<zmlatex>\\text{B}</zmlatex>是整式乘法．</p><p>考察了因式分解,把一个多项式化成几个整式积的形式,叫做把这个多项式因式分解．这道题主要考察因式分解中的完全平方．</p>',
        subjectId: 2,
        gradeId: 8,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 3,
        cityId: 3,
        countyId: 10,
        schoolId: null,
        year: 2016,
        score: 5,
        sourceId: 2,
        difficulty: 1,
        distinction: 2,
        recommendationIndex: null,
        rating: 1,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          0,
          13,
          1
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          512,
          12457
        ],
        examPointIdList: [
          586
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 8,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1520927313000,
        createdUser: 1002318580,
        updatedTime: 1536896511000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 2,
        examTypeId: 0,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '因式分解的十字相乘法',
          '因式分解的定义'
        ],
        examPointNameList: [
          '十字相乘法'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2016年北京省北京市海淀区',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    },
    {
      id: 2866720,
      serialNumber: 21,
      questionId: 452840,
      questionOutputDTO: {
        id: 452840,
        title: '<p>对<zmlatex>{{x}^{2}}-3x+2</zmlatex>分解因式,结果为(&nbsp; ).</p>',
        content: null,
        optionList: [
          '<p><zmlatex>x(x-3)+2</zmlatex></p>',
          '<p><zmlatex>(x-1)(x-2)</zmlatex></p>',
          '<p><zmlatex>(x-1)(x+2)</zmlatex></p>',
          '<p><zmlatex>(x+1)(x-2)</zmlatex></p>'
        ],
        answerList: [
          'B'
        ],
        analysis: '<p><zmlatex>{{x}^{2}}-3x+2=(x-1)(x-2).</zmlatex></p><p>故选<zmlatex>\\text{B}.</zmlatex></p>',
        subjectId: 2,
        gradeId: 8,
        phaseId: 2,
        termId: 1,
        typeId: 1,
        questionType: '单选题',
        provinceId: 26,
        cityId: 189,
        countyId: 1520,
        schoolId: null,
        year: 2018,
        score: 5,
        sourceId: 2,
        difficulty: 1,
        distinction: 2,
        recommendationIndex: null,
        rating: 1,
        comprehensiveDegreeId: 1,
        abilityIdList: [
          0,
          2
        ],
        subjectCharacteristicIdList: null,
        editionIdList: null,
        chapterIdList: null,
        knowledgeIdList: [
          512
        ],
        examPointIdList: [
          586
        ],
        coreLiteracyIdList: null,
        costTime: null,
        browseCount: 0,
        quoteCount: 104,
        examCount: 0,
        correctRate: null,
        storageTime: null,
        sub: false,
        state: null,
        createdTime: 1522666220000,
        createdUser: 1002318579,
        updatedTime: 1536896499000,
        updatedUser: 1000888483,
        versions: null,
        remarks: null,
        picUrl: null,
        cutUserId: null,
        auditCutUserId: null,
        entryUserId: null,
        auditEntryUserId: null,
        tagUserId1: null,
        tagUserId2: null,
        auditTagUserId: null,
        cutTime: null,
        auditCutTime: null,
        entryTime: null,
        auditEntryTime: null,
        tag1Time: null,
        tag2Time: null,
        auditTagTime: null,
        errType: 0,
        errReason: '',
        templateType: 2,
        adoptUser1Tag: null,
        adoptUser2Tag: null,
        children: null,
        questionTag1: null,
        questionTag2: null,
        tagAdopt: null,
        tagReason: null,
        tagFeedback1: null,
        tagFeedback2: null,
        auditTagFeedback: null,
        sceneIdList: [
          10
        ],
        suggestTime: 1,
        examTypeId: null,
        tagUser1FeedbackAdoptFlag: null,
        tagUser2FeedbackAdoptFlag: null,
        auditTagUserFeedbackAdoptFlag: null,
        tagUser1AdoptFlag: null,
        tagUser2AdoptFlag: null,
        knowledgeNameList: [
          '因式分解的十字相乘法'
        ],
        examPointNameList: [
          '十字相乘法'
        ],
        layoutStyle: 3,
        x1: null,
        y1: null,
        x2: null,
        y2: null,
        picIndex: null,
        label: '2018年广东省广州市天河区',
        deleted: false,
        parentTypeId: 38,
        parentTypeName: '选择题',
        originPaperName: null,
        examPaperTypeId: null
      },
      epcId: 490553,
      score: 5
    }
  ]
};