export default {
  code: '0',
  message: '',
  data: [
    {
      id: 1534555,
      title: '<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<strong>A</strong></p><p><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Washington,&nbsp;D.C.&nbsp;Bicycle&nbsp;Tours</strong><br/> <strong>Cherry&nbsp;Blossom&nbsp;Bike&nbsp;Tour&nbsp;in&nbsp;Washington,&nbsp;D.C.</strong><br/>&nbsp; &nbsp; Duration:&nbsp;3hours<br/>&nbsp; &nbsp; This&nbsp;small&nbsp;group&nbsp;bike&nbsp;tour&nbsp;is&nbsp;a&nbsp;fantastic&nbsp;way&nbsp;to&nbsp;see&nbsp;the&nbsp;world&nbsp;famous&nbsp;cherry&nbsp;trees&nbsp;with<br/> beautiful&nbsp;flowers&nbsp;of&nbsp;Washington,&nbsp;D.C.&nbsp;Your&nbsp;guide&nbsp;will&nbsp;provide&nbsp;a&nbsp;history&nbsp;lesson&nbsp;about&nbsp;the&nbsp;trees<br/> and&nbsp;the&nbsp;famous&nbsp;monuments&nbsp;where&nbsp;they&nbsp;blossom.&nbsp;Reserve&nbsp;your&nbsp;spot&nbsp;before&nbsp;availability&nbsp;-and<br/> the&nbsp;cherry&nbsp;blossoms-disappear!</p><p><strong>Washington&nbsp;Capital&nbsp;Monuments&nbsp;Bicycle&nbsp;Tour</strong><br/>&nbsp; &nbsp; Duration:&nbsp;3&nbsp;hours&nbsp;(4&nbsp;miles)<br/>&nbsp; &nbsp; Join&nbsp;a&nbsp;guided&nbsp;bike&nbsp;tour&nbsp;and&nbsp;view&nbsp;some&nbsp;of&nbsp;the&nbsp;most&nbsp;popular&nbsp;monuments&nbsp;</p><p>in&nbsp;Washington,&nbsp;D.C.&nbsp;Explore&nbsp;the&nbsp;monuments&nbsp;and&nbsp;memorials&nbsp;on&nbsp;the&nbsp;National&nbsp;Mall&nbsp;as&nbsp;your&nbsp;guide&nbsp;shares&nbsp;unique&nbsp;facts&nbsp;and&nbsp;history&nbsp;at&nbsp;each&nbsp;stop. &nbsp;Guided&nbsp;tour&nbsp;includes&nbsp;bike,&nbsp;helmet,&nbsp;cookies&nbsp;and&nbsp;bottled&nbsp;water.<br/> <strong>Capital&nbsp;City&nbsp;Bike&nbsp;Tour&nbsp;in&nbsp;Washington,&nbsp;D.C.</strong><br/>&nbsp; &nbsp; Duration:3&nbsp;hours<br/></p><p>&nbsp; &nbsp; Morning&nbsp;or&nbsp;Afternoon,&nbsp;this&nbsp;bike&nbsp;tour&nbsp;is&nbsp;the&nbsp;perfect&nbsp;tour&nbsp;for&nbsp;D.C.&nbsp;</p><p>newcomers&nbsp;and&nbsp;locals&nbsp;looking&nbsp;to&nbsp;experience&nbsp;Washington,&nbsp;D.C.&nbsp;in&nbsp;a&nbsp;healthy&nbsp;way&nbsp;with&nbsp;minimum&nbsp;effort.&nbsp;Knowledgeable&nbsp;guides&nbsp;will&nbsp;entertain&nbsp;you&nbsp;with&nbsp;the&nbsp;most&nbsp;interesting&nbsp;stories&nbsp;about&nbsp;Presidents,&nbsp;Congress,&nbsp;memorials,&nbsp;and&nbsp;parks.&nbsp;Comfortable&nbsp;bikes&nbsp;and&nbsp;a&nbsp;smooth&nbsp;tour-route(路线）make&nbsp;cycling&nbsp;between&nbsp;the&nbsp;sites&nbsp;fun&nbsp;and&nbsp;relaxing.<br/> <strong>Washington&nbsp;Capital&nbsp;Sites&nbsp;at&nbsp;Night&nbsp;Bicycle&nbsp;Tour&nbsp;</strong><br/>&nbsp; &nbsp;Duration:3&nbsp;hours&nbsp;（7&nbsp;miles)<br/>&nbsp;Join&nbsp;a&nbsp;small&nbsp;group&nbsp;bike&nbsp;tour&nbsp;for&nbsp;an&nbsp;evening&nbsp;of&nbsp;exploration&nbsp;in&nbsp;the&nbsp;heart&nbsp;of&nbsp;Washington,&nbsp;D.C.&nbsp;Get&nbsp;up&nbsp;close&nbsp;to&nbsp;the&nbsp;monuments&nbsp;and&nbsp;memorials&nbsp;as&nbsp;you&nbsp; bike&nbsp;the&nbsp;sites&nbsp;of&nbsp;Capitol&nbsp;Hill&nbsp;and&nbsp;the&nbsp;National&nbsp;Mall.&nbsp;Frequent&nbsp;stops&nbsp;are made&nbsp;for&nbsp;photo&nbsp;taking&nbsp;as&nbsp;your&nbsp;guide&nbsp;offers&nbsp;unique&nbsp;facts&nbsp;and&nbsp;history.Tour&nbsp;includes&nbsp;bike,&nbsp;helmet,&nbsp;and&nbsp;bottled&nbsp;water.All&nbsp;riders&nbsp;are&nbsp;equipped&nbsp;with reflective&nbsp;vests&nbsp;and&nbsp;safety&nbsp;lights.<br/></p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 9,
      sourceId: 6,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2522484,
          questionId: 1534555,
          title: '<p>Which&nbsp;tour&nbsp;do&nbsp;you&nbsp;need&nbsp;to&nbsp;book&nbsp;in&nbsp;advance?</p>',
          optionList: [
                '<p>Cherry&nbsp;Blossom&nbsp;Bike&nbsp;Tour&nbsp;in&nbsp;Washington,&nbsp;D.C.<br/></p>',
                '<p>Washington&nbsp;Capital&nbsp;Monuments&nbsp;Bicycle&nbsp;Tour.<br/></p>',
                '<p>Capital&nbsp;City&nbsp;Bike&nbsp;Tour&nbsp;in&nbsp;Washington,&nbsp;D.C.<br/></p>',
                '<p>Washington&nbsp;Capital&nbsp;Sites&nbsp;at&nbsp;Night&nbsp;Bicycle&nbsp;Tour.<br/></p>'
              ],
          answerList: [
                'A'
              ],
          analysis: '<p>细节理解题，根据第一个景点的第二段的最后一句Reserve your spot before availability–and the cherry blossoms-disappear!(预定位置，在有效性和樱花消失之前)，可知在樱花自行车旅行中需要提前订票，故选A。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2522485,
          questionId: 1534555,
          title: '<p>What&nbsp;will&nbsp;you&nbsp;do&nbsp;on&nbsp;the&nbsp;Capital&nbsp;City&nbsp;Bike&nbsp;Tour?<br/></p>',
          optionList: [
                '<p>Meet&nbsp;famous&nbsp;people. &nbsp; &nbsp; &nbsp;&nbsp;<br/></p>',
                '<p>Go&nbsp;to&nbsp;a&nbsp;national&nbsp;park.<br/></p>',
                '<p>Visit&nbsp;well-known&nbsp;museums.&nbsp;<br/></p>',
                '<p>Enjoy&nbsp;interesting&nbsp;stories.<br/></p>'
              ],
          answerList: [
                'D'
              ],
          analysis: '<p>细节理解题，根据第三个景点的第二段的第二句knowledgeable guides will entertain you with the most interesting stories about presidents,congress,memories,and parks(知识渊博的向导将用最有趣的关于总统，议会，纪念碑和公园的故事来逗你)，可知在首都城市的自行车旅行中可以享受有趣的故事，故选D。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2522486,
          questionId: 1534555,
          title: '<p>Which&nbsp;of&nbsp;the&nbsp;following&nbsp;does&nbsp;the&nbsp;bicycle&nbsp;tour&nbsp;at&nbsp;night&nbsp;provide?<br/></p>',
          optionList: [
                '<p>City&nbsp;maps &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<br/></p>',
                '<p>Cameras.</p>',
                '<p>Meals. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>',
                '<p>Safety&nbsp;lights.&nbsp;</p>'
              ],
          answerList: [
                'D'
              ],
          analysis: '<p>细节理解题，根据第四个景点的第二段的最后一句All riders are equipped with reflective vests and safety lights(所有的骑行者会被配备马甲和安全灯，故选D。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1534500,
      title: '<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;B</p><p>&nbsp; &nbsp; &nbsp; &nbsp;Good Morning Britain&#39;s Susanna Reid is used to grilling guests on the sofa everymorning, but she is cooking up a storm in her latest role-showing families how to prepare delicious and nutritious meals on a tight budget.</p><p>&nbsp; &nbsp; &nbsp; &nbsp;In Save Money: Good Food, she visits a different home each week and with the help of chef Mart Tebbutt offers top tips on how to reduce food waste, while preparing recipes for under￡5 per family a day. And the Good morning Britain presenter says she&#39;s been able to put a lot of what she&#39;s learnt to practice in her own home, preparing meals for sons, Sam, 14, Finn, 13, and Jack 11.</p><p>&nbsp; &nbsp; “We love Mexican churros, so I buy them on my phone from my local Mexican takeaway restaurant,&quot; she explains. “I pay ￡5 for a portion （一份）, but Matt makes them 26p a portion, because they are flour, water, sugar and oil. Everybody can buy takeaway food, but sometimes we&#39;re not aware how cheaply we can make this food ourselves.”</p><p>&nbsp; &nbsp; &nbsp; &nbsp;The eight-part series(系列药目），Save Money: Good foot, follows in the footsteps of ITV&#39;s Save Money: Good health , which gave viewers advice on how to get value from the vast range of health products on the market.</p><p>&nbsp; &nbsp; &nbsp; &nbsp;With food our biggest weekly household expense, Susanna and Matt spend time with a different family each week. In tonight’s Easter special they come to the aid of a family in need of some delicious inspiration on a budet. The team transforms the family&#39;s long weekend of celebration with less expensive but still tasty recipes.</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 8,
      sourceId: 6,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2529917,
          questionId: 1534500,
          title: '<p>What do we know about&nbsp; Susanna Reid?</p>',
          optionList: [
                '<p>She enjoys embarrassing her guests.</p>',
                '<p>She has started a new programme.</p>',
                '<p>She dislikes working early in the morning.</p>',
                '<p>She has had a tight budget for her family.</p>'
              ],
          answerList: [
                'B'
              ],
          analysis: '<p>A错误：文章第一段提到 she is used to grilling guests 而选项A则是embarrassing her guests, 因此A错&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p><p>B正确：文章第一段提到Susanna 在节目中已经开始了一个新的角色 而B选项正是这个含义&nbsp; &nbsp; &nbsp;&nbsp;</p><p>C错误：C选项属于无中生有，文中根本没有提到Susanna不喜欢早晨工作&nbsp; &nbsp; &nbsp; &nbsp;</p><p>D错误文章第一段指出Susanna是在节目中为大家演示如何以低预算来做出美味的食物，而D选项将其曲解为Susanna家庭预算紧张。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2529918,
          questionId: 1534500,
          title: '<p>How does Mat Tebbutt help Susanna?</p>',
          optionList: [
                '<p>He buys cooking materials for her.</p>',
                '<p>He prepares food for her kids.</p>',
                '<p>He assists her in cooking matters.</p>',
                '<p>He invites guest families for her.</p>'
              ],
          answerList: [
                'C'
              ],
          analysis: '<p>文中第二段提到厨师Matt在减少食物浪费和准备食材方面给Susanna提供了帮助，A选项说Matt给Susanna买食材，与原文不符；B选项杂糅概念，Matt并没有给Susanna的孩子提供食物；C选项指的是Matt在食材上给予她帮助，符合原文；D选项也属于杂糅概念，Matt并没有帮助Susanna邀请家庭，因为她只是个厨师。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2529919,
          questionId: 1534500,
          title: '<p>What does the author intend to do in paragraph 4?</p>',
          optionList: [
                '<p>Summarize the previous paragraphs.</p>',
                '<p>Provide some advice for the readers.</p>',
                '<p>Add some background information.</p>',
                '<p>Introduce a new topic&nbsp; for discussion.</p>'
              ],
          answerList: [
                'C'
              ],
          analysis: '<p>文章第四段介绍 “省钱与好食物”这一节目是紧跟着 “省钱与健康” 节目播出的，因此第四段的作用是给这一节目增加了背景信息，所以C正确。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2529920,
          questionId: 1534500,
          title: '<p>What can be a suitable title for the text?</p>',
          optionList: [
                '<p>Keeping Fit by Eating Smart</p>',
                '<p>Balancing Our Daily Diet</p>',
                '<p>Making Yourself a Perfect Chef</p>',
                '<p>Cooking Well for Less</p>'
              ],
          answerList: [
                'D'
              ],
          analysis: '<p>全文都在介绍如何在预算紧张的情况下来做出美味的食物，而D选项切合题意。 A、B、C与文中主旨不符。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1534568,
      title: '<p style="text-align: center;">C</p><p><zmindent contenteditable="false">空类0</zmindent>Languages have been coming and going for thousands of years, but in recent times there has been less coming and a lot more going. When the world was still populated by hunter-gatherers, small, tightly knit(联系)groups developed their own patterns of speech independent of each other. Some language experts believe that 10,000 years ago, when the world had just five to ten million people, they spoke perhaps 12,000 languages between them.<br/> <zmindent contenteditable="false">空类0</zmindent>Soon afterwards, many of those people started settling down to become farmers, and their languages too became more settled and fewer in number. In recent centuries, trade, industrialisation, the development of the nation-state and the spread of universal compulsory education, especially globalisation and better communications in the past few decades, all have caused many languages to disappear, and&nbsp;<ins>dominant</ins>&nbsp;languages such as English, Spanish and Chinese are increasingly taking over.<br/> <zmindent contenteditable="false">空类0</zmindent>At present, the world has about 6,800 languages.The distribution of these languages is hugely uneven.The general rule is that mild zones have relatively few languages, often spoken by many people, while hot, wet zones have lots, often spoken by small numbers. Europe has only around 200 languages; the Americas about 1,000; Africa 2,400; and Asia and the Pacific perhaps 3, 200, of which New Papua New Guinea along accounts for well over 800.The median number(中位数)of speakers is a mere 6,000, which means that at half the world&#39;s languages are spoken by fewer people than that.&nbsp;</p><p><zmindent contenteditable="false">空类0</zmindent>Already well over 400 of the total of 6,800 languages are close to extinction(消亡),with only a few elderly speakers left. Pick, at random, Busuu in Cameron (eight remaining speakers), Chiapaneco in Mexico (150), Lipan Apache in the United States (two or three) or Wadjigu in Australia (one, with a question-mark): none of these seems to have much chance of survival.</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 12,
      sourceId: 6,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2522455,
          questionId: 1534568,
          title: '<p>What can we infer about languages in hunter-gatherer times?</p>',
          optionList: [
                '<p>They developed very fast.</p>',
                '<p>They were large in number.</p>',
                '<p>They had similar patterns.</p>',
                '<p>They were closely connected.<br/></p>'
              ],
          answerList: [
                'B'
              ],
          analysis: '<p>根据文章中第1段第2句“When the world was still populated by hunter-gatherers,small,tightly knit(联系) groups developed their own atterns of speechindependent of each other. Some language experts believe that 10,000 years ago, when the world had just five to ten million people, they spoke perhaps 12000 languages between them.( 当世界上仍有狩猎采集者居住时，小而紧密的群体就形成了他们各自的相互依赖的话语。一些语言专家认为，10000年前，当世界只有五到一千万人时，他们之间可能会讲12000种语言。)”可知在地球上仍有狩猎采集者居住的时期，语言种类数量是非常多的，故答案选则B。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2522456,
          questionId: 1534568,
          title: '<p>Which of the following best explain “dominant” underlined in paragraph 2?</p>',
          optionList: [
                '<p>Complex.</p>',
                '<p>Advanced.</p>',
                '<p>Powerful.</p>',
                '<p>Modern.</p>'
              ],
          answerList: [
                'C'
              ],
          analysis: '<p>根据文章中第2段第2句“…all have caused many languages to disappear, and dominant languages such as English, Spanish and Chinese are increasingly taking over. ”可知，dominant用来形容英语 西班牙语 中文这类语言，而与前面提到的一些已经消失了的语言相比，这些主要语种是具有优势的，在四个选项中，powerful可以表示此意，故答案选B。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2522457,
          questionId: 1534568,
          title: '<p>How many languages are spoken by less than 6,000 people at present?</p>',
          optionList: [
                '<p>About 6,800.</p>',
                '<p>About 3,400.</p>',
                '<p>About 2,400.</p>',
                '<p>About 1,200.</p>'
              ],
          answerList: [
                'B'
              ],
          analysis: '<p>根据文章中第3段第1句“At present, the world has about 6,800 languages.（目前世界上约有6800种语言）”和第5句“The median number （中位数） of speakers is a mere 6000,which means that that half the world&#39;s languages are spoken by fewer people than that.（使用该语言的人数的中位数仅为6000，这意味着世界上一半的语言只有不到6000人在使用。）”可知目前使用者少于6000人的语言大约有6800÷2=3400，故答案选择B。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2522458,
          questionId: 1534568,
          title: '<p>What is the main idea&nbsp;of&nbsp;the text?</p>',
          optionList: [
                '<p>New languages will be created.</p>',
                '<p>People&#39;s lifestyles are reflected in languages.</p>',
                '<p>Human development results in fewer languages.</p>',
                '<p>Geography determines&nbsp;language evolution.</p>'
              ],
          answerList: [
                'C'
              ],
          analysis: '<p>根据文章中第4段第一句“Already well over 400 of the total of 6800 languages are close to extinction,……（6800种语言中已经大约有400种濒临消亡）”可知，由于人类的发展导致了语言种类数量减少,故答案选C。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1534573,
      title: '<p style="text-align: center;">D</p><p><zmindent contenteditable="false">空类0</zmindent>We may think we&#39;re&nbsp;a&nbsp;culture that&nbsp;gets rid of our worn technology at the first&nbsp;sight of something shiny and new, but a new study shows that we keep using our old devices（装置）well&nbsp;after they go&nbsp;out of style. That&#39;s bad&nbsp;news for the environment -and our wallets -as these outdated devices consume much more energy than the newer ones&nbsp;that do the same&nbsp;things.</p><p><zmindent contenteditable="false">空类0</zmindent>To figure out how much power these&nbsp;devices are using.&nbsp;Callie Babbitt&nbsp;and her colleagues at&nbsp;the Rochester lnstitute&nbsp;of Technology in New York tracked the environmental costs for each product throughout&nbsp;his life-from where&nbsp;its minerals are mined to when&nbsp;we stop using the device. This method provided a&nbsp;readout for&nbsp; how home&nbsp;energy use has evolved since the early&nbsp;1990s. Devices were grouped by generation&nbsp;Desktop&nbsp;computers, basic mobile&nbsp;phones,and&nbsp;box-set TVs defined 1992&nbsp;.Digital&nbsp;cameras arrived on the scene in 1997. And MP3 players,&nbsp;smart phones, and LCD TVs entered homes in 2002, before tablets and e-readers showed up in 2007.</p><p><zmindent contenteditable="false">空类0</zmindent>As we accumulated more devices, however, we didn&#39;t throw&nbsp;out our old ones. &quot;The living-room television&nbsp;is replaced and gets planted in the kids&#39; rooms and suddenly&nbsp;one day, you have a TV in every room&nbsp;of the house.&quot; said one researcher. The average&nbsp;number of electronic&nbsp;devices rose from four per household in 1992 to I3 in 2007. We&#39;re pot just keeping these old devices-we continue to use them.&nbsp;According to the analysis of Babbitt&#39;s&nbsp;team, old monitors and box TVs with&nbsp;cathode ray tubes are the worst devices with their energy consumption and contribution to greenhouse gas emissions（排放）more than doubling during the 1992 to 2007 window.</p><p><zmindent contenteditable="false">空类0</zmindent>So what&#39;s the solution（解决方案）! The team&#39;s date only went up to 2007, bus the researchers&nbsp;also explored&nbsp;what would happen if consumers replaced old products with new electronics that serve more than one function, such as a tablet fer word processing and TV Viewing.&nbsp;They found that&nbsp;&nbsp;more on demand entertainment, &nbsp;viewing on tablets instead of TVs and desktop computers could cut energy consumption by 44%.</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 16,
      questionType: '阅读理解',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 8,
      sourceId: 6,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2522820,
          questionId: 1534573,
          title: '<p>What does the author think of new devices?&nbsp;<zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: [
                '<p>They are environment-friendly.</p>',
                '<p>They are no better than the old.</p>',
                '<p>They cost more to use at home.</p>',
                '<p>They go out of style quickly.</p>'
              ],
          answerList: [
                'A'
              ],
          analysis: '<p>推理判断题。第一段第三句 That&#39;s bad news for the environment（这对于环境是个坏消息）可知，这对环境是不友好的。 故选A。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2522821,
          questionId: 1534573,
          title: '<p>Why did Babbitt&#39;s team conduct the research?&nbsp;<zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: [
                '<p>To reduce the cost of minerals.</p>',
                '<p>To test the life cycle of a product.</p>',
                '<p>To update consumers on new technology.</p>',
                '<p>To find out electricity consumption of the devices.</p>'
              ],
          answerList: [
                'D'
              ],
          analysis: '<p>事实细节题。根据第二段中第一句To&nbsp;figure out how much power these devices are using（为了弄清楚这些装备的使用要耗费多少电量）可知，选项D项意思为这些装备要消耗多少电量 与原文大意相符，故选D。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2522822,
          questionId: 1534573,
          title: '<p>Which of the following uses the least energy?&nbsp;<zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: [
                '<p>The box-set TV.&nbsp;</p>',
                '<p>The tablet.</p>',
                '<p>The LCD TV.</p>',
                '<p>The desktop computer.</p>'
              ],
          answerList: [
                'B'
              ],
          analysis: '<p>主旨大意题。根据第三段第五句old&nbsp;desktop monitors and box TVs with cathode ray tubes are the worst devices with their energy consumption and contribution to greenhouse gas emissions more than doubing during the 1992 to 2007wiondow可知，old&nbsp;desktop and box TVs对于电量的消耗和温室气体的排放贡献量为两倍，所以排除A和D项 最后一段最后一句They found that more on demand environment viewing on tablets instead of TVs and desktops computers could cut energy consumption 44%（他们发现在平板电脑上看娱乐节目比在电视上和台式电脑能减少44%的耗能故选B。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2522823,
          questionId: 1534573,
          title: '<p>What does the text suggest people do about old electronic devices?&nbsp;<zmsubline contenteditable="false">空类2</zmsubline></p>',
          optionList: [
                '<p>Stop using them</p>',
                '<p>Take them apart</p>',
                '<p>Upgrade them</p>',
                '<p>Recycle them</p>'
              ],
          answerList: [
                'A'
              ],
          analysis: '<p>推理判断题。根据最后一段最后一句They found that more on demand environment viewing on tablets instead of TVs and desktops computers could cut energy consumption 44%（他们发现在平板电脑上看娱乐节目比在电视上和台式电脑能减少44%的耗能instead&nbsp;of 的意思是替代，可知，是不再使用它们，故选A。</p>',
          typeId: 2,
          score: 2,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1534600,
      title: '<p>第二节（共5小题；每小题2分，满分10分）</p><p>&nbsp; &nbsp; &nbsp; &nbsp;根据短文内容,从短文后的选项中选出能填入空白处的最佳选项。选项中有两项为多余选项。&nbsp;</p><p><br/></p><p><zmindent></zmindent>Color is fundamental in home design--something you’ll always have in every room. A grasp of how to manage color in your spaces is one of the first steps to creating rooms you&#39;ll love to live in. Do you want a room that&#39;s full of life? Professional? Or are you just looking for a place to relax after a long day?<zmsubline></zmsubline>,color is the key to making a room feel the way you want it to feel.</p><p><zmindent></zmindent>Over the years, three have been a number of different techniques to help designers approach this important point.<zmsubline></zmsubline>, they can get a little complex. But good news is that there&#39;re really only three kinds of decisions you need to make about color in your home: the small ones, the medium ones, and the large ones.&nbsp;</p><p><zmindent></zmindent><zmsubline></zmsubline>. They&#39;re the little spots of color like throw pillows, mirrors and baskets that most of us use to add visual interest to our rooms. Less tiring than painting your walls and less expensive than buying a colorful sofa, small color choices bring with them the significant benefit of being easily changeable.</p><p><zmindent></zmindent>Medium color choices are generally furniture pieces such as sofas, dinner tables or&nbsp;bookshelves.<zmsubline></zmsubline>. They require a bigger commitment than smaller ones, and they have a more powerful effect on the feeling of a space.</p><p><zmindent></zmindent>The large color decisions in your rooms concern the walls, ceilings and floors. Whether you&#39;re looking at wallpaper or paint, the time ,effort and relative expense put into it are significant.<zmsubline></zmsubline>.</p><p>A.While all of them are useful</p><p>B.Whatever you&#39;re looking for</p><p>C.If you&#39;re experimenting with a color</p><p>D.Small color choices are the ones we&#39;re most familiar with</p><p>E.It&#39;s not really a good idea to use too many small color pieces</p><p>F.So it pays to be sure, because you want to get it right the first time</p><p>G.Color choices in this range are a step up from the small ones in two major ways</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>B<br/></p>',
        '<p>A</p>',
        '<p>D</p>',
        '<p>G</p>',
        '<p>F<br/></p>'
      ],
      analysis: '<p>1.&nbsp;根据上文第一段中提到的Do you want a room that’s full of life?professional? Or are you just looking for a place to relax after a long day?可知作者是在告诉我们到底需要房间是什么样子的，但是无论我们需要什么样子的房间，color 对于房子来说都很重要，故选B。</p><p>2.根据第二段中上文提到的there have been a number of &nbsp;to help designers approach this important point，以及后文提到的they can get a little complex 中的they指代的就是前面different techniques ，虽然他们很有用但是还是有点complex（复杂），故选A。</p><p>3.根据上文第三段中提到the small ones， the medium ones， and the large ones的一个小标题的结构可知，本段是从the small ones 入手，来讲解小颜色的选择对于房子的影响，故选D 。</p><p>4.根据上文第四段中提到的medium color choices are generally furniture pieces such as sofas, dinner tables or bookshelves可知这些家具是中等颜色的选择过程中需要考虑的问题，因为下文提到了他们对于空间感有很大的影响作用可知他们很重要，刚好就呼应了G&nbsp;选项中的在这个环节中的颜色的选择会比之前的小范围的颜色的选择要提升了一个档次，故选G。</p><p>5.根据上文第五段中提到whether you’re looking at a wallpaper or paint, the time, effort and&nbsp;Relative expense put into it are significant的可知，尽管墙纸等的颜色选择需要投入大量的时间和精力，但是毕竟是值得的pays 因为他们是房子选择颜色的第一步，the first time，故选F。</p>',
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 19,
      questionType: '七选五',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 10,
      sourceId: 6,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 44,
      parentTypeName: '阅读题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 874995,
      title: '<p><zmindent contenteditable="false">空类0</zmindent>During my second year at the city college, I was told that the education department was offering a “free&quot; course, called Thinking Chess, for three credits. I<zmsubline contenteditable="false">空类2</zmsubline>the idea of taking the class because after all who doesn’t want to<zmsubline contenteditable="false">空类2</zmsubline>a few dollars. More than that, I‘d always wanted to learn chess. And, even if f weren&#39;t<zmsubline contenteditable="false">空类2</zmsubline>enough about free credits, news about our<zmsubline contenteditable="false">空类2</zmsubline>was appealing enough to me. He was an international grandmaster, which<zmsubline contenteditable="false">空类2</zmsubline>I would be learning from one of the game&#39;s<zmsubline contenteditable="false">空类2</zmsubline>. &nbsp;I could hardly wait to<zmsubline contenteditable="false">空类2</zmsubline>him.</p><p>&nbsp; &nbsp; &nbsp; Maurice Ashley was kind and smart, a former graduate returning to teach, and this<zmsubline contenteditable="false">空类2</zmsubline>was no game for him; he meant business. In his introduction, he made it<zmsubline contenteditable="false">空类2</zmsubline>that our credits would be hard-earned. In order to<zmsubline contenteditable="false">空类2</zmsubline>the class, among other criteria, wehad to write a paper on how we plan to<zmsubline contenteditable="false">空类2</zmsubline>what we would learn in class to our future professions and,<zmsubline contenteditable="false">空类2</zmsubline>, to our lives. I managed to get an A in that<zmsubline contenteditable="false">空类2</zmsubline>and learned life lessons that have served me one well beyond the<zmsubline contenteditable="false">空类2</zmsubline>.</p><p>&nbsp; &nbsp; &nbsp;Ten years after my chess class with Ashley, I&#39;m still putting to use what he<zmsubline contenteditable="false">空类2</zmsubline>me:&quot;The absolute most important<zmsubline contenteditable="false">空类2</zmsubline>that you learn when you play chess is how to make good<zmsubline contenteditable="false">空类2</zmsubline>. On every single move you have to<zmsubline contenteditable="false">空类2</zmsubline>a situation, process what your opponent(对手）is doing and<zmsubline contenteditable="false">空类2</zmsubline>the best move from among all your options.”These words still ring true today in my<zmsubline contenteditable="false">空类2</zmsubline>as a journalist.</p>',
      content: null,
      optionList: null,
      answerList: null,
      analysis: null,
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: 1,
      typeId: 15,
      questionType: '完形填空',
      provinceId: 26,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 3,
      sourceId: 6,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112043,
        112048,
        112053
      ],
      examPointIdList: [
        12043,
        12048,
        12053
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: true,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 1,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: [
        {
          id: 2523021,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>put forward</p>',
                '<p>jumped at</p>',
                '<p>tried out</p>',
                '<p>turned down</p>'
              ],
          answerList: [
                'B'
              ],
          analysis: '<p>考查动词词组。根据文章中前文所说的学校给我们所提供的课程，使得我欣然接受了这个课程。&nbsp;Put forward 提出，拿出，放出，&nbsp;&nbsp;jump at 欣然接受，急切的接受，&nbsp;try out 试验，考验，turn down 减小，关小</p><p><br/></p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523022,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>waste</p>',
                '<p>earn</p>',
                '<p>save&nbsp;</p>',
                '<p>pay</p>'
              ],
          answerList: [
                'C'
              ],
          analysis: '<p>考查动词。save 对应文章中的免费课程，指出“谁不想要节省一些钱？”A waste 浪费，B earn 赚钱，&nbsp;D 支付。</p><p><br/></p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523023,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>excitcd</p>',
                '<p>worried</p>',
                '<p>moved</p>',
                '<p>tired</p>'
              ],
          answerList: [
                'A'
              ],
          analysis: '<p>考查非谓语动词。我对免费的课程并没有感到很兴奋，我所兴奋的是因为这个老师足够的吸引我。A兴奋，激动，B。担心&nbsp;C。移动，感动，&nbsp;D努力</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523024,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>title&nbsp;</p>',
                '<p>competitor</p>',
                '<p>textbook</p>',
                '<p>instuctor</p>'
              ],
          answerList: [
                'D'
              ],
          analysis: '<p>考查名词。instructor 讲师。后文部分开始讲的是一个具体的一个人故选项中的A 题目，B竞争者，C参考书都不合适</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523025,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>urged</p>',
                '<p>demanded</p>',
                '<p>held</p>',
                '<p>meant</p>'
              ],
          answerList: [
                'D'
              ],
          analysis: '<p>&nbsp;meant意味着，因为前文中说他是一个国际象棋大师，所以后文意味着我可以从他身上学习。A 。urged 催促，B demanded 被要求的&nbsp;，C held 提出，举起，提升</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523026,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>fastest&nbsp;</p>',
                '<p>easiest</p>',
                '<p>best</p>',
                '<p>rarest</p>'
              ],
          answerList: [
                'C'
              ],
          analysis: '<p>考查形容词。&nbsp;学习到游戏中最好的一部分。&nbsp;A 最快的，B最容易的，C 最好的，D 最珍贵的</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523027,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>interview&nbsp;</p>',
                '<p>meet</p>',
                '<p>challenge&nbsp;</p>',
                '<p>beat</p>'
              ],
          answerList: [
                'B'
              ],
          analysis: '<p>考查动词。迫不及待的想见到他。A采访，&nbsp;C挑战，D打败</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523028,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>chance&nbsp;</p>',
                '<p>qualification</p>',
                '<p>honor</p>',
                '<p>job</p>'
              ],
          answerList: [
                'D'
              ],
          analysis: '<p>考查名词。这份工作对他来说不是一个游戏。A 机会，B资格，条件，限制，C 荣誉</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523029,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>real</p>',
                '<p>perfect&nbsp;</p>',
                '<p>clear&nbsp;</p>',
                '<p>possible</p>'
              ],
          answerList: [
                'C'
              ],
          analysis: '<p>考查形容词。&nbsp;made it clear that很明白的告诉我们。A real 真的，B perfect完美，D可能的</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523030,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>attend&nbsp;</p>',
                '<p>pass</p>',
                '<p>skip</p>',
                '<p>observe</p>'
              ],
          answerList: [
                'B'
              ],
          analysis: '<p>考查动词。pass the class 通过课程。A attend 参加，C skip 略过，D observe 遵守，观察，注意</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523031,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>add&nbsp;</p>',
                '<p>expose&nbsp;</p>',
                '<p>apply&nbsp;</p>',
                '<p>compare</p>'
              ],
          answerList: [
                'C'
              ],
          analysis: '<p>考查动词。apply 把我们课堂中所学习的应用到未来的职业中。A。add 增加，B expose 揭露，解释。D。compare 比较，对比</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523032,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>eventually</p>',
                '<p>naturally</p>',
                '<p>directly</p>',
                '<p>normally</p>'
              ],
          answerList: [
                'A'
              ],
          analysis: '<p>考查副词。最后地。文中指的是这对未来职业最后对生活的影响。B自然地，C直接地。D正常地.</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523033,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>game&nbsp;</p>',
                '<p>presentation&nbsp;</p>',
                '<p>course</p>',
                '<p>experiment</p>'
              ],
          answerList: [
                'C'
              ],
          analysis: '<p>考查名词&nbsp;在这门课程中选course，表明我想在这门课程中得到一个A。A游戏，B展现，呈现，&nbsp;D实验&nbsp;，该三个选项用在此处都不合适</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523034,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>criterion</p>',
                '<p>classroom</p>',
                '<p>department</p>',
                '<p>situation</p>'
              ],
          answerList: [
                'B'
              ],
          analysis: '<p>考查名词指我们在这门课上所学习的远比在教室中的多，我们还学到了很多关于人生的课程&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A标准，&nbsp;C 部门，D情况。</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523035,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>taught&nbsp;</p>',
                '<p>wrote&nbsp;</p>',
                '<p>questioned</p>',
                '<p>promised</p>'
              ],
          answerList: [
                'A'
              ],
          analysis: '<p>考查动词。taught 是teach 的过去式，表示老师教给我们的。B 写，&nbsp;C询问，D许诺&nbsp;在此处均不合适</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523036,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>fact</p>',
                '<p>step</p>',
                '<p>manner&nbsp;</p>',
                '<p>skill</p>'
              ],
          answerList: [
                'D'
              ],
          analysis: '<p>考查名词。所学习的最重要的技巧。B，step 步骤，&nbsp;C manner 方式，规矩&nbsp;D skill 技巧。</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523037,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>grades</p>',
                '<p>decisons&nbsp;</p>',
                '<p>impressions</p>',
                '<p>impressions</p>'
              ],
          answerList: [
                'B'
              ],
          analysis: '<p>&nbsp;考查名词。作出好的决定，后文中指出走出的每一步都很重要，所以此处只有这个选项最合适。A分数，C印象，&nbsp;D 评价</p><p><br/></p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523038,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>analyze</p>',
                '<p>describe&nbsp;</p>',
                '<p>rebuild</p>',
                '<p>control</p>'
              ],
          answerList: [
                'A'
              ],
          analysis: '<p>考查动词。分析情况，文中指出分析情况，然后开始处理你的对手是如何做的。B描述，C重建，D 控制</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523039,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>announce&nbsp;</p>',
                '<p>signal</p>',
                '<p>block&nbsp;</p>',
                '<p>evaluate</p>'
              ],
          answerList: [
                'D'
              ],
          analysis: '<p>考查动词。经过分析之后评估选出最好的一步&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A 宣布，&nbsp;B 信号&nbsp;，标志，&nbsp;C。block 阻止，封盖&nbsp;D评估出</p><p><br/></p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        },
        {
          id: 2523040,
          questionId: 874995,
          title: '',
          optionList: [
                '<p>role</p>',
                '<p>desire</p>',
                '<p>concern&nbsp;</p>',
                '<p>behavior</p>'
              ],
          answerList: [
                'A'
              ],
          analysis: '<p>考查名词。in my role as a journalist 文中大意：这些话对我现在作为一个新闻工作者的角色依然受用。B desire 渴望，concern 关心，&nbsp;behavior 表现，行为。</p>',
          typeId: 2,
          score: 1,
          difficulty: null,
          knowledgeIdList: null,
          examPointIdList: null,
          subQuestionMemberList: null
        }
      ],
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '记叙文',
        '个人情况               ',
        '兴趣与爱好'
      ],
      examPointNameList: [
        '记叙文',
        '个人情况               ',
        '兴趣与爱好'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 39,
      parentTypeName: '填空题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1534686,
      title: '<p>&nbsp; &nbsp; &nbsp;According&nbsp;to&nbsp;a&nbsp;review&nbsp;of&nbsp;evidence&nbsp;in&nbsp;a&nbsp;medical&nbsp;journal,runners&nbsp;live&nbsp;three&nbsp;years<zmsubline contenteditable="false">空类2</zmsubline>(long)&nbsp;than&nbsp;non-runners.You&nbsp;don’t&nbsp;have&nbsp;to&nbsp;run&nbsp;fast&nbsp;or&nbsp;long&nbsp;&nbsp;(see)&nbsp;the&nbsp;benefit.You&nbsp;may&nbsp;drink, smoke, be&nbsp;overweight&nbsp;and&nbsp;still&nbsp;reduce&nbsp;your&nbsp;risk&nbsp;of&nbsp;<ins><zmsubline contenteditable="false">空类2</zmsubline></ins>&nbsp;(die)&nbsp;early&nbsp;by&nbsp;running&nbsp;.<br/>&nbsp; &nbsp; &nbsp;While&nbsp;running&nbsp;regularly&nbsp;can’t&nbsp;make&nbsp;you&nbsp;live&nbsp;forever, the&nbsp;review&nbsp;says&nbsp;it&nbsp;<ins><zmsubline contenteditable="false">空类2</zmsubline></ins>&nbsp;be&nbsp;more&nbsp;effective at&nbsp;lengthening&nbsp;life&nbsp;<ins><zmsubline contenteditable="false">空类2</zmsubline></ins>&nbsp;walking, cycling&nbsp;or&nbsp;swimming.Two&nbsp;of&nbsp;the&nbsp;authors&nbsp;of&nbsp;the&nbsp;review&nbsp;also&nbsp;made&nbsp;a&nbsp;study&nbsp;published&nbsp;in&nbsp;2014&nbsp;<ins><zmsubline contenteditable="false">空类2</zmsubline></ins>&nbsp;showed&nbsp;a&nbsp;mere&nbsp;five&nbsp;to&nbsp;10&nbsp;minutes&nbsp;a&nbsp;day&nbsp;of&nbsp;running&nbsp;reduced&nbsp;the&nbsp;risk&nbsp;of heart&nbsp;disease&nbsp;and&nbsp;early&nbsp;deaths&nbsp;from&nbsp;all&nbsp;<ins><zmsubline contenteditable="false">空类2</zmsubline></ins>&nbsp;(cause).<br/>&nbsp; &nbsp; &nbsp;The&nbsp;best&nbsp;exercise&nbsp;is&nbsp;one&nbsp;that&nbsp;you&nbsp;enjoy&nbsp;and&nbsp;will&nbsp;do. But&nbsp;otherwise...it&#39;s&nbsp;probably&nbsp;running. To&nbsp;avoid&nbsp;knee&nbsp;pain,you&nbsp;can&nbsp;run&nbsp;on&nbsp;soft&nbsp;surfaces, do&nbsp;exercises&nbsp;to&nbsp;<ins><zmsubline contenteditable="false">空类2</zmsubline></ins>&nbsp;(strength)&nbsp;your&nbsp;leg&nbsp;muscles(肌肉）,avoid&nbsp;hills&nbsp;and&nbsp;get&nbsp;good&nbsp;running&nbsp;shoes. Running&nbsp;is&nbsp;cheap,easy&nbsp;and&nbsp;it&#39;s&nbsp;always&nbsp;<ins><zmsubline contenteditable="false">空类2</zmsubline></ins>(energy).If&nbsp;you&nbsp;are&nbsp;time&nbsp;poor, you&nbsp;need&nbsp;run&nbsp;for&nbsp;only&nbsp;half&nbsp;the&nbsp;time&nbsp;to&nbsp;get&nbsp;the&nbsp;same&nbsp;benefits&nbsp;as&nbsp;other&nbsp;sports,so&nbsp;perhaps&nbsp;we&nbsp;should&nbsp;all&nbsp;give&nbsp;<ins><zmsubline contenteditable="false">空类2</zmsubline></ins>&nbsp;a&nbsp;try.</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>longer</p>',
        '<p>to see<br/></p>',
        '<p>dying<br/></p>',
        '<p>is<br/></p>',
        '<p>than<br/></p>',
        '<p>which/that<br/></p>',
        '<p>causes<br/></p>',
        '<p>strengthen<br/></p>',
        '<p>energetic<br/></p>',
        '<p>it<br/></p>'
      ],
      analysis: '<p>61.&nbsp;longer 考査形容词的比较级。根据后面的提示词than可知此处需用形容词的比较级.故填longer.</p><p>62.&nbsp;to see 考査非谓语动词。句意:你不必跑得快,也不需要长时间看到益处。此处表目的,需用to do 不定式。故填to&nbsp;see。<br/>63. dying 考査非谓语动词。risk&nbsp;of&nbsp;doing&nbsp;sth.冒着---的危险，固定搭配。故填 dying。</p><p>64. is 考査动词时态。此处是评论指出的一个客观事实，需用一般现在时，又因主语是単数，故填is.<br/>65. than 考査比较级结构,根据前面的more effective可知,此处是形容词比较级结构，需用than。故填than。<br/>66. which/that 考査定语从句的引导词。此处是一个定语从句，空格处所填的词指代先行词a&nbsp;study,指物,且定语从句中缺主语，需要用which或that引导该从句.故填which/that。</p><p>67. causes&nbsp;考査名词的数:&nbsp;cause原因,可数名词。根据空前的修饰词all可知,此处需用名词复数形式。故填causes.<br/>68. strevgthen&nbsp;考査非谓语动词。根据句意此处指锻炼的目的是増强腿部肌肉。strengthen 动词,加强,巩固。不定式符号to后需用动词原形,故填strengthen。<br/>69.&nbsp;energetic 考査形容词。空处所填的词在句中作表语，需用形容词.&nbsp;energetic形容词,精精力充沛的，充满活カ的。故填energetic。<br/>70. it 考査代词.结合前文可知，此处指的是我们都应该尝试一下跑步.指代前面的running,需用代词it。故填it.<br/></p>',
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 32,
      questionType: '语法填空',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 15,
      sourceId: 6,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 39,
      parentTypeName: '填空题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1534497,
      title: '<p>第四部分&nbsp;&nbsp;写作<br/>第一节&nbsp; 短文改错<br/>假定英语课上老师要求同桌之间交换修改作文，请你修改你同桌写的以下作文。文中共有10处语言错误，每句中最多有两处。每处错误仅涉及一个单词的增加、到除或修改。<br/>增加：在缺词处加一个漏字符号（Λ），并在其下面写出该加的词。<br/>删除：把多余的词用斜线（\\）划掉。<br/>售改：在错的词下划一横线，并在该词下面写出修改后的词。<br/>注意：1.每处错议及其修改均仅限一词：<br/>2.只允许修改10处，多者（从第11处起）不计分。</p><p><zmindent contenteditable="false">空类0</zmindent>During my last winter holiday.&nbsp;I went to countryside with my father to visit&nbsp;my gandparents.&nbsp;I find a big change there.&nbsp;The fist time I went there,&nbsp;they were&nbsp;living in a small house with dogs,ducks,and another&nbsp;animals.&nbsp;Last&nbsp;winter when&nbsp;&nbsp;I&nbsp;went here again,&nbsp;they had a big separate house to raise dozens of&nbsp;chicken.&nbsp;They&nbsp;also&nbsp;had a small pond which they raised&nbsp;fish.My&nbsp;grandpa&nbsp;said last summer they carned&nbsp;&nbsp;quite a&nbsp;lot by sell the fish.I felt happily that their life had&nbsp;improved.At&nbsp;the end of&nbsp;our trip,&nbsp;I told my father that I planned to return for every two years,&nbsp;but he agreed.</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>I went to countryside with my father to visit&nbsp;my gandparents.句子中的countryside 改为 the countryside.</p>',
        '<p>&nbsp;I find a big change there.&nbsp;句子中的find改为found。</p>',
        '<p>they were&nbsp;living in a small house with dogs,ducks,and another&nbsp;animals.&nbsp;句子中的another&nbsp;改为other.</p>',
        '<p>Last&nbsp;winter when&nbsp;&nbsp;I&nbsp;went here again,&nbsp;句子中的here改为there。</p>',
        '<p>they had a big separate house to raise dozens of&nbsp;chicken.句子中的chicken是可数名词，所以需要改为chickens。</p>',
        '<p>They&nbsp;also&nbsp;had a small pond which they raised&nbsp;fish.句子中的&nbsp;&nbsp;which&nbsp;改为where.</p>',
        '<p>My&nbsp;grandpa&nbsp;said last summer they carned&nbsp;&nbsp;quite a&nbsp;lot by sell the fish.句子中的sell改为seling.</p>',
        '<p>I felt happily that their life had&nbsp;improved.句子中的happily改为happy.</p>',
        '<p>I told my father that I planned to return for every two years,&nbsp;句子中删去for</p>',
        '<p>but he agreed.句子中的but改为and.</p>'
      ],
      analysis: '<p>第一处：考查冠词，the修饰特指，这里特指爷爷奶奶所住乡村，故要添加the。<br/>第二处：考查动词的时态。句意：我发现那里的一个大变化。故事发生在过去，因此这里用一般过去时。故find改为found。<br/>第三处：考查不定代词。句意：我第一次到达那里，他们住在一个有着狗，鸭子和其他动物的房子里。another后面接名词单数，other后接名词复数，表示其他的。故another&nbsp;改为other.<br/>第四处：考查地点副词。上个寒假，我再一次到了那里。根据句意，现在不在那个地方了，应该用那里。故here改为there.<br/>第五处：考查非谓语动词，句意：他们有个很大的房子来养许多只鸡，这里seperate和房子是被动关系。应该用动词的过去分词来修怖房子，故separate改为separated.<br/>第六处：考查定语从句关系词选择，句意：他们有个养鱼的小池塘。这里先行词是pond，在从句中作地点状语，因此这里要用where.故which&nbsp;改为where.</p><p>第七处：考查动名词。句意：爷爷说上个夏天，他们通过卖鱼挣了好多钱，by是个介词，介词后面加动名词，故sell改为seling.<br/></p><p>第八处：考查形容词，句意；我对他们生活已经改善很多感到高兴，fell是feel过去式，是系动词，后面接形容词。故happily改为happy.<br/>第九处：考查时间状语。句意；我告诉父亲我打算每两年回去。For&nbsp;后加时间段，every&nbsp;two&nbsp;years为每两年，和for&nbsp;不可同时用，故删去for。<br/>第十处：考查连词。句意：而且父亲同意了，根据句意这里应该是父亲同意了。与上文是递进关系。But表示但是，是转折关系。故but改为and.</p>',
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 21,
      questionType: '短文改错',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 3,
      sourceId: 6,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 3,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 45,
      parentTypeName: '变形改错题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 1534492,
      title: '<p>书面表达</p><p>假定你是李华，你的新西兰朋友Terry将去中国朋友家做客，发邮件向你询问有关<br/>习俗。请你回复邮件，内容包括：<br/>1.到达时间：<br/>2.合适的礼物：<br/>3.餐桌礼仪。<br/>注意：<br/>1.词数100左右：<br/>2.可以适当增加细节，以使行文连贯。<br/></p><p><zmsubline></zmsubline></p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>Dear&nbsp;Terry,<br/>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;How&nbsp;are&nbsp;you&nbsp;doing?&nbsp;In&nbsp;your&nbsp;last&nbsp;letter,&nbsp;you asked&nbsp;me&nbsp;about&nbsp;being&nbsp;a&nbsp;guest&nbsp;to&nbsp;a&nbsp;Chinese friend&#39;s&nbsp;home.&nbsp;Now, I&nbsp;am&nbsp;</p><p>writing&nbsp;to&nbsp;inform&nbsp;you of&nbsp;some&nbsp;relevant&nbsp;details.</p><p><zmindent contenteditable="false">空类0</zmindent>To&nbsp;begin&nbsp;with,&nbsp;according&nbsp;to&nbsp;our&nbsp;tradition,&nbsp;you&nbsp;are&nbsp;supposed&nbsp;to&nbsp;arrive&nbsp;early,&nbsp;so&nbsp;that&nbsp;you&nbsp;can help&nbsp;the family</p><p>prepare&nbsp;the&nbsp;dinner,&nbsp;which&nbsp;is&nbsp;not only&nbsp;meaningful&nbsp;but&nbsp;also&nbsp;interesting.&nbsp;Besides, you&#39;d&nbsp;better&nbsp;bring&nbsp;some&nbsp;gifts,such&nbsp;</p><p>as&nbsp;a&nbsp;book&nbsp;or a&nbsp;Chinese&nbsp;knot.&nbsp;What&#39;s&nbsp;more,&nbsp;when&nbsp;you&nbsp;are enjoying&nbsp;the&nbsp;meal,&nbsp;you&nbsp;need&nbsp;to&nbsp;avoid&nbsp;making noises&nbsp;</p><p>while&nbsp;chewing&nbsp;food.<br/><zmindent contenteditable="false">空类0</zmindent>Hopefully,&nbsp;these&nbsp;suggestions&nbsp;would&nbsp;be&nbsp;helpful for&nbsp;you.&nbsp;I&nbsp;have&nbsp;the&nbsp;confidence&nbsp;that&nbsp;you&nbsp;will&nbsp; have&nbsp;a&nbsp;great&nbsp;time.</p><p>I&nbsp;am&nbsp;looking&nbsp;forward&nbsp;to&nbsp;your good&nbsp;news.<br/>Best&nbsp;wishes！<br/></p><p>yours</p><p>Li Hua</p>'
      ],
      analysis: '<p>【点评】这是一篇建议类的作文。要求写一封信，向Terry介绍中国餐桌礼仪。文章宜分为三部分：第一部分点明写作目的，表明回信给Terry提建议。第二部分介绍中国习俗，包括题目提示的三个方面：到达时间、合适的礼物和餐桌礼仪。该部分虽然有提示写作方向，但并无详细提示，要求学生本身对中国餐桌文化有一定的了解，并能简洁清晰地表达出来，使文章内容充实具体，有较大的写作难度。第三部分则表达自己对Terry的祝福。</p><p>【亮点分析】所给范文内容齐全，对习俗有一定的解释，建议具体可行。较好地运用了连接词（From&nbsp;my perspective, First and foremost, What’s more, Most importantly），文章条理清晰。且文章句型灵活多样，使用了强调句型（Not&nbsp;only…but also…），虚拟句型（If&nbsp;I were you, I would …），宾语从句等，以及词汇表述较为优秀，如动词短语（express&nbsp;your&nbsp;gratitude for, have an unforgettable time, grasp），名词词汇（hospitality, table manner）。</p>',
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: null,
      typeId: 18,
      questionType: '书面表达',
      provinceId: null,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: 2018,
      score: 25,
      sourceId: 6,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 2,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: null,
      createdUser: null,
      updatedTime: null,
      updatedUser: null,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: null,
      errReason: null,
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: 3,
      examTypeId: 2,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: null,
      deleted: null,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: null
    }
  ]
};