export default {
  code: '0',
  message: '',
  data: [
    {
      id: 112201,
      title: '<p>下列各句中，没有语病的一句是（ &nbsp;）</p>',
      content: null,
      optionList: [
        '<p>近期发射的首个中国自行研制的货运飞船“天舟”一号与“天宫”二号交会对接，开展推进剂在轨补加等技术验证，为中国建成空间站搭桥铺路。</p>',
        '<p>今年国际消费者权益日在央视一套播出了以“用责任汇聚诚信的力量”为主题的“3·15”晚会，满足了观众渴望了解消费侵权事件的收视期待。</p>',
        '<p>因把《红岩》《平凡的世界》等作品也纳入高考必考范围，众多师生和家长对《2017北京高考语文考纲》中出现的这一变化极为关注。</p>',
        '<p>植树节的意义不在于种下了多少棵树，而在于让更多的人关注生态环境问题，在于通过植树造林来增强人们的环保意识，建设美丽中国。</p>'
      ],
      answerList: [
        'D'
      ],
      analysis: '<p>本题考查辨析并修改病句的能力。A项语序不当，“首个”位置错误，应放在“货运飞船”的前面；B项成分残缺，应在“满足”前加“晚会”；C项结构混乱，前后两句的主语不一致。可去掉“把”。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: 2,
      typeId: 1,
      questionType: '单选题',
      provinceId: 20,
      cityId: 107,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 1,
      distinction: 2,
      recommendationIndex: null,
      rating: 1,
      comprehensiveDegreeId: 1,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112577,
        112583,
        112595
      ],
      examPointIdList: [
        12577,
        12583,
        12595
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 191,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513672935000,
      createdUser: 1002508641,
      updatedTime: 1522217183000,
      updatedUser: 768640,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 2,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '主谓搭配不当',
        '主语残缺',
        '中途易辙'
      ],
      examPointNameList: [
        '主谓搭配不当',
        '主语残缺',
        '中途易辙'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '河南省濮阳市',
      deleted: false,
      parentTypeId: 38,
      parentTypeName: '选择题',
      originPaperName: null,
      examPaperTypeId: 10
    },
    {
      id: 156444,
      title: '<p>下面文段有三处推断存在问题，请参照①的方式。说明另外两处问题。</p><p><zmindent></zmindent>高考之后，我们将面临大学专业的选择问题，如果有机会，我们要选择工科方面的专业，因为只有学了工科才能激发强烈的好奇心，培养探索未知事物的兴趣，而有了浓厚的兴趣，必将取得好成绩，毕业后也就一定能很好地适应社会需要。</p><p>①不是只有学了工科才能激发好奇心。</p><p>②</p><p>③</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>不是有兴趣就一定能取得好成绩。</p>',
        '<p>不是成绩好就一定能很好地适应社会需要。</p>'
      ],
      analysis: '<p>本题题目是“下面文段有三处推断存在三处问题，请参照①的方式，说明另外两处问题”，文段中“有了浓厚的兴趣，必将取得好成绩”“毕业后也就一定能很好地适应社会需要”推断存在问题，由推断的条件，并不一定能得出所推断的结果。仿照①的方式——“不是只有学了工科才能激发好奇心”把理由表述出来即可。</p>',
      subjectId: 1,
      gradeId: 10,
      phaseId: 3,
      termId: 2,
      typeId: 3,
      questionType: '填空题',
      provinceId: 17,
      cityId: 74,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 2,
      distinction: 2,
      recommendationIndex: null,
      rating: 1,
      comprehensiveDegreeId: 2,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        115016
      ],
      examPointIdList: [
        15016
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 23,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513921319000,
      createdUser: 1002330390,
      updatedTime: 1522207576000,
      updatedUser: 768640,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '逻辑推断题'
      ],
      examPointNameList: [
        '逻辑推断题'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '山西省忻州市',
      deleted: false,
      parentTypeId: 39,
      parentTypeName: '填空题',
      originPaperName: null,
      examPaperTypeId: 7
    },
    {
      id: 75499,
      title: '<p>第二十四届世界哲学大会将于2018年由中国承办，这是中国首次获得世界哲学大会的承办权。哲学具有无限关怀和终极追问的特点，总揽一切，综括一般，仰观宇宙之无穷，俯究万物之运动。这段话表明（&nbsp; ）</p><p>①哲学的研究对象即自然、社会和人类思维发展的最一般本质和规律</p><p>②哲学从一般规律中概括和总结出各种特殊规律</p><p>③哲学是一门包罗万象、囊括万物的综合性科学</p><p>④哲学吧把整个世界以及人与世界的关系作为自己的研究对象<br/></p>',
      content: null,
      optionList: [
        '<p>①②</p>',
        '<p>①④</p>',
        '<p>②③</p>',
        '<p>③④</p>'
      ],
      answerList: [
        'B'
      ],
      analysis: '<p>哲学的内容</p><p>哲学以整个世界作为研究对象，揭示的是整个世界最一般的本质和最普遍的规律．</p><p>①符合题意，“哲学总揽一切，综括一般，仰观宇宙之无穷，俯究万物之运动”，这说明哲学的研究对象即自然、社会和人类思维发展的最一般本质和规律；</p><p>②说法错误，哲学是从各种特殊规律中概括和总结出一般规律；</p><p>③说法错误，哲学有正确与错误之分，哲学不一定都是科学的；</p><p>④符合题意，材料中“哲学总揽一切，综括一般”，这说明了哲学的研究对象是整个世界以及人与世界的关系；</p><p>故本题选B。<br/></p>',
      subjectId: 7,
      gradeId: 11,
      phaseId: 3,
      termId: 1,
      typeId: 1,
      questionType: '单选题',
      provinceId: 24,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 1,
      distinction: 2,
      recommendationIndex: null,
      rating: 5,
      comprehensiveDegreeId: 1,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        5896
      ],
      examPointIdList: [
        8078
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 25,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513177528000,
      createdUser: 1002318623,
      updatedTime: 1522150570000,
      updatedUser: 1002799684,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 2,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '世界观与哲学的关系'
      ],
      examPointNameList: [
        '哲学的内容'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '江苏省',
      deleted: false,
      parentTypeId: 38,
      parentTypeName: '选择题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 218007,
      title: '<p>下面是一位父亲给正在上高三的儿子的一封书信的节选，其中有三处用语不得体，请找出并加以修改</p><p>亲爱的儿子：</p><p><zmindent></zmindent>①你好！②距离高考只剩下四十天的时间了！③此时此刻，爸爸的心情和你一样难以平静。④十二年磨剑，即将见分晓。⑤你将走向人生的又一个重要赛场，预祝你马到成功！⑥在这里，一并奉上你妈妈的祝福。⑦我们相信，你一定能忝列北大新生的队伍中！⑧希望你好好配合老师，不耻下问。⑨当你金榜题名时，老师们会感到非常欣慰的！</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>⑥将“奉上”改为“送上”</p>',
        '<p>⑦将“忝列”改为“站在”</p>',
        '<p>将“不耻下问”改为“多多请教”</p>'
      ],
      analysis: '<p>本题考查学生语言表达得体能力。⑥将“奉上”改为“送上”。“奉上”为敬词，本文是父亲写给儿子的信，用敬词不符合语境。⑦将“忝列”改为“站在”。“忝列”是谦词，有愧于排列在其中。⑧将“不耻下问”改为“多多请教”。“不耻下问”意思是乐于向学问或地位比自己低的人学习，而不觉得不好意思。语境是配合老师，向老师请教，不能用“不耻下问”。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: 2,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 21,
      cityId: 116,
      countyId: null,
      schoolId: null,
      year: null,
      score: 6,
      sourceId: 2,
      difficulty: 2,
      distinction: 2,
      recommendationIndex: null,
      rating: 1,
      comprehensiveDegreeId: 2,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112671,
        112674
      ],
      examPointIdList: [
        12671,
        12674
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 1,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1514365650000,
      createdUser: 1002318624,
      updatedTime: 1522146495000,
      updatedUser: 768640,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '综合考点：语言综合表达',
        '修改应用文'
      ],
      examPointNameList: [
        '综合考点：语言综合表达',
        '修改应用文'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '湖北省武汉市',
      deleted: false,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: 10
    },
    {
      id: 184409,
      title: '<p>下列几种估测最符合实际情况的是( &nbsp;)</p>',
      content: null,
      optionList: [
        '<p>人步行的速度约为<zmlatex>5m/s</zmlatex></p>',
        '<p>全新的<zmlatex>2B</zmlatex>铅笔长约<zmlatex>20cm</zmlatex></p>',
        '<p>一个中学生的身高是<zmlatex>160 mm</zmlatex></p>',
        '<p>一张试卷厚度的大约<zmlatex>1mm</zmlatex></p>'
      ],
      answerList: [
        'B'
      ],
      analysis: '<p>A、人正常步行的速度在<zmlatex>4km/h=4{\\times}m/s{\\approx}1.1m/s</zmlatex>左右．此选项不符合实际；</p><p>B、中学生伸开手掌，大拇指指尖到中指指尖的距离大约<zmlatex>20cm</zmlatex>，新铅笔的长度与此差不多，在<zmlatex>20cm</zmlatex>左右．此选项符合实际；</p><p>C、成年人的身高在<zmlatex>170cm</zmlatex>左右，中学生的身高接近成年人，在<zmlatex>160cm=1600mm</zmlatex>左右，此选项不符合实际；</p><p>D、一般纸张的厚度在<zmlatex>75μm=0.075mm</zmlatex>左右，试卷纸的厚度与此差不多，不可能为<zmlatex>1mm</zmlatex>，此选项不符合实际。</p>',
      subjectId: 4,
      gradeId: 8,
      phaseId: 2,
      termId: 1,
      typeId: 1,
      questionType: '单选题',
      provinceId: 20,
      cityId: 100,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 1,
      distinction: 1,
      recommendationIndex: null,
      rating: 1,
      comprehensiveDegreeId: 1,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        1545,
        12320
      ],
      examPointIdList: [
        14423,
        15648
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 15,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1514037459000,
      createdUser: 1002318612,
      updatedTime: 1522130683000,
      updatedUser: 1002760346,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 2,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '速度的公式和单位',
        '长度的估测'
      ],
      examPointNameList: [
        '常见物体的速度',
        '长度的估测'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '河南省洛阳市',
      deleted: false,
      parentTypeId: 38,
      parentTypeName: '选择题',
      originPaperName: null,
      examPaperTypeId: 6
    },
    {
      id: 156507,
      title: '<p><zmindent></zmindent>假定英语课上老师要求同桌之间交换修改作文，请你修改你同桌写的以下作文。作文中共有10处语言错误，每句中最多有两处。每处错误仅涉及一个单词的增加、删除或修改。</p><p>增加：在缺词处加一个漏字符号（∧）并在其下面写出该加的词。</p><p>删除:把多余的词用斜线（\\）划掉。</p><p>修改：在错的词下划一横线，并在该词下面写出修改后的词。</p><p>注意：1.每处错误及其修改均仅限一词；</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.只允许修改10处，多者（从第11处起）不计分。　&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<zmindent></zmindent><br/></p><p><zmindent></zmindent>Recently, if browsing a high school website of Australia, I saw the message you post on it. It get to know that you intend to travel to Xi’an during the summer vacation with a Chinese student as you guide.</p><p><zmindent></zmindent>Learning this news, I am really willing to travel with you and introducing Xi’an to you. I know as a excellent guide I should make your journey interesting and meaningless. I will keep you company visiting numerous places of interests and enjoying the wonderful scenery. However, I am going to tell you the long but rich history of Xi’an.</p><p><zmindent></zmindent>Hope you reply me soon.</p><p><br/></p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>第一句中的if改为while/when 或if去掉</p>',
        '<p>第一句中的post改为posted</p>',
        '<p>第二句中的you改为your</p>',
        '<p>第三句中的introducing改为introduce</p>',
        '<p>第三句中的a改为an</p>',
        '<p>第四句中的meaningless 改为meaningful</p>',
        '<p>第五句中的interest改为interest</p>',
        '<p>第五句中的However改为Besides/Additionally</p>',
        '<p>第五句中的but改为and</p>',
        '<p>第六句中的reply后加to</p>'
      ],
      analysis: '<p>1.去掉句意: 最近，当我在浏览一所澳大和阻的高中学校网站时，我发现了你发在上面的信息。连词错误.句中browse与主语I构成主谓关系，可以用现在分词作时间状语; 也可以用连词连接时间省略的时间状语从句。故If→while/when 或if 去掉。</p><p>2.post-posted时态错误.句意表达的是过去的动作，要用一般过去时态。故post→posted。</p><p>3.you-your考察代词.句中your修饰名guide,要用形容词性物主代词。故you→your。</p><p>4.动词错误.句中introduce和travel 并列作be willing to 的宾语，要用动词原型。故introducing→introduce。</p><p>5.考察冠词.句中excellent是以元音开头的单，要用an来限定。</p><p>6.句意表达的是肯定（有趣且有意义）；meaningless表示无意义的，不符合句意meaningless→meaningful。</p><p>7.考察短语搭配.places of interest风景名胜。故interest→interest。</p><p>8.句意: 而且我准备告诉你漫长且丰富的西安历史。句意表达的是递进，且句中有逗号分隔，要用表示递进关系的副词。故However→Besides/Additionally。</p><p>9.句意long和rich表达的是承接，不是转折。故but→and。</p><p>10.reply后加to 短语搭配错误.reply to sb. 回复某人，常用短语。故reply后加to。<br/></p>',
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: 2,
      typeId: 21,
      questionType: '短文改错',
      provinceId: 25,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: null,
      score: 10,
      sourceId: 2,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112241,
        112242,
        112243
      ],
      examPointIdList: [
        12241,
        12242,
        12243
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513921386000,
      createdUser: 476735,
      updatedTime: 1522054485000,
      updatedUser: 783030,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '错词——涉及动词最多',
        '多词——主要是介词',
        '少词——主要是介词或冠词'
      ],
      examPointNameList: [
        '错词——涉及动词最多',
        '多词——主要是介词',
        '少词——主要是介词或冠词'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '江西省',
      deleted: false,
      parentTypeId: 45,
      parentTypeName: '变形改错题',
      originPaperName: null,
      examPaperTypeId: 10
    },
    {
      id: 157763,
      title: '<p>假定你是李华，你接受了一项写作任务，要为英语校报写一篇人物介绍。请你根据以下信息，向编辑介绍一位伟大的人物。</p><table><tbody><tr class="firstRow"><td><p>姓名:Mark Twain</p><p>出生日期：1835年11月30日</p><p>职业：作家</p><p>生平：出生于美国乡村。11岁时父亲去世。年轻时做过工人、记者等。一生中出版过许多小说。1910年4月21日因病逝世。</p><p>性格特征：聪明，幽默。</p></td></tr></tbody></table><p>参考词汇：出版publish幽默的humorous<br/></p><p>注意：</p><p>1.词数100左右；</p><p>2.可以适当增加细节，以使行文连贯；</p><p>3.开头和结尾已为你写好，不计入总词数。</p><p>Dear editor.</p><p>I’d like to introduce a great man to you.</p><p>____________________________________________________________________________________________________________________________________________________________________________________________</p><p style="text-align: right;">Yours faithfully,</p><p style="text-align: right;">Li Hua</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>Dear editor,</p><p><zmindent contenteditable="false">空类0</zmindent>I’d like to introduce a great man to you.</p><p><zmindent contenteditable="false">空类0</zmindent>Mark Twain, an American man, was born in a poor family in the countryside on November 30, 1835. He is known to the world as a great writer. Unluckily, his father died when he was 11 years old. However, he was always positive toward life. As a young man, he did different jobs, such as a worker and a reporter. He was fond of writing all the time. As a result, many novels were published in his life. He devoted himself to writing and died of an illness on April 21, 1910.</p><p><zmindent contenteditable="false">空类0</zmindent>Mark Twain who is a clever and humorous master will be remembered by the world forever.</p><p style="text-align: right;">Yours faithfully,</p><p style="text-align: right;">Li Hua</p>'
      ],
      analysis: '<p>略</p>',
      subjectId: 3,
      gradeId: 10,
      phaseId: 3,
      termId: 2,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 17,
      cityId: 72,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 4,
      distinction: 3,
      recommendationIndex: null,
      rating: 5,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112280,
        112291,
        112298
      ],
      examPointIdList: [
        12280,
        12291,
        12298
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513925318000,
      createdUser: 1001794935,
      updatedTime: 1521884169000,
      updatedUser: 1003686919,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '解决方法题型  ',
        '说明文概要写作',
        '应用文'
      ],
      examPointNameList: [
        '解决方法题型  ',
        '说明文概要写作',
        '应用文'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '山西省晋中市',
      deleted: false,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: 6
    },
    {
      id: 79746,
      title: '<p><zmindent>zmindent</zmindent>假设你是某校九年级（1）班的学生，你校英文俱乐部正在举行“YoungStat Award”的评选活动，请你用英语写一篇短文，介绍你的同学李明，以供参评。内容要点如下：</p><p>1.高个，擅长篮球，成绩优秀；</p><p>2.乐于助人，积极参加活动，热衷<img width="2" height="2" src="http://tr.zmlearn.com/ueditor/themes/default/images/spacer.gif" word_img="file:///C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\ksohtml\\wpsEEBD.tmp.jpg" style="background:url(http://tr.zmlearn.com/ueditor/themes/default/images/word.gif) no-repeat center center;border:1px solid #ddd"/>慈善；</p><p>3.去年，他……；</p><p>4.已筹集一千多元，准备寄给贫困地区学生；</p><p>5.得到高度赞扬，我们以他为荣。</p><p>注意事项：</p><p>1.短文须包括所有内容要点，要求语句通顺、意思连贯；</p><p>2.第3要点的内容须围绕主题，用2-3句话展开合理想象，作适当发挥；</p><p>3.词数在90个左右，短文的开头已在答题卡上给出，不计入总词数；</p><p>4.短文内容必须写在答题卡指定的位置上。</p><p>参考词汇：慈善（charity）</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>Young Star Award</p><p>&nbsp; &nbsp; &nbsp; &nbsp;My classmate Liming is very tall, and he is good at football. He is one of the top students in my class. Liming is very helpful, and he often takes an active part in different activities, especially in charities.</p><p><zmindent>ndent</zmindent>Last year, he held a charity programme for children in poor areas. Since last year, he has raised more than 1,000 yuan. Now he gets ready to send the money to the children in poor areas.</p><p>&nbsp; &nbsp; &nbsp; &nbsp;His action has won high praise from our school. He is our pride.</p>'
      ],
      analysis: '<p>此类作文考查学生的基本习作能力，总体难度属于中等。考查点都属于中考的重点难点语法知识和一些固定句型及表达。考查点主要集中在七年级下册和八年级下册和九年级上册。</p><p>1.个子高，描述外貌特征；擅长篮球，成绩优异，内在品质特征。</p><p>2. 乐于助人，积极参与活动，热衷慈善；属于学生性格，行为活动。</p><p>3. 去年，他。。。考查学生对一般过去时态的表达考查，对发生在过去行为的一个复述。</p><p>4. 已筹集一千多元，准备寄给贫困山区学生，考查现在完成时的用法，描述过去发生的动作状态对现在的影响。</p><p>5. 得到高度赞扬，我们以他为荣，考查固定句型的用法，难度中等。</p><p>考生在完成此类作文时，要注意人称；时态如一般过去时和现在完成时等；语态即主动语态和被动语态的问题。</p><p>一篇将9A第一单元的人物描写和9B第一单元的重点短语相结合，考查学生对课文的熟练掌握度。</p>',
      subjectId: 3,
      gradeId: 9,
      phaseId: 2,
      termId: 2,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 24,
      cityId: 166,
      countyId: null,
      schoolId: null,
      year: null,
      score: 10,
      sourceId: 2,
      difficulty: 4,
      distinction: 3,
      recommendationIndex: null,
      rating: 5,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        103576
      ],
      examPointIdList: [
        3576
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513241127000,
      createdUser: 1002318612,
      updatedTime: 1521790112000,
      updatedUser: 1003686779,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '话题作文'
      ],
      examPointNameList: [
        '话题作文'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '江苏省无锡市',
      deleted: false,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: 14
    },
    {
      id: 105528,
      title: '<p>假定英语课上老师要求同桌之间交换修改作文，请你修改你同桌写的以下作文。文中共有<zmlatex>10</zmlatex>处语言错误，每句最多有两处。每处错误仅涉及一个单词的增加、删除或修改。</p><p>增加：在缺词处加一个漏字符号（∧），并在其下面写出该加的词。</p><p>删除：把多余的词用（＼）划掉。</p><p>修改：在错的词下划一横线，并在该词下面写出修改后的词。</p><p>注意：⒈每处错误及其修改均仅限一词。</p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ⒉只允许修改<zmlatex>10</zmlatex>处，多者（从第<zmlatex>11</zmlatex>处起）不计分。</p><p><zmindent></zmindent>When I was young, I didn’t get along well with my classmates,that made me lonely. Therefore, Lucy was an exception, who was outgoing and enthusiastic. Without doubt all of them liked her very much.</p><p><zmindent></zmindent>One day, I was about to search my math book while I found it was gone. I was very worry. At last, it was under the help of Lucy that my math book was found. As the time went by, a deep friendship was formed between us.Lucy always encourages me to practice oral English, which she thought was vital for me. I learned from her that whatever difficulty we have in our study or life, we should never giving up.</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>第一句中that改为which</p>',
        '<p>第二句中Therefore改为However</p>',
        '<p>第三句中them改为us</p>',
        '<p>第四句中search后加for</p>',
        '<p>第四句中while改为when</p>',
        '<p>第四句中worry改为worried</p>',
        '<p>第五句中under改为with</p>',
        '<p>第六句中去掉time前的the</p>',
        '<p>第七句中encourages改为encouraged</p>',
        '<p>第八句中giving改为give</p>'
      ],
      analysis: '<p>⒈考查定语从句。“whichmade me lonely”是非限制性定语从句，which指代整个主句的意思，从句中作主语，that不能引导非限制性定语从句。故将that改为which。</p><p>⒉考查副词。上文讲述“我与同学相处不好”，下文讲述“Lucy是个例外”，因此上下文是转折关系，有逗号与主句分开，用however。故将Therefore改为However。</p><p>⒊考查代词。根据语境可知，句意为：毫无疑问，我们大家都非常喜欢她。作宾语用人称代词的宾格。故将them改为us。</p><p>⒋考查介词。句意：一天，我正打算寻找我的数学课本这时候发现书不见了。search“在 (某地) 搜寻; 搜查 (某地)”，search for“寻找……”。根据语境，search后加for。</p><p>⒌考查连词。beabout to do…when…“正打算做某事，这（那）时候……”是固定句型，when是并列连词，意思是：在那时（在这时）。根据语境，故将while改为when。</p><p>⒍考查形容词。worry是动词，意思是“使担心”，was接形容词构成系表结构，worried“担心的”表示主语的感受。故将worry改为worried。</p><p>⒎考查介词。withthe help of…“在……帮助下”是常用短语。故将under改为with。</p><p>⒏查冠词。句意：随着时间的推移，我们之间产生了深深的友谊。time“时间”是不可数名词，此处表示泛指。故去掉time前的the。</p><p>⒐考查动词。根据上下文语境可知，文章讲述过去发生的事情，用一般过去时。故将encourages改为encouraged。</p><p>⒑考查动词。句意：从她身上我学会了无论我们在学习和生活中有什么困难，我绝不应当放弃。should是情态动词，后接动词原形，故将giving改为give。</p>',
      subjectId: 3,
      gradeId: 11,
      phaseId: 3,
      termId: 2,
      typeId: 21,
      questionType: '短文改错',
      provinceId: 17,
      cityId: 73,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 3,
      distinction: 3,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112241,
        112242,
        112243
      ],
      examPointIdList: [
        12241,
        12242,
        12243
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513601703000,
      createdUser: 476735,
      updatedTime: 1521686364000,
      updatedUser: 783030,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '错词——涉及动词最多',
        '多词——主要是介词',
        '少词——主要是介词或冠词'
      ],
      examPointNameList: [
        '错词——涉及动词最多',
        '多词——主要是介词',
        '少词——主要是介词或冠词'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '山西省运城市',
      deleted: false,
      parentTypeId: 45,
      parentTypeName: '变形改错题',
      originPaperName: null,
      examPaperTypeId: 7
    },
    {
      id: 160268,
      title: '<p>假设你是李华，两周前你从网上订购了一套英语书虫系列读物（Bookworm Series），昨天才收到货，且包装破损、数量不足。请就此向网点客服写邮件投诉。要点如下：</p><p>1．介绍购物情况；</p><p>2．反映存在问题；</p><p>3．提出解决方案。</p><p>注意：1．词数100左右；</p><p>2．可以适当增加细节，以使行文连贯；</p><p>3．开头语已为你写好，不计入总次数。</p><p>To whom it may concern,</p><p>____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________</p><p zmalign="right">Li Hua</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>To whom it may concern,</p><p><zmindent></zmindent>I’m one of your customers. I ordered a set of Bookworm Series on your website two weeks ago, but I didn’t receive them until yesterday. And much to my disappointment, the books were so poorly packed up that the cover of one book was torn. To make matters worse, it is not a complete set, as I found one book missing.</p><p><zmindent></zmindent>I’m sorry to have received such poor service, and I believe I have every right to ask you to deal with this problem. I hope that you either return my money or deliver a new set of books to me. Besides, I’d like to be informed of the process of your dealing with my complaint.</p><p><zmindent></zmindent>Looking forward to your reply.</p><p zmalign="right">Li Hua</p>'
      ],
      analysis: '<p>略</p>',
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: 2,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 17,
      cityId: 75,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 3,
      distinction: 3,
      recommendationIndex: null,
      rating: 3,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112280,
        112285,
        112298
      ],
      examPointIdList: [
        12280,
        12285,
        12298
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513930849000,
      createdUser: 476735,
      updatedTime: 1521533156000,
      updatedUser: 783030,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '解决方法题型  ',
        '提供建议型',
        '应用文'
      ],
      examPointNameList: [
        '解决方法题型  ',
        '提供建议型',
        '应用文'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '山西省临汾市',
      deleted: false,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: 10
    },
    {
      id: 172855,
      title: '<p>下列各句中画横线的成语的使用，全部正确的一项是（ ）</p><p>①作为历史上的重大事件，几乎所有史书都对此事件<ins>语焉不详</ins>，一笔带过，专家推测可能是当时统治者钳制思想的结果。</p><p>②为了理想，我们高三学子面对高考压力迎难而上，而老师和家长们<ins>具体而微</ins>的关怀，更使我们斗志昂扬，信心百倍。</p><p>③历史专业毕业的张明，不愿意像其他同学那样<ins>皓首穷经</ins>，著书立说，而是选择了与自己专业相去甚远的工作，实在让人匪夷所思。</p><p>④他似乎有一种超常的直觉，能够捕捉到事物美丽的瞬间，在这个<ins>稍纵即逝</ins>的瞬间，他书写生命的绽放，也由此体会生命的快意。</p><p>⑤随着经济的迅速发展，各种社会问题也<ins>络绎不绝</ins>，GDP上升的同时，污染严重、百姓素质不高等社会问题日益凸显。</p><p>⑥历史学家黄仁宇爱读古书，他的《万历十五年》在叙事之中论古讽今，注重历史学著作的社会效益和<ins>经世致用</ins>。</p>',
      content: null,
      optionList: [
        '<p>①③⑥</p>',
        '<p>②③⑤</p>',
        '<p>②④⑥</p>',
        '<p>①②⑤</p>'
      ],
      answerList: [
        'A'
      ],
      analysis: '<p>本题考查词语成语的运用。题中，①语焉不详：说到了，但说得不详细，不清楚。使用正确。②具体而微：内容大体具备而形状或规模小。望文生义，应改为“无微不至”。③皓首穷经：一直到年老头白之时还在深入钻研经书和古籍，使用正确。④稍纵即逝：形容时间或机会等很容易过去。使用正确。⑤络绎不绝：形容行人、车马、船只等来往频繁，连续不断。不能用来修饰“各种社会问题”。 ⑥经世致用：指学问必须有益于国事。使用正确。对于成语题，第一要辨析词义，包括词语的语义侧重点、词语的词义轻重、词义范围的大小等。第二，辨析色彩。包括词语的感情色彩跟 语体色彩。第三，辨析用法。包括搭配习惯、语法功能 、使用对象等方面。解答成语题，第一、逐字解释成语，运用成语结构特点把握成语大意，但要注意不能望文生义；第二 、注意成语潜在的感情色彩和语体色彩；第三 、要注意成语使用范围，搭配的对象；第四、弄清所用成语的前后 语境，尽可能找出句中相关联的信息。第五、从修饰与被修饰关系上分析，看修饰成分跟中心词 之间是否存在前后语义矛盾或者前后语义重复的现象 。</p>',
      subjectId: 1,
      gradeId: 12,
      phaseId: 3,
      termId: 2,
      typeId: 1,
      questionType: '单选题',
      provinceId: 21,
      cityId: 116,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 2,
      distinction: 2,
      recommendationIndex: null,
      rating: 1,
      comprehensiveDegreeId: 2,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112556
      ],
      examPointIdList: [
        12556
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513998787000,
      createdUser: 1002508641,
      updatedTime: 1520912907000,
      updatedUser: 1002589917,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 2,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '望文生义'
      ],
      examPointNameList: [
        '望文生义'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '湖北省武汉市',
      deleted: false,
      parentTypeId: 38,
      parentTypeName: '选择题',
      originPaperName: null,
      examPaperTypeId: 10
    },
    {
      id: 84535,
      title: '<p>假如你是高二学生名叫王海。最近你发现班上部分同学每次遇到重要考试都会出现焦虑症状。请你用英语写一封信给某英文报编辑反映这个问题。信的内容包括：1 焦虑症状 2建议（至少三点）</p><p>注意：1根据以上内容写一篇短文，不要逐字翻译</p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2可适当增加细节使行文连贯</p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3词数100左右 ，开头已给出，不计入总数</p><p>参考词汇：头晕 dizzy &nbsp;&nbsp;&nbsp;食欲不振：lose one’s appetite &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p><p><zmindent></zmindent>Dear editor,</p><p><zmindent></zmindent>I’m Wang hai, a student of Grade 2 in senior high school. I ‘m writing to tell you some symptoms of anxiety among us students before exams.</p><p><br/></p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>Dear editor,</p><p><zmindent contenteditable="false">空类0</zmindent>&nbsp;I’m Wang hai, a student of Grade 2 in senior high school. I &#39;m writing to tell you some symptoms of anxiety among us students before exams.</p><p><zmindent contenteditable="false">空类0</zmindent>Most of us feel nervous whenever we&#39;re taking an important exam. Some will feel dizzy or tired, some will suffer from lack of sleep and some will lose their appetite. In fact, all those symptoms have terrible effects on our exam and we are all eager to get rid of them.</p><p><zmindent contenteditable="false">空类0</zmindent>First of all, in my opinion, it&#39;s important for us to have a right attitude towards exams. They are only a means of checking how we are getting along with our studies. Study hard every day and make careful plans for every exam. In this way we can avoid suffering from the pressure of exams. Besides, enough sleep can make us energetic and enable us to perform well in an exam. Therefore, during the period of exam, we should not stay up too late. We can also try a warm bath or a cup of warm milk before going to bed. They might help us to have a sound sleep.</p><p><br/></p>'
      ],
      analysis: '<p>文章要求向英文报编辑写一封同学每次遇到重要考试都会出现焦虑症状的反映信，信里需要包括焦虑症状和建议，文章中建议有高级词汇和句式，同时要控制字数在100字左右，参考词汇要用上。</p>',
      subjectId: 3,
      gradeId: 11,
      phaseId: 3,
      termId: 1,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 37,
      cityId: 336,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 5,
      distinction: 3,
      recommendationIndex: null,
      rating: 5,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112285,
        112286,
        112298
      ],
      examPointIdList: [
        12285,
        12286,
        12298
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 1,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513310992000,
      createdUser: 476735,
      updatedTime: 1522056487000,
      updatedUser: 783030,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '提供建议型',
        '释疑解惑型',
        '应用文'
      ],
      examPointNameList: [
        '提供建议型',
        '释疑解惑型',
        '应用文'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '安徽省蚌埠市',
      deleted: null,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: 6
    },
    {
      id: 143539,
      title: '<p>为了配合＂足球进校园＂活动，你们班开展了一次主题班会，请你以足球迷的身份，根据下列表格中的要点提示，用英语向同学们介绍足球这项运动并谈谈自己的梦想。</p><p><br/></p><p>常 识：历史悠久，深受喜爱，世界杯4年举行一次</p><p>好 处：男生女生皆可参加，利于培养团队精神，考生自拟（至少1点）</p><p>偶 像：梅西，有足球天赋</p><p>梦 想：考生自拟（至少1点）</p><p>注意：（1）词数80左右，短文的开头已为你写好，不计入总词数；<br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（2）短文须包括所有要点，不要逐词翻译，可适当发挥，使短文连贯、通顺；</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（3）文中不得出现真实的人名、校名、地名等相关信息。</p><p>参考词汇：梅西 Messi（阿根廷著名足球运动员）</p><p>Dear classmates,</p><p><zmindent></zmindent>I’m very excited to hear that China will build 20,000 football-themed schools by 2020._________________________________________________</p><p>_______________________________________________________</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>Dear classmates,</p><p><zmindent></zmindent>I&#39;m very exated to hear that China will build 20,000 football-themed schools by 2020. Football has a very long history It is liked by people all over the world The World Cup takes place every four years Playing football has lots of advantages First both boys and girls can take part in it Second, it helps develop team spirit. What&#39;s more, playing football is good for our health.</p><p><zmindent></zmindent>I&#39;m a football fan. Messi is my hero. He has a gift far playing football My dream is to become a famous faotball player like Messi. I hope China will hold the World Cup someday.</p><p><zmindent></zmindent>Thank you for your attention.</p><p><zmindent></zmindent><br/></p>'
      ],
      analysis: '<p>略</p>',
      subjectId: 3,
      gradeId: 9,
      phaseId: 2,
      termId: 2,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 19,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 5,
      distinction: 3,
      recommendationIndex: null,
      rating: 5,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        103572,
        103576
      ],
      examPointIdList: [
        3572,
        3576
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513839529000,
      createdUser: 1001373185,
      updatedTime: 1521021571000,
      updatedUser: 1001765256,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '书信',
        '话题作文'
      ],
      examPointNameList: [
        '书信',
        '话题作文'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '河北省',
      deleted: null,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: 13
    },
    {
      id: 241321,
      title: '<p>假如你是李华,要参加你校举办的以&quot;Better English, Better Life&quot;为主题的英语演讲比赛。请根据以下提示写一篇演讲稿讲述学英语的益处。</p><p>1.在生活上的好处;</p><p>2.在学业上的好处;</p><p>3.在就业上的好处。</p><p>注意:1.词数80左右;</p><p>2.可适当增加细节,以使行文连贯。</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p style="text-align: justify;">Hello, everyone!</p><p style="text-align: justify;"><zmindent contenteditable="false">空类0</zmindent>I am here to show that the better English, the better life.</p><p style="text-align: justify;"><zmindent contenteditable="false">空类0</zmindent>Initially, English can enrich our lives and broaden our horizons. Having a better command of English can contribute to our reading original works. Besides, better English can improve our academic level, which increases the potential of our being admitted to a key university. Finally, international companies prefer the staff with better English. To put it differently, the more fluently you speak English, the more doors will open up to you.</p><p style="text-align: justify;"><zmindent contenteditable="false">空类0</zmindent>Let’s better ourselves and polish our life through better English!</p><p style="text-align: justify;">&nbsp; &nbsp; &nbsp; That’s all. Thank you!</p>'
      ],
      analysis: '<p style="text-align: justify;">演讲稿是介绍性说明文,语言一定要准确简洁、通俗易懂、逻辑性强、结构多变、节奏感强。演讲稿由开头语、正文和结束语三部分组成。开头语一般来说比较简单,目的就是吸引听众或读者的注意力。考生在写作时首先要审清楚题目,题目已经要求内容包括三点,因此重点是将所要表达的语言点都表达到位,不要遗漏了某一点。同时应尽量选择自己最熟悉的单词、句型来表达自己的意思。在写作过程中注意使用起承转合的连词和高级词汇,这样作文就能得到比较高的分数。</p>',
      subjectId: 3,
      gradeId: 12,
      phaseId: 3,
      termId: 2,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 38,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112281,
        112287,
        112298
      ],
      examPointIdList: [
        12281,
        12287,
        12298
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1514691947000,
      createdUser: 1002318605,
      updatedTime: 1522048068000,
      updatedUser: 783030,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '说明利弊题型',
        '主题演讲型',
        '应用文'
      ],
      examPointNameList: [
        '说明利弊题型',
        '主题演讲型',
        '应用文'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '浙江省',
      deleted: null,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: 10
    },
    {
      id: 134900,
      title: '<p>根据提示写一个便条。你(Ann）去找Lucy还书，但是Lucy不在家，所以把它留给莉莉。周六晚上开英语晚会，如果能来，请电话告知。（约30词）</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>Dear Lucy,</p><p><zmindent>zmindent</zmindent>I returned your book today but you weren’t at home.I gave your book to Lucy.Let her give it to you.There will be an English party.If you can come,please call me.</p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Yours,</p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Ann</p>'
      ],
      analysis: '<p>本文要求写一张便条。便条是一种简单形式的书信。其特点是格式简单，内容简短，便条上一般只需要一两句话。因此，便条要求做到：内容简明扼要，文字简洁明了，讲清谁写的，写给谁，什么事以及什么时候写的等。要把提示内容写清写全。</p>',
      subjectId: 3,
      gradeId: 9,
      phaseId: 2,
      termId: 2,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 15,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: null,
      score: 20,
      sourceId: 2,
      difficulty: 4,
      distinction: 3,
      recommendationIndex: null,
      rating: 5,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        103571
      ],
      examPointIdList: [
        3571
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513780223000,
      createdUser: 1001373185,
      updatedTime: 1521530381000,
      updatedUser: 1001765256,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '通知'
      ],
      examPointNameList: [
        '通知'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '辽宁省',
      deleted: null,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: 13
    },
    {
      id: 169742,
      title: '<p>下列句子中划横线成语的使用，正确的一项是</p>',
      content: null,
      optionList: [
        '<p>黄山石形状各异，有的像莲花，有的像孔雀开屏，也有的像鱼，像蛇，像兔，我们一路欣赏，一路惊叹，惊叹它的奇异绝伦，惊叹它的<ins>巧夺天工</ins>。</p>',
        '<p>那古色斑斓的青铜器，那琳琅满目的汉代工艺品，那<ins>笔走龙蛇</ins>的晋代书法，无一不是我国灿烂文化的直接展示。</p>',
        '<p>高考越考越细,为迎合高考,一部分教师也越教越碎,其后果是肢解一篇完整的美文。长此以往,学生自然<ins>目无全牛</ins>。</p>',
        '<p>美国政府在台湾问题上的<ins>危言危行</ins>，势必受到全世界人民的唾弃。</p>'
      ],
      answerList: [
        'B'
      ],
      analysis: '<p>本题考查成语意思和用法的辨析。首先把握成语的意思，然后结合语境辨析正误。B项，“笔走龙蛇”，形容书法生动而有气势。句中形容晋代书法，使用正确。A项，“巧夺天工”，人工的精巧胜过天然。形容技艺十分巧妙。句中所说的“黄山石”本就是天然的，对象不当。C项，“目无全牛”，形容人的技艺高超，得心应手，已经到达非常纯熟的地步。句中望文生义。D项，“危言危行”，说正直之言，行正直之事。句中误把“危”理解成“危险”，望文生义。对于词语题，第一要辨析词义，包括词语的语义侧重点、词语的词义轻重、词义范围的大小等。切忌望文生义，比如“目无全牛”，句中误把该成语理解成支离破碎；“危言危行”，句中误把该成语理解成“危险的话和危险的事”。第二，辨析感青。第三，辨析用法。包括搭配习惯、语法功能、使用对象等方面。比如“巧夺天工”就属于对象不当。解答词语题李第一、逐字解释词语，把握大意；第二、注意词语潜在的感青色彩和语体色彩；第三、要注意词语使用范围，搭配的对象；第四、弄清所用词语的前后语境，尽可能找出句中相关联的信息；第五、从修饰与被修饰关系上分析，看修饰成分跟中心词之间是否存在前后语义矛盾或者前后语义重复的现象。</p>',
      subjectId: 1,
      gradeId: 10,
      phaseId: 3,
      termId: 2,
      typeId: 1,
      questionType: '单选题',
      provinceId: 30,
      cityId: 261,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 1,
      distinction: 2,
      recommendationIndex: null,
      rating: 1,
      comprehensiveDegreeId: 2,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112556,
        112557
      ],
      examPointIdList: [
        12556,
        12557
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513955081000,
      createdUser: 1002598102,
      updatedTime: 1522122767000,
      updatedUser: 768640,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 2,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '望文生义',
        '对象误用'
      ],
      examPointNameList: [
        '望文生义',
        '对象误用'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '四川省宜宾市',
      deleted: null,
      parentTypeId: 38,
      parentTypeName: '选择题',
      originPaperName: null,
      examPaperTypeId: 6
    },
    {
      id: 246707,
      title: '<p>假如你是Linda，在美国学习英语。你的朋友Lin Tao 在学习英语过程中遇到一些困难，向你求助，请给他写封信，介绍一下你学习英语的方法,并鼓励他不要放弃。要求80词左右。</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>My friend Lin Tao,</p><p><zmindent>zmindent</zmindent>I am glade to hear from you! In your letter, you said that you had had some trouble in learning English! But you can&#39;t give it up! To learn English is not difficult as you thought.I have some suggestions which may help you learn English!</p><p><zmindent>zmindent</zmindent>First , you should believe yourself you can learn English well! You can make it!</p><p><zmindent>zmindent</zmindent>Second, you read English materials, like newspapers, English books and so on !</p><p><zmindent>zmindent</zmindent>Third, you should learn English everyday!</p><p><zmindent>zmindent</zmindent>It is easy to learn English! I like English!</p><p><zmindent>zmindent</zmindent>I hope you can learn it better!</p><p><zmindent contenteditable="false">空类0</zmindent>Best wishes to you!</p><p><zmindent>zmi</zmindent></p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Yours</p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Linda!</p>'
      ],
      analysis: '<p>考生首先要认真阅读前面的提示，认真审题，根据提示，确定文章的中心。注意人称和时态。尽量使用熟悉句型，使用简单句式，同时应选用合适的连接词或过渡词，使文章具有一定的连贯性。</p>',
      subjectId: 3,
      gradeId: 8,
      phaseId: 2,
      termId: 2,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 16,
      cityId: 58,
      countyId: null,
      schoolId: null,
      year: null,
      score: 10,
      sourceId: 2,
      difficulty: 4,
      distinction: 3,
      recommendationIndex: null,
      rating: 5,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        103572
      ],
      examPointIdList: [
        3572
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 0,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1514809533000,
      createdUser: 1002330373,
      updatedTime: 1522128678000,
      updatedUser: 1003686919,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '书信'
      ],
      examPointNameList: [
        '书信'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '山东省威海市',
      deleted: null,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: 6
    },
    {
      id: 122912,
      title: '<p>假定英语课上老师要求同桌之间交换修改作文，请你修改你同桌写的以下作文，文中共有10处语言错误，每句中最多有两处，每处错误仅涉及一个单词的增加、删除或修改。</p><p>增加：在缺词处加一个漏字符号（∧），并在其下面写出该加的词。</p><p>删除：把多余的词用斜线（\\）划掉。</p><p>修改：在错的词下划一横线，并在该词下面写出修改后的词。</p><p>注意：1. 每处错误及其修改均仅限一词；</p><p>2. 只允许修改10处，多者（从第11处起）不计分。<br/><zmindent></zmindent></p><p><zmindent></zmindent>It is three years now since I graduate from Xinhua High School. Last Sunday, the class that I was on held a get﹣together, which took us a long time prepare. It was indeed not easy to get in touch with everybody and set a properly time for all of us. We all enjoyed a precious day greatly, remember the time we spent together. It reminded us of the interesting stories and the people they were familiar with. It was a pity which some of us were not present as they had gone to abroad for further studies, but they called back or sent greeting card from different palaces.</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p>It is three years now since I graduate from Xinhua High School．中graduate改成graduated</p>',
        '<p>the class that I was on held a get﹣together，中on改为in</p>',
        '<p>which took us a long time prepare,中time后加to</p>',
        '<p>It was indeed not easy to get in touch with everybody and set a properly time for all of us．中properly改为proper</p>',
        '<p>We all enjoyed a precious day greatly，中a改为the</p>',
        '<p>remember the time we spent together,中remember改为remembering</p>',
        '<p>It reminded us of the interesting stories and the people they were familiar with．中they改为we</p>',
        '<p>It was a pity which some of us were not present as they had gone to abroad for further studies，中which改为that</p>',
        '<p>It was a pity which some of us were not present as they had gone to abroad for further studies，中删除abroad前的to</p>',
        '<p>but they called back or sent greeting card from different palaces．card改为cards．考查名词复数．根据句意可知一些同学们从不同地方寄来贺卡，所以应该用复数．</p>'
      ],
      analysis: '<p>改成graduated． 考查动词时态．在since引导的时间状语从句中应该用动词的过去式，把graduate改为graduated．</p><p>改为in．考查介词．从句意可知此处指作者所在的班级，介词用in．</p><p>后加to．考查动词．固定句型：it takes sb some time to do sth&quot;做某事花费某人多长时间&quot;，故在prepare前加to．</p><p>改为proper．考查形容词．此处是修饰名词应该用形容词，把properly改为proper．</p><p>改为remembering．考查非谓语动词． 从结构可知此处是非谓语短语做状语，和句子主语之间是主动关系，应该用现在分词，故把remember改为remembering．</p><p>改为we．考查代词．由上文内容可知此处指&quot;我们&quot;同学们一起玩的很开心，把they改为we．<br/></p><p>改为that．考查代词．固定句型：it is a pity that…..&quot;很遗憾&quot;，故把which改为that．</p><p>删除abroad前的to．考查介词．Abroad是副词，前面不需介词．固定短语：go abroad&quot;去国外&quot;，把to去掉．</p><p>改为cards．考查名词复数．根据句意可知一些同学们从不同地方寄来贺卡，所以应该用复数．</p>',
      subjectId: 3,
      gradeId: 10,
      phaseId: 3,
      termId: 2,
      typeId: 21,
      questionType: '短文改错',
      provinceId: 36,
      cityId: 319,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 3,
      distinction: 2,
      recommendationIndex: null,
      rating: 2,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        112241,
        112242,
        112243
      ],
      examPointIdList: [
        12241,
        12242,
        12243
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 11,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1513742871000,
      createdUser: 1001794935,
      updatedTime: 1521096672000,
      updatedUser: 783030,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 3,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '错词——涉及动词最多',
        '多词——主要是介词',
        '少词——主要是介词或冠词'
      ],
      examPointNameList: [
        '错词——涉及动词最多',
        '多词——主要是介词',
        '少词——主要是介词或冠词'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '新疆省哈密地区市',
      deleted: null,
      parentTypeId: 45,
      parentTypeName: '变形改错题',
      originPaperName: null,
      examPaperTypeId: 6
    },
    {
      id: 4135,
      title: '<p>学校校刊正举行征文活动，主题为“我第一次参加的运动会”。根据中英文提示，写一篇意思连贯、符合逻辑、不少于50词的英语短文。内容要求：</p><p>1. 你参加了什么项目；</p><p>2. 成绩如何；</p><p>3. 有什么感受；</p><table><tbody><tr class="firstRow"><td><p>提示</p></td><td><p>1. What event did you take part in for the first time?</p><p>2. What was your result?</p><p>3. How did you feel?</p></td></tr></tbody></table><p>提示词语：long jump, win, feel, nervous and excited, sorry</p><p>___________________________________________________________________________________</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p><zmindent></zmindent>In Grade 4, I took part in the sports meet for the first time. My event was the relay race. I was running the last lap. It was the finalevent on sports meet. Everyone was nervous but excited. All the runners got ready at the starting line.</p><p><zmindent></zmindent>As soon as the race began, everyone was too excited to stop cheering. When it was my turn, I thought the Class 4’s runner would catch up with me. So I tried my best to run faster though I was nervous. Finally, our class won the first prize inthe most exciting event.</p><p><zmindent></zmindent>I was happy that we won the prize for my class. Of course, I was happy I was a part of them. This is my first time to take part in the sports met and I think it’s the most unforgettable sports meet in my school life.</p>'
      ],
      analysis: '<p>这是一篇给材料作文，主题为“我第一次参加的运动会”。动笔前要先认真阅读要点，尽量将提示的内容利用上；以提示的问题作为写作的主线，结合材料内容，可知本文主要是第一人称，一般过去时态进行叙述。语言的表述应该符合语法的结构，造句应该符合英语的表达习惯。适当使用连词，做到上下文联系紧密，符合逻辑关系。</p>',
      subjectId: 3,
      gradeId: 8,
      phaseId: 2,
      termId: 1,
      typeId: 18,
      questionType: '书面表达',
      provinceId: 3,
      cityId: 3,
      countyId: 12,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 5,
      distinction: 3,
      recommendationIndex: null,
      rating: 5,
      comprehensiveDegreeId: 3,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        103576,
        115977
      ],
      examPointIdList: [
        3576,
        15977
      ],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 2,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1511970758000,
      createdUser: 1002330390,
      updatedTime: 1521627642000,
      updatedUser: 1003686919,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '话题作文',
        '材料作文'
      ],
      examPointNameList: [
        '话题作文',
        '材料作文'
      ],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '北京省北京市房山区',
      deleted: null,
      parentTypeId: 46,
      parentTypeName: '写作题',
      originPaperName: null,
      examPaperTypeId: null
    },
    {
      id: 28026,
      title: '<p>明明期末考试的语文成绩是<zmlatex>94</zmlatex>分，数学、英语、科学三科的平均成绩是<zmlatex>95</zmlatex>分，明明四科的平均分是多少分？</p>',
      content: null,
      optionList: null,
      answerList: [
        '<p><zmlatex>(95{\\times}3+94){\\div}4</zmlatex></p><p><zmlatex>=379\\div 4</zmlatex></p><p><zmlatex>=94.75</zmlatex>（分）</p><p>答：四门课的平均成绩是<zmlatex>94.75</zmlatex>分。</p>'
      ],
      analysis: '<p>先根据“平均成绩<zmlatex>{\\times}</zmlatex>门数”求出数学、英语、科学三科的总成绩，加上语文的成绩求出四门课的总成绩，再除以<zmlatex>4</zmlatex>即可解答问题。</p>',
      subjectId: 2,
      gradeId: 4,
      phaseId: 1,
      termId: 2,
      typeId: 4,
      questionType: '解答题',
      provinceId: 0,
      cityId: null,
      countyId: null,
      schoolId: null,
      year: null,
      score: 3,
      sourceId: 2,
      difficulty: 2,
      distinction: 2,
      recommendationIndex: null,
      rating: 5,
      comprehensiveDegreeId: 1,
      abilityIdList: null,
      subjectCharacteristicIdList: null,
      editionIdList: null,
      chapterIdList: null,
      knowledgeIdList: [
        3422,
        3423
      ],
      examPointIdList: [],
      coreLiteracyIdList: null,
      costTime: null,
      browseCount: 0,
      quoteCount: 7,
      examCount: 0,
      correctRate: null,
      storageTime: null,
      sub: false,
      state: null,
      createdTime: 1512307158000,
      createdUser: 1002318586,
      updatedTime: 1522143749000,
      updatedUser: 1000993464,
      versions: null,
      remarks: null,
      picUrl: null,
      cutUserId: null,
      auditCutUserId: null,
      entryUserId: null,
      auditEntryUserId: null,
      tagUserId1: null,
      tagUserId2: null,
      auditTagUserId: null,
      cutTime: null,
      auditCutTime: null,
      entryTime: null,
      auditEntryTime: null,
      tag1Time: null,
      tag2Time: null,
      auditTagTime: null,
      errType: 0,
      errReason: '',
      templateType: 4,
      adoptUser1Tag: null,
      adoptUser2Tag: null,
      children: null,
      questionTag1: null,
      questionTag2: null,
      tagAdopt: null,
      tagReason: null,
      tagFeedback1: null,
      tagFeedback2: null,
      auditTagFeedback: null,
      sceneIdList: null,
      suggestTime: null,
      examTypeId: null,
      tagUser1FeedbackAdoptFlag: null,
      tagUser2FeedbackAdoptFlag: null,
      auditTagUserFeedbackAdoptFlag: null,
      tagUser1AdoptFlag: null,
      tagUser2AdoptFlag: null,
      knowledgeNameList: [
        '平均数的意义',
        '求平均数的方法'
      ],
      examPointNameList: [],
      layoutStyle: 3,
      x1: null,
      y1: null,
      x2: null,
      y2: null,
      picIndex: null,
      label: '全国',
      deleted: null,
      parentTypeId: 40,
      parentTypeName: '解答题',
      originPaperName: null,
      examPaperTypeId: 1
    }
  ],
  count: 20,
  pageCount: 223,
  firstResult: 0,
  lastResult: 20,
  maxResults: 20
};