/*
 *
 * Login constants
 *
 */

export const DEFAULT_ACTION = 'app/Login/DEFAULT_ACTION';
export const CHANGE_MOBILE_ACTION = 'app/Login/CHANGE_MOBILE_ACTION';
export const CHANGE_PASSWORD_ACTION = 'app/Login/CHANGE_PASSWORD_ACTION';
export const CHANGE_IS_LOADING_ACTION = 'app/Login/CHANGE_IS_LOADING_ACTION';
export const CHANGE_SHOW_PASSWORD_ACTION = 'app/Login/CHANGE_SHOW_PASSWORD_ACTION';
export const CHANGE_LOGIN_SUCCESS_ACTION = 'app/Login/CHANGE_LOGIN_SUCCESS_ACTION';
//
export const CHANGE_OPEN_OR_CLOSE_ALERT_ACTION = 'app/Login/CHANGE_OPEN_OR_CLOSE_ALERT_ACTION';
export const SET_LOGIN_MISS_TEXT_ACTION = 'app/Login/SET_LOGIN_MISS_TEXT_ACTION';
