/*
 *
 * PaperInputVerify constants
 *
 */

export const DEFAULT_ACTION = 'app/PaperInputVerify/DEFAULT_ACTION';
export const CHANGE_PAGE_INDEX_ACTION = 'app/PaperInputVerify/CHANGE_PAGE_INDEX_ACTION';
export const CHANGE_PAPER_STATE_ACTION = 'app/PaperInputVerify/CHANGE_PAPER_STATE_ACTION';
export const GET_PAPER_MSG_ACTION = 'app/PaperInputVerify/GET_PAPER_MSG_ACTION';
export const CHANGE_PAGE_STATE_ACTION = 'app/PaperInputVerify/CHANGE_PAGE_STATE_ACTION';
export const SET_PAPER_LIST_ACTION = 'app/PaperInputVerify/SET_PAPER_LIST_ACTION';
export const CHANGE_NOT_GET_PAPER_COUNT_ACTION = 'app/PaperInputVerify/CHANGE_NOT_GET_PAPER_COUNT_ACTION';
export const CHANGE_HAS_GET_PAPER_COUNT_ACTION = 'app/PaperInputVerify/CHANGE_HAS_GET_PAPER_COUNT_ACTION';
export const CHANGE_NEED_VERIFY_PAPER_ID_ACTION = 'app/PaperInputVerify/CHANGE_NEED_VERIFY_PAPER_ID_ACTION';
export const CHANGE_NEED_VERIFY_PAPER_ITEM_ACTION = 'app/PaperInputVerify/CHANGE_NEED_VERIFY_PAPER_ITEM_ACTION';
export const CHANGE_NEED_VERIFY_PAPER_ACTION = 'app/PaperInputVerify/CHANGE_NEED_VERIFY_PAPER_ACTION';
export const CHANGE_ALERT_SHOW_OR_HIDE_ACTION = 'app/PaperInputVerify/CHANGE_ALERT_SHOW_OR_HIDE_ACTION';
export const CHANGE_QUESTION_LIST_ACTION = 'app/PaperInputVerify/CHANGE_QUESTION_LIST_ACTION';
export const CHANGE_QUESTION_MSG_LIST_ACTION = 'app/PaperInputVerify/CHANGE_QUESTION_MSG_LIST_ACTION';
export const CHANGE_REAL_QUESTION_COUNT_ACTION = 'app/PaperInputVerify/CHANGE_REAL_QUESTION_COUNT_ACTION';
export const CHANGE_QUESTION_RESULT_ACTION = 'app/PaperInputVerify/CHANGE_QUESTION_RESULT_ACTION';
export const SET_ALL_QUESTION_TYPE_LIST_ACTION = 'app/PaperInputVerify/SET_ALL_QUESTION_TYPE_LIST_ACTION';
export const GET_ALL_QUESTION_TYPE_LIST_ACTION = 'app/PaperInputVerify/GET_ALL_QUESTION_TYPE_LIST_ACTION';
export const CHANGE_SELECTED_QUESTION_INDEX_ACTION = 'app/PaperInputVerify/CHANGE_SELECTED_QUESTION_INDEX_ACTION';
export const CHANGE_ERR_TEXTAREA_SHOW_ACTION = 'app/PaperInputVerify/CHANGE_ERR_TEXTAREA_SHOW_ACTION';
export const CHANGE_QUESTION_RESULT_STATE_ACTION = 'app/PaperInputVerify/CHANGE_QUESTION_RESULT_STATE_ACTION';
export const CHANGE_PREVIEW_IMG_SRC_ACTION = 'app/PaperInputVerify/CHANGE_PREVIEW_IMG_SRC_ACTION';
export const SUBMIT_QUESTION_CUT_VERIFY_ACTION = 'app/PaperInputVerify/SUBMIT_QUESTION_CUT_VERIFY_ACTION';
export const CHANGE_SORT_ACTION = 'app/PaperInputVerify/CHANGE_SORT_ACTION';
export const SET_PAPER_DOWNLOAD_MSG_ACTION = 'app/PaperInputVerify/SET_PAPER_DOWNLOAD_MSG_ACTION';
export const INIT_VERIFY_DATA_ACTION = 'app/PaperInputVerify/INIT_VERIFY_DATA_ACTION';
export const CHANGE_SHOW_SUBMIT_BTN_ACTION = 'app/PaperInputVerify/CHANGE_SHOW_SUBMIT_BTN_ACTION';
export const CHANGE_QUESTION_EDIT_STATE_ACTION = 'app/PaperInputVerify/CHANGE_QUESTION_EDIT_STATE_ACTION';
export const SET_CLICK_TARGET_ACTION = 'app/PaperInputVerify/SET_CLICK_TARGET_ACTION';
export const SUBMIT_QUESTION_ITEM_ACTION = 'app/PaperInputVerify/SUBMIT_QUESTION_ITEM_ACTION';
export const SET_NEW_QUESTION_MSG_ACTION = 'app/PaperInputVerify/SET_NEW_QUESTION_MSG_ACTION';
export const SET_QUESTIONS_ACTION = 'app/PaperInputVerify/SET_QUESTIONS_ACTION';
