/*
 *
 * AddVideoWrapper constants
 *
 */

export const DEFAULT_ACTION = 'app/AddVideoWrapper/DEFAULT_ACTION';
export const SET_CURRENTMENU_ACTION = 'app/AddVideoWrapper/SET_CURRENTMENU_ACTION';
export const SET_CHOOSEWATCHEROPEN_ACTION = 'app/AddVideoWrapper/SET_CHOOSEWATCHEROPEN_ACTION';
export const SET_UPLOADMODALOPEN_ACTION = 'app/AddVideoWrapper/SET_UPLOADMODALOPEN_ACTION';
export const SET_UPLOADMODALCONTENTINDEX_ACTION = 'app/AddVideoWrapper/SET_UPLOADMODALCONTENTINDEX_ACTION';
export const GET_VIDEORECORDLIST_ACTION = 'app/AddVideoWrapper/GET_VIDEORECORDLIST_ACTION';
export const GET_SUBJECT_ACTION = 'app/AddVideoWrapper/GET_SUBJECT_ACTION';
export const GET_GRADE_ACTION = 'app/AddVideoWrapper/GET_GRADE_ACTION';
export const GET_LESSONTYPE_ACTION = 'app/AddVideoWrapper/GET_LESSONTYPE_ACTION';
export const SET_SELECTSUBJECT_ACTION = 'app/AddVideoWrapper/SET_SELECTSUBJECT_ACTION';
export const SET_SELECTGRADE_ACTION = 'app/AddVideoWrapper/SET_SELECTGRADE_ACTION';
export const SET_TEACHERPHONE_ACTION = 'app/AddVideoWrapper/SET_TEACHERPHONE_ACTION';
export const SET_STUDENTPHONE_ACTION = 'app/AddVideoWrapper/SET_STUDENTPHONE_ACTION';
export const SET_SELECTLESSONTYPE_ACTION = 'app/AddVideoWrapper/SET_SELECTLESSONTYPE_ACTION';
export const SET_CHANGESTATUS_ACTION = 'app/AddVideoWrapper/SET_CHANGESTATUS_ACTION';
export const SET_SELECTSTARTTIME_ACTION = 'app/AddVideoWrapper/SET_SELECTSTARTTIME_ACTION';
export const SET_SELECTENDTIME_ACTION = 'app/AddVideoWrapper/SET_SELECTENDTIME_ACTION';
export const SET_SEARCHFIELDVALUE_ACTION = 'app/AddVideoWrapper/SET_SEARCHFIELDVALUE_ACTION';

export const SET_VIDEORECORDLIST_ACTION = 'app/AddVideoWrapper/SET_VIDEORECORDLIST_ACTION';
export const SET_VIDEORECORDTOTALCOUNT_ACTION = 'app/AddVideoWrapper/SET_VIDEORECORDTOTALCOUNT_ACTION';
export const SET_CURRENTPAGINATIONINDEX_ACTION = 'app/AddVideoWrapper/SET_CURRENTPAGINATIONINDEX_ACTION';
export const SET_LOADINGSTATE_ACTION = 'app/AddVideoWrapper/SET_LOADINGSTATE_ACTION';
export const REMOVE_SELETEVIDEOS_ACTION = 'app/AddVideoWrapper/REMOVE_SELETEVIDEOS_ACTION';
export const SET_REMOVEVIDEO_ACTION = 'app/AddVideoWrapper/SET_REMOVEVIDEO_ACTION';
export const SET_ADDLESSONVIDEO_ACTION = 'app/AddVideoWrapper/SET_ADDLESSONVIDEO_ACTION';
export const SET_CHOOSEWATCHERROLES_ACTION = 'app/AddVideoWrapper/SET_CHOOSEWATCHERROLES_ACTION';
export const SET_SELECTADDLESSONVIDEO_ACTION = 'app/AddVideoWrapper/SET_SELECTADDLESSONVIDEO_ACTION';
export const SET_UPLOADFILEINFO_ACTION = 'app/AddVideoWrapper/SET_UPLOADFILEINFO_ACTION';
export const SET_GRADELIST_ACTION = 'app/AddVideoWrapper/SET_GRADELIST_ACTION';
export const SET_SUBJECTLIST_ACTION = 'app/AddVideoWrapper/SET_SUBJECTLIST_ACTION';
export const SET_LESSONTYPELIST_ACTION = 'app/AddVideoWrapper/SET_LESSONTYPELIST_ACTION';
export const SET_UPLOADFILE_ACTION = 'app/AddVideoWrapper/SET_UPLOADFILE_ACTION';
export const SET_BATCHADDVIDEO_ACTION = 'app/AddVideoWrapper/SET_BATCHADDVIDEO_ACTION';
export const SET_BATVHADDVIDEOITEMS_ACTION = 'app/AddVideoWrapper/SET_BATVHADDVIDEOITEMS_ACTION';
export const SET_ISBATCHADDVIDEO_ACTION = 'app/AddVideoWrapper/SET_ISBATCHADDVIDEO_ACTION';
export const GET_USERID_ACTION = 'app/AddVideoWrapper/GET_USERID_ACTION';
export const SET_USERIDITEM_ACTION = 'app/AddVideoWrapper/SET_USERIDITEM_ACTION';
export const SET_CHANGEFULLNAMEVALUE_ACTION = 'app/AddVideoWrapper/SET_CHANGEFULLNAMEVALUE_ACTION';
export const SET_STUDENTUSERIDSITEM_ACTION = 'app/AddVideoWrapper/SET_STUDENTUSERIDSITEM_ACTION';
export const SET_UPLOADFILEINFOINIT_ACTION = 'app/AddVideoWrapper/SET_UPLOADFILEINFOINIT_ACTION';
export const SET_BUTTONLOADING_ACTION = 'app/AddVideoWrapper/SET_BUTTONLOADING_ACTION';



