/*
 *
 * GetAndCutPaper constants
 *
 */

// export const DEFAULT_ACTION = 'app/GetAndCutPaper/DEFAULT_ACTION';
export const CHANGE_PAGE_STATE_ACTION = 'app/GetAndCutPaper/CHANGE_PAGE_STATE_ACTION';
export const PREVIEW_WRAPPER_SHOW_OR_HIDE_ACTION = 'app/GetAndCutPaper/PREVIEW_WRAPPER_SHOW_OR_HIDE_ACTION';
export const CHANGE_SELECTED_QUESTION_INDEX_ACTION = 'app/GetAndCutPaper/CHANGE_SELECTED_QUESTION_INDEX_ACTION';
export const CHANGE_IMGSRC_ACTION = 'app/GetAndCutPaper/CHANGE_IMGSRC_ACTION';
export const CHANGE_CURRENT_CUT_PAPER_IMG_ACTION = 'app/GetAndCutPaper/CHANGE_CURRENT_CUT_PAPER_IMG_ACTION';
export const GET_PAPER_MSG_ACTION = 'app/GetAndCutPaper/GET_PAPER_MSG_ACTION';
export const CHANGE_PAGE_INDEX_ACTION = 'app/GetAndCutPaper/CHANGE_PAGE_INDEX_ACTION';
export const CHANGE_PAPER_STATE_ACTION = 'app/GetAndCutPaper/CHANGE_PAPER_STATE_ACTION';
export const CHANGE_SUBJECT_ID_ACTION = 'app/GetAndCutPaper/CHANGE_SUBJECT_ID_ACTION';
export const CHANGE_GRADE_ID_ACTION = 'app/GetAndCutPaper/CHANGE_GRADE_ID_ACTION';
export const CHANGE_ALERT_SHOW_OR_HIDE_ACTION = 'app/GetAndCutPaper/CHANGE_ALERT_SHOW_OR_HIDE_ACTION';
export const CHANGE_CURRENT_PAPER_ITEM_ACTION = 'app/GetAndCutPaper/CHANGE_CURRENT_PAPER_ITEM_ACTION';
export const SET_PAPER_LIST_ACTION = 'app/GetAndCutPaper/SET_PAPER_LIST_ACTION';
export const CHANGE_PAPER_COUNT_ACTION = 'app/GetAndCutPaper/CHANGE_PAPER_COUNT_ACTION';
export const GET_CUT_PAPER_TASK_ACTION = 'app/GetAndCutPaper/GET_CUT_PAPER_TASK_ACTION';
export const CHANGE_HAS_GET_PAPER_COUNT_ACTION = 'app/GetAndCutPaper/CHANGE_HAS_GET_PAPER_COUNT_ACTION';
export const CHANGE_ALERT_STATES_ACTION = 'app/GetAndCutPaper/CHANGE_ALERT_STATES_ACTION';

//
export const GET_CUT_PAPER_ITEM_ACTION = 'app/GetAndCutPaper/GET_CUT_PAPER_ITEM_ACTION';
export const CHANGE_NEED_CUT_PAPER_ID_ACTION = 'app/GetAndCutPaper/CHANGE_NEED_CUT_PAPER_ID_ACTION';
export const SET_PIC_URL_LIST_ACTION = 'app/GetAndCutPaper/SET_PIC_URL_LIST_ACTION';
export const CHANGE_PAPER_IS_BE_CUT_ITEM_ACTION = 'app/GetAndCutPaper/CHANGE_PAPER_IS_BE_CUT_ITEM_ACTION';
export const SET_CANVAS_DOM_ACTION = 'app/GetAndCutPaper/SET_CANVAS_DOM_ACTION';
export const GET_ALL_QUESTION_TYPE_LIST_ACTION = 'app/GetAndCutPaper/GET_ALL_QUESTION_TYPE_LIST_ACTION';
export const SET_ALL_QUESTION_TYPE_LIST_ACTION = 'app/GetAndCutPaper/SET_ALL_QUESTION_TYPE_LIST_ACTION';
export const CHANGE_SELECTED_QUESTION_TYPE_ACTION = 'app/GetAndCutPaper/CHANGE_SELECTED_QUESTION_TYPE_ACTION';
export const CHANGE_BIG_QUESTION_ACTION = 'app/GetAndCutPaper/CHANGE_BIG_QUESTION_ACTION';
export const SET_SMALL_QUESTION_ACTION = 'app/GetAndCutPaper/SET_SMALL_QUESTION_ACTION';
export const SAVE_QUESTION_MSG_LIST_ACTION = 'app/GetAndCutPaper/SAVE_QUESTION_MSG_LIST_ACTION';
export const SAVE_QUESTION_LIST_ACTION = 'app/GetAndCutPaper/SAVE_QUESTION_LIST_ACTION';
export const CHANGE_QUESTION_PREVIEW_SHOW_ACTION = 'app/GetAndCutPaper/CHANGE_QUESTION_PREVIEW_SHOW_ACTION';
export const CHANGE_PREVIEW_IMG_SRC_ACTION = 'app/GetAndCutPaper/CHANGE_PREVIEW_IMG_SRC_ACTION';
export const CHANGE_PAPER_PREVIEW_SHOW_ACTION = 'app/GetAndCutPaper/CHANGE_PAPER_PREVIEW_SHOW_ACTION';
export const SUNMIT_CUT_PAPER_ACTION = 'app/GetAndCutPaper/SUNMIT_CUT_PAPER_ACTION';
export const BACK_INIT_DATA_ACTION = 'app/GetAndCutPaper/BACK_INIT_DATA_ACTION';
export const CHANGE_IS_SUBMIT_ING_ACTION = 'app/GetAndCutPaper/CHANGE_IS_SUBMIT_ING_ACTION';
export const CHANGE_SORT_ACTION = 'app/GetAndCutPaper/CHANGE_SORT_ACTION';
export const CHANGE_IMG_START_INDEX_ACTION = 'app/GetAndCutPaper/CHANGE_IMG_START_INDEX_ACTION';
export const SET_SELECT_INSERT_WAY_ACTION = 'app/GetAndCutPaper/SET_SELECT_INSERT_WAY_ACTION';
export const SET_SELECT_BIG_QUESTION_ACTION = 'app/GetAndCutPaper/SET_SELECT_BIG_QUESTION_ACTION';
export const SET_SELECTED_INDEX_ACTION = 'app/GetAndCutPaper/SET_SELECTED_INDEX_ACTION';
export const SET_SELECTED_INSERT_INDEX_ACTION = 'app/GetAndCutPaper/SET_SELECTED_INSERT_INDEX_ACTION';
export const SET_BIG_QUESTION_MSG_ACTION = 'app/GetAndCutPaper/SET_BIG_QUESTION_MSG_ACTION';
export const SET_EDITOR_BIG_QUESTION_ACTION = 'app/GetAndCutPaper/SET_EDITOR_BIG_QUESTION_ACTION';
export const IMG_COUNT_CRITICAL_ACTION = 'app/GetAndCutPaper/IMG_COUNT_CRITICAL_ACTION';
export const IMG_IMG_STEP_ACTION = 'app/GetAndCutPaper/IMG_IMG_STEP_ACTION';
export const CHANGE_BIG_PIC_INDEX_ACTION = 'app/GetAndCutPaper/CHANGE_BIG_PIC_INDEX_ACTION';

export const SET_PIC_INPUT_DTO_LIST_ACTION = 'app/GetAndCutPaper/SET_PIC_INPUT_DTO_LIST_ACTION'; // 保存切割数据
export const ADD_BIG_IMG_ACTION = 'app/GetAndCutPaper/ADD_BIG_IMG_ACTION'; // 保存切割数据
export const SET_NEED_CUT_PAPER_ACTION = 'app/GetAndCutPaper/SET_NEED_CUT_PAPER_ACTION'; // 保存切割数据
